In [102]:
import pandas as pd
import os
import re
from mistralai.client import Mistral
from rapidfuzz import fuzz, process
from tqdm import tqdm
from dotenv import load_dotenv
import json

In [56]:
load_dotenv(dotenv_path='../.env')

True

In [57]:
client = Mistral(api_key=os.getenv('MISTRAL_API_KEY'))

In [58]:
TEMPLATE_OLD_PATH = "../data/submission_template.csv"
OLD_SUBMISSION = "./submission2.csv"

In [59]:
old_submission_df = pd.read_csv(OLD_SUBMISSION)
template_old_df = pd.read_csv(TEMPLATE_OLD_PATH)
old_submission_df['doc_id'] = template_old_df['doc_id']
old_submission_df['party_name'] = template_old_df['party_name']
old_submission_df

                        id  votes             doc_id      party_name
0      constituency_10_1_1  14813  constituency_10_1    ประชาธิปัตย์
1      constituency_10_1_2  14368  constituency_10_1       ภูมิใจไทย
2      constituency_10_1_3    979  constituency_10_1        เศรษฐกิจ
3      constituency_10_1_4    244  constituency_10_1        กล้าธรรม
4      constituency_10_1_5    351  constituency_10_1           พลวัต
...                    ...    ...                ...             ...
10048  party_list_34_11_53     14   party_list_34_11  ไทยพิทักษ์ธรรม
10049  party_list_34_11_54     41   party_list_34_11    ความหวังใหม่
10050  party_list_34_11_55     29   party_list_34_11       ไทยรวมไทย
10051  party_list_34_11_56     41   party_list_34_11  เพื่อบ้านเมือง
10052  party_list_34_11_57     71   party_list_34_11  พลังไทยรักชาติ

[10053 rows x 4 columns]

#### Extraction

In [86]:
def thai_num_to_int(text: str) -> int:

    thai_to_arabic = str.maketrans("๐๑๒๓๔๕๖๗๘๙", "0123456789")
    text = text.translate(thai_to_arabic)

    # remove non-numeric prefixes
    text = re.sub(r"[^\d,]", " ", text)

    match = re.search(r"[\d,]+", text)
    if not match:
        raise ValueError("No numeric value found")

    return int(match.group().replace(",", ""))

In [120]:
KNOWN_PARTIES = [
    'ประชาธิปัตย์', 'ภูมิใจไทย', 'เศรษฐกิจ', 'กล้าธรรม', 'พลวัต',
    'ประชาชน', 'เพื่อไทย', 'ไทยภักดี', 'รวมไทยสร้างชาติ', 'ปวงชนไทย',
    'ไทยสร้างไทย', 'โอกาสใหม่', 'วิชชั่นใหม่', 'ประชาธิปไตยใหม่',
    'รักชาติ', 'ไทยก้าวใหม่', 'ทางเลือกใหม่', 'พลังประชารัฐ',
    'ประชากรไทย', 'ความหวังใหม่', 'อนาคตไทย', 'บ้านเมือง',
    'เพื่อบ้านเมือง', 'ไทยก้าวหน้า', 'รวมไทยสร้าง', 'แรงงานสร้างชาติ',
    'ไทยชนะ', 'พร้อม', 'ไทยพิทักษ์ธรรม', 'ไทยก้าวไทย', 'ไทยก้าวใหม',
    'เสรีรวมไทย', 'เป็นธรรม', 'ไทยธรรม', 'ฟิวชน', 'ฟิวชัน',
    'รวมพลังประชาชน', 'แรงงานสร้างไทย', 'ไทยสร้างชาติ',
    'ปวงชนชาวไทย', 'กลาธรรม', 'สังคมประชาธิปไตยไทย', 'คลองไทย',
    'รวมใจไทย', 'รวมไทยสร้างชา', 'รักษ์ธรรม', 'ชาติ', 'ไทยพร้อม',
    'สร้างชาติ', 'พลังสังคมใหม่', 'สร้างอนาคตไทย',
    'ไทยทรัพย์ทวี', 'รวมพลัง', 'ไทรวมพลัง', 'เพื่อชาติไทย', 'มิติใหม่',
    'ท้องที่ไทย', 'พลังเพื่อไทย', 'ก้าวอิสระ', 'เพื่อชีวิตใหม่',
    'ครูไทยเพื่อประชาชน', 'ประชาชาติ', 'พลังธรรมใหม่', 'กรีน',
    'แผ่นดินธรรม', 'ประชาไทย', 'ประชาอาสาชาติ',
    'เครือข่ายชาวนาแห่งประเทศไทย', 'ไทยรวมไทย', 'พลังไทยรักชาติ', 'ใหม่'
]

def is_party(text, threshold=70):
    match = process.extractOne(text, KNOWN_PARTIES, scorer=fuzz.ratio)
    return match and match[1] >= threshold

In [91]:
def extract_party_score_dict(md: str) -> dict:
    result = {}

    for line in md.split('\n'):
        if '---' in line or 'รวมคะแนน' in line:
            continue

        parts = [p.strip() for p in line.split('|') if p.strip()]
        if len(parts) < 2:
            continue

        for i, p in enumerate(parts):
            match = process.extractOne(p, KNOWN_PARTIES, scorer=fuzz.ratio)
            if match and match[1] >= 60:
                canonical_party = match[0]
                for vote_raw in reversed(parts[i+1:]):
                    try:
                        vote = thai_num_to_int(vote_raw)
                        result[canonical_party] = vote
                        break
                    except Exception:
                        pass
                break

    return result

In [ ]:
def extraction(path):
    try:
        if not os.path.exists(path):
            return {}
        filename = os.path.basename(path)
        with open(path, "rb") as f:
            uploaded = client.files.upload(
                file={"file_name": filename, "content": f},
                purpose="ocr"
            )
        signed_url = client.files.get_signed_url(file_id=uploaded.id)
        result = client.ocr.process(
            model="mistral-ocr-latest",
            document={"type": "document_url", "document_url": signed_url.url}
        )
        # Combine all pages markdown
        #print(result.pages[0].markdown)
        md = "".join(page.markdown for page in result.pages)
        return extract_party_score_dict(md)
    except Exception as e:
        print(e.__str__())
        return {}

### Inference

In [89]:
def assign_votes(df, vote_dict, threshold=60):
    vote_dict = {k: v for k, v in vote_dict.items() if k != 'รวมคะแนนทั้งสิ้น'}
    keys = list(vote_dict.keys())

    def get_vote(party_name):
        if pd.isna(party_name):
            return 0
        match = process.extractOne(
            party_name,
            keys,
            scorer=fuzz.token_set_ratio
        )
        if match is None:
            return 0
        best_key, score, _ = match
        return vote_dict[best_key] if score >= threshold else 0

    df['votes'] = df['party_name'].apply(get_vote)
    return df

### Run

In [65]:
submission_df = old_submission_df.copy()

In [96]:
bad_one = [
	'constituency_12_6',
	'party_list_10_24',
	'party_list_10_31',
	'party_list_10_9',
	'party_list_14_2',
	'party_list_19_2',
	'party_list_20_1',
	'party_list_20_5',
	'party_list_20_7',
	'party_list_21_5',
	'party_list_22_2',
	'party_list_30_2',
	'party_list_30_3',
	'party_list_30_4',
	'party_list_31_8',
	'party_list_32_7',
	'party_list_33_3',
	'party_list_33_6'
]

In [70]:
PREFIX = "../pdf/"

In [97]:
happen = {}

for doc_id in tqdm(bad_one, desc="Processing", unit="doc"):
	try:
		vote_dict = extraction(PREFIX + doc_id + '.pdf')
		happen[doc_id] = vote_dict
		mask = submission_df["doc_id"] == doc_id
		submission_df.loc[mask] = assign_votes(
			submission_df.loc[mask].copy(),
			vote_dict,
			threshold=60
		)
	except Exception as e:
		print(f"{doc_id}: {str(e)}")

Processing:   6%|▌         | 1/18 [00:03<01:06,  3.89s/doc]

|  หมายเลข
ประจำตัว
ผู้สมัคร | ชื่อตัว – ชื่อสกุล
ผู้สมัครรับเลือกตั้ง | สังกัด
พรรค
การเมือง | ได้คะแนน
(ให้กรอกทั้งตัวเลขและตัวอักษร)  |
| --- | --- | --- | --- |
|  ๔ | นายสุทัศน์ มิศิริ | ประชาชน | ๔๔,๔๐๕ (สี่หมื่นสี่พันสี่ร้อยห้า)  |
|  ๒ | นางสาวศศิประภา ดีรอด | ภูมิใจไทย | ๒๕,๒๑๘ (สองหมื่นห้าพันสองร้อยสิบแปด)  |
|  ๕ | นายประมการ อ่วมอ่อง | เพื่อไทย | ๑๗,๙๖๘ (หนึ่งหมื่นเจ็ดพันเก้าร้อยหกสิบแปด)  |
|  ๑ | นายพงศกร นกทรัพย์ | ประชาธิปไตย | ๖,๕๙๕ (หกพันห้าร้อยเก้าสิบห้า)  |
|  ๘ | นายเกริกหิรัญ แปลกประเสริฐ | เศรษฐกิจ | ๑,๗๔๑ (หนึ่งพันเจ็ดร้อยสี่สิบเอ็ด)  |
|  ๙ | นายชานนท์ พงษ์เจริญ | ทางเลือกใหม่ | ๑,๓๘๙ (หนึ่งพันสามร้อยแปดสิบเก้า)  |
|  ๑๑ | นายธีรวัจน์ ดารามาศ | พลวัต | ๘๘๗ (แปดร้อยแปดสิบเจ็ด)  |
|  ๑๒ | นายคุณากร มั่นนทีรัย | กล้าธรรม | ๘๒๓ (แปดร้อยยี่สิบสาม)  |
|  รวมคะแนนทั้งสิ้น |   |   | ๙๙,๐๒๖ (เก้าหมื่นเก้าพันยี่สิบหก)  |

Processing:  11%|█         | 2/18 [00:11<01:40,  6.29s/doc]

|  **ความเคยจะเป็นข้าวหรือของพวกเขาวะมือ>** | **ข้อพรรคการมือ>** | **1. ให้พรรคการ (ให้พวกเขาได้รับประเภทสำหรับพรรค)**  |
| --- | --- | --- |
|  ๑ | โพดทรัพย์ทวี | ส่ง: (สำหรับผลิต)  |
|  ๒ | เตือกปลื้อก | แบบ: (หนึ่งในหากสักจะลด)  |
|  ๓ | ไหม | แบบ: (นกสีจะมือ)  |
|  ๔ | อิชั่วทอ | แบบ: (หนึ่งในหากสักจะลด)  |
|  ๕ | รวมไออิคม | แบบ: (สามในหลักสาม)  |
|  ๖ | รวมไออิสร้างขาด | แบบ: (หนึ่งในหลักสาม)  |
|  ๗ | ขยะใย | แบบ: (หนึ่งในจะกำลังงดง)  |
|  ๘ | ประชาสิ่งใหม่ใหม่ | แบบ: (หนึ่งในจะกำลังง)  |
|  ๙ | เพื่อไทย | แบบ: (เพื่อขับสารที่สะดวกสลับงดง)  |
|  ๑+ | ชาวเมืองไทย | แบบ: (สามในหนึ่งหรือสี่)  |
|  ๒+ | เหรอภูมิอ | แบบ: (หนึ่งในเพื่อให้พวกเขามีความรู้)  |
|  ๓+ | เสร็จวนไทย | แบบ: (สำคัญหนึ่ง)  |
|  ๔+ | รวมพลังประชาชน | แบบ: (หนึ่งในจะได้รับประเภท)  |
|  ๕+ | ห้องซิโคม | แบบ: (สำคัญ)  |
|  ๖+ | อะเหงน้อย | ส่ง: (สำคัญ)  |
|  ๗+ | หลังเพื่อไทย | ส่ง: (สำคัญ)  |
|  **ความเคยจะเป็นข้าวหรือของพวกเขาวะมือ>** | **ข้อพรรคการมือ>** | **1. ให้พรรคการ (ให้พวกเขาได้รับประเภทสำหรับพรรค)**  |
|  ๑+ | โพดท่อย | (ให้ระมือ)  |
|  ๒+ | หลังอิคมใหม่ | แบบ: (สำหรับ)  |
|  ๓+ | สิ่งของประชาธิปไตยไทย | แบบ: (ให้ระมือ)  |
|  ๔+ | สิ่งสั้น | แบบ: (ให้ระมือ)  |
|  ๖+ | โพรวมพลัง | แบบ: (ให้ระมือ)  |
|  ๗+ | ส้างอิสระ | แบบ: (สำหรับ)  |
|  ๘+ | ปวกขนไทย | ส่ง: (สำคัญ)  |
|  ๙+ | วัชชั่นใหม่ | แบบ: (สำหรับ)  |
|  ๚+ | เพื่อชีวิตใหม่ | แบบ: (สำหรับ)  |
|  ๛+ | คะแงไทย | แบบ: (ให้ระมือ)  |
|  ๖+ | ประชาธิปไตย | แบบ: (หนึ่งในจริงจริง)  |
|  ๖+ | โดยก้าวหน้า | แบบ: (หนึ่งในจริงจริง)  |
|  ๖+ | โดยตัวที | แบบ: (หนึ่งในแต่เนิ่นหน้าสิบกว่า)  |
|  ๗+ | แปลกโพธ์วิทยานี้ | แบบ: (ให้ระมือ)  |
|  ๘+ | ประชากรไทย | แบบ: (สามสิ่งเดียว)  |
|  ๙+ | ครูไทยเพื่อประชาชน | แบบ: (สำหรับ)  |
|  ๙+ | ประชาชาติ | แบบ: (น่าสงสัย)  |
|  **ความเคยจะเป็นข้าวหรือของพวกเขาวะมือ>** | **ข้อพรรคการมือ>** | **1. ให้พรรคการ (ให้พวกเขาได้รับประเภทสำหรับพรรค)**  |
|  ๑+ | สร้างอะเหงน้อย | (ให้รส)  |
|  ๒+ | รู้จักที | แบบ: (หนึ่งในความลึกเถียง)  |
|  ๓+ | โพดพร้อม | แบบ: (หนึ่งในความลึก)  |
|  ๔+ | ดูชั้นไทย | แบบ: (หนึ่งในความลึก)  |
|  ๕+ | พลังประชาชีพ | แบบ: (ให้รส)  |
|  ๖+ | หลังประชาชีพ | แบบ: (หนึ่งในความลึก)  |
|  ๗+ | แต่น้อยไทย | แบบ: (ให้รส)  |
|  ๚+ | แต่น้อยไทย | แบบ: (หนึ่งในความลึก)  |
|  ๚+ | แต่น้อยไทย | แบบ: (หนึ่งในความลึก)  |
|  ๙+ | ประชาชนไทย | แบบ: (น่าสงสัย)  |
|  ๚+ | ประชาชน | แบบ: (ให้รส)  |
|  ๚+ | ประชาชน | แบบ: (หนึ่งในความลึก)  |
|  ๙+ | แต่น้อยไทย | แบบ: (ให้รส)  |
|  ๚+ | แต่น้อยไทย | แบบ: (หนึ่งในความลึก)  |
|  ๙+ | ประชาชนไทย | แบบ: (น่าสงสัย)  |

Processing:  17%|█▋        | 3/18 [00:21<01:57,  7.83s/doc]

|  หมายเลขของบัญชี
รายชื่อของพรรค
การเมือง | ลั่งกัด
พรรคการเมือง | ได้คะแนน
(ให้กรอกตั้งตัวเลขและตัวอักษร)  |   |
| --- | --- | --- | --- |
|  ๑ | ไทยทรัพย์ทวี | ๕๙ | (ห้าสิบเก้า)  |
|  ๒ | เพื่อชาติไทย | ๓๒๑ | (สามร้อยยี่สิบเอ็ด)  |
|  ๓ | ไพม่ | ๗๕ | (เจ็ดสิบห้า)  |
|  ๔ | มิติไพม่ | ๖๑ | (หกสิบเอ็ด)  |
|  ๕ | รวมใจไทย | ๑๕๕ | (หนึ่งร้อยห้าสิบห้า)  |
|  ๖ | รวมไทยสร้างชาติ | ๒,๘๖๑ | (สองพันแปดร้อยหกสิบเอ็ด)  |
|  ๗ | พลวัต | ๒๓๙ | (สองร้อยสามสิบเก้า)  |
|  ๘ | ประชาธิปไตยไพม่ | ๓๑๙ | (สามร้อยสิบเก้า)  |
|  ๙ | เพื่อไทย | ๑๑,๐๑๖ | (หนึ่งหมื่นหนึ่งพันสิบหก)  |
|  ๑๐ | ท่าฉลือกไพม่ | ๕๓๒ | (ห้าร้อยสามสิบสอง)  |
|  ๑๑ | เศรษฐกิจ | ๒,๒๐๘ | (สองพันสองร้อยแปด)  |
|  ๑๒ | เสรีรวมไทย | ๗๔๑ | (เจ็ดร้อยสี่สิบเอ็ด)  |
|  ๑๓ | รวมพลังประชาชน | ๓๙๐ | (สามร้อยเก้าสิบ)  |
|  ๑๔ | ห้องทีไทย | ๓๔ | (สามสิบสี่)  |
|  ๑๕ | อนาคตไทย | ๓๖ | (สามสิบหก)  |
|  ๑๖ | พลังเพื่อไทย | ๑๑๓ | (หนึ่งร้อยสิบสาม)  |
|  ๑๗ | ไทยชนะ | ๗๔ | (เจ็ดสิบสี่)  |
|  ๑๘ | พลังสังคมไพม่ | ๗ | (เจ็ด)  |
|  ๑๘ | สังคมประชาธิปไตยไทย | ๓๑ | (สามสิบเอ็ด)  |
|  ๒๐ | ฟิวชัน | ๑๓ | (สิบสาม)  |
|  ๒๑ | ไทรวมพลัง | ๓๓ | (สามสิบสาม)  |
|  ๒๒ | ก้าวอิสระ | ๒๐ | (ยี่สิบ)  |
|  ๒๓ | ปวงชนไทย | ๕๑ | (ห้าสิบเอ็ด)  |
|  ๒๔ | วิชชั่นไพม่ | ๓๖ | (สามสิบหก)  |
|  ๒๕ | เพื่อชีวิตไพม่ | ๘ | (แปด)  |
|  ๒๖ | คลองไทย | ๒๑ | (ยี่สิบเอ็ด)  |
|  ๒๗ | ประชาธิปัตย์ | ๑๑,๓๑๓ | (หนึ่งหมื่นหนึ่งพันสามร้อยสิบสาม)  |
|  หมายเลขของบัญชี
รายชื่อของพรรค
การเมือง | ลั่งกัด
พรรคการเมือง | ได้คะแนน
(ให้กรอกตั้งตัวเลขและตัวอักษร)  |   |
|  ๒๘ | ไทยก้าวหน้า | ๘๔ | (แปดสิบสี่)  |
|  ๒๙ | ไทยกักดี | ๒,๐๖๐ | (สองพันหกสิบ)  |
|  ๓๐ | แรงงานสร้างชาติ | ๒๓ | (ยี่สิบสาม)  |
|  ๓๑ | ประชากรไทย | ๖๙ | (หกสิบเก้า)  |
|  ๓๒ | ครูไทยเพื่อประชาชน | ๓๗ | (สามสิบเจ็ด)  |
|  ๓๓ | ประชาชาติ | ๖๑ | (หกสิบเอ็ด)  |
|  ๓๔ | สร้างอนาคตไทย | ๓๗ | (สามสิบเจ็ด)  |
|  ๓๕ | รักชาติ | ๒๒๖ | (สองร้อยยี่สิบหก)  |
|  ๓๖ | ไทยพร้อม | ๖๕ | (หกสิบห้า)  |
|  ๓๗ | ภูมิใจไทย | ๑๙,๖๒๒ | (หนึ่งหมื่นเก้าพันหกร้อยยี่สิบสอง)  |
|  ๓๘ | พลังธรรมไพม่ | ๖๔ | (หกสิบสี่)  |
|  ๓๙ | กรีน | ๑๐๖ | (หนึ่งร้อยหก)  |
|  ๔๐ | ไทยธรรม | ๘๒ | (แปดสิบสอง)  |
|  ๔๑ | แผ่นดินธรรม | ๑๕ | (สิบห้า)  |
|  ๔๒ | กล้าธรรม | ๑๘๖ | (หนึ่งร้อยแปดสิบหก)  |
|  ๔๓ | พลังประชารัฐ | ๙๐ | (เก้าสิบ)  |
|  ๔๔ | โอกาสไพม่ | ๑๒๖ | (หนึ่งร้อยยี่สิบหก)  |
|  ๔๕ | เป็นธรรม | ๘๗ | (แปดสิบเจ็ด)  |
|  ๔๖ | ประชาชน | ๔๖,๒๐๔ | (สี่หมื่นหกพันสองร้อยสี่)  |
|  ๔๗ | ประชาไทย | ๘๖ | (แปดสิบหก)  |
|  ๔๘ | ไทยสร้างไทย | ๙๑๔ | (เก้าร้อยสิบสี่)  |
|  ๔๙ | ไทยก้าวใหม่ | ๗๔๙ | (เจ็ดร้อยสี่สิบเก้า)  |
|  ๕๐ | ประชาอาสาชาติ | ๘ | (แปด)  |
|  ๕๑ | พร้อม | ๑๗ | (สิบเจ็ด)  |
|  ๕๒ | เครือข่ายชาวนาแห่งประเทศไทย | ๗ | (เจ็ด)  |
|  ๕๓ | ไทยพิทักษ์ธรรม | ๖ | (หก)  |
|  ๕๔ | ความหวังไพม่ | ๙ | (เก้า)  |
|  ๕๕ | ไทยรวมไทย | ๗ | (เจ็ด)  |
|  ๕๖ | เพื่อบ้านเมือง | ๒๓ | (ยี่สิบสาม)  |
|  ๕๗ | พลังไทยรักชาติ | ๑๘ | (สิบแปด)  |
|  รวมคะแนนทั้งสิ้น |   | ๑๐๑,๘๕๕ | (หนึ่งแสนหนึ่งพันแปดร้อยห้าสิบห้า)  |

Processing:  22%|██▏       | 4/18 [00:31<01:59,  8.52s/doc]

|  ขยายแยกของบัญชีรายชื่อของหกททกานมีลง | ชื่อหกททกานมีลง | ได้ยอมรับ (ให้กรอกทั้งตัวแทนและตัวอักษร)  |
| --- | --- | --- |
|  1 | ขยะคงโหยหรือยั่งไร | ๖๒ (หกสิบสอง)  |
|  2 | ขยะคนซื้ออาห์ไหม | ๒๓๐ (สองร้อยสิบ)  |
|  3 | ขยะคงไหม | ๕๗ (ห้าสิบเอ็ด)  |
|  4 | ขยะคนไข่ไหม | ๖๘ (หกสี่ห้าปกติ)  |
|  5 | ขยะครวรเล็กไหม | ๓๑๗ (สามสี่สองห้าปกติ)  |
|  6 | ขยะครวรเล็กอสร้างอาห์ | ๒,๖๗๖ (สองพันหกร้อยสี่สิบ)  |
|  7 | ขยะคนอวัย | ๑๓๓ (หนึ่งร้อยสามสิบสาม)  |
|  8 | ขยะครวรเอาไว้เล็กไหม | ๑๖๒ (สามร้อยหกสิบสอง)  |
|  9 | ขยะคนซื้อไหม | ๗,๗๒๔ (สี่พันเอ็ดร้อยสี่สิบห้า)  |
|  10 | ขยะคราวรเล็กก็ไหม | ๑๖๖ (สี่ร้อยแปดสิบ)  |
|  11 | ขยะคราวรูปแบบ | ๑,๘๕๒ (หนึ่งพันแปดร้อยห้าสิบสอง)  |
|  12 | ขยะคนบริการไหม | ๕๖๗ (สี่ร้อยหกสิบเอ็ด)  |
|  13 | ขยะครวรคนไข่ประชาชน | ๒๓๐ (สองร้อยสามสิบ)  |
|  14 | ขยะคนไข่คนไข่ไหม | ๓๔ (สิบสี่)  |
|  15 | ขยะครวรคนไข่ไหม | ๕๕ (ห้าสิบห้า)  |
|  16 | ขยะคนอ่อนซื้อไหม | ๗๒ (เอ็ดสิบเอ็ด)  |
|  17 | ขยะคงโหยชนิด | ๘๖ (สามสิบหก)  |
|  18 | ขยะคนอัลลังกะไหม | ๑๐ (สิบ)  |
|  19 | ขยะคนที่เคยอวัยเอาไว้เล็กไหม | ๑๘ (สิบแปด)  |
|  20 | ขยะคนไข่ไหม | ๑๗ (สิบห้า)  |
|  ขยายแยกของบัญชีรายชื่อของหกททกานมีลง | ชื่อหกททกานมีลง | ได้ยอมรับ (ให้กรอกทั้งตัวแทนและตัวอักษร)  |
| --- | --- | --- |
|  21 | ขยะคงโหยชนิด | ๖๘ (หกสิบเอ็ด)  |
|  22 | ขยะคนไว้เล็กไหม | ๓๔ (สิบสี่)  |
|  23 | ขยะคราวรอสโหย | ๕๗ (ห้าสิบเอ็ด)  |
|  24 | ขยะคนไข่อย่างไหม | ๘๖ (สี่สิบสอง)  |
|  25 | ขยะคนซื้อไร้ไหม | ๘ (แปด)  |
|  26 | ขยะคนอ่อนไหม | ๒๖ (สี่สิบหก)  |
|  27 | ขยะคราวรอการไร้ไหม | ๙,๑๐๘ (สี่พันหนึ่งร้อยแปด)  |
|  28 | ขยะคงโหยหรือคนไว้ | ๗๘ (เอ็ดสิบแปด)  |
|  29 | ขยะคงโหยอาหารไหม | ๑,๖๖๘ (หนึ่งพันหกร้อยหกสิบห้า)  |
|  30 | ขยะคนแรงงานสร้างอาห์ | ๒๓ (สี่สิบเอ็ด)  |
|  31 | ขยะคราวรอการไหม | ๔๕ (สี่สิบห้า)  |
|  32 | ขยะคนรูปแบบอื่น (ร่างชาย) | ๒๓ (สี่สิบสาม)  |
|  33 | ขยะคราวรออาหารไหม | ๕๘ (ห้าสิบหก)  |
|  34 | ขยะคนบริการแปลงคนไข่ไหม | ๒๔ (สี่สิบสี่)  |
|  35 | ขยะคนบริเวณไหน | ๑๔,๕๘๘ (หนึ่งหนึ่งเล็กพันห้าร้อยสามสิบแปด)  |
|  36 | ขยะคนคนไข่ไหม | ๑๕ (สี่สิบห้า)  |
|  37 | ขยะคนไข่ไหม | ๑๖,๖๘ (หนึ่งร้อยสี่สิบ)  |
|  38 | ขยะคนไข่ไหม | ๑๗ (สิบสาม)  |
|  39 | ขยะคนไข่ไหม | ๑๘ (ห้าสิบหก)  |
|  40 | ขยะคนไข่ไหม | ๑๙ (สิบแปด)  |
|  41 | ขยะคนอ่อนไหม | ๑๙ (สิบแปด)  |
|  42 | ขยะคนบริเวณไหน | ๕๘๘ (ห้าร้อยเล็กสิบห้า)  |
|  ขยายแยกของบัญชีรายชื่อของหกททกานมีลง | ชื่อหกททกานมีลง | ได้ยอมรับ (ให้กรอกทั้งตัวแทนและตัวอักษร)  |
| --- | --- | --- |
|  43 | ขยะคนอัลปาเรนซ์ | ๑๓๘ (หนึ่งร้อยสามสิบแปด)  |
|  44 | ขยะคงโยบายไหม | ๑๔๘ (หนึ่งร้อยสี่สิบเอ็ด)  |
|  45 | ขยะคนปั่นสายม | ๖๖ (หกสิบหก)  |
|  46 | ขยะคราวรอชาย | ๕๗,๒๓๐ (สี่หนึ่งเอ็ดพันสองร้อยสามสิบ)  |
|  47 | ขยะคราวรอออสโหย | ๗๕ (เอ็ดสิบห้า)  |
|  48 | ขยะคงโหยสร้างไหม | ๑,๐๗๕ (หนึ่งพันเอ็ดสิบห้า)  |
|  49 | ขยะคงโหยบริเวณไหน | ๑๑๗ (แปดร้อยสามสิบสอง)  |
|  50 | ขยะคราวรออาอาหารไหม | ๔ (สี่)  |
|  51 | ขยะคนอ่อน | ๒๕ (สี่สิบห้า)  |
|  52 | ขยะคนหรือหัวอชายบางแห่งประหยัดไหม | ๙ (ห้า)  |
|  53 | ขยะคงโหยพืชไหม | ๖ (หก)  |
|  54 | ขยะคราวรออวัยไหม | ๑๓ (สิบสาม)  |
|  55 | ขยะคงโหยชนิดอื่น | ๘ (แปด)  |
|  56 | ขยะคนซื้อไว้บนโยบาย | ๑๔ (สิบสี่)  |
|  57 | ขยะคนอัลลังกะไรมาก | ๑๖ (สิบหก)  |
|  รวมคะแนนทั้งสิ้น |   | ๙๘,๙๖๗ (สี่พันเอ็ดพันสามร้อยหกสิบเอ็ด)  |

Processing:  28%|██▊       | 5/18 [00:40<01:55,  8.86s/doc]

|  ขอบเขต
ของรัฐสักขยัน
ของพวก
การเมือง | ชื่อ
พวกกการเมือง | โต้ตอบบน
(ให้กรอกทั้งตัวเลขและตัวอักษร) | หมายเหตุ  |
| --- | --- | --- | --- |
|  ๑ | ไทยทรัพย์ทวี | ๒๗๔ (สองร้อยเจ็ดสิบแปด) |   |
|  ๒ | เพื่อชาติไทย | ๑,๒๓๔ (หนึ่งพันสองร้อยสามสิบแปด) |   |
|  ๓ | ไทม์ | ๓๖๔ (เจ็ดร้อยเก้า) |   |
|  ๔ | มิติไทม์ | ๑๖๔ (หนึ่งร้อยหกสิบแปด) |   |
|  ๕ | รวมใจไทย | ๘๑๖ (แปดร้อยสิบหก) |   |
|  ๖ | รวมไทยสร้างชาติ | ๒,๖๗๓ (สองพันหกร้อยเจ็ดสิบสาม) |   |
|  ๗ | พลวัด | ๒,๔๖๒ (สองพันสี่ร้อยสอง) |   |
|  ๘ | ประชาธิปไตยไทม์ | ๕๖๔ (ห้าร้อยหกสิบสี่) |   |
|  ๙ | เพื่อไทย | ๑๑,๖๑๓ (หนึ่งหมื่นหนึ่งพันหกร้อยสามสิบสาม) |   |
|  ๑๐ | ท่าฉลือกไทม์ | ๕๗๕ (ห้าร้อยเจ็ดสิบห้า) |   |
|  ๑๑ | เศรษฐกิจ | ๓,๓๖๖ (สามพันเจ็ดร้อยหก) |   |
|  ๑๒ | เสร็จรวมไทย | ๔๗๔ (สี่ร้อยเก้าสิบเก้า) |   |
|  ๑๓ | รวมพลังประชาชน | ๘๑๐ (แปดร้อยสิบ) |   |
|  ๑๔ | ท้องที่ไทย | ๑๖๔ (หนึ่งร้อยหกสิบเก้า) |   |
|  ๑๕ | อนาคตไทย | ๘๗ (แปดสิบเจ็ด) |   |
|  ๑๖ | พลังเพื่อไทย | ๒๗๔ (สองร้อยเจ็ดสิบเก้า) |   |
|  ๑๗ | ไทยชนะ | ๑๔๔ (หนึ่งร้อยสี่สิบสี่) |   |
|  ๑๘ | พลังสังคมไทม์ | ๓๔ (สามสิบสี่) |   |
|  ๑๙ | สังคมประชาธิปไตยไทย | ๓๖ (สามสิบหก) |   |
|  ๒๐ | ฟิวชัน | ๔๖ (สี่สิบหก) |   |
|  ๒๑ | ไทรวมพลัง | ๔๖ (สี่สิบหก) |   |
|  ๒๒ | ก้าวอิสระ | ๔๓ (สี่สิบสาม) |   |
|  ๒๓ | ปวงชนไทย | ๖๗ (หกสิบเจ็ด) |   |
|  ๒๔ | วิชชั่นไทม์ | ๔๖ (สี่สิบหก) |   |
|  ๒๕ | เพื่อชีวิตไทม์ | ๓๗ (สามสิบเจ็ด) |   |
|  ขอบเขต
ของรัฐสักขยัน
ของพวก
การเมือง | ชื่อ
พวกกการเมือง | โต้ตอบบน
(ให้กรอกทั้งตัวเลขและตัวอักษร) | หมายเหตุ  |
|  ๒๖ | คลองไทย | ๕๗ (ห้าสิบเก้า) |   |
|  ๒๗ | ประชาธิปไตย | ๔,๒๓๑ (สี่พันสองร้อยสามสิบเอ็ด) |   |
|  ๒๘ | ไทยก้าวหน้า | ๑๗๖ (หนึ่งร้อยเจ็ดสิบหก) |   |
|  ๒๙ | ไทยภักดี | ๕๘๑ (ห้าร้อยแปดสิบเอ็ด) |   |
|  ๓๐ | แรงงานสร้างชาติ | ๑๐๖ (หนึ่งร้อยหก) |   |
|  ๓๑ | ประชากรไทย | ๑๖๓ (หนึ่งร้อยหกสิบสาม) |   |
|  ๓๒ | ครูไทยเพื่อประชาชน | ๑๐๗ (หนึ่งร้อยเจ็ด) |   |
|  ๓๓ | ประชาชาติ | ๑๔๖ (หนึ่งร้อยสี่สิบหก) |   |
|  ๓๔ | สร้างอนาคตไทย | ๑๕๐ (หนึ่งร้อยห้าสิบ) |   |
|  ๓๕ | รักชาติ | ๑๘๒ (หนึ่งร้อยแปดสิบสอง) |   |
|  ๓๖ | ไทยพร้อม | ๓๐๖ (สามร้อยหก) |   |
|  ๓๗ | ภูมิใจไทย | ๒๕,๔๐๖ (สองหมื่นห้าพันสี่ร้อยหก) |   |
|  ๓๘ | พลังธรรมไทม์ | ๑๔๑ (หนึ่งร้อยสี่สิบเอ็ด) |   |
|  ๓๙ | กรีน | ๕๘ (ห้าสิบแปด) |   |
|  ๔๐ | ไทยธรรม | ๕๙ (สี่สิบเก้า) |   |
|  ๔๑ | แผ่นดินธรรม | ๒๘ (ยี่สิบแปด) |   |
|  ๔๒ | กล้าธรรม | ๑๗๑ (หนึ่งร้อยเจ็ดสิบเอ็ด) |   |
|  ๔๓ | พลังประชารัฐ | ๒๒๕ (สองร้อยยี่สิบห้า) |   |
|  ๔๔ | โอกาสไทม์ | ๑๕๗ (หนึ่งร้อยห้าสิบเจ็ด) |   |
|  ๔๕ | เป็นธรรม | ๖๐ (หกสิบ) |   |
|  ๔๖ | ประชาชน | ๓๑,๗๒๒ (สามหมื่นหนึ่งพันเจ็ดร้อยยี่สิบสอง) |   |
|  ๔๗ | ประชาไทย | ๒๔๙ (สองร้อยสี่สิบเก้า) |   |
|  ๔๘ | ไทยสร้างไทย | ๓๕๘ (สามร้อยห้าสิบแปด) |   |
|  ๔๙ | ไทยก้าวไทม์ | ๓๓๗ (สามร้อยสามสิบเอ็ด) |   |
|  ๕๐ | ประชาอาสาชาติ | ๑๑ (สิบเอ็ด) |   |
|  ขอบเขต
ของรัฐสักขยัน
ของพวก
การเมือง | ชื่อ
พวกกการเมือง | โต้ตอบบน
(ให้กรอกทั้งตัวเลขและตัวอักษร) | หมายเหตุ  |
|  ๕๑ | พร้อม | ๖๑ (หกสิบเอ็ด) |   |
|  ๕๒ | เครือข่ายชาวนาแห่งประเทศไทย | ๑๑๕ (หนึ่งร้อยสิบห้า) |   |
|  ๕๓ | ไทยพิทักษ์ธรรม | ๑๗ (สิบเอ็ด) |   |
|  ๕๔ | ความหวังไทม์ | ๒๖ (ยี่สิบหก) |   |
|  ๕๕ | ไทยรวมไทย | ๒๔ (ยี่สิบสี่) |   |
|  ๕๖ | เพื่อบ้านเมือง | ๓๓ (สามสิบสาม) |   |
|  ๕๗ | พลังไทยรักชาติ | ๘๙ (แปดสิบเก้า) |   |
|  รวมคะแนนทั้งสิ้น |   | ๙๒,๖๔๙ (เก้าหมื่นสองพันหกร้อยสี่สิบเก้า) |   |

Processing:  33%|███▎      | 6/18 [00:50<01:48,  9.06s/doc]

|  หมายเลข
ของรัฐสังวลรัม
ของพรรค
การเมือง | ชื่อ
พรรคการเมือง | ได้คะแนน
(ให้กรอกทั้งตัวเลขและตัวอักษร) | หมายเหตุ  |
| --- | --- | --- | --- |
|  ๑ | ไทยขวัชย์ทวี | ๔๓๓ (สิริอยสามสิบสาม) |   |
|  ๒ | เพื่อชาติไทย | ๑,๘๘๕ (หนึ่งพันแปดร้อยแปดสิบห้า) |   |
|  ๓ | ไหม้ | ๔๓๑ (สิริอยสามสิบเอ็ด) |   |
|  หมายเลข
ของรัฐสังวลรัม
ของพรรค
การเมือง | ชื่อ
พรรคการเมือง | ได้คะแนน
(ให้กรอกทั้งตัวเลขและตัวอักษร) | หมายเหตุ  |
|  ๔ | อัติไหม้ | ๕๗๔ (ห้าร้อยเอ็ดสิบสี่) |   |
|  ๕ | รวมใจไทย | ๔,๗๑๐ (สี่พันเอ็ดร้อยสิบ) |   |
|  ๖ | รวมไทยสร้างชาติ | ๒,๖๔๐ (สองพันหกร้อยสี่สิบ) |   |
|  ๗ | ทสวัค | ๒๓๗ (สองร้อยสามสิบเอ็ด) |   |
|  ๘ | ประชาธิปไตยไหม้ | ๒,๖๖๙ (สองพันหกร้อยหกสิบเก้า) |   |
|  ๙ | เพื่อไทย | ๑๕,๑๘๘ (หนึ่งพันห้าพันหนึ่งร้อยแปดสิบแปด) |   |
|  ๑๐ | ทางเลือกไหม้ | ๖๗๒ (หกร้อยสามสิบสอง) |   |
|  ๑๑ | เศรษฐกิจ | ๔,๒๕๘ (สี่พันสองร้อยห้าสิบแปด) |   |
|  ๑๒ | เสรีรวมไทย | ๖๔๕ (หกร้อยสี่สิบห้า) |   |
|  ๑๓ | รวมพลังประชาชน | ๗๔๓ (เอ็ดร้อยสี่สิบสาม) |   |
|  ๑๔ | ท้องที่ไทย | ๘๓ (แปดสิบสาม) |   |
|  ๑๕ | อนาคตไทย | ๑๒๕ (หนึ่งร้อยสี่สิบห้า) |   |
|  ๑๖ | หลังเพื่อไทย | ๓๗๐ (สามร้อยเอ็ดสิบ) |   |
|  ๑๗ | ไทยขณะ | ๑๓๑ (หนึ่งร้อยสามสิบเอ็ด) |   |
|  ๑๘ | พลังสังคมไหม้ | ๕๑ (ห้าสิบเอ็ด) |   |
|  ๑๙ | สังคมประชาธิปไตยไทย | ๖๗ (หกสิบเอ็ด) |   |
|  ๒๐ | ฟิวชัน | ๕๘ (ห้าสิบแปด) |   |
|  ๒๑ | โหรวมพลัง | ๕๔ (ห้าสิบสี่) |   |
|  ๒๒ | ก้าวอิสระ | ๔๓ (สี่สิบสาม) |   |
|  ๒๓ | ปวงชนไทย | ๑๖๐ (หนึ่งร้อยหกสิบ) |   |
|  ๒๔ | วิชชั่นไหม้ | ๗๑ (เอ็ดสิบเอ็ด) |   |
|  ๒๕ | เพื่อชีวิตไหม้ | ๕๗ (ห้าสิบเอ็ด) |   |
|  ๒๖ | คลองไทย | ๓๖ (เก้าสิบหก) |   |
|  ๒๗ | ประชาธิปไตย | ๔,๐๙๔ (สี่พันเก้าสิบสี่) |   |
|  ๒๘ | ไทยก้าวหน้า | ๒๕๑ (สองร้อยห้าสิบเอ็ด) |   |
|  ๒๙ | ไทยภักดี | ๕๘๗ (ห้าร้อยแปดสิบเอ็ด) |   |
|  ๓๐ | แรงงานสร้างชาติ | ๑๕๐ (หนึ่งร้อยห้าสิบ) |   |
|  ๓๑ | ประชากรไทย | ๑๘๗ (หนึ่งร้อยแปดสิบเอ็ด) |   |
|  ๓๒ | ครูไทยเพื่อประชาชน | ๑๑๗ (หนึ่งร้อยสิบเก้า) |   |
|  ๓๓ | ประชาชาติ | ๑๕๖ (หนึ่งร้อยห้าสิบหก) |   |
|  ๓๔ | สร้างอนาคตไทย | ๒๕๗ (สองร้อยห้าสิบเอ็ด) |   |
|  ๓๕ | รักชาติ | ๑๗๖ (หนึ่งร้อยเก้าสิบหก) |   |
|  ๓๖ | ไทยพร้อม | ๑๕๐ (หนึ่งร้อยห้าสิบ) |   |
|  หมายเลข
ของรัฐสังวลรัม
ของพรรค
การเมือง | ชื่อ
พรรคการเมือง | ได้คะแนน
(ให้กรอกทั้งตัวเลขและตัวอักษร) | หมายเหตุ  |
|  ๓๗ | ภูมิใจไทย | ๑๗,๖๖๑ (หนึ่งพันเอ็ดพันหกร้อยหกสิบเอ็ด) |   |
|  ๓๘ | พลังธรรมไหม้ | ๒๐๖ (สองร้อยหก) |   |
|  ๓๙ | กรีน | ๓๗ (เอ็ดสิบเอ็ด) |   |
|  ๔๐ | ไทยธรรม | ๕๙ (ห้าสิบเก้า) |   |
|  ๔๑ | แผ่นดินธรรม | ๔๘ (สี่สิบแปด) |   |
|  ๔๒ | กล้าธรรม | ๒๒๐ (สองร้อยสี่สิบ) |   |
|  ๔๓ | พลังประชาธิปไตย | ๑๗๖ (หนึ่งร้อยเก้าสิบหก) |   |
|  ๔๔ | โอกาสไหม้ | ๓๔ (เอ็ดสิบสี่) |   |
|  ๔๕ | เป็นธรรม | ๓๕ (เก้าสิบห้า) |   |
|  ๔๖ | ประชาชน | ๓๔,๗๑๒ (สามหมื่นสี่พันเก้าร้อยสิบสอง) |   |
|  ๔๗ | ประชาไทย | ๑๗๔ (หนึ่งร้อยเก้าสิบสี่) |   |
|  ๔๘ | ไทยสร้างไทย | ๔๑๔ (สิริอยสิบสี่) |   |
|  ๔๙ | ไทยก้าวไหม้ | ๖๐๑ (หกร้อยเอ็ด) |   |
|  ๕๐ | ประชาอาสาชาติ | ๑๖ (สิบหก) |   |
|  ๕๑ | พร้อม | ๖๗ (หกสิบเอ็ด) |   |
|  ๕๒ | เครือข่ายชาวนาแห่งประเทศไทย | ๒๐ (สี่สิบ) |   |
|  ๕๓ | ไทยพิทักษ์ธรรม | ๒๑ (สี่สิบเอ็ด) |   |
|  ๕๔ | ความหวังไหม้ | ๓๐ (สามสิบ) |   |
|  ๕๕ | ไทยรวมไทย | ๓๕ (สามสิบห้า) |   |
|  ๕๖ | เพื่อบ้านเมือง | ๑๗ (สามสิบเอ็ด) |   |
|  ๕๗ | พลังไทยรักชาติ | ๘๓ (แปดสิบสาม) |   |
|  รวมคะแนนทั้งสิ้น |   | ๓๗,๖๒๔ (เก้าหมื่นเอ็ดพันหกร้อยสี่สิบสี่) |   |

Processing:  39%|███▉      | 7/18 [01:01<01:49,  9.91s/doc]

|  ข้อ/รายการ
ของข้อมูลที่ขายเพื่อ
ข้อแนะนำการ
การเมือง | ชื่อ
พราหการเมือง | ได้คะแนน
(ให้กรอกทั้งตัวเลขและตัวอักษร) | หมายเหตุ  |
| --- | --- | --- | --- |
|  ๑ | ไทยทวีพย์ทวี | ๑,๔๑๓
(หนึ่งพันสี่ร้อยสิบสาม) |   |
|  ๒ | เพื่อชาติไทย | ๗๔๕
(เจ็ดร้อยสี่สิบห้า) |   |
|  ๓ | ไหม่ | ๑๗๓
(หนึ่งร้อยเจ็ดสิบสาม) |   |
|  ๔ | มิติไหม่ | ๙๕
(เก้าสิบห้า) |   |
|  ๕ | รวมใจไทย | ๕๒๕
(ห้าร้อยสี่สิบห้า) |   |
|  ๖ | รวมไทยสร้างชาติ | ๒,๖๘๓
(สองพันหกร้อยเมปต์สิบสาม) |   |
|  ๗ | หมวัด | ๒๔๔
(สองร้อยสี่สิบสี่) |   |
|  ข้อ/รายการ
ของข้อมูลที่ขายเพื่อ
ข้อแนะนำการเมือง | ชื่อ
พราหการเมือง | ได้คะแนน
(ให้กรอกทั้งตัวเลขและตัวอักษร) | หมายเหตุ  |
| --- | --- | --- | --- |
|  ๘ | ประชาธิปไตยไหม่ | ๑๔๐
(สามร้อยสี่สิบ) |   |
|  ๙ | เพื่อไทย | ๕,๒๘๘
(ห้าพันสองร้อยเมปต์สิบแปด) |   |
|  ๑๐ | ทางเลือกไหม่ | ๔๖๙
(สี่ร้อยหกสิบเก้า) |   |
|  ๑๑ | เศรษฐกิจ | ๒,๕๗๗
(สองพันห้าร้อยเจ็ดสิบเจ็ด) |   |
|  ๑๒ | เสรีรวมไทย | ๕๓๔
(ห้าร้อยสามสิบสี่) |   |
|  ๑๓ | รวมพลังประชาชน | ๓๓๖
(สามร้อยสามสิบหก) |   |
|  ๑๔ | ห้องที่ไทย | ๓๐
(สามสิบ) |   |
|  ๑๕ | อนาคตไทย | ๓๖
(สามสิบหก) |   |
|  ๑๖ | พลังเพื่อไทย | ๙๗
(เก้าสิบเจ็ด) |   |
|  ๑๗ | ไทยชนะ | ๗๐
(เจ็ดสิบ) |   |
|  ๑๘ | พลังสังคมไหม่ | ๑๗
(สิบเจ็ด) |   |
|  ๑๙ | สังคมประชาธิปไตยไทย | ๓๗
(สามสิบเจ็ด) |   |
|  ๒๐ | ฟิวชัน | ๒๑
(สี่สิบเอ็ด) |   |
|  ๒๑ | ไทรวมพลัง | ๓๓
(สามสิบสาม) |   |
|  ๒๒ | ก้าวอิสระ | ๑๗
(สิบเจ็ด) |   |
|  ๒๓ | ปวงชนไทย | ๕๘
(ห้าสิบแปด) |   |
|  ๒๔ | วิชชั่นไหม่ | ๓๖
(สามสิบหก) |   |
|  ๒๕ | เพื่อชีวิตไหม่ | ๑๙
(สิบเก้า) |   |
|  ๒๖ | คลองไทย | ๔๑
(สี่สิบเอ็ด) |   |
|  ๒๗ | ประชาธิปไตย | ๕,๕๗๐
(ห้าพันห้าร้อยเจ็ดสิบ) |   |
|  ๒๘ | ไทยก้าวหน้า | ๗๙
(เจ็ดสิบเก้า) |   |
|  ๒๙ | ไทยภักดี | ๑,๕๓๕
(หนึ่งพันห้าร้อยสิบห้า) |   |
|  ๓๐ | แรงงานสร้างชาติ | ๑๒๕
(หนึ่งร้อยสี่สิบห้า) |   |
|  ๓๑ | ประชากรไทย | ๘๗
(แปดสิบเจ็ด) |   |
|  ๓๒ | ครูไทยเพื่อประชาชน | ๔๕
(สี่สิบห้า) |   |
|  ๓๓ | ประชาชาติ | ๖๔
(หกสิบสี่) |   |
|  ๓๔ | สร้างอนาคตไทย | ๖๔
(หกสิบสี่) |   |
|  ๓๕ | รักชาติ | ๑๐๑
(หนึ่งร้อยเอ็ด) |   |
|  ๓๖ | ไทยพร้อม | ๑๑๐
(หนึ่งร้อยสิบ) |   |
|  ๓๗ | ภูมิใจไทย | ๒๘,๗๔๗
(สองหมื่นแปดพันเด็ดร้อยสี่สิบเจ็ด) |   |
|  ๓๘ | พลังธรรมไหม่ | ๕๓
(ห้าสิบสาม) |   |
|  ๓๙ | กรีน | ๔๗
(สี่สิบเจ็ด) |   |
|  ๔๐ | ไทยธรรม | ๑๕
(สิบห้า) |   |
|  ๔๑ | แผ่นดินธรรม | ๑๒
(สิบสอง) |   |
|  ๔๒ | กล้าธรรม | ๑๐๓
(หนึ่งร้อยสาม) |   |
|  ๔๓ | พลังประชาธิปไตย | ๒๗๗
(สองร้อยเจ็ดสิบเจ็ด) |   |
|  ๔๔ | โอกาสไหม่ | ๔๓
(สี่สิบสาม) |   |
|  ข้อ
หมายเหตุ
ของข้อมูลที่ขายเพื่อ
ข้อแนะนำการเมือง | ชื่อ
พราหการเมือง | ได้คะแนน
(ให้กรอกทั้งตัวเลขและตัวอักษร) | หมายเหตุ  |
| --- | --- | --- | --- |
|  ๔๕ | เป็นธรรม | ๕๖
(ห้าสิบหก) |   |
|  ๔๖ | ประชาชน | ๔๔,๐๑๔
(สี่หมื่นสี่พันสิบสี่) |   |
|  ๔๗ | ประชาไทย | ๒๕๘
(สองร้อยห้าสิบแปด) |   |
|  ๔๘ | ไทยสร้างไทย | ๔๐๒
(สี่ร้อยสอง) |   |
|  ๔๙ | ไทยก้าวไหม่ | ๓๘๑
(สามร้อยแปดสิบเอ็ด) |   |
|  ๕๐ | ประชาอาสาชาติ | ๔
(สี่) |   |
|  ๕๑ | พร้อม | ๓๖
(สามสิบหก) |   |
|  ๕๒ | เครือข่ายชาวนาแห่งประเทศไทย | ๕
(ห้า) |   |
|  ๕๓ | ไทยฟิสิกษ์ธรรม | ๓
(สาม) |   |
|  ๕๔ | ความหวังไหม่ | ๑๖
(สิบหก) |   |
|  ๕๕ | ไทยรวมไทย | ๖
(หก) |   |
|  ๕๖ | เพื่อบ้านเมือง | ๑๖
(สิบหก) |   |
|  ๕๗ | พลังไทยรักชาติ | ๒๖
(สี่สิบหก) |   |

Processing:  44%|████▍     | 8/18 [01:13<01:44, 10.43s/doc]

|  ขอบเขต
ของบัญชีรายชื่อ
ของพรรค
การเมือง | ชื่อ
พรรคการเมือง | โต้ตอบบน
(ให้กรอกทั้งตัวเลขและตัวอักษร) | หมายเหตุ  |
| --- | --- | --- | --- |
|  ๑ | ไทยทรัพย์ทวี | ๒๖๑ (สองร้อยพบสืบเย็น) |   |
|  ๒ | เพื่อชาติไทย | ๓,๓๓๔ (หนึ่งพันสามร้อยสามสิบสี่) |   |
|  ๓ | ไทม์ | ๓,๒๒๘ (สามพันสองร้อยสี่สิบแปด) |   |
|  ๔ | มีดีไทม์ | ๒๑๘ (สองร้อยสิบแปด) |   |
|  ๕ | รวมใจไทย | ๙๘๐ (เก้าร้อยแปดสิบ) |   |
|  ๖ | รวมไทยสร้างชาติ | ๒,๙๒๖ (สองพันเก้าร้อยสี่สิบหก) |   |
|  ขอบเขต
ของบัญชีรายชื่อ
ของพรรค
การเมือง | ชื่อ
พรรคการเมือง | โต้ตอบบน
(ให้กรอกทั้งตัวเลขและตัวอักษร) | หมายเหตุ  |
| --- | --- | --- | --- |
|  ๗ | พลวัต | ๕๐๑ (ห้าร้อยเย็น) |   |
|  ๘ | ประชาธิปไตยไทม์ | ๗๓๑ (เจ็ดร้อยสามสิบเย็น) |   |
|  ๙ | เพื่อไทย | ๗,๓๑๒ (แปดพันสามร้อยสิบสอง) |   |
|  ๑๐ | ทางเลือกไทม์ | ๖๘๖ (หกร้อยแปดสิบหก) |   |
|  ๑๑ | เศรษฐกิจ | ๕,๕๑๗ (ห้าพันห้าร้อยสิบเก้า) |   |
|  ๑๒ | เสร็จรวมไทย | ๕๘๑ (ห้าร้อยเก้าสิบเจ็ด) |   |
|  ๑๓ | รวมพลังประชาชน | ๕๖๘ (ห้าร้อยหกสิบแปด) |   |
|  ๑๔ | ท้องที่ไทย | ๘๘ (แปดสิบแปด) |   |
|  ๑๕ | อนาคตไทย | ๘๒ (แปดสิบสอง) |   |
|  ๑๖ | พลังเพื่อไทย | ๑๗๒ (หนึ่งร้อยเจ็ดสิบสอง) |   |
|  ๑๗ | ไทยชนะ | ๑๑๗ (หนึ่งร้อยสิบเจ็ด) |   |
|  ๑๘ | พลังสังคมไทม์ | ๒๘ (สี่สิบแปด) |   |
|  ๑๙ | สังคมประชาธิปไตยไทย | ๖๗ (หกสิบเจ็ด) |   |
|  ๒๐ | ฟิวชัน | ๑๖ (สามสิบหก) |   |
|  ๒๑ | ไทรวมพลัง | ๕๔ (ห้าสิบสี่) |   |
|  ๒๒ | ก้าวอิสระ | ๑๖ (สามสิบหก) |   |
|  ๒๓ | ปวเชนไทย | ๘๗ (แปดสิบเจ็ด) |   |
|  ๒๔ | วิชชั่นไทม์ | ๔๐ (สี่สิบ) |   |
|  ๒๕ | เพื่อชีวิตไทม์ | ๓๗ (สามสิบเจ็ด) |   |
|  ๒๖ | ตลอดไทย | ๖๓ (หกสิบสาม) |   |
|  ๒๗ | ประชาธิปไตย | ๗,๓๕๖ (เจ็ดพันสามร้อยห้าสิบหก) |   |
|  ๒๘ | ไทยก้าวหน้า | ๑๔๒ (หนึ่งร้อยสี่สิบสอง) |   |
|  ๒๙ | ไทยกับดี | ๘๘๑ (แปดร้อยแปดสิบเย็น) |   |
|  ๓๐ | แรงงานสร้างชาติ | ๑๖๑ (หนึ่งร้อยหกสิบเย็น) |   |
|  ๓๑ | ประชากรไทย | ๑๑๖ (หนึ่งร้อยสามสิบหก) |   |
|  ๓๒ | ครูไทยเพื่อประชาชน | ๒๓๔ (สองร้อยสามสิบสี่) |   |
|  ๓๓ | ประชาชาติ | ๑๗๙ (หนึ่งร้อยเจ็ดสิบเก้า) |   |
|  ๓๔ | สร้างอนาคตไทย | ๑๓๔ (หนึ่งร้อยสามสิบสี่) |   |
|  ๓๕ | รักชาติ | ๑๑๙ (หนึ่งร้อยสิบเก้า) |   |
|  ๓๖ | ไทยพร้อม | ๒๑๓ (สองร้อยสิบสาม) |   |
|  ๓๗ | ภูมิใจไทย | ๒๔,๙๘๔ (สองหมื่นสี่พันเก้าร้อยแปดสิบสี่) |   |
|  ๓๘ | พลังธรรมไทม์ | ๑๕๗ (หนึ่งร้อยห้าสิบเจ็ด) |   |
|  ๓๙ | กรีน | ๕๘ (ห้าสิบแปด) |   |
|  ๔๐ | ไทยธรรม | ๘๖ (แปดสิบหก) |   |
|  ๔๑ | แผ่นดินธรรม | ๒๕ (สี่สิบห้า) |   |
|  ขอบเขต
ของบัญชีรายชื่อ
ของพรรค
การเมือง | ชื่อ
พรรคการเมือง | โต้ตอบบน
(ให้กรอกทั้งตัวเลขและตัวอักษร) | หมายเหตุ  |
| --- | --- | --- | --- |
|  ๔๒ | กล้ากรรม | ๑๔๔ (หนึ่งร้อยสี่สิบสี่) |   |
|  ๔๓ | พลังประชาธิปไตย | ๓๑๗ (สามร้อยสิบเจ็ด) |   |
|  ๔๔ | โอกาสไทม์ | ๓๓ (สามสิบสาม) |   |
|  ๔๕ | เป็นธรรม | ๕๒ (ห้าสิบสอง) |   |
|  ๔๖ | ประชาชน | ๓๑,๘๘๐ (สามหมื่นหนึ่งพันแปดร้อยแปดสิบ) |   |
|  ๔๗ | ประชาไทย | ๑๕๐ (หนึ่งร้อยห้าสิบ) |   |
|  ๔๘ | ไทยสร้างไทย | ๒๘๖ (สองร้อยแปดสิบหก) |   |
|  ๔๙ | ไทยก้าวไทม์ | ๒๓๔ (สองร้อยสามสิบสี่) |   |
|  ๕๐ | ประชาชนสาขาตี | ๔ (สี่) |   |
|  ๕๑ | พร้อม | ๗๒ (เจ็ดสิบสอง) |   |
|  ๕๒ | เครือข่ายชาวบ้านต่อประเทศไทย | ๕๑ (ห้าสิบเย็น) |   |
|  ๕๓ | ไทยพิทักษ์ธรรม | ๑๗ (สิบเจ็ด) |   |
|  ๕๔ | ความหวังไทม์ | ๒๗ (สี่สิบเจ็ด) |   |
|  ๕๕ | ไทยรวมไทย | ๒๒ (สี่สิบสอง) |   |
|  ๕๖ | เพื่อบ้านเมือง | ๕๖ (ห้าสิบหก) |   |
|  ๕๗ | พลังไทยรักชาติ | ๗๘ (เจ็ดสิบแปด) |   |
|  รวมคะแนนทั้งสิ้น |   | ๗๕,๐๕๖ (เก้าหมื่นห้าพันห้าสิบหก) |   |

Processing:  50%|█████     | 9/18 [01:24<01:36, 10.72s/doc]

|  ระบบ
ของผู้เข้ารหรือ
ของพรรค
การเมือง | ชื่อ
พรรคการเมือง | ได้คะแนน
(ให้กรอกทั้งตัวเลขและตัวอักษร) | หมายเหตุ  |
| --- | --- | --- | --- |
|  ๑ | ไทยทรัพย์ทวี | ๒๗๕ (สองร้อยเอ็ดสิบห้า) |   |
|  ๒ | เพื่อชาติไทย | ๕๐๗ (ห้าร้อยเอ็ด) |   |
|  ๓ | ไพม์ | ๓๕๒ (หนึ่งร้อยห้าสิบสอง) |   |
|  ๔ | อิติไพม์ | ๓๐๓ (หนึ่งร้อยสาม) |   |
|  ๕ | รวมใจไทย | ๔๕๔ (สี่ร้อยห้าสิบสี่) |   |
|  ๖ | รวมไทยสร้างชาติ | ๓,๗๑๑ (สามพันเจ็ดร้อยสามสิบเอ็ด) |   |
|  ๗ | พลวัต | ๑๒๐ (หนึ่งร้อยสี่สิบ) |   |
|  หมายเหตุ
ของผู้เข้ารหรือ
ของพรรค
การเมือง | ชื่อ
พรรคการเมือง | ได้คะแนน
(ให้กรอกทั้งตัวเลขและตัวอักษร) | หมายเหตุ  |
| --- | --- | --- | --- |
|  ๘ | ประชาธิปไตยใหม่ | ๓๔๙ (สามร้อยสี่สิบเก้า) |   |
|  ๙ | เพื่อไทย | ๕,๕๑๔ (ห้าพันห้าร้อยสิบสี่) |   |
|  ๑๐ | ทางเลือกใหม่ | ๔๑๐ (สี่ร้อยสิบ) |   |
|  ๑๑ | เศรษฐกิจ | ๓,๑๐๖ (สามพันหนึ่งร้อยหก) |   |
|  ๑๒ | เสร็จรวมไทย | ๖๕๙ (หกร้อยห้าสิบเก้า) |   |
|  ๑๓ | รวมพลังประชาชน | ๕๐๖ (ห้าร้อยหก) |   |
|  ๑๔ | ท้องที่ไทย | ๑๘ (สิบแปด) |   |
|  ๑๕ | อนาคตไทย | ๖๖ (หกสิบหก) |   |
|  ๑๖ | พลังเพื่อไทย | ๑๗๒ (หนึ่งร้อยสามสิบสอง) |   |
|  ๑๗ | ไทยขณะ | ๕๐ (ห้าสิบ) |   |
|  ๑๘ | พลังสังคมใหม่ | ๑๗ (สิบเอ็ด) |   |
|  ๑๙ | สังคมประชาธิปไตยไทย | ๑๗๑ (หนึ่งร้อยเก้าสิบเอ็ด) |   |
|  ๒๐ | ฟิวชัน | ๘ (แปด) |   |
|  ๒๑ | ไทรวมพลัง | ๕๓ (ห้าสิบสาม) |   |
|  ๒๒ | ก้าวอิสระ | ๑๗ (สิบเอ็ด) |   |
|  ๒๓ | ปวดชนไทย | ๑๔๓ (หนึ่งร้อยสี่สิบสาม) |   |
|  ๒๔ | วิชชั่นใหม่ | ๓๔ (สามสิบสี่) |   |
|  ๒๕ | เพื่อชีวิตใหม่ | ๑๑ (สิบเอ็ด) |   |
|  ๒๖ | คลองไทย | ๓๔ (สามสิบสี่) |   |
|  ๒๗ | ประชาธิปัตย์ | ๓,๕๘๙ (สามพันห้าร้อยแปดสิบเก้า) |   |
|  ๒๘ | ไทยก้าวหน้า | ๑๐๗ (หนึ่งร้อยเอ็ด) |   |
|  ๒๙ | ไทยภักดี | ๕๒๓ (ห้าร้อยสี่สิบสาม) |   |
|  ๓๐ | แรงงานสร้างชาติ | ๖๙ (หกสิบเก้า) |   |
|  ๓๑ | ประชากรไทย | ๖๖ (หกสิบหก) |   |
|  ๓๒ | ครูไทยเพื่อประชาชน | ๔๙ (สี่สิบเก้า) |   |
|  ๓๓ | ประชาชาติ | ๖๙ (หกสิบเก้า) |   |
|  ๓๔ | สร้างอนาคตไทย | ๖๓ (หกสิบสาม) |   |
|  ๓๕ | รักษาดี | ๑๑๕ (หนึ่งร้อยสิบห้า) |   |
|  ๓๖ | ไทยพร้อม | ๑๖๖ (หนึ่งร้อยหกสิบหก) |   |
|  ๓๗ | ภูมิใจไทย | ๑๗,๘๕๓ (หนึ่งหนึ่งเอ็ดพันแปดร้อยห้าสิบสาม) |   |
|  ๓๘ | พลังธรรมใหม่ | ๕๔ (ห้าสิบสี่) |   |
|  ๓๙ | กรีน | ๓๕ (สามสิบห้า) |   |
|  ๔๐ | ไทยธรรม | ๓๐ (สามสิบ) |   |
|  ๔๑ | แผ่นดินธรรม | ๑๗ (สิบเอ็ด) |   |
|  ๔๒ | กล้าธรรม | ๘๙ (แปดสิบเก้า) |   |
|  ๔๓ | พลังประชารัฐ | ๒๒๕ (สองร้อยสี่สิบห้า) |   |
|  ๔๔ | โอกาสใหม่ | ๒๐ (สี่สิบ) |   |
|  หมายเหตุ
ของผู้เข้ารหรือ
ของพรรค
การเมือง | ชื่อ
พรรคการเมือง | ได้คะแนน
(ให้กรอกทั้งตัวเลขและตัวอักษร) | หมายเหตุ  |
| --- | --- | --- | --- |
|  ๔๕ | เป็นธรรม | ๔๑ (สี่สิบเอ็ด) |   |
|  ๔๖ | ประชาชน | ๔๓,๑๗๒ (สี่หนึ่งสามพันสามร้อยเอ็ดสิบสอง) |   |
|  ๔๗ | ประชาไทย | ๑๒๙ (หนึ่งร้อยสี่สิบเก้า) |   |
|  ๔๘ | ไทยสร้างไทย | ๒๙๒ (สองร้อยเก้าสิบสอง) |   |
|  ๔๙ | ไทยก้าวใหม่ | ๒๑๐ (สองร้อยสิบ) |   |
|  ๕๐ | ประชาอาสาชาติ | ๖ (หก) |   |
|  ๕๑ | พร้อม | ๖๑ (หกสิบเอ็ด) |   |
|  ๕๒ | เครือข่ายชาวนาแห่งประเทศไทย | ๑๖ (สิบหก) |   |
|  ๕๓ | ไทยพิทักษ์ธรรม | ๔ (สี่) |   |
|  ๕๔ | ความหวังใหม่ | ๑๖ (สิบหก) |   |
|  ๕๕ | ไทยรวมไทย | ๙ (เก้า) |   |
|  ๕๖ | เพื่อบ้านเมือง | ๑๓ (สิบสาม) |   |
|  ๕๗ | พลังไทยรักชาติ | ๒๑ (สี่สิบเอ็ด) |   |
|  รวมคะแนนทั้งสิ้น |   | ๘๓,๗๘๙ (แปดหนึ่งสามพันเก้าร้อยแปดสิบเก้า) |   |

Processing:  56%|█████▌    | 10/18 [01:34<01:24, 10.57s/doc]

|  หมายเลขของบัญชี
รายชื่อของพรรค
การเมือง | สังกัด
พรรคการเมือง | ได้คะแนน
(ให้กรอกทั้งตัวเลขและตัวอักษร)  |
| --- | --- | --- |
|  ๑ | ไทยทรัพย์ทวี | ๒๕๘ (สองร้อยห้าสิบแปด)  |
|  ๒ | เพื่อชาติไทย | ๑,๐๗๘ (หนึ่งพันเจ็ดสิบแปด)  |
|  ๓ | ใหม่ | ๓๔๓ (สามร้อยสี่สิบสาม)  |
|  ๔ | มิติใหม่ | ๑๕๒ (หนึ่งร้อยห้าสิบสอง)  |
|  ๕ | รวมใจไทย | ๒,๕๐๗ (สองพันห้าร้อยเจ็ด)  |
|  ๖ | รวมไทยสร้างชาติ | ๑,๗๔๐ (หนึ่งพันเก้าร้อยสี่สิบ)  |
|  ๗ | พลวัต | ๖๗ (หกสิบเจ็ด)  |
|  ๘ | ประชาสืบโดยใหม่ | ๔๘๗ (สี่ร้อยแปดสิบเจ็ด)  |
|  ๙ | เพื่อไทย | ๖,๑๔๑ (หกพันหนึ่งร้อยสี่สิบเอ็ด)  |
|  ๑๐ | ทางเลือกใหม่ | ๔๒๖ (สี่ร้อยยี่สิบหก)  |
|  ๑๑ | เศรษฐกิจ | ๓,๑๒๒ (สามพันหนึ่งร้อยยี่สิบสอง)  |
|  ๑๒ | เสรีรวมไทย | ๕๐๔ (ห้าร้อยสี่)  |
|  ๑๓ | รวมพลังประชาชน | ๕๒๕ (ห้าร้อยยี่สิบห้า)  |
|  ๑๔ | ห้องที่ไทย | ๒๔ (ยี่สิบสี่)  |
|  ๑๕ | อนาคตไทย | ๕๕ (ห้าสิบห้า)  |
|  ๑๖ | พลังเพื่อไทย | ๓๔ (เก้าสิบสี่)  |
|  ๑๗ | ไทยชนะ | ๖๙ (หกสิบเก้า)  |
|  ๑๘ | พลังสังคมใหม่ | ๑๗ (สิบเจ็ด)  |
|  ๑๙ | สังคมประชาสืบโดยไทย | ๒๘ (ยี่สิบแปด)  |
|  ๒๐ | ฟิวชัน | ๑๘ (สิบแปด)  |
|  ๒๑ | ไทรวมพลัง | ๕๓ (ห้าสิบสาม)  |
|  ๒๒ | ก้าวอิสระ | ๒๑ (ยี่สิบเอ็ด)  |
|  ๒๓ | ปวงชนไทย | ๔๐ (สี่สิบ)  |
|  ๒๔ | วิชชั้นใหม่ | ๔๗ (สี่สิบเจ็ด)  |
|  ๒๕ | เพื่อชีวิตใหม่ | ๒๖ (ยี่สิบหก)  |
|  ๒๖ | คลองไทย | ๘๙ (แปดสิบเก้า)  |
|  ๒๗ | ประชาสืบ็ดยี่ | ๖,๖๕๖ (หกพันหกร้อยห้าสิบหก)  |
|  ๒๘ | ไทยก้าวหน้า | ๑๑๙ (หนึ่งร้อยสิบเก้า)  |
|  ๒๙ | ไทยภักดี | ๕๐๘ (ห้าร้อยแปด)  |
|  ๓๐ | แรงงานสร้างชาติ | ๗๙ (เจ็ดสิบเก้า)  |
|  หมายเลขของบัญชี
รายชื่อของพรรค
การเมือง | สังกัด
พรรคการเมือง | ได้คะแนน
(ให้กรอกทั้งตัวเลขและตัวอักษร)  |
| --- | --- | --- |
|  ๓๑ | ประชากรไทย | ๙๗ (เก้าสิบเจ็ด)  |
|  ๓๒ | ครูไทยเพื่อประชาชน | ๕๕ (ห้าสิบห้า)  |
|  ๓๓ | ประชาชาติ | ๘๙ (แปดสิบเก้า)  |
|  ๓๔ | สร้างอนาคตไทย | ๑๓๙ (หนึ่งร้อยสามสิบเก้า)  |
|  ๓๕ | รักชาติ | ๑๓๘ (หนึ่งร้อยสามสิบแปด)  |
|  ๓๖ | ไทยพร้อม | ๑๖๕ (หนึ่งร้อยหกสิบห้า)  |
|  ๓๗ | ภูมิใจไทย | ๑๖,๑๑๙ (หนึ่งหนึ่งหกพันหนึ่งร้อยสิบเก้า)  |
|  ๓๘ | พลังธรรมใหม่ | ๖๙ (หกสิบเก้า)  |
|  ๓๙ | กรีน | ๔๕ (สี่สิบห้า)  |
|  ๔๐ | ไทยธรรม | ๒๘ (ยี่สิบแปด)  |
|  ๔๑ | แผ่นดินธรรม | ๑๒ (สิบสอง)  |
|  ๔๒ | กล้าธรรม | ๑๐๓ (หนึ่งร้อยสาม)  |
|  ๔๓ | พลังประชารัฐ | ๑๓๐ (หนึ่งร้อยสามสิบ)  |
|  ๔๔ | โอกาสใหม่ | ๒๔ (ยี่สิบสี่)  |
|  ๔๕ | เป็นธรรม | ๖๖ (หกสิบหก)  |
|  ๔๖ | ประชาชน | ๓๙,๗๑๖ (สามหนึ่งเก้าพันเจ็ดร้อยสิบหก)  |
|  ๔๗ | ประชาไทย | ๑๓๓ (หนึ่งร้อยสามสิบสาม)  |
|  ๔๘ | ไทยสร้างไทย | ๔๒๔ (สี่ร้อยยี่สิบสี่)  |
|  ๔๙ | ไทยก้าวใหม่ | ๓๐๗ (สามร้อยเจ็ด)  |
|  ๕๐ | ประชาอาสาชาติ | ๔ (สี่)  |
|  ๕๑ | พร้อม | ๖๘ (หกสิบแปด)  |
|  ๕๒ | เครือข่ายชาวนาแห่งประเทศไทย | ๑๐ (สิบ)  |
|  ๕๓ | ไทยพิทักษ์ธรรม | ๑๑ (สิบเอ็ด)  |
|  ๕๔ | ความหวังใหม่ | ๒๒ (ยี่สิบสอง)  |
|  ๕๕ | ไทยรวมไทย | ๑๒ (สิบสอง)  |
|  ๕๖ | เพื่อบ้านเมือง | ๒๕ (ยี่สิบห้า)  |
|  ๕๗ | พลังไทยรักชาติ | ๓๗ (สามสิบเจ็ด)  |
|  รวมคะแนนทั้งสิ้น |   | ๘๓,๕๔๑ (แปดหนึ่งสามพันห้าร้อยสี่สิบเอ็ด)  |

Processing:  61%|██████    | 11/18 [01:43<01:09,  9.96s/doc]

|  หมายเลขของบัญชี
รายชื่อของพรรค
การเมือง | ลังกัด
พรรคการเมือง | ได้คะแนน
(ให้กรอกทั้งตัวเลขและตัวอักษร)  |
| --- | --- | --- |
|  ๑ | ไทยทรัพย์ทวี | ๓๐๒ (เจ็ดร้อยสอง)  |
|  ๒ | เพื่อชาติไทย | ๒,๓๓๘ (สองพันสามร้อยสามสิบแปด)  |
|  ๓ | ใหม่ | ๒,๘๓๔ (สองพันแปดร้อยเจ็ดสิบสี่)  |
|  ๔ | มิติใหม่ | ๗๗๒ (เจ็ดร้อยเจ็ดสิบสอง)  |
|  ๕ | รวมใจไทย | ๘๐๑ (แปดร้อยหนึ่ง)  |
|  ๖ | รวมไทยสร้างชาติ | ๒,๓๓๓ (สองพันสามร้อยเก้าสิบสาม)  |
|  ๗ | พลวัต | ๑๓๘ (หนึ่งร้อยสามสิบแปด)  |
|  ๘ | ประชาธิปไตยใหม่ | ๘๖๑ (แปดร้อยหกสิบหนึ่ง)  |
|  ๙ | เพื่อไทย | ๖,๗๑๖ (หกพันเจ็ดร้อยสิบหก)  |
|  ๑๐ | ทางเลือกใหม่ | ๖๒๔ (หกร้อยยี่สิบสี่)  |
|  ๑๑ | เศรษฐกิจ | ๗,๓๖๖ (เจ็ดพันสามร้อยหกสิบหก)  |
|  ๑๒ | เสรีรวมไทย | ๔๕๕ (สี่ร้อยห้าสิบห้า)  |
|  ๑๓ | รวมพลังประชาชน | ๕๗๑ (ห้าร้อยเจ็ดสิบหนึ่ง)  |
|  ๑๔ | ท้องที่ไทย | ๑๓๔ (หนึ่งร้อยสามสิบสี่)  |
|  ๑๕ | อนาคตไทย | ๗๗ (เจ็ดสิบเจ็ด)  |
|  ๑๖ | พลังเพื่อไทย | ๑๖๒ (หนึ่งร้อยหกสิบสอง)  |
|  ๑๗ | ไทยชนะ | ๑๗๗ (หนึ่งร้อยเจ็ดสิบเจ็ด)  |
|  ๑๘ | พลังสังคมใหม่ | ๑๙ (สิบเก้า)  |
|  ๑๙ | สังคมประชาธิปไตยไทย | ๕๓ (ห้าสิบสาม)  |
|  ๒๐ | ฟิวชัน | ๔๐ (สี่สิบ)  |
|  ๒๑ | ไทรวมพลัง | ๔๓ (สี่สิบสาม)  |
|  ๒๒ | ก้าวอิสระ | ๓๗ (สามสิบเจ็ด)  |
|  ๒๓ | ปวงชนไทย | ๘๒ (แปดสิบสอง)  |
|  ๒๔ | วิชชั่นใหม่ | ๘๖ (แปดสิบหก)  |
|  ๒๕ | เพื่อชีวิตใหม่ | ๒๖ (ยี่สิบหก)  |
|  ๒๖ | คอองไทย | ๑๔๖ (หนึ่งร้อยสี่สิบหก)  |
|  ๒๗ | ประชาธิปไตย | ๑๐,๓๕๐ (หนึ่งหมื่นสามร้อยห้าสิบ)  |
|  ๒๘ | ไทยก้าวหน้า | ๑๐๙ (หนึ่งร้อยเก้า)  |
|  ๒๙ | ไทยภักดี | ๕๓๔ (ห้าร้อยเจ็ดสี่)  |
|  ๓๐ | แรงงานสร้างชาติ | ๑๕๐ (หนึ่งร้อยห้าสิบ)  |
|  ๓๑ | ประชากรไทย | ๒๑๑ (สองร้อยสิบเอ็ด)  |
|  หมายเลขของบัญชี
รายชื่อของพรรค
การเมือง | ลังกัด
พรรคการเมือง | ได้คะแนน
(ให้กรอกทั้งตัวเลขและตัวอักษร)  |
| --- | --- | --- |
|  ๑๒ | ครูไทยเพื่อปวงชน | ๒๑๙ (สองร้อยสิบเก้า)  |
|  ๓๓ | ประชาชาติ | ๒๑๖ (สองร้อยสิบหก)  |
|  ๓๔ | สร้างอนาคตไทย | ๑๓๘ (หนึ่งร้อยสามสิบแปด)  |
|  ๓๕ | รักชาติ | ๑๖๘ (หนึ่งร้อยหกสิบแปด)  |
|  ๓๖ | ไทยพร้อม | ๑๔๙ (หนึ่งร้อยสี่สิบเก้า)  |
|  ๓๗ | ภูมิใจไทย | ๒๐,๔๙๑ (สองหมื่นสี่ร้อยเก้าสิบเอ็ด)  |
|  ๓๘ | พลังธรรมเนียม | ๑๒๒ (หนึ่งร้อยยี่สิบสอง)  |
|  ๓๙ | กรีน | ๕๐ (ห้าสิบ)  |
|  ๓๖ | ไทยธรรม | ๘๘ (แปดสิบแปด)  |
|  ๓๗ | แผ่นดินธรรม | ๒๖ (ยี่สิบหก)  |
|  ๓๘ | กล้าธรรม | ๑๗๖ (หนึ่งร้อยเจ็ดสิบหก)  |
|  ๓๙ | พลังประชารัฐ | ๑๗๖ (หนึ่งร้อยเจ็ดสิบหก)  |
|  ๓๙ | โอกาสใหม่ | ๖๑ (หกสิบเอ็ด)  |
|  ๓๔ | เป็นธรรม | ๖๘ (หกสิบแปด)  |
|  ๓๖ | ประชาชน | ๒๙,๑๐๑ (สองหมื่นเก้าพันหนึ่งร้อยเอ็ด)  |
|  ๓๗ | ประชาไทย | ๑๙๐ (หนึ่งร้อยเก้าสิบ)  |
|  ๓๘ | ไทยสร้างไทย | ๓๕๔ (เก้าร้อยห้าสิบสี่)  |
|  ๓๙ | ไทยก้าวใหม่ | ๑๗๕ (หนึ่งร้อยเจ็ดสิบห้า)  |
|  ๕๐ | ประชาอาสาชาติ | ๙ (เก้า)  |
|  ๕๑ | พร้อม | ๕๕ (ห้าสิบห้า)  |
|  ๕๒ | เครือข่ายชาวนาแห่งประเทศไทย | ๔๔ (สี่สิบสี่)  |
|  ๕๓ | ไทยพิทักษ์ธรรม | ๘ (แปด)  |
|  ๕๔ | ความทรงเหนือ | ๑๖ (สิบหก)  |
|  ๕๕ | ไทยรวมไทย | ๑๘ (สิบแปด)  |
|  ๕๖ | เพื่อบ้านเมือง | ๖๒ (หกสิบสอง)  |
|  ๕๗ | พลังไทยรักชาติ | ๘๓ (แปดสิบสาม)  |
|  รวมคะแนนทั้งสิ้น |   | ๙๑,๓๕๐ (เก้าพันหนึ่งพันเก้าร้อยห้าสิบ)  |

Processing:  67%|██████▋   | 12/18 [01:52<00:58,  9.68s/doc]

|  หมายเหตุ
ของปัญหีช่วยเพิ่ม
ของพวกเขา
การเมือง | ชื่อ
พวกเขาควรเมือง | ได้คะแนน
(ให้กรอกทั้งตัวเลขและตัวอักษร) | หมายเหตุ  |
| --- | --- | --- | --- |
|  ๑ | ไทยทรัพย์ทวี | ๑๗๑ (หนึ่งร้อยเอ็ดสิบสาม) |   |
|  ๒ | เพื่อชาติไทย | ๑,๓๓๖ (หนึ่งพันสามร้อยสามสิบหก) |   |
|  ๓ | ใหม่ | ๒๑๔ (สองร้อยสิบสี่) |   |
|  ๔ | มิติใหม่ | ๑๑๐ (หนึ่งร้อยสิบ) |   |
|  หมายเหตุ
ของปัญหีช่วยเพิ่ม
ของพวกเขา
การเมือง | ชื่อ
พวกเขาควรเมือง | ได้คะแนน
(ให้กรอกทั้งตัวเลขและตัวอักษร) | หมายเหตุ  |
| --- | --- | --- | --- |
|  ๕ | รวมใจไทย | ๓๘๘ (สามร้อยแปดสิบแปด) |   |
|  ๖ | รวมไทยสร้างชาติ | ๒,๓๑๓ (สองพันสามร้อยสิบสาม) |   |
|  ๗ | พลวัต | ๔๙๑ (สี่ร้อยเก้าสิบเอ็ด) |   |
|  ๘ | ประชาธิปไตยใหม่ | ๒,๔๔๔ (สองพันสี่ร้อยสี่สิบสี่) |   |
|  ๙ | เพื่อไทย | ๑๖,๕๘๓ (หนึ่งหมื่นหกพันห้าร้อยแปดสิบสาม) |   |
|  ๑๐ | ทางเลือกใหม่ | ๔๖๘ (สี่ร้อยหกสิบแปด) |   |
|  ๑๑ | เศรษฐกิจ | ๔,๓๗๕ (สี่พันสามร้อยเอ็ดสิบห้า) |   |
|  ๑๒ | เสรีรวมไทย | ๕๒๓ (ห้าร้อยสี่สิบสาม) |   |
|  ๑๓ | รวมพลังประชาชน | ๖๒๙ (หกร้อยสี่สิบเก้า) |   |
|  ๑๔ | ท้องที่ไทย | ๕๗ (ห้าสิบเอ็ด) |   |
|  ๑๕ | อนาคตไทย | ๑๓๙ (หนึ่งร้อยสามสิบเก้า) |   |
|  ๑๖ | พลังเพื่อไทย | ๑๘๙ (หนึ่งร้อยแปดสิบเก้า) |   |
|  ๑๗ | ไทยชนะ | ๙๖ (เก้าสิบหก) |   |
|  ๑๘ | พลังสังคมใหม่ | ๑๙ (สามสิบเก้า) |   |
|  ๑๙ | สังคมประชาธิปไตยไทย | ๑๘ (สามสิบแปด) |   |
|  ๒๐ | ฟิวชัน | ๓๐ (สามสิบ) |   |
|  ๒๑ | ไทรวมพลัง | ๓๗ (เอ็ดสิบเอ็ด) |   |
|  ๒๒ | ก้าวอิสระ | ๓๑ (สามสิบเอ็ด) |   |
|  ๒๓ | ปวเชนไทย | ๓๕ (สามสิบห้า) |   |
|  ๒๔ | วิชชั่นใหม่ | ๔๙ (สี่สิบเก้า) |   |
|  ๒๕ | เพื่อชีวิตใหม่ | ๑๕ (สิบห้า) |   |
|  ๒๖ | คลองไทย | ๔๘ (สี่สิบแปด) |   |
|  ๒๗ | ประชาธิปไตย | ๒,๘๓๘ (สองพันแปดร้อยสามสิบแปด) |   |
|  ๒๘ | ไทยก้าวหน้า | ๑๔๙ (หนึ่งร้อยสี่สิบเก้า) |   |
|  ๒๙ | ไทยภักดี | ๘๗๔ (แปดร้อยเอ็ดสิบเก้า) |   |
|  ๓๐ | แรงงานสร้างชาติ | ๘๐ (แปดสิบ) |   |
|  ๓๑ | ประชากรไทย | ๙๗ (เก้าสิบเอ็ด) |   |
|  ๓๒ | ครูไทยเพื่อประชาชน | ๙๕ (เก้าสิบห้า) |   |
|  ๓๓ | ประชาชาติ | ๑๒๔ (หนึ่งร้อยสี่สิบสี่) |   |
|  ๓๔ | สร้างอนาคตไทย | ๖๕ (หกสิบห้า) |   |
|  ๓๕ | รักชาติ | ๑๗๖ (หนึ่งร้อยเอ็ดสิบหก) |   |
|  ๓๖ | ไทยพร้อม | ๑๕๖ (หนึ่งร้อยห้าสิบหก) |   |
|  ๓๗ | ภูมิใจไทย | ๑๔,๘๘๑ (หนึ่งหมื่นสี่พันแปดร้อยเก้าสิบเอ็ด) |   |
|  ๓๘ | พลังธรรมใหม่ | ๑๘๗ (หนึ่งร้อยแปดสิบเอ็ด) |   |
|  ๓๙ | กรีน | ๖๕ (หกสิบห้า) |   |
|  หมายเหตุ
ของปัญหีช่วยเพิ่ม
ของพวกเขา
การเมือง | ชื่อ
พวกเขาควรเมือง | ได้คะแนน
(ให้กรอกทั้งตัวเลขและตัวอักษร) | หมายเหตุ  |
| --- | --- | --- | --- |
|  ๔๖ | ไทยธรรม | ๔๑ (สี่สิบเอ็ด) |   |
|  ๔๑ | แผ่นดินธรรม | ๒๕ (สี่สิบห้า) |   |
|  ๔๒ | กล้าธรรม | ๑๓๓ (หนึ่งร้อยสามสิบสาม) |   |
|  ๔๓ | พลังประชารัฐ | ๒๐๒ (สองร้อยสอง) |   |
|  ๔๔ | โอกาสใหม่ | ๓,๓๐๖ (สามพันสามร้อยหก) |   |
|  ๔๕ | เป็นธรรม | ๕๕ (ห้าสิบห้า) |   |
|  ๔๖ | ประชาชน | ๔๑,๐๕๑ (สี่หมื่นหนึ่งพันห้าสิบสาม) |   |
|  ๔๗ | ประชาไทย | ๒๓๒ (สองร้อยสามสิบสอง) |   |
|  ๔๘ | ไทยสร้างไทย | ๕๐๗ (ห้าร้อยเอ็ด) |   |
|  ๔๙ | ไทยก้าวใหม่ | ๔๑๓ (สี่ร้อยสิบสาม) |   |
|  ๕๐ | ประชาอาสาชาติ | ๘ (แปด) |   |
|  ๕๑ | พร้อม | ๕๖ (สี่สิบหก) |   |
|  ๕๒ | เครือข่ายชาวนาแห่งประเทศไทย | ๑๗ (สิบเอ็ด) |   |
|  ๕๓ | ไทยพิทักษ์ธรรม | ๑๐ (สิบ) |   |
|  ๕๔ | ความหวังใหม่ | ๒๕ (สี่สิบห้า) |   |
|  ๕๕ | ไทยรวมไทย | ๑๖ (สิบหก) |   |
|  ๕๖ | เพื่อบ้านเมือง | ๓๒ (สามสิบสอง) |   |
|  ๕๗ | พลังไทยรักชาติ | ๖๑ (หกสิบเอ็ด) |   |

Processing:  72%|███████▏  | 13/18 [02:03<00:50, 10.14s/doc]

|  พรวดตรง
ของบัญชีรายชื่อ
ของพรรคการเมือง | ชื่อ
พรรคการเมือง | ได้คะแนน
(ให้กรอกทั้งตัวเลขและตัวอักษร) | หมายเหตุ  |
| --- | --- | --- | --- |
|  ๑ | ไทยทรัพย์ทวี | ๒๔๔ (สองร้อยสีสิบสี) |   |
|  ๒ | เพื่อชาติไทย | ๑,๖๕๐ (หนึ่งพันหกร้อยห้าสิบ) |   |
|  ๓ | ใหม่ | ๒,๙๙๑ (สองพันเก้าร้อยเก้าสิบเอ็ด) |   |
|  ๔ | มิติใหม่ | ๒๑๖ (สองร้อยสีบหร) |   |
|  ๕ | รวมใจไทย | ๙๘๓ (เก้าร้อยสีสิบเอ็ด) |   |
|  พรวดตรง
ของบัญชีรายชื่อ
ของพรรคการเมือง | ชื่อ
พรรคการเมือง | ได้คะแนน
(ให้กรอกทั้งตัวเลขและตัวอักษร) | หมายเหตุ  |
| --- | --- | --- | --- |
|  ๖ | รวมไทยสร้างชาติ | ๒,๕๑๒ (สองพันห้าร้อยสิบสอง) |   |
|  ๗ | พลวัต | ๑๕๘ (หนึ่งร้อยห้าสิบแปด) |   |
|  ๘ | ประชาธิปไตยใหม่ | ๓๕๐ (สามร้อยห้าสิบ) |   |
|  ๙ | เพื่อไทย | ๑๗,๑๘๗ (หนึ่งหมื่นเอ็ดพันหนึ่งร้อยแปดสิบเอ็ด) |   |
|  ๑๐ | ท่าองค์ตาใหม่ | ๔๖๔ (สี่ร้อยหกสิบสี่) |   |
|  ๑๑ | เศรษฐกิจ | ๔,๔๕๓ (สี่พันสี่ร้อยห้าสิบสาม) |   |
|  ๑๒ | เสร็จรวมไทย | ๓๘๓ (สามร้อยแปดสิบสาม) |   |
|  ๑๓ | รวมพลังประชาชน | ๖๖๕ (หกร้อยหกสิบห้า) |   |
|  ๑๔ | ท้องฟ้ไทย | ๓๖ (สามสิบหก) |   |
|  ๑๕ | อนาคตไทย | ๑๕๖ (หนึ่งร้อยห้าสิบหก) |   |
|  ๑๖ | พลังเพื่อไทย | ๑๙๘ (หนึ่งร้อยเก้าสิบแปด) |   |
|  ๑๗ | ไทยชนะ | ๑๓๕ (หนึ่งร้อยสามสิบห้า) |   |
|  ๑๘ | พลังสังคมใหม่ | ๑๙ (สิบเก้า) |   |
|  ๑๙ | สังคมประชาธิปไตยไทย | ๕๕ (ห้าสิบห้า) |   |
|  ๒๐ | ฟิวชัน | ๓๗ (สามสิบเอ็ด) |   |
|  ๒๑ | ไทรวมพลัง | ๘๔ (แปดสิบสี่) |   |
|  ๒๒ | ก้าวอิสระ | ๑๙ (สิบเก้า) |   |
|  ๒๓ | ปวงชนไทย | ๔๖ (สี่สิบหก) |   |
|  ๒๔ | วิชชั่นใหม่ | ๔๕ (สี่สิบห้า) |   |
|  ๒๕ | เพื่อชีวิตใหม่ | ๓๘ (สามสิบแปด) |   |
|  ๒๖ | คลองไทย | ๕๕ (ห้าสิบห้า) |   |
|  ๒๗ | ประชาธิปัตย์ | ๓,๓๔๑ (สามพันสามร้อยสี่สิบเอ็ด) |   |
|  ๒๘ | ไทยก้าวหน้า | ๑๓๔ (หนึ่งร้อยสามสิบสี่) |   |
|  ๒๙ | ไทยภักดี | ๘๖๗ (แปดร้อยหกสิบเอ็ด) |   |
|  ๓๐ | แรงงานสร้างชาติ | ๙๖ (เก้าสิบหก) |   |
|  ๓๑ | ประชากรไทย | ๑๑๖ (หนึ่งร้อยสิบหก) |   |
|  ๓๒ | ครูไทยเพื่อประชาชน | ๒๐๘ (สองร้อยแปด) |   |
|  ๓๓ | ประชาชาติ | ๑๐๖ (หนึ่งร้อยหก) |   |
|  ๓๔ | สร้างอนาคตไทย | ๑๑๑ (หนึ่งร้อยสิบเอ็ด) |   |
|  ๓๕ | รักชาติ | ๑๓๑ (หนึ่งร้อยสามสิบเอ็ด) |   |
|  ๓๖ | ไทยพร้อม | ๑๒๗ (หนึ่งร้อยสี่สิบเอ็ด) |   |
|  ๓๗ | ภูมิใจไทย | ๑๔,๔๘๕ (หนึ่งหมื่นสี่พันสี่ร้อยแปดสิบห้า) |   |
|  ๓๘ | พลังธรรมใหม่ | ๒๓๓ (สองร้อยสามสิบสาม) |   |
|  ๓๙ | กรีน | ๕๓ (ห้าสิบสาม) |   |
|  ๔๐ | ไทยธรรม | ๕๔ (ห้าสิบสี่) |   |
|  ๔๑ | แผ่นดินธรรม | ๑๙ (สิบเก้า) |   |
|  พรวดตรง
ของบัญชีรายชื่อ
พรรคการเมือง | ชื่อ
พรรคการเมือง | ได้คะแนน
(ให้กรอกทั้งตัวเลขและตัวอักษร) | หมายเหตุ  |
| --- | --- | --- | --- |
|  ๔๒ | กล้าธรรม | ๑๗๐ (หนึ่งร้อยเอ็ดสิบ) |   |
|  ๔๓ | พลังประชาธิปไตย | ๒๑๘ (สองร้อยสิบแปด) |   |
|  ๔๔ | โอกาสใหม่ | ๖๑๗ (หกร้อยสิบเอ็ด) |   |
|  ๔๕ | เป็นธรรม | ๑๑๐ (หนึ่งร้อยสิบ) |   |
|  ๔๖ | ประชาชน | ๓๘,๒๖๔ (สามหมื่นแปดพันสองร้อยหกสิบเก้า) |   |
|  ๔๗ | ประชาไทย | ๑๒๑ (หนึ่งร้อยสี่สิบเอ็ด) |   |
|  ๔๘ | ไทยสร้างไทย | ๔๕๔ (สี่ร้อยห้าสิบสี่) |   |
|  ๔๙ | ไทยก้าวใหม่ | ๓๔๙ (สามร้อยสี่สิบเก้า) |   |
|  ๕๐ | ประชาอาสาชาติ | ๙ (เก้า) |   |
|  ๕๑ | พร้อม | ๕๖ (ห้าสิบหก) |   |
|  ๕๒ | เครือข่ายชาวบ้านหง่าประเทศไทย | ๑๖ (สิบหก) |   |
|  ๕๓ | ไทยพิทักษ์ธรรม | ๑๖ (สิบหก) |   |
|  ๕๔ | ความหวังใหม่ | ๓๓ (สามสิบสาม) |   |
|  ๕๕ | ไทยรวมไทย | ๓๐ (สามสิบ) |   |
|  ๕๖ | เพื่อบ้านเมือง | ๕๒ (ห้าสิบสอง) |   |
|  ๕๗ | พลังไทยรักชาติ | ๕๘ (ห้าสิบแปด) |   |
|  รวมคะแนนทั้งสิ้น |   | ๓๓,๘๐๒ (เก้าหมื่นสามพันแปดร้อยสอง) |   |

Processing:  78%|███████▊  | 14/18 [02:17<00:45, 11.27s/doc]

|  ขอบเขต
ของบัญชีรายชื่อ
ของพรรค
การเมือง | ชื่อ
พรรคการเมือง | ได้คะแนน
(ให้กรอกทั้งตัวเลขและตัวอักษร) | หมายเหตุ  |
| --- | --- | --- | --- |
|  ๑ | ไทยทรัพย์ทวี | ๔๒๐ (สี่ร้อยยี่สิบ) |   |
|  ๒ | เพื่อชาติไทย | ๑,๘๕๓ (หนึ่งพันแปดร้อยห้าสิบสาม) |   |
|  ๓ | ใหม่ | ๑,๐๘๕ (หนึ่งพันแปดสิบห้า) |   |
|  ขอบเขต
ของบัญชีรายชื่อ
ของพรรค
การเมือง | ชื่อ
พรรคการเมือง | ได้คะแนน
(ให้กรอกทั้งตัวเลขและตัวอักษร) | หมายเหตุ  |
|  ๔ | มิติใหม่ | ๒,๖๔๒ (สองพันหกร้อยสี่สิบสอง) |   |
|  ๕ | รวมใจไทย | ๑,๓๒๔ (หนึ่งพันเก้าร้อยสี่สิบสี่) |   |
|  ๖ | รวมไทยสร้างชาติ | ๑,๓๘๑ (หนึ่งพันเก้าร้อยแปดสิบเอ็ด) |   |
|  ๗ | พลวัค | ๑๓๔ (หนึ่งร้อยสามสิบสี่) |   |
|  ๘ | ประชาธิปไตยใหม่ | ๓๘๘ (สามร้อยแปดสิบแปด) |   |
|  ๙ | เพื่อไทย | ๑๓,๙๑๘ (หนึ่งหมื่นเอ็ดพันเก้าร้อยยี่สิบแปด) |   |
|  ๑๐ | ทางเลือกใหม่ | ๕๔๑ (ห้าร้อยสี่สิบเอ็ด) |   |
|  ๑๑ | เศรษฐกิจ | ๔,๒๓๗ (สี่พันสองร้อยสามสิบเอ็ด) |   |
|  ๑๒ | เสร็จรวมไทย | ๓๙๑ (สามร้อยเก้าสิบเอ็ด) |   |
|  ๑๓ | รวมพลังประชาชน | ๖๕๖ (หกร้อยห้าสิบหก) |   |
|  ๑๔ | ท้องที่ไทย | ๗๘ (เก้าสิบแปด) |   |
|  ๑๕ | อนาคตไทย | ๑๔๒ (หนึ่งร้อยสี่สิบสอง) |   |
|  ๑๖ | พลังเพื่อไทย | ๒๒๕ (สองร้อยยี่สิบห้า) |   |
|  ๑๗ | ไทยชนะ | ๑๓๑ (หนึ่งร้อยสามสิบเอ็ด) |   |
|  ๑๘ | พลังสังคมใหม่ | ๓๓ (สามสิบสาม) |   |
|  ๑๙ | สังคมประชาธิปไตยไทย | ๕๑ (ห้าสิบเอ็ด) |   |
|  ๒๐ | ฟิวชัน | ๓๙ (สามสิบเก้า) |   |
|  ๒๑ | โทรวมพลัง | ๑๐๑ (หนึ่งร้อยเอ็ด) |   |
|  ๒๒ | ก้าวอิสระ | ๓๖ (สามสิบหก) |   |
|  ๒๓ | ปวงชนไทย | ๙๒ (เก้าสิบสอง) |   |
|  ๒๔ | วิชชั่นใหม่ | ๕๒ (ห้าสิบสอง) |   |
|  ๒๕ | เพื่อชีวิตใหม่ | ๒๕ (ยี่สิบห้า) |   |
|  ๒๖ | คลองไทย | ๕๔ (ห้าสิบสี่) |   |
|  ๒๗ | ประชาธิปัตย์ | ๒,๘๐๙ (สองพันแปดร้อยเก้า) |   |
|  ๒๘ | ไทยก้าวหน้า | ๑๑๕ (หนึ่งร้อยสิบห้า) |   |
|  ๒๙ | ไทยภักดี | ๔๕๘ (สี่ร้อยห้าสิบแปด) |   |
|  ๓๐ | แรงงานสร้างชาติ | ๑๔๙ (หนึ่งร้อยสี่สิบเก้า) |   |
|  ๓๑ | ประชากรไทย | ๑๕๒ (หนึ่งร้อยห้าสิบสอง) |   |
|  ๓๒ | ครูไทยเพื่อประชาชน | ๑๔๒ (หนึ่งร้อยสี่สิบสอง) |   |
|  ๓๓ | ประชาชาติ | ๒๘๖ (สองร้อยแปดสิบหก) |   |
|  ๓๔ | สร้างอนาคตไทย | ๒๔๔ (สองร้อยสี่สิบสี่) |   |
|  ๓๕ | รักชาติ | ๒๓๓ (สองร้อยสามสิบสาม) |   |
|  ๓๖ | ไทยพร้อม | ๑๘๑ (หนึ่งร้อยแปดสิบเอ็ด) |   |
|  ขอบเขต
ของบัญชีรายชื่อ
ของพรรค
การเมือง | ชื่อ
พรรคการเมือง | ได้คะแนน
(ให้กรอกทั้งตัวเลขและตัวอักษร) | หมายเหตุ  |
|  ๓๗ | ภูมิใจไทย | ๑๓,๕๑๓ (หนึ่งหมื่นสามพันห้าร้อยสิบสาม) |   |
|  ๓๘ | พลังธรรมใหม่ | ๒๖๔ (สองร้อยหกสิบสี่) |   |
|  ๓๙ | กรีน | ๕๕ (ห้าสิบห้า) |   |
|  ๔๐ | ไทยธรรม | ๕๘ (ห้าสิบแปด) |   |
|  ๔๑ | แผ่นดินธรรม | ๒๖ (ยี่สิบหก) |   |
|  ๔๒ | กล้าธรรม | ๑๕๒ (หนึ่งร้อยห้าสิบสอง) |   |
|  ๔๓ | พลังประชารัฐ | ๒๓๔ (สองร้อยสามสิบสี่) |   |
|  ๔๔ | โอกาสใหม่ | ๒,๐๕๔ (สองพันห้าสิบสี่) |   |
|  ๔๕ | เป็นธรรม | ๑๐๑ (หนึ่งร้อยเอ็ด) |   |
|  ๔๖ | ประชาชน | ๒๗,๖๖๓ (สองหมื่นเอ็ดพันหกร้อยหกสิบสาม) |   |
|  ๔๗ | ประชาไทย | ๑๒๗ (หนึ่งร้อยสี่สิบเอ็ด) |   |
|  ๔๘ | ไทยสร้างไทย | ๓๖๕ (สามร้อยหกสิบห้า) |   |
|  ๔๙ | ไทยก้าวใหม่ | ๒๓๙ (สองร้อยสามสิบเก้า) |   |
|  ๕๐ | ประชาอาสาชาติ | ๑๖ (สิบหก) |   |
|  ๕๑ | พร้อม | ๕๙ (ห้าสิบเก้า) |   |
|  ๕๒ | เครือข่ายชาวนาแห่งประเทศไทย | ๑๙ (สิบเก้า) |   |
|  ๕๓ | ไทยพิทักษ์ธรรม | ๒๑ (ยี่สิบเอ็ด) |   |
|  ๕๔ | ความหวังใหม่ | ๒๔ (ยี่สิบสี่) |   |
|  ๕๕ | ไทยรวมไทย | ๒๓ (ยี่สิบสาม) |   |
|  ๕๖ | เพื่อบ้านเมือง | ๔๓ (สี่สิบสาม) |   |
|  ๕๗ | พลังไทยรักชาติ | ๑๑๑ (หนึ่งร้อยสิบเอ็ด) |   |
|  รวมคะแนนทั้งสิ้น |   | ๘๕,๑๙๕ (แปดหมื่นห้าพันหนึ่งร้อยเก้าสิบห้า) |   |

Processing:  83%|████████▎ | 15/18 [02:27<00:32, 10.78s/doc]

|  หมายเลขของบัญชี
รายชื่อของพรรค
การเมือง | ลั่งกัด
พรรคการเมือง | ได้คะแนน
(ให้กรอกตั้งตัวเลขและตัวอักษร)  |
| --- | --- | --- |
|  ๑ | ไทยทรัพย์ทวี | ๔๖๕ (สี่ร้อยหกสิบห้า)  |
|  ๒ | เพื่อชาติไทย | ๗๔๐ (เจ็ดร้อยสี่สิบ)  |
|  ๓ | ใหม่ | ๒๐๒ (สองร้อยสอง)  |
|  ๔ | มิติใหม่ | ๑๕๑ (หนึ่งร้อยห้าสิบเอ็ด)  |
|  ๕ | รวมใจไทย | ๓,๐๑๑ (สามพันสิบเอ็ด)  |
|  ๖ | รวมไทยสร้างชาติ | ๘๔๔ (แปดร้อยสี่สิบสี่)  |
|  ๗ | พลวัต | ๓๒๘ (สามร้อยสี่สิบแปด)  |
|  ๘ | ประชาธิปไตยใหม่ | ๖๖๑ (หกร้อยหกสิบเอ็ด)  |
|  ๙ | เพื่อไทย | ๗,๒๗๗ (เจ็ดพันสองร้อยเจ็ดสิบเอ็ด)  |
|  ๑๐ | ทางเลือกใหม่ | ๒๗๙ (สองร้อยเจ็ดสิบเก้า)  |
|  ๑๑ | เศรษฐกิจ | ๒,๘๙๖ (สองพันแปดร้อยเก้าสิบหก)  |
|  ๑๒ | เสร็จรวมไทย | ๒๓๖ (สองร้อยสามสิบหก)  |
|  ๑๓ | รวมพลังประชาชน | ๑๕๔ (สามร้อยห้าสิบสี่)  |
|  ๑๔ | ท้องที่ไทย | ๔๙ (สี่สิบเก้า)  |
|  ๑๕ | อนาคตไทย | ๗๓ (เจ็ดสิบสาม)  |
|  ๑๖ | พลังเพื่อไทย | ๑๔๐ (หนึ่งร้อยสี่สิบ)  |
|  ๑๗ | ไทยชนะ | ๑๔๓ (หนึ่งร้อยสี่สิบสาม)  |
|  ๑๘ | พลังสังคมใหม่ | ๒๐ (สี่สิบ)  |
|  ๑๙ | สังคมประชาธิปไตยไทย | ๑๘ (สิบแปด)  |
|  ๒๐ | ฟิวชัน | ๒๕ (สี่สิบห้า)  |
|  ๒๑ | ไทรวมพลัง | ๖๐ (หกสิบ)  |
|  ๒๒ | ก้าวอิสระ | ๒๕ (สี่สิบห้า)  |
|  ๒๓ | ปวงชนไทย | ๕๔ (ห้าสิบสี่)  |
|  ๒๔ | วิชชั่นใหม่ | ๓๗ (สามสิบเอ็ด)  |
|  ๒๕ | เพื่อชีวิตใหม่ | ๓๗ (สามสิบเอ็ด)  |
|  ๒๖ | คลองไทย | ๔๙ (สี่สิบเก้า)  |
|  ๒๗ | ประชาธิปไตย | ๑,๔๕๑ (หนึ่งพันสี่ร้อยห้าสิบเอ็ด)  |
|  ๒๘ | ไทยก้าวหน้า | ๗๖ (เจ็ดสิบหก)  |
|  ๒๙ | ไทยกักดี | ๒๖๖ (สองร้อยหกสิบหก)  |
|  ๓๐ | แรงงานสร้างชาติ | ๑๐๙ (หนึ่งร้อยเก้า)  |
|  ๓๑ | ประชากรไทย | ๒๖๓ (สองร้อยหกสิบสาม)  |
|  ๓๒ | ครูไทยเพื่อประชาชน | ๑๒๖ (หนึ่งร้อยสี่สิบหก)  |
|  ๓๓ | ประชาชาติ | ๘๗ (แปดสิบเอ็ด)  |
|  หมายเลขของบัญชี
รายชื่อของพรรค
การเมือง | ลั่งกัด
พรรคการเมือง | ได้คะแนน
(ให้กรอกตั้งตัวเลขและตัวอักษร)  |
| --- | --- | --- |
|  ๓๔ | สร้างอนาคตไทย | ๒๖๔ (สองร้อยหกสิบสี่)  |
|  ๓๕ | รักชาติ | ๓๓๔ (สามร้อยสามสิบสี่)  |
|  ๓๖ | ไทยพร้อม | ๒๒๕ (สองร้อยสี่สิบห้า)  |
|  ๓๗ | ภูมิใจไทย | ๓๙,๓๑๘ (สามหมื่นเก้าพันสามร้อยสิบแปด)  |
|  ๓๘ | พลังธรรมใหม่ | ๑๙๙ (หนึ่งร้อยเก้าสิบเก้า)  |
|  ๓๙ | กรีน | ๓๙ (สามสิบเก้า)  |
|  ๔๐ | ไทยธรรม | ๓๗ (สามสิบเอ็ด)  |
|  ๔๑ | แผ่นดินธรรม | ๒๗ (สี่สิบเอ็ด)  |
|  ๔๒ | กล้าอรวม | ๙๗ (เก้าสิบเอ็ด)  |
|  ๔๓ | พลังประชารัฐ | ๘๑ (แปดสิบเอ็ด)  |
|  ๔๔ | โอกาสใหม่ | ๒๗๖ (สองร้อยเจ็ดสิบหก)  |
|  ๔๕ | เป็นธรรม | ๖๑ (หกสิบเอ็ด)  |
|  ๔๖ | ประชาชน | ๑๖,๔๒๕ (หนึ่งหมื่นหกพันสี่ร้อยสี่สิบห้า)  |
|  ๔๗ | ประชาไทย | ๑๒๓ (หนึ่งร้อยสี่สิบสาม)  |
|  ๔๘ | ไทยสร้างไทย | ๑๘๔ (หนึ่งร้อยแปดสิบสี่)  |
|  ๔๙ | ไทยก้าวใหม่ | ๑๐๗ (หนึ่งร้อยเอ็ด)  |
|  ๕๐ | ประชาอาสาชาติ | ๘ (แปด)  |
|  ๕๑ | พร้อม | ๔๑ (สี่สิบเอ็ด)  |
|  ๕๒ | เครือข่ายชาวนาแห่งประเทศไทย | ๑๘ (สิบแปด)  |
|  ๕๓ | ไทยพิทักษ์ธรรม | ๑๕ (สิบห้า)  |
|  ๕๔ | ความหวังใหม่ | ๑๒ (สิบสอง)  |
|  ๕๕ | ไทยรวมไทย | ๒๑ (สี่สิบเอ็ด)  |
|  ๕๖ | เพื่อบ้านเมือง | ๓๖ (สามสิบหก)  |
|  ๕๗ | พลังไทยรักชาติ | ๘๗ (แปดสิบเอ็ด)  |
|  รวมคะแนนทั้งสิ้น |   | 78,587 (เจ็ดหมื่นแปดพันห้าร้อยแปดสิบเอ็ด)  |

Processing:  89%|████████▉ | 16/18 [02:37<00:21, 10.69s/doc]

|  ขอขอบเขต
ของบัญชีการเชื่อ
ของพรรค
การเมือง | ชื่อ
พรรคการเมือง | โต้ตอบแนว
(ให้การถกเยี่ยงตัวเลขและตัวอักษร) | หมายเหตุ  |
| --- | --- | --- | --- |
|  ๑ | ไทยทรัพย์ทวี | ๔๖๖ (สิร้อยสีสันพก) |   |
|  ๒ | เพื่อชาติไทย | ๑,๒๒๕ (หนึ่งพันสองร้อยสีสันเท้า) |   |
|  ๓ | ไหม | ๑,๘๕๗ (หนึ่งพันแปดร้อยสีเส้นเอ็ด) |   |
|  ขอขอบเขต
ของบัญชีการเชื่อ
ของพรรค
การเมือง | ชื่อ
พรรคการเมือง | โต้ตอบแนว
(ให้การถกเยี่ยงตัวเลขและตัวอักษร) | หมายเหตุ  |
|  ๔ | มีดีไหม | ๒,๓๔๔ (สองพันสามร้อยสีสันสี) |   |
|  ๕ | รวมใจไทย | ๕๗๑ (ห้าร้อยเก้าสิบเอ็ด) |   |
|  ๖ | รวมไทยสร้างชาติ | ๑,๑๕๖ (หนึ่งพันหนึ่งร้อยสีเส้นพก) |   |
|  ๗ | พลวัต | ๑๐๗ (หนึ่งร้อยเก้า) |   |
|  ๘ | ประชาธิปไตยไหม | ๑๐๑ (สิร้อยสาม) |   |
|  ๙ | เพื่อไทย | ๒๐,๓๘๙ (สองพันสามร้อยแปดสิบเก้า) |   |
|  ๑๐ | ทางเลือกไหม | ๓๓๖ (สามร้อยสามสันพก) |   |
|  ๑๑ | เศรษฐกิจ | ๕,๓๑๐ (ห้าพันสามร้อยสีบ) |   |
|  ๑๒ | เสรีรวมไทย | ๓๓๔ (สามร้อยสามสีบสี) |   |
|  ๑๓ | รวมพลังประชาชน | ๓๕๒ (สามร้อยสีเส้นสอง) |   |
|  ๑๔ | ท้องที่ไทย | ๕๖ (ห้าสิบพก) |   |
|  ๑๕ | อนาคตไทย | ๕๗ (ห้าสิบเอ็ด) |   |
|  ๑๖ | พลังเพื่อไทย | ๑๘๘ (หนึ่งร้อยแปดสิบแปด) |   |
|  ๑๗ | ไทยขณะ | ๑๐๓ (หนึ่งร้อยสาม) |   |
|  ๑๘ | พลังสังคมไหม | ๑๗ (สิบเอ็ด) |   |
|  ๑๙ | สังคมประชาธิปไตยไทย | ๒๘ (ยี่สิบแปด) |   |
|  ๒๐ | ฟิวชัน | ๒๐ (ยี่สิบ) |   |
|  ๒๑ | โทรวมพลัง | ๑๐๘ (หนึ่งร้อยแปด) |   |
|  ๒๒ | ก้าวอิสระ | ๕๐ (ห้าสิบ) |   |
|  ๒๓ | ปวงชนไทย | ๓๗ (เอ็ดสิบเก้า) |   |
|  ๒๔ | วิชชั่นไหม | ๖๒ (หกสิบสอง) |   |
|  ๒๕ | เพื่อชีวิตไหม | ๒๔ (ยี่สิบสี่) |   |
|  ๒๖ | คลองไทย | ๔๗ (สี่สิบเอ็ด) |   |
|  ๒๗ | ประชาธิปไตย | ๑,๔๙๖ (หนึ่งพันสี่ร้อยเก้าสิบพก) |   |
|  ๒๘ | ไทยก้าวหน้า | ๗๖ (เอ็ดสิบพก) |   |
|  ๒๙ | ไทยภักดี | ๒๗๙ (สองร้อยเอ็ดสิบเก้า) |   |
|  ๓๐ | แรงงานสร้างชาติ | ๑๒๑ (หนึ่งร้อยสี่สิบเอ็ด) |   |
|  ๓๑ | ประชากรไทย | ๑๖๙ (หนึ่งร้อยพกสิบเก้า) |   |
|  ๓๒ | ครูไทยเพื่อประชาชน | ๒๑๔ (สองร้อยสีบสี) |   |
|  ๓๓ | ประชาชาติ | ๒๗๐ (สองร้อยเอ็ดสิบ) |   |
|  ๓๔ | สร้างอนาคตไทย | ๑๘๙ (หนึ่งร้อยแปดสิบเก้า) |   |
|  ๓๕ | รักชาติ | ๑๑๙ (หนึ่งร้อยสีบเก้า) |   |
|  ๓๖ | ไทยพร้อม | ๑๕๓ (หนึ่งร้อยสีเส้นสาม) |   |
|  ขอขอบเขต
ของบัญชีการเชื่อ
ของพรรค
การเมือง | ชื่อ
พรรคการเมือง | โต้ตอบแนว
(ให้การถกเยี่ยงตัวเลขและตัวอักษร) | หมายเหตุ  |
|  ๓๗ | ภูมิใจไทย | ๒๗,๘๘๑ (สองพันเอ็ดพันแปดร้อยสีเส้นเอ็ด) |   |
|  ๓๘ | พลังธรรมไหม | ๔๓๖ (สิร้อยสามสันพก) |   |
|  ๓๙ | กรีน | ๕๖ (ห้าสิบพก) |   |
|  ๔๐ | ไทยธรรม | ๘๘ (แปดสิบแปด) |   |
|  ๔๑ | แผ่นดินธรรม | ๒๙ (ยี่สิบเก้า) |   |
|  ๔๒ | กล้าธรรม | ๑๗๐ (หนึ่งร้อยเอ็ดสิบ) |   |
|  ๔๓ | พลังประชาธิปไตย | ๑๐๕ (หนึ่งร้อยห้า) |   |
|  ๔๔ | โอกาสไหม | ๒๒ (ยี่สิบสอง) |   |
|  ๔๕ | เป็นธรรม | ๔๕ (สี่สิบห้า) |   |
|  ๔๖ | ประชาชน | ๑๖,๘๗๔ (หนึ่งพันพกพันแปดร้อยเอ็ดสิบสี) |   |
|  ๔๗ | ประชาไทย | ๑๓๖ (หนึ่งร้อยสามสันพก) |   |
|  ๔๘ | ไทยสร้างไทย | ๒๕๗ (สองร้อยสีเส้นเอ็ด) |   |
|  ๔๙ | ไทยก้าวไหม | ๑๓๕ (หนึ่งร้อยสามสันห้า) |   |
|  ๕๐ | ประชาอาสาชาติ | ๙ (เก้า) |   |
|  ๕๑ | พร้อม | ๓๙ (สามสิบเก้า) |   |
|  ๕๒ | เครือข่ายชาวนาแห่งประเทศไทย | ๒๐ (ยี่สิบ) |   |
|  ๕๓ | ไทยพิทักษ์ธรรม | ๘ (แปด) |   |
|  ๕๔ | ความหวังไหม | ๑๖ (สิบพก) |   |
|  ๕๕ | ไทยรวมไทย | ๑๓ (สิบสาม) |   |
|  ๕๖ | เพื่อบ้านเมือง | ๓๐ (สามสิบ) |   |
|  ๕๗ | พลังไทยรักชาติ | ๕๕ (ห้าสิบห้า) |   |
|  รวมคะแนนทั้งสิ้น |   | ๘/๕,๒๑๑ (แปดหนึ่งสำคัญของร้อยสิบเอ็ด)  |   |

Processing:  94%|█████████▍| 17/18 [02:45<00:09,  9.92s/doc]

|  หมายเลขของบัญชี
รายชื่อของพรรค
การเมือง | สังกัด
พรรคการเมือง | ได้คะแนน
(ให้กรอกทั้งตัวเลขและตัวอักษร)  |
| --- | --- | --- |
|  ๑ | ไทยทรัพย์ทวี | ๓๙๓ (สามร้อยเก้าสิบสาม)  |
|  ๒ | เพื่อชาติไทย | ๑,๕๙๑ (หนึ่งพันห้าร้อยเก้าสิบเอ็ด)  |
|  ๓ | ไน่น่ | ๔๕๗ (สี่ร้อยห้าสิบเจ็ด)  |
|  ๔ | มิติไน่น่ | ๒,๙๕๘ (สองพันเก้าร้อยห้าสิบแปด)  |
|  ๕ | รวมใจไทย | ๑,๔๙๐ (หนึ่งพันสี่ร้อยเก้าสิบ)  |
|  ๖ | รวมไทยสร้างชาติ | ๘๑๖ (แปดร้อยสิบหก)  |
|  ๗ | พลวัต | ๓๔๔ (สามร้อยสี่สิบสี่)  |
|  ๘ | ประชาธิปไตยไน่น่ | ๕๑๐ (ห้าร้อยสิบ)  |
|  ๙ | เพื่อไทย | ๑๗,๖๙๗ (หนึ่งหมื่นเจ็ดพันหกร้อยเก้าสิบเจ็ด)  |
|  ๑๐ | ทางเลือกไน่น่ | ๓๒๙ (สามร้อยยี่สิบเก้า)  |
|  ๑๑ | เศรษฐกิจ | ๔,๐๔๔ (สี่พันสี่สิบสี่)  |
|  ๑๒ | เสรีรวมไทย | ๓๙๑ (สามร้อยเก้าสิบเอ็ด)  |
|  ๑๓ | รวมพลังประชาชน | ๔๘๑ (สี่ร้อยแปดสิบเอ็ด)  |
|  ๑๔ | ท้องที่ไทย | ๑๐๙ (หนึ่งร้อยเก้า)  |
|  ๑๕ | อนาคตไทย | ๘๙ (แปดสิบเก้า)  |
|  ๑๖ | พลังเพื่อไทย | ๒๕๕ (สองร้อยห้าสิบห้า)  |
|  ๑๗ | ไทยชนะ | ๑๖๘ (หนึ่งร้อยหกสิบแปด)  |
|  ๑๘ | พลังสังคมไน่น่ | ๓๑ (สามสิบเอ็ด)  |
|  ๑๙ | สังคมประชาธิปไตยไทย | ๔๕ (สี่สิบห้า)  |
|  ๒๐ | ทิวชัน | ๕๐ (ห้าสิบ)  |
|  ๒๑ | ไทรวมพลัง | ๑,๔๗๕ (หนึ่งพันสี่ร้อยเจ็ดสิบห้า)  |
|  ๒๒ | ก้าวอิสระ | ๓๕ (สามสิบห้า)  |
|  ๒๓ | ปวงชนไทย | ๘๓ (แปดสิบสาม)  |
|  ๒๔ | วิชชั่นไน่น่ | ๗๓ (เจ็ดสิบสาม)  |
|  ๒๕ | เพื่อชีวิตไน่น่ | ๕๓ (ห้าสิบสาม)  |
|  หมายเลขของบัญชี
รายชื่อของพรรค
การเมือง | สังกัด
พรรคการเมือง | ได้คะแนน
(ให้กรอกทั้งตัวเลขและตัวอักษร)  |
|  ๒๖ | คลองไทย | ๖๔ (หกสิบสี่)  |
|  ๒๗ | ประชาธิปัตย์ | ๑,๕๒๒ (หนึ่งพันห้าร้อยยี่สิบสอง)  |
|  ๒๘ | ไทยก้าวหน้า | ๘๙ (แปดสิบเก้า)  |
|  ๒๙ | ไทยกักดี | ๒๓๖ (สองร้อยสามสิบหก)  |
|  ๓๐ | แรงงานสร้างชาติ | ๑๗๙ (หนึ่งร้อยเจ็ดสิบเก้า)  |
|  ๓๑ | ประชากรไทย | ๒๗๒ (สองร้อยเจ็ดสิบสอง)  |
|  ๓๒ | ครูไทยเพื่อประชาชน | ๑๖๑ (หนึ่งร้อยหกสิบเอ็ด)  |
|  ๓๓ | ประชาชาติ | ๓๖๒ (สามร้อยหกสิบสอง)  |
|  ๓๔ | สร้างอนาคตไทย | ๒๓๐ (สองร้อยสามสิบ)  |
|  ๓๕ | รักชาติ | ๑๒๖ (หนึ่งร้อยยี่สิบหก)  |
|  ๓๖ | ไทยพร้อม | ๓๕๙ (สามร้อยห้าสิบเก้า)  |
|  ๓๗ | ภูมิใจไทย | ๒๐,๔๔๑ (สองหมื่นสี่ร้อยสี่สิบเอ็ด)  |
|  ๓๘ | พลังธรรมไน่น่ | ๔๐๓ (สี่ร้อยสาม)  |
|  ๓๙ | กรีน | ๖๔ (หกสิบสี่)  |
|  ๔๐ | ไทยธรรม | ๙๖ (เก้าสิบหก)  |
|  ๔๑ | แผ่นดินธรรม | ๕๘ (ห้าสิบแปด)  |
|  ๔๒ | กล้าธรรม | ๑๔๘ (หนึ่งร้อยสี่สิบแปด)  |
|  ๔๓ | พลังประชารัฐ | ๓๓๑ (สามร้อยสามสิบเอ็ด)  |
|  ๔๔ | โอกาสไน่น่ | ๓๕ (สามสิบห้า)  |
|  ๔๕ | เป็นธรรม | ๔๙ (สี่สิบเก้า)  |
|  ๔๖ | ประชาชน | ๑๕,๑๙๕ (หนึ่งหมื่นห้าพันหนึ่งร้อยเก้าสิบห้า)  |
|  ๔๗ | ประชาไทย | ๑๙๙ (หนึ่งร้อยเก้าสิบเก้า)  |
|  ๔๘ | ไทยสร้างไทย | ๓๘๘ (สามร้อยแปดสิบแปด)  |
|  ๔๙ | ไทยก้าวไน่น่ | ๑๑๑ (หนึ่งร้อยสิบเอ็ด)  |
|  ๕๐ | ประชาอาสาชาติ | ๒๕ (ยี่สิบห้า)  |
|  ๕๑ | พร้อม | ๓๑ (สามสิบเอ็ด)  |
|  ๕๒ | เครือข่ายชาวนาแห่งประเทศไทย | ๒๐ (ยี่สิบ)  |
|  ๕๓ | ไทยพิทักษ์ธรรม | ๑๑ (สิบเอ็ด)  |
|  ๕๔ | ความหงั่งไน่น่ | ๑๗ (สิบเจ็ด)  |
|  ๕๕ | ไทยรวมไทย | ๓๐ (สามสิบ)  |
|  ๕๖ | เพื่อบ้านเมือง | ๓๖ (สามสิบหก)  |
|  ๕๗ | พลังไทยรักชาติ | ๗๘ (เจ็ดสิบแปด)  |
|  รวมคะแนนทั้งสิ้น | ๗๕,๓๓๓ (เจ็ดหมื่นห้าพันสามร้อยสามสิบสาม)  |   |

Processing: 100%|██████████| 18/18 [02:56<00:00,  9.82s/doc]

|  ขอบเขต
ของบัญชีรายชื่อ
ของสภาค
การเมือง | ชื่อ
พรรคการเมือง | ได้คะแนน
(ให้การถกที่สร้างลานลวดตัวอักษร) | หมายเหตุ  |
| --- | --- | --- | --- |
|  ๑ | ไทยทรัพย์ทวี | ๕๖๘ (ห้าร้อยสามสิบแปด) |   |
|  ๒ | เพื่อชาติไทย | ๓,๓๑๐ (สามพันสามร้อยสิบ) |   |
|  ขอบเขต
ของบัญชีรายชื่อ
ของสภาค
การเมือง | ชื่อ
พรรคการเมือง | ได้คะแนน
(ให้การถกที่สร้างลานลวดตัวอักษร) | หมายเหตุ  |
|  ๓ | ไทม์ | ๒๗๔ (สองร้อยเจ็ดสิบเก้า) |   |
|  ๔ | มีติไทม์ | ๒,๒๑๓ (สองพันสองร้อยสิบสาม) |   |
|  ๕ | รวมใจไทย | ๑๖๔ (สี่ร้อยสามสิบสี่) |   |
|  ๖ | รวมไทยสร้างชาติ | ๘๔๘ (แปดร้อยเก้าสิบแปด) |   |
|  ๗ | พลวัต | ๑๒๖ (หนึ่งร้อยสี่สิบหก) |   |
|  ๘ | ประชาธิปไตยไทม์ | ๗๐๓ (เจ็ดร้อยสาม) |   |
|  ๙ | เพื่อไทย | ๒๓,๓๕๗ (สองหมื่นสามพันสามร้อยห้าสิบเจ็ด) |   |
|  ๑๐ | ทางเลือกไทม์ | ๒๕๘ (สองร้อยห้าสิบแปด) |   |
|  ๑๑ | เศรษฐกิจ | ๒,๒๐๔ (สองพันสองร้อยเก้า) |   |
|  ๑๒ | เสร็จรวมไทย | ๒๒๗ (สองร้อยสี่สิบเจ็ด) |   |
|  ๑๓ | รวมพลังประชาชน | ๓๖๓ (สามร้อยหกสิบสาม) |   |
|  ๑๔ | ท้องที่ไทย | ๕๕ (ห้าสิบห้า) |   |
|  ๑๕ | อนาคตไทย | ๕๘ (ห้าสิบแปด) |   |
|  ๑๖ | พลังเพื่อไทย | ๑๘๔ (หนึ่งร้อยแปดสิบสี่) |   |
|  ๑๗ | ไทยชนะ | ๑๓๖ (หนึ่งร้อยสามสิบหก) |   |
|  ๑๘ | พลังสังคมไทม์ | ๓๓ (สามสิบสาม) |   |
|  ๑๙ | สังคมประชาธิปไตยไทย | ๔๓ (สี่สิบสาม) |   |
|  ๒๐ | จิตรชิน | ๓๓ (สามสิบสาม) |   |
|  ๒๑ | ไทรวมพลัง | ๑๒๕ (หนึ่งร้อยสี่สิบห้า) |   |
|  ๒๒ | ก้าวอิสระ | ๒๘ (สี่สิบแปด) |   |
|  ๒๓ | ปวงชนไทย | ๕๐ (ห้าสิบ) |   |
|  ๒๔ | วิชชั้นไทม์ | ๔๓ (สี่สิบสาม) |   |
|  ๒๕ | เพื่อชีวิตไทม์ | ๒๖ (สี่สิบหก) |   |
|  ๒๖ | คลองไทย | ๖๒ (หกสิบสอง) |   |
|  ๒๗ | ประชาธิปไตย | ๑,๐๕๓ (หนึ่งพันห้าสิบสาม) |   |
|  ๒๘ | ไทยก้าวหน้า | ๗๐ (เจ็ดสิบ) |   |
|  ๒๙ | ไทยภักดี | ๑๘๕ (หนึ่งร้อยแปดสิบห้า) |   |
|  ๓๐ | แรงงานสร้างชาติ | ๑๒๘ (หนึ่งร้อยสี่สิบแปด) |   |
|  ๓๑ | ประชากรไทย | ๓๔๒ (สามร้อยเก้าสิบสอง) |   |
|  ๓๒ | ครูไทยเพื่อประชาชน | ๒๓๔ (สองร้อยสามสิบสี่) |   |
|  ๓๓ | ประชาชาติ | ๒๕๕ (สองร้อยห้าสิบห้า) |   |
|  ๓๔ | สร้างอนาคตไทย | ๑๑๑ (หนึ่งร้อยสิบเอ็ด) |   |
|  ขอบเขต
ของบัญชีรายชื่อ
ของสภาค
การเมือง | ชื่อ
พรรคการเมือง | ได้คะแนน
(ให้การถกที่สร้างลานลวดตัวอักษร) | หมายเหตุ  |
| --- | --- | --- | --- |
|  ๓๕ | รักชาติ | ๙๖ (เก้าสิบหก) |   |
|  ๓๖ | ไทยพร้อม | ๑๘๑ (หนึ่งร้อยแปดสิบเอ็ด) |   |
|  ๓๗ | ภูมิใจไทย | ๒๑,๑๖๖ (สองหมื่นหนึ่งพันหนึ่งร้อยหกสิบหก) |   |
|  ๓๘ | พลังธรรมไทม์ | ๑๖๔ (สี่ร้อยเจ็ดสิบสี่) |   |
|  ๓๙ | กรีน | ๗๓ (เจ็ดสิบสาม) |   |
|  ๔๐ | ไทยธรรม | ๔๐ (สี่สิบ) |   |
|  ๔๑ | แผ่นดินธรรม | ๓๐ (สามสิบ) |   |
|  ๔๒ | กล้าธรรม | ๑๕๘ (หนึ่งร้อยห้าสิบแปด) |   |
|  ๔๓ | พลังประชาธิปไตย | ๘๑ (แปดสิบเอ็ด) |   |
|  ๔๔ | โอกาสไทม์ | ๓๔ (สามสิบสี่) |   |
|  ๔๕ | เป็นธรรม | ๓๖ (สามสิบหก) |   |
|  ๔๖ | ประชาชน | ๑๖,๖๗๔ (หนึ่งหมื่นหกพันหกร้อยเจ็ดสิบสี่) |   |
|  ๔๗ | ประชาไทย | ๑๐๗ (หนึ่งร้อยเจ็ด) |   |
|  ๔๘ | ไทยสร้างไทย | ๑๘๒ (หนึ่งร้อยแปดสิบสอง) |   |
|  ๔๙ | ไทยก้าวไทม์ | ๑๔๙ (หนึ่งร้อยสี่สิบเก้า) |   |
|  ๕๐ | ประชากรสชาติ | ๖ (หก) |   |
|  ๕๑ | พร้อม | ๒๐ (สี่สิบ) |   |
|  ๕๒ | เครือข่ายชาวนาแห่งประเทศไทย | ๑๕ (สิบห้า) |   |
|  ๕๓ | ไทยพิทักษ์ธรรม | ๕ (ห้า) |   |
|  ๕๔ | ความหวังไทม์ | ๑๖ (สิบหก) |   |
|  ๕๕ | ไทยรวมไทย | ๑๕ (สิบห้า) |   |
|  ๕๖ | เพื่อบ้านเมือง | ๒๕ (สี่สิบห้า) |   |
|  ๕๗ | พลังไทยรักชาติ | ๔๘ (สี่สิบแปด) |   |
|  รวมคะแนนทั้งสิ้น |   | ๗๗,๘๕๐ (เจ็ดหมื่นเจ็ดพันแปดร้อยห้าสิบ) |   |

ประกาศ ณ วันที่ ๔ กุมภาพันธ์/๕๗, ๒๕๖๔

In [98]:
output_df = submission_df.drop(['doc_id', 'party_name'], axis=1)
output_df

                        id  votes
0      constituency_10_1_1  14813
1      constituency_10_1_2  14368
2      constituency_10_1_3    979
3      constituency_10_1_4    244
4      constituency_10_1_5    351
...                    ...    ...
10048  party_list_34_11_53     14
10049  party_list_34_11_54     41
10050  party_list_34_11_55     29
10051  party_list_34_11_56     41
10052  party_list_34_11_57     71

[10053 rows x 2 columns]

In [99]:
output_df.to_csv("submission3.csv", index=False)

In [100]:
for key, values in happen.items():
	if values == {}:
		print(key)

party_list_10_24

In [121]:
with open("../anormaly/party_list_10_24.json") as f:
    data = json.load(f)

for item in data:
    party = item["สังกัดพรรคการเมือง"].strip()
    vote_raw = item["คะแนน"].strip()
    try:
        vote = thai_num_to_int(vote_raw)
        match = process.extractOne(party, KNOWN_PARTIES, scorer=fuzz.ratio)
        if match and match[1] >= 60:
            canonical = match[0]
            mask = (submission_df["doc_id"] == "party_list_10_24") & (submission_df["party_name"] == canonical)
            submission_df.loc[mask, "votes"] = vote
    except Exception as e:
        print(f"Error: {party} - {e}")

In [123]:
output_df = submission_df.drop(['doc_id', 'party_name'], axis=1)
output_df

                        id  votes
0      constituency_10_1_1  14813
1      constituency_10_1_2  14368
2      constituency_10_1_3    979
3      constituency_10_1_4    244
4      constituency_10_1_5    351
...                    ...    ...
10048  party_list_34_11_53     14
10049  party_list_34_11_54     41
10050  party_list_34_11_55     29
10051  party_list_34_11_56     41
10052  party_list_34_11_57     71

[10053 rows x 2 columns]

In [124]:
output_df.to_csv("submission3.csv", index=False)