In [1]:
import pandas as pd
import os
from typhoon_ocr import ocr_document
from bs4 import BeautifulSoup
import re
from rapidfuzz import fuzz, process
from tqdm import tqdm

In [2]:
os.environ["TYPHOON_OCR_API_KEY"] = "sk-ogvTcIwhoNXX69zmxalfZwZXW8JU5YcohnT4ISIgLTTapvJQ"

In [ ]:
[]asddadsadasdasdasdasd]

                        id      party_name  votes             doc_id
0      constituency_10_1_1    ประชาธิปัตย์      0  constituency_10_1
1      constituency_10_1_2       ภูมิใจไทย      0  constituency_10_1
2      constituency_10_1_3        เศรษฐกิจ      0  constituency_10_1
3      constituency_10_1_4        กล้าธรรม      0  constituency_10_1
4      constituency_10_1_5           พลวัต      0  constituency_10_1
...                    ...             ...    ...                ...
10048  party_list_34_11_53  ไทยพิทักษ์ธรรม      0   party_list_34_11
10049  party_list_34_11_54    ความหวังใหม่      0   party_list_34_11
10050  party_list_34_11_55       ไทยรวมไทย      0   party_list_34_11
10051  party_list_34_11_56  เพื่อบ้านเมือง      0   party_list_34_11
10052  party_list_34_11_57  พลังไทยรักชาติ      0   party_list_34_11

[10053 rows x 4 columns]

In [6]:
old_submission_df = pd.read_csv('./submission.csv')
old_submission_df

                        id  votes
0      constituency_10_1_1  14813
1      constituency_10_1_2  14368
2      constituency_10_1_3    979
3      constituency_10_1_4    244
4      constituency_10_1_5    351
...                    ...    ...
10048  party_list_34_11_53     14
10049  party_list_34_11_54     41
10050  party_list_34_11_55      0
10051  party_list_34_11_56     29
10052  party_list_34_11_57     43

[10053 rows x 2 columns]