### Setup

In [53]:
import pandas as pd
import os
from typhoon_ocr import ocr_document
from bs4 import BeautifulSoup
import re
from rapidfuzz import fuzz, process
from tqdm import tqdm

In [54]:
os.environ["TYPHOON_OCR_API_KEY"] = "sk-ogvTcIwhoNXX69zmxalfZwZXW8JU5YcohnT4ISIgLTTapvJQ"

In [55]:
SUBMISSION_PATH = "../data/submission_template.csv"

In [56]:
template_df = pd.read_csv(SUBMISSION_PATH)
template_df

                        id             doc_id  row_num      party_name  votes
0      constituency_10_1_1  constituency_10_1        1    ประชาธิปัตย์      0
1      constituency_10_1_2  constituency_10_1        2       ภูมิใจไทย      0
2      constituency_10_1_3  constituency_10_1        3        เศรษฐกิจ      0
3      constituency_10_1_4  constituency_10_1        4        กล้าธรรม      0
4      constituency_10_1_5  constituency_10_1        5           พลวัต      0
...                    ...                ...      ...             ...    ...
10048  party_list_34_11_53   party_list_34_11       53  ไทยพิทักษ์ธรรม      0
10049  party_list_34_11_54   party_list_34_11       54    ความหวังใหม่      0
10050  party_list_34_11_55   party_list_34_11       55       ไทยรวมไทย      0
10051  party_list_34_11_56   party_list_34_11       56  เพื่อบ้านเมือง      0
10052  party_list_34_11_57   party_list_34_11       57  พลังไทยรักชาติ      0

[10053 rows x 5 columns]

### EDA

In [57]:
template_df['party_name'].unique()

array(['ประชาธิปัตย์', 'ภูมิใจไทย', 'เศรษฐกิจ', 'กล้าธรรม', 'พลวัต',
       'ประชาชน', 'เพื่อไทย', 'ไทยภักดี', 'รวมไทยสร้างชาติ', 'ปวงชนไทย',
       'ไทยสร้างไทย', 'โอกาสใหม่', 'วิชชั่นใหม่', 'ประชาธิปไตยใหม่',
       'รักชาติ', 'ไทยก้าวใหม่', 'ทางเลือกใหม่', 'พลังประชารัฐ',
       'ประชากรไทย', 'ความหวังใหม่', 'อนาคตไทย', 'บ้านเมือง',
       'เพื่อบ้านเมือง', 'ไทยก้าวหน้า', 'รวมไทยสร้าง', 'แรงงานสร้างชาติ',
       'ไทยชนะ', 'พร้อม', 'ไทยพิทักษ์ธรรม', 'ไทยก้าวไทย', 'ไทยก้าวใหม',
       'เสรีรวมไทย', 'เป็นธรรม', 'ไทยธรรม', 'ฟิวชน', 'ฟิวชัน',
       'รวมพลังประชาชน', 'แรงงานสร้างไทย', 'ไทยสร้างชาติ', nan,
       'ปวงชนชาวไทย', 'กลาธรรม', 'สังคมประชาธิปไตยไทย', 'คลองไทย',
       'รวมใจไทย', 'รวมไทยสร้างชา', 'รักษ์ธรรม', 'ชาติ', 'ไทยพร้อม',
       'สร้างชาติ', 'ใหม่', 'พลังสังคมใหม่', 'สร้างอนาคตไทย',
       'ไทยทรัพย์ทวี', 'รวมพลัง', 'ไทรวมพลัง', 'เพื่อชาติไทย', 'มิติใหม่',
       'ท้องที่ไทย', 'พลังเพื่อไทย', 'ก้าวอิสระ', 'เพื่อชีวิตใหม่',
       'ครูไทยเพื่อประชาชน', 'ประชาชาติ', 'พลังธรรมใหม่', 'กรีน',
       'แผ่นดินธรรม', 'ประชาไทย', 'ประชาอาสาชาติ',
       'เครือข่ายชาวนาแห่งประเทศไทย', 'ไทยรวมไทย', 'พลังไทยรักชาติ',
       'ไทยรวมพลัง', 'พลังธรรมไทย', 'บิติใหม่', 'วิชั่นใหม่',
       'สังคมประชาธิปไตย', 'กาวอิสระ', 'แผนดินธรรม', 'พรอม', 'ฟิวซัน',
       'พลังประเสริฐ', 'ฟิวชั่น', 'วิชชันใหม่', 'ประชาติปไตยใหม่',
       'UNKNOWN', 'บ่วงชนไทย', 'เครือข่าวชาวนาแห่งประเทศไทย', 'พรรคที่ 1',
       'รวมพลังประชาชน์', 'สังคมใหม่', 'พรรคที่ 1 (ไม่ระบุชื่อ)',
       'ครูไทยเพื่อปวงชน', 'พรรครวมใจไทย', 'อนาคตใหม่', 'ประชาธิปปัตย์',
       'เครือข่ายชาวนา', 'ไม่ระบุ', 'หลังสังคมใหม่', 'กริน', 'กสิกรธรรม',
       'ชาติพัฒนา', 'Unknown Party', 'วิชซั่นใหม่', 'วิชชั่นไทย',
       'เพื่อบ้านใหม่'], dtype=object)

In [58]:
template_df.head()

                    id             doc_id  row_num    party_name  votes
0  constituency_10_1_1  constituency_10_1        1  ประชาธิปัตย์      0
1  constituency_10_1_2  constituency_10_1        2     ภูมิใจไทย      0
2  constituency_10_1_3  constituency_10_1        3      เศรษฐกิจ      0
3  constituency_10_1_4  constituency_10_1        4      กล้าธรรม      0
4  constituency_10_1_5  constituency_10_1        5         พลวัต      0

In [59]:
invalid_name = ["Unknown Party", "พรรคที่ 1 (ไม่ระบุชื่อ)", "ไม่ระบุ"]

NaN_df = template_df[
    template_df['party_name'].isna() | template_df['party_name'].isin(invalid_name)
]

NaN_df

,id,doc_id,row_num,party_name,votes
737,constituency_14_2_10,constituency_14_2,10,NaN,0
738,constituency_14_2_11,constituency_14_2,11,NaN,0
739,constituency_14_2_12,constituency_14_2,12,NaN,0
740,constituency_14_2_13,constituency_14_2,13,NaN,0
741,constituency_14_2_14,constituency_14_2,14,NaN,0
742,constituency_14_2_15,constituency_14_2,15,NaN,0
743,constituency_14_2_16,constituency_14_2,16,NaN,0
744,constituency_14_2_17,constituency_14_2,17,NaN,0
2698,party_list_10_3_1,party_list_10_3,1,NaN,0
2700,party_list_10_3_3,party_list_10_3,3,NaN,0
6461,party_list_21_4_1,party_list_21_4,1,พรรคที่ 1 (ไม่ระบุชื่อ),0
6892,party_list_24_2_33,party_list_24_2,33,NaN,0
7031,party_list_25_1_1,party_list_25_1,1,NaN,0
7033,party_list_25_1_3,party_list_25_1,3,NaN,0
7375,party_list_27_3_1,party_list_27_3,1,ไม่ระบุ,0
8000,party_list_30_4_1,party_list_30_4,1,Unknown Party,0
9426,party_list_33_2_1,party_list_33_2,1,NaN,0

In [60]:
# 737 - 744 Correctly Null
template_df.iloc[737]

id            constituency_14_2_10
doc_id           constituency_14_2
row_num                         10
party_name                     NaN
votes                            0
Name: 737, dtype: object

In [61]:
# 2698
template_df.iloc[2698]

id            party_list_10_3_1
doc_id          party_list_10_3
row_num                       1
party_name                  NaN
votes                         0
Name: 2698, dtype: object

In [62]:
# 2700
template_df.iloc[2700]

id            party_list_10_3_3
doc_id          party_list_10_3
row_num                       3
party_name                  NaN
votes                         0
Name: 2700, dtype: object

In [63]:
# 6461
template_df.iloc[6461]

id                  party_list_21_4_1
doc_id                party_list_21_4
row_num                             1
party_name    พรรคที่ 1 (ไม่ระบุชื่อ)
votes                               0
Name: 6461, dtype: object

In [64]:
# 6892
template_df.iloc[6892]

id            party_list_24_2_33
doc_id           party_list_24_2
row_num                       33
party_name                   NaN
votes                          0
Name: 6892, dtype: object

In [65]:
# 7031
template_df.iloc[7031]

id            party_list_25_1_1
doc_id          party_list_25_1
row_num                       1
party_name                  NaN
votes                         0
Name: 7031, dtype: object

In [66]:
# 7033
template_df.iloc[7033]

id            party_list_25_1_3
doc_id          party_list_25_1
row_num                       3
party_name                  NaN
votes                         0
Name: 7033, dtype: object

In [67]:
# 8000
template_df.iloc[8000]

id            party_list_30_4_1
doc_id          party_list_30_4
row_num                       1
party_name        Unknown Party
votes                         0
Name: 8000, dtype: object

In [68]:
# 9426
template_df.iloc[9426]

id            party_list_33_2_1
doc_id          party_list_33_2
row_num                       1
party_name                  NaN
votes                         0
Name: 9426, dtype: object

In [69]:
fix_invalid = {
    2698: ('ไทยทรัพย์ทวี', 31),
    2700: ('ใหม่', 149),
    6461: ('ไทยทรัพย์ทวี', 473),
    6892: ('ประชาชาติ', 632),
    7031: ('ไทยทรัพย์ทวี', 2250),
    7033: ('ใหม่', 481),
    8000: ('ไทยทรัพย์ทวี', 420),
    9426: ('ไทยทรัพย์ทวี', 347)
}

In [70]:
# Fix invalid
for idx, (party, vote) in fix_invalid.items():
    template_df.loc[idx, 'party_name'] = party
    template_df.loc[idx, 'votes'] = vote

for idx, (party, vote) in fix_invalid.items():
    print(template_df.iloc[idx])
    print()

id            party_list_10_3_1
doc_id          party_list_10_3
row_num                       1
party_name         ไทยทรัพย์ทวี
votes                        31
Name: 2698, dtype: object

id            party_list_10_3_3
doc_id          party_list_10_3
row_num                       3
party_name                 ใหม่
votes                       149
Name: 2700, dtype: object

id            party_list_21_4_1
doc_id          party_list_21_4
row_num                       1
party_name         ไทยทรัพย์ทวี
votes                       473
Name: 6461, dtype: object

id            party_list_24_2_33
doc_id           party_list_24_2
row_num                       33
party_name             ประชาชาติ
votes                        632
Name: 6892, dtype: object

id            party_list_25_1_1
doc_id          party_list_25_1
row_num                       1
party_name         ไทยทรัพย์ทวี
votes                      2250
Name: 7031, dtype: object

id            party_list_25_1_3
doc_id          party_list_25_1
row_num                       3
party_name                 ใหม่
votes                       481
Name: 7033, dtype: object

id            party_list_30_4_1
doc_id          party_list_30_4
row_num                       1
party_name         ไทยทรัพย์ทวี
votes                       420
Name: 8000, dtype: object

id            party_list_33_2_1
doc_id          party_list_33_2
row_num                       1
party_name         ไทยทรัพย์ทวี
votes                       347
Name: 9426, dtype: object

### Extraction

In [71]:
def thai_num_to_int(text: str) -> int:

    thai_to_arabic = str.maketrans("๐๑๒๓๔๕๖๗๘๙", "0123456789")
    text = text.translate(thai_to_arabic)

    # remove non-numeric prefixes
    text = re.sub(r"[^\d,]", " ", text)

    match = re.search(r"[\d,]+", text)
    if not match:
        raise ValueError("No numeric value found")

    return int(match.group().replace(",", ""))

In [72]:
def extract_party_score_dict(html: str) -> dict:
    soup = BeautifulSoup(html, "html.parser")

    table = soup.find("table")
    if table is None:
        raise ValueError("No <table> found")

    rows = table.find_all("tr")
    if not rows:
        return {}

    headers = [td.get_text(strip=True) for td in rows[0].find_all(["td", "th"])]

    # Candidate labels
    party_candidates = ["พรรคการเมือง", "ชื่อพรรคการเมือง", "สังกัดพรรคการเมือง"]
    score_candidates = ["ได้คะแนน"]

    party_idx = None
    score_idx = None
    best_party_score = 0
    best_score_score = 0

    for i, h in enumerate(headers):
        # compute best similarity across all candidates
        party_sim = max(fuzz.partial_ratio(h, c) for c in party_candidates)
        score_sim = max(fuzz.partial_ratio(h, c) for c in score_candidates)

        if party_sim > best_party_score:
            best_party_score = party_sim
            party_idx = i

        if score_sim > best_score_score:
            best_score_score = score_sim
            score_idx = i

    if best_party_score < 60 or best_score_score < 60:
        raise ValueError("Required columns not confidently found")

    result = {}

    for row in rows[1:]:
        cols = [td.get_text(strip=True) for td in row.find_all("td")]

        if len(cols) <= max(party_idx, score_idx):
            continue

        key = cols[party_idx]
        value = cols[score_idx]

        try:
            value = thai_num_to_int(value)
        except Exception:
            continue  # safer: skip invalid rows

        result[key] = value

    return result

In [73]:
def extraction(path):
    try:
        if not os.path.exists(path):
            return {}
        markdown = ocr_document(
            pdf_or_image_path=path
        )
        party_dict = extract_party_score_dict(markdown)
        return party_dict
    except Exception as e:
        print(e.__str__())
        return {}

### Inference

In [74]:
def merge_pages(*pages):
    merged = {}
    for page in pages:
        if page is None:
            continue
        for k, v in page.items():
            merged[k] = merged.get(k, 0) + v
    return merged

In [75]:
def assign_votes(df, vote_dict, threshold=80):
    # Remove non-party keys
    vote_dict = {
        k: v for k, v in vote_dict.items()
        if k != 'รวมคะแนนทั้งสิ้น'
    }

    keys = list(vote_dict.keys())

    def get_vote(party_name):
        match = process.extractOne(
            party_name,
            keys,
            scorer=fuzz.ratio
        )
        
        if match is None:
            return 0
        
        best_key, score, _ = match
        
        if score >= threshold:
            return vote_dict[best_key]
        return 0

    df['votes'] = df['party_name'].apply(get_vote)
    return df

In [76]:
submission_df = template_df.copy()

In [77]:
PREFIX = "../data/images/"

doc_ids = submission_df['doc_id'].unique()

In [78]:
for doc_id in tqdm(doc_ids, desc="Processing", unit="doc"):
    try:
        pages = []

        for i in range(1, 11):
            if i == 1:
                path = PREFIX + doc_id + ".png"
            else:
                path = PREFIX + doc_id + f"_page{i}.png"

            pages.append(extraction(path))

        vote_dict = merge_pages(*pages)

        mask = submission_df['doc_id'] == doc_id

        submission_df.loc[mask] = assign_votes(
            submission_df.loc[mask].copy(),
            vote_dict,
            threshold=80
        )

    except Exception as e:
        print(f"{doc_id}: {str(e)}")

Processing:   0%|          | 0/300 [00:00<?, ?doc/s]

No <table> found

Processing:   0%|          | 1/300 [00:19<1:37:08, 19.49s/doc]

No <table> found
No <table> found

Processing:   1%|          | 3/300 [01:21<2:29:11, 30.14s/doc]

No <table> found
No <table> found

Processing:   1%|▏         | 4/300 [01:38<2:04:01, 25.14s/doc]

Required columns not confidently found
No <table> found

Processing:   2%|▏         | 5/300 [02:06<2:08:16, 26.09s/doc]

No <table> found

Processing:   2%|▏         | 6/300 [02:37<2:16:57, 27.95s/doc]

No <table> found
No <table> found

Processing:   2%|▏         | 7/300 [03:01<2:10:03, 26.63s/doc]

No <table> found

Processing:   3%|▎         | 8/300 [03:20<1:57:49, 24.21s/doc]

No <table> found

Processing:   3%|▎         | 9/300 [03:47<2:00:40, 24.88s/doc]

No <table> found
No <table> found

Processing:   3%|▎         | 10/300 [04:15<2:05:24, 25.94s/doc]

No <table> found
No <table> found

Processing:   4%|▎         | 11/300 [04:40<2:03:44, 25.69s/doc]

No <table> found
No <table> found

Processing:   4%|▍         | 13/300 [05:36<2:13:36, 27.93s/doc]

No <table> found

Processing:   5%|▍         | 14/300 [06:16<2:29:18, 31.32s/doc]

No <table> found

Processing:   5%|▌         | 15/300 [06:56<2:41:39, 34.03s/doc]

No <table> found
No <table> found

Processing:   5%|▌         | 16/300 [07:26<2:36:00, 32.96s/doc]

No <table> found
No <table> found

Processing:   6%|▌         | 17/300 [07:54<2:27:40, 31.31s/doc]

No <table> found

Processing:   6%|▌         | 18/300 [08:10<2:05:43, 26.75s/doc]

No <table> found

Processing:   6%|▋         | 19/300 [08:35<2:02:33, 26.17s/doc]

No <table> found

Processing:   7%|▋         | 20/300 [08:59<1:59:03, 25.51s/doc]

No <table> found
No <table> found

Processing:   7%|▋         | 21/300 [09:20<1:52:08, 24.12s/doc]

No <table> found

Processing:   7%|▋         | 22/300 [09:48<1:57:23, 25.34s/doc]

No <table> found

Processing:   8%|▊         | 23/300 [10:18<2:03:46, 26.81s/doc]

No <table> found
No <table> found

Processing:   8%|▊         | 24/300 [10:49<2:08:54, 28.02s/doc]

No <table> found
No <table> found

Processing:   9%|▉         | 27/300 [12:21<2:13:06, 29.25s/doc]

Required columns not confidently found

Processing:   9%|▉         | 28/300 [12:41<1:59:25, 26.34s/doc]

No <table> found
No <table> found

Processing:  10%|▉         | 29/300 [12:58<1:47:08, 23.72s/doc]

No <table> found

Processing:  10%|█         | 31/300 [13:29<1:27:09, 19.44s/doc]

No <table> found

Processing:  11%|█         | 32/300 [13:49<1:27:51, 19.67s/doc]

No <table> found

Processing:  14%|█▎        | 41/300 [17:34<1:50:47, 25.67s/doc]

No <table> found

Processing:  14%|█▍        | 42/300 [17:52<1:40:02, 23.26s/doc]

No <table> found

Processing:  14%|█▍        | 43/300 [18:14<1:38:10, 22.92s/doc]

No <table> found

Processing:  15%|█▍        | 44/300 [18:29<1:27:52, 20.59s/doc]

No <table> found

Processing:  15%|█▌        | 45/300 [18:57<1:37:00, 22.82s/doc]

No <table> found

Processing:  16%|█▌        | 48/300 [20:26<1:58:53, 28.31s/doc]

No <table> found

Processing:  16%|█▋        | 49/300 [20:41<1:42:10, 24.43s/doc]

No <table> found

Processing:  17%|█▋        | 50/300 [20:56<1:29:31, 21.49s/doc]

No <table> found

Processing:  17%|█▋        | 52/300 [21:36<1:28:24, 21.39s/doc]

No <table> found

Processing:  18%|█▊        | 53/300 [21:53<1:22:44, 20.10s/doc]

No <table> found

Processing:  18%|█▊        | 54/300 [22:10<1:18:48, 19.22s/doc]

No <table> found

Processing:  18%|█▊        | 55/300 [22:29<1:18:40, 19.27s/doc]

No <table> found

Processing:  19%|█▊        | 56/300 [22:45<1:13:57, 18.19s/doc]

No <table> found

Processing:  19%|█▉        | 57/300 [23:20<1:34:36, 23.36s/doc]

No <table> found

Processing:  19%|█▉        | 58/300 [23:38<1:27:07, 21.60s/doc]

No <table> found

Processing:  20%|█▉        | 59/300 [23:59<1:26:43, 21.59s/doc]

No <table> found

Processing:  20%|██        | 60/300 [24:24<1:30:27, 22.61s/doc]

No <table> found

Processing:  21%|██        | 62/300 [25:09<1:28:38, 22.35s/doc]

No <table> found

Processing:  22%|██▏       | 65/300 [26:20<1:34:32, 24.14s/doc]

No <table> found

Processing:  22%|██▏       | 66/300 [26:37<1:24:52, 21.76s/doc]

No <table> found

Processing:  23%|██▎       | 69/300 [27:32<1:14:26, 19.33s/doc]

No <table> found

Processing:  23%|██▎       | 70/300 [27:45<1:07:03, 17.49s/doc]

No <table> found

Processing:  25%|██▌       | 76/300 [29:57<1:19:01, 21.17s/doc]

Required columns not confidently found

Processing:  26%|██▌       | 78/300 [30:59<1:36:19, 26.03s/doc]

No <table> found

Processing:  28%|██▊       | 84/300 [33:02<1:12:06, 20.03s/doc]

No <table> found

Processing:  29%|██▊       | 86/300 [33:56<1:24:53, 23.80s/doc]

No <table> found
No <table> found

Processing:  29%|██▉       | 87/300 [34:11<1:14:34, 21.00s/doc]

No <table> found

Processing:  29%|██▉       | 88/300 [34:30<1:12:17, 20.46s/doc]

No <table> found

Processing:  30%|███       | 90/300 [35:11<1:12:11, 20.63s/doc]

No <table> found

Processing:  31%|███       | 93/300 [36:25<1:23:48, 24.29s/doc]

No <table> found

Processing:  31%|███▏      | 94/300 [36:35<1:08:52, 20.06s/doc]

No <table> found

Processing:  32%|███▏      | 95/300 [36:45<57:56, 16.96s/doc]

No <table> found

Processing:  32%|███▏      | 96/300 [37:05<1:01:07, 17.98s/doc]

No <table> found

Processing:  32%|███▏      | 97/300 [37:41<1:18:49, 23.30s/doc]

No <table> found
No <table> found

Processing:  33%|███▎      | 98/300 [37:53<1:07:37, 20.09s/doc]

No <table> found

Processing:  33%|███▎      | 99/300 [38:09<1:02:37, 18.69s/doc]

No <table> found
No <table> found

Processing:  33%|███▎      | 100/300 [38:21<55:18, 16.59s/doc]

No <table> found

Processing:  35%|███▌      | 105/300 [40:11<1:12:45, 22.39s/doc]

Required columns not confidently found
No <table> found

Processing:  35%|███▌      | 106/300 [40:32<1:10:54, 21.93s/doc]

Required columns not confidently found

Processing:  36%|███▌      | 107/300 [40:50<1:06:34, 20.70s/doc]

No <table> found

Processing:  39%|███▉      | 117/300 [44:53<1:22:02, 26.90s/doc]

No <table> found

Processing:  40%|███▉      | 119/300 [45:22<1:02:59, 20.88s/doc]

No <table> found

Processing:  41%|████      | 122/300 [46:09<51:31, 17.37s/doc]

No <table> found

Processing:  41%|████      | 123/300 [46:22<47:34, 16.13s/doc]

No <table> found

Processing:  41%|████▏     | 124/300 [46:57<1:03:20, 21.59s/doc]

No <table> found

Processing:  42%|████▏     | 125/300 [47:10<55:22, 18.98s/doc]

No <table> found

Processing:  42%|████▏     | 126/300 [47:37<1:02:13, 21.46s/doc]

No <table> found

Processing:  42%|████▏     | 127/300 [47:57<1:00:36, 21.02s/doc]

No <table> found

Processing:  43%|████▎     | 128/300 [48:18<59:57, 20.92s/doc]

No <table> found

Processing:  43%|████▎     | 129/300 [48:42<1:02:21, 21.88s/doc]

No <table> found

Processing:  44%|████▎     | 131/300 [49:32<1:04:04, 22.75s/doc]

Required columns not confidently found

Processing:  46%|████▌     | 138/300 [52:04<55:38, 20.61s/doc]

No <table> found

Processing:  46%|████▋     | 139/300 [52:16<48:38, 18.13s/doc]

No <table> found

Processing:  47%|████▋     | 140/300 [52:43<55:17, 20.73s/doc]

No <table> found

Processing:  47%|████▋     | 142/300 [53:12<45:54, 17.43s/doc]

No <table> found

Processing:  48%|████▊     | 145/300 [54:23<58:23, 22.60s/doc]

No <table> found

Processing:  49%|████▊     | 146/300 [54:45<57:34, 22.43s/doc]

No <table> found

Processing:  49%|████▉     | 147/300 [55:07<56:47, 22.27s/doc]

No <table> found

Processing:  49%|████▉     | 148/300 [55:28<55:34, 21.94s/doc]

No <table> found

Processing:  50%|█████     | 150/300 [56:06<49:53, 19.96s/doc]

No <table> found

Processing:  50%|█████     | 151/300 [56:44<1:03:04, 25.40s/doc]

No <table> found
No <table> found

Processing:  51%|█████     | 152/300 [57:15<1:06:51, 27.11s/doc]

No <table> found
Required columns not confidently found

Processing:  51%|█████     | 153/300 [57:57<1:17:35, 31.67s/doc]

Required columns not confidently found
No <table> found

Processing:  51%|█████▏    | 154/300 [58:37<1:23:09, 34.18s/doc]

No <table> found
No <table> found

Processing:  52%|█████▏    | 155/300 [59:21<1:29:41, 37.11s/doc]

Required columns not confidently found
No <table> found

Processing:  52%|█████▏    | 156/300 [1:00:07<1:34:56, 39.56s/doc]

No <table> found
Required columns not confidently found
Required columns not confidently found
Required columns not confidently found

Processing:  52%|█████▏    | 157/300 [1:01:11<1:52:15, 47.10s/doc]

Required columns not confidently found
No <table> found

Processing:  53%|█████▎    | 158/300 [1:01:46<1:42:52, 43.47s/doc]

No <table> found

Processing:  53%|█████▎    | 159/300 [1:02:24<1:38:13, 41.80s/doc]

No <table> found
No <table> found

Processing:  53%|█████▎    | 160/300 [1:02:50<1:26:28, 37.06s/doc]

Required columns not confidently found
No <table> found

Processing:  54%|█████▎    | 161/300 [1:03:18<1:19:14, 34.20s/doc]

No <table> found
No <table> found

Processing:  54%|█████▍    | 163/300 [1:04:26<1:15:13, 32.95s/doc]

No <table> found

Processing:  55%|█████▌    | 165/300 [1:05:45<1:21:37, 36.28s/doc]

No <table> found
No <table> found

Processing:  55%|█████▌    | 166/300 [1:06:20<1:20:20, 35.97s/doc]

No <table> found
No <table> found

Processing:  56%|█████▌    | 167/300 [1:06:50<1:15:24, 34.02s/doc]

No <table> found

Processing:  56%|█████▌    | 168/300 [1:07:56<1:36:27, 43.84s/doc]

No <table> found

Processing:  56%|█████▋    | 169/300 [1:11:34<3:29:20, 95.88s/doc]

No <table> found

Processing:  57%|█████▋    | 170/300 [1:13:30<3:41:03, 102.03s/doc]

No <table> found

Processing:  57%|█████▋    | 171/300 [1:15:05<3:34:43, 99.87s/doc]

No <table> found

Processing:  57%|█████▋    | 172/300 [1:16:17<3:15:15, 91.52s/doc]

No <table> found

Processing:  58%|█████▊    | 173/300 [1:18:21<3:34:34, 101.37s/doc]

No <table> found

Processing:  58%|█████▊    | 174/300 [1:19:38<3:17:13, 93.91s/doc]

Required columns not confidently found
No <table> found

Processing:  58%|█████▊    | 175/300 [1:22:29<4:03:47, 117.02s/doc]

No <table> found

Processing:  59%|█████▉    | 177/300 [1:28:23<5:00:23, 146.53s/doc]

No <table> found
No <table> found
Required columns not confidently found
No <table> found
No <table> found
No <table> found
No <table> found

Processing:  59%|█████▉    | 178/300 [1:34:19<7:05:50, 209.43s/doc]

Required columns not confidently found
No <table> found

Processing:  60%|█████▉    | 179/300 [1:36:37<6:18:58, 187.92s/doc]

No <table> found

Processing:  60%|██████    | 181/300 [1:42:08<5:41:42, 172.29s/doc]

No <table> found

Processing:  61%|██████    | 182/300 [1:48:31<7:43:19, 235.59s/doc]

No <table> found

Processing:  63%|██████▎   | 188/300 [2:05:52<6:50:14, 219.78s/doc]

No <table> found

Processing:  64%|██████▎   | 191/300 [2:16:56<6:34:49, 217.34s/doc]

No <table> found

Processing:  64%|██████▍   | 192/300 [2:18:48<5:34:24, 185.78s/doc]

No <table> found

Processing:  64%|██████▍   | 193/300 [2:21:42<5:24:49, 182.14s/doc]

No <table> found

Processing:  65%|██████▌   | 195/300 [2:29:23<5:52:59, 201.71s/doc]

No <table> found

Processing:  66%|██████▌   | 198/300 [2:39:23<5:16:04, 185.93s/doc]

No <table> found

Processing:  66%|██████▋   | 199/300 [2:42:23<5:10:16, 184.32s/doc]

No <table> found

Processing:  67%|██████▋   | 200/300 [2:46:20<5:33:19, 199.99s/doc]

No <table> found

Processing:  67%|██████▋   | 201/300 [2:48:49<5:04:55, 184.81s/doc]

No <table> found

Processing:  67%|██████▋   | 202/300 [2:51:02<4:36:26, 169.25s/doc]

No <table> found

Processing:  68%|██████▊   | 203/300 [2:53:05<4:10:54, 155.20s/doc]

No <table> found
No <table> found

Processing:  68%|██████▊   | 204/300 [2:53:47<3:14:25, 121.51s/doc]

No <table> found

Processing:  68%|██████▊   | 205/300 [2:54:53<2:45:54, 104.79s/doc]

No <table> found

Processing:  69%|██████▊   | 206/300 [2:55:50<2:21:48, 90.52s/doc]

No <table> found

Processing:  69%|██████▉   | 207/300 [2:56:47<2:04:25, 80.28s/doc]

Required columns not confidently found
No <table> found

Processing:  69%|██████▉   | 208/300 [2:57:50<1:55:22, 75.24s/doc]

No <table> found

Processing:  70%|██████▉   | 209/300 [2:58:47<1:45:28, 69.54s/doc]

No <table> found

Processing:  70%|███████   | 210/300 [3:00:23<1:56:37, 77.75s/doc]

Required columns not confidently found

Processing:  71%|███████   | 212/300 [3:02:34<1:44:49, 71.47s/doc]

No <table> found

Processing:  72%|███████▏  | 215/300 [3:06:10<1:42:43, 72.51s/doc]

No <table> found

Processing:  73%|███████▎  | 219/300 [3:10:51<1:31:28, 67.75s/doc]

No <table> found

Processing:  73%|███████▎  | 220/300 [3:12:18<1:37:59, 73.49s/doc]

No <table> found

Processing:  78%|███████▊  | 234/300 [3:30:29<1:22:03, 74.60s/doc]

No <table> found

Processing:  78%|███████▊  | 235/300 [3:31:50<1:23:07, 76.74s/doc]

No <table> found

Processing:  79%|███████▊  | 236/300 [3:32:46<1:15:01, 70.34s/doc]

No <table> found

Processing:  79%|███████▉  | 237/300 [3:34:01<1:15:32, 71.95s/doc]

No <table> found
No <table> found

Processing:  79%|███████▉  | 238/300 [3:35:17<1:15:24, 72.98s/doc]

Required columns not confidently found
No <table> found

Processing:  80%|███████▉  | 239/300 [3:36:11<1:08:35, 67.47s/doc]

Required columns not confidently found

Processing:  80%|████████  | 240/300 [3:37:44<1:14:55, 74.92s/doc]

No <table> found

Processing:  81%|████████  | 243/300 [3:43:19<1:29:00, 93.69s/doc]

No <table> found

Processing:  81%|████████▏ | 244/300 [3:44:20<1:18:05, 83.67s/doc]

No <table> found

Processing:  82%|████████▏ | 245/300 [3:45:28<1:12:30, 79.09s/doc]

No <table> found

Processing:  82%|████████▏ | 246/300 [3:46:23<1:04:45, 71.95s/doc]

Required columns not confidently found
No <table> found

Processing:  82%|████████▏ | 247/300 [3:47:55<1:08:50, 77.94s/doc]

Required columns not confidently found
No <table> found

Processing:  83%|████████▎ | 248/300 [3:49:03<1:05:00, 75.02s/doc]

Required columns not confidently found
No <table> found

Processing:  83%|████████▎ | 249/300 [3:50:14<1:02:34, 73.62s/doc]

Required columns not confidently found
No <table> found

Processing:  83%|████████▎ | 250/300 [3:51:25<1:00:45, 72.90s/doc]

No <table> found

Processing:  84%|████████▎ | 251/300 [3:52:39<59:46, 73.19s/doc]

No <table> found
Required columns not confidently found
No <table> found
No <table> found

Processing:  84%|████████▍ | 252/300 [3:55:59<1:29:04, 111.34s/doc]

No <table> found

Processing:  85%|████████▍ | 254/300 [3:58:27<1:11:54, 93.80s/doc]

No <table> found

Processing:  86%|████████▌ | 257/300 [4:02:19<1:00:01, 83.76s/doc]

No <table> found

Processing:  89%|████████▉ | 267/300 [4:16:16<48:16, 87.77s/doc]

No <table> found

Processing:  91%|█████████ | 272/300 [4:22:51<37:09, 79.62s/doc]

No <table> found

Processing:  91%|█████████ | 273/300 [4:24:05<35:03, 77.91s/doc]

No <table> found

Processing:  91%|█████████▏| 274/300 [4:25:20<33:25, 77.15s/doc]

No <table> found

Processing:  92%|█████████▏| 275/300 [4:26:37<32:02, 76.89s/doc]

No <table> found

Processing:  92%|█████████▏| 277/300 [4:29:06<29:22, 76.65s/doc]

Required columns not confidently found

Processing:  93%|█████████▎| 278/300 [4:30:05<26:04, 71.11s/doc]

Required columns not confidently found
No <table> found

Processing:  93%|█████████▎| 279/300 [4:30:48<21:55, 62.66s/doc]

No <table> found

Processing:  93%|█████████▎| 280/300 [4:32:03<22:07, 66.39s/doc]

No <table> found
Required columns not confidently found

Processing:  94%|█████████▎| 281/300 [4:33:09<20:59, 66.31s/doc]

Required columns not confidently found

Processing:  96%|█████████▌| 288/300 [4:43:20<18:34, 92.87s/doc]

No <table> found

Processing:  97%|█████████▋| 290/300 [4:45:44<13:37, 81.71s/doc]

No <table> found

Processing:  97%|█████████▋| 291/300 [4:48:37<16:21, 109.09s/doc]

No <table> found

Processing:  97%|█████████▋| 292/300 [4:49:35<12:31, 93.91s/doc]

No <table> found

Processing:  98%|█████████▊| 293/300 [4:50:41<09:58, 85.48s/doc]

Required columns not confidently found

Processing:  99%|█████████▉| 297/300 [4:55:37<03:27, 69.30s/doc]

No <table> found

Processing:  99%|█████████▉| 298/300 [4:57:11<02:33, 76.56s/doc]

No <table> found

Processing: 100%|██████████| 300/300 [4:59:24<00:00, 59.88s/doc]

In [79]:
submission_df

                        id             doc_id  row_num      party_name  votes
0      constituency_10_1_1  constituency_10_1        1    ประชาธิปัตย์  14813
1      constituency_10_1_2  constituency_10_1        2       ภูมิใจไทย  14368
2      constituency_10_1_3  constituency_10_1        3        เศรษฐกิจ    979
3      constituency_10_1_4  constituency_10_1        4        กล้าธรรม    244
4      constituency_10_1_5  constituency_10_1        5           พลวัต    351
...                    ...                ...      ...             ...    ...
10048  party_list_34_11_53   party_list_34_11       53  ไทยพิทักษ์ธรรม     14
10049  party_list_34_11_54   party_list_34_11       54    ความหวังใหม่     41
10050  party_list_34_11_55   party_list_34_11       55       ไทยรวมไทย      0
10051  party_list_34_11_56   party_list_34_11       56  เพื่อบ้านเมือง     29
10052  party_list_34_11_57   party_list_34_11       57  พลังไทยรักชาติ     43

[10053 rows x 5 columns]

In [80]:
submission_df.to_csv("submission.csv")