### Setup

In [83]:
import pandas as pd
import os
import re
from mistralai.client import Mistral
from rapidfuzz import fuzz, process
from tqdm import tqdm
from dotenv import load_dotenv

In [88]:
load_dotenv(dotenv_path='../.env')

True

In [90]:
client = Mistral(api_key=os.getenv('MISTRAL_API_KEY'))

In [31]:
TEMPLATE_OLD_PATH = "../data/submission_template.csv"
TEMPLATE_PATH = "../data/submission_template_v3.csv"

In [32]:
template_df = pd.read_csv(TEMPLATE_PATH)
template_old_df = pd.read_csv(TEMPLATE_OLD_PATH)
template_df['doc_id'] = template_old_df['doc_id']
template_df

                        id      party_name  votes             doc_id
0      constituency_10_1_1    ประชาธิปัตย์      0  constituency_10_1
1      constituency_10_1_2       ภูมิใจไทย      0  constituency_10_1
2      constituency_10_1_3        เศรษฐกิจ      0  constituency_10_1
3      constituency_10_1_4        กล้าธรรม      0  constituency_10_1
4      constituency_10_1_5           พลวัต      0  constituency_10_1
...                    ...             ...    ...                ...
10048  party_list_34_11_53  ไทยพิทักษ์ธรรม      0   party_list_34_11
10049  party_list_34_11_54    ความหวังใหม่      0   party_list_34_11
10050  party_list_34_11_55       ไทยรวมไทย      0   party_list_34_11
10051  party_list_34_11_56  เพื่อบ้านเมือง      0   party_list_34_11
10052  party_list_34_11_57  พลังไทยรักชาติ      0   party_list_34_11

[10053 rows x 4 columns]

### EDA

In [33]:
template_df['party_name'].unique()

array(['ประชาธิปัตย์', 'ภูมิใจไทย', 'เศรษฐกิจ', 'กล้าธรรม', 'พลวัต',
       'ประชาชน', 'เพื่อไทย', 'ไทยภักดี', 'รวมไทยสร้างชาติ', 'ปวงชนไทย',
       'ไทยสร้างไทย', 'โอกาสใหม่', 'วิชชั่นใหม่', 'ประชาธิปไตยใหม่',
       'รักชาติ', 'ไทยก้าวใหม่', 'ทางเลือกใหม่', 'พลังประชารัฐ',
       'ประชากรไทย', 'ความหวังใหม่', 'อนาคตไทย', 'บ้านเมือง',
       'เพื่อบ้านเมือง', 'ไทยก้าวหน้า', 'รวมไทยสร้าง', 'แรงงานสร้างชาติ',
       'ไทยชนะ', 'พร้อม', 'ไทยพิทักษ์ธรรม', 'ไทยก้าวไทย', 'ไทยก้าวใหม',
       'เสรีรวมไทย', 'เป็นธรรม', 'ไทยธรรม', 'ฟิวชน', 'ฟิวชัน',
       'รวมพลังประชาชน', 'แรงงานสร้างไทย', 'ไทยสร้างชาติ', nan,
       'ปวงชนชาวไทย', 'กลาธรรม', 'สังคมประชาธิปไตยไทย', 'คลองไทย',
       'รวมใจไทย', 'รวมไทยสร้างชา', 'รักษ์ธรรม', 'ชาติ', 'ไทยพร้อม',
       'สร้างชาติ', 'ใหม่', 'พลังสังคมใหม่', 'สร้างอนาคตไทย',
       'ไทยทรัพย์ทวี', 'รวมพลัง', 'ไทรวมพลัง', 'เพื่อชาติไทย', 'มิติใหม่',
       'ท้องที่ไทย', 'พลังเพื่อไทย', 'ก้าวอิสระ', 'เพื่อชีวิตใหม่',
       'ครูไทยเพื่อประชาชน', 'ประชาชาติ', 'พลังธรรมใหม่', 'กรีน',
       'แผ่นดินธรรม', 'ประชาไทย', 'ประชาอาสาชาติ',
       'เครือข่ายชาวนาแห่งประเทศไทย', 'ไทยรวมไทย', 'พลังไทยรักชาติ'],
      dtype=object)

In [34]:
template_df.head()

                    id    party_name  votes             doc_id
0  constituency_10_1_1  ประชาธิปัตย์      0  constituency_10_1
1  constituency_10_1_2     ภูมิใจไทย      0  constituency_10_1
2  constituency_10_1_3      เศรษฐกิจ      0  constituency_10_1
3  constituency_10_1_4      กล้าธรรม      0  constituency_10_1
4  constituency_10_1_5         พลวัต      0  constituency_10_1

In [35]:
NaN_df = template_df[
    template_df['party_name'].isna()
]

NaN_df

                       id party_name  votes             doc_id
737  constituency_14_2_10        NaN      0  constituency_14_2
738  constituency_14_2_11        NaN      0  constituency_14_2
739  constituency_14_2_12        NaN      0  constituency_14_2
740  constituency_14_2_13        NaN      0  constituency_14_2
741  constituency_14_2_14        NaN      0  constituency_14_2
742  constituency_14_2_15        NaN      0  constituency_14_2
743  constituency_14_2_16        NaN      0  constituency_14_2
744  constituency_14_2_17        NaN      0  constituency_14_2

In [36]:
# 737 - 744 Correctly Null
template_df.iloc[737]

id            constituency_14_2_10
party_name                     NaN
votes                            0
doc_id           constituency_14_2
Name: 737, dtype: object

### Extraction

In [37]:
def thai_num_to_int(text: str) -> int:

    thai_to_arabic = str.maketrans("๐๑๒๓๔๕๖๗๘๙", "0123456789")
    text = text.translate(thai_to_arabic)

    # remove non-numeric prefixes
    text = re.sub(r"[^\d,]", " ", text)

    match = re.search(r"[\d,]+", text)
    if not match:
        raise ValueError("No numeric value found")

    return int(match.group().replace(",", ""))

In [53]:
KNOWN_PARTIES = [
    'ประชาธิปัตย์', 'ภูมิใจไทย', 'เศรษฐกิจ', 'กล้าธรรม', 'พลวัต',
    'ประชาชน', 'เพื่อไทย', 'ไทยภักดี', 'รวมไทยสร้างชาติ', 'ปวงชนไทย',
    'ไทยสร้างไทย', 'โอกาสใหม่', 'วิชชั่นใหม่', 'ประชาธิปไตยใหม่',
    'รักชาติ', 'ไทยก้าวใหม่', 'ทางเลือกใหม่', 'พลังประชารัฐ',
    'ประชากรไทย', 'ความหวังใหม่', 'อนาคตไทย', 'บ้านเมือง',
    'เพื่อบ้านเมือง', 'ไทยก้าวหน้า', 'รวมไทยสร้าง', 'แรงงานสร้างชาติ',
    'ไทยชนะ', 'พร้อม', 'ไทยพิทักษ์ธรรม', 'ไทยก้าวไทย', 'ไทยก้าวใหม',
    'เสรีรวมไทย', 'เป็นธรรม', 'ไทยธรรม', 'ฟิวชน', 'ฟิวชัน',
    'รวมพลังประชาชน', 'แรงงานสร้างไทย', 'ไทยสร้างชาติ',
    'ปวงชนชาวไทย', 'กลาธรรม', 'สังคมประชาธิปไตยไทย', 'คลองไทย',
    'รวมใจไทย', 'รวมไทยสร้างชา', 'รักษ์ธรรม', 'ชาติ', 'ไทยพร้อม',
    'สร้างชาติ', 'พลังสังคมใหม่', 'สร้างอนาคตไทย',
    'ไทยทรัพย์ทวี', 'รวมพลัง', 'ไทรวมพลัง', 'เพื่อชาติไทย', 'มิติใหม่',
    'ท้องที่ไทย', 'พลังเพื่อไทย', 'ก้าวอิสระ', 'เพื่อชีวิตใหม่',
    'ครูไทยเพื่อประชาชน', 'ประชาชาติ', 'พลังธรรมใหม่', 'กรีน',
    'แผ่นดินธรรม', 'ประชาไทย', 'ประชาอาสาชาติ',
    'เครือข่ายชาวนาแห่งประเทศไทย', 'ไทยรวมไทย', 'พลังไทยรักชาติ'
]

def is_party(text, threshold=70):
    match = process.extractOne(text, KNOWN_PARTIES, scorer=fuzz.ratio)
    return match and match[1] >= threshold

In [40]:
def extract_party_score_dict(md: str) -> dict:
    result = {}
    party_idx = None
    vote_idx = None

    for line in md.split('\n'):
        if '---' in line or 'รวมคะแนน' in line:
            continue

        parts = [p.strip() for p in line.split('|') if p.strip()]
        if len(parts) < 2:
            continue

        # Auto-detect column positions from first data row with a known party
        if party_idx is None:
            for i, p in enumerate(parts):
                if is_party(p):
                    party_idx = i
                    # Vote column is always the next one after party
                    vote_idx = i + 1
                    break
            if party_idx is None:
                continue

        if len(parts) <= max(party_idx, vote_idx):
            continue

        party = parts[party_idx].strip()
        vote_raw = parts[vote_idx].strip()

        if not is_party(party):
            continue

        try:
            vote = thai_num_to_int(vote_raw)
            if party:
                result[party] = vote
        except Exception:
            pass

    return result

In [ ]:
def extraction(path):
    try:
        if not os.path.exists(path):
            return {}
        filename = os.path.basename(path)
        with open(path, "rb") as f:
            uploaded = client.files.upload(
                file={"file_name": filename, "content": f},
                purpose="ocr"
            )
        signed_url = client.files.get_signed_url(file_id=uploaded.id)
        result = client.ocr.process(
            model="mistral-ocr-latest",
            document={"type": "document_url", "document_url": signed_url.url}
        )
        # Combine all pages markdown
        print(result.pages[0].markdown)
        md = "".join(page.markdown for page in result.pages)
        return extract_party_score_dict(md)
    except Exception as e:
        print(e.__str__())
        return {}

### Inference

In [54]:
def assign_votes(df, vote_dict, threshold=60):
    vote_dict = {k: v for k, v in vote_dict.items() if k != 'รวมคะแนนทั้งสิ้น'}
    keys = list(vote_dict.keys())

    def get_vote(party_name):
        if pd.isna(party_name):
            return 0
        match = process.extractOne(
            party_name,
            keys,
            scorer=fuzz.token_set_ratio  # changed from fuzz.ratio
        )
        if match is None:
            return 0
        best_key, score, _ = match
        return vote_dict[best_key] if score >= threshold else 0

    df['votes'] = df['party_name'].apply(get_vote)
    return df

In [43]:
submission_df = template_df.copy()

In [ ]:
PREFIX = "../pdf/"

doc_ids = submission_df['doc_id'].unique()

In [75]:
for doc_id in tqdm(doc_ids, desc="Processing", unit="doc"):
	try:
		vote_dict = extraction(PREFIX + doc_id + '.pdf')
		print(doc_id, vote_dict)
		mask = submission_df["doc_id"] == doc_id
		submission_df.loc[mask] = assign_votes(
			submission_df.loc[mask].copy(),
			vote_dict,
			threshold=60
		)
	except Exception as e:
		print(f"{doc_id}: {str(e)}")

Processing:   0%|          | 1/300 [00:07<37:13,  7.47s/doc]

constituency_10_1 {'ประชาชน': 34167, 'ประชาธิปไตย': 14813, 'ภูมิใจไทย': 14368, 'เพื่อไทย': 6030, 'รวมไทยสร้างชาติ': 2075, 'โอกาสใหม่': 1133, 'ไทยภักดี': 1023, 'เศรษฐกิจ': 979, 'ไทยสร้างไทย': 629, 'ไทยก้าวใหม่': 489, 'พลวัต': 351, 'กล้าธรรม': 244, 'ปวงชนไทย': 168, 'รักชาติ': 165, 'ทางเลือกใหม่': 154, 'วิชชั่นใหม่': 113, 'ประชาธิปไตยใหม่': 94, 'พลังประชารัฐ': 80}

Processing:   1%|          | 2/300 [00:14<34:58,  7.04s/doc]

constituency_10_10 {'ประชาชน': 41804, 'เพื่อไทย': 19047, 'โอกาสใหม่': 9440, 'ภูมิใจไทย': 7925, 'ประชาธิปัตย์': 6372, 'รวมไทยสร้างชาติ': 2012, 'เศรษฐกิจ': 1437, 'ไทยสร้างไทย': 636, 'ไทยก้าวใหม่': 583, 'กล้าธรรม': 545, 'ประชาธิปไตยใหม่': 503, 'รักชาติ': 495, 'พลวัต': 461, 'ประชากรไทย': 282, 'ความหวังใหม่': 203, 'วิชชั่นใหม่': 168}

Processing:   1%|          | 3/300 [00:21<35:22,  7.15s/doc]

constituency_10_11 {'ประชาชน': 3877, 'เพื่อไทย': 24856, 'ภูมิใจไทย': 26598, 'ประชาธิปไตย': 3839, 'ประชากรไทย': 1168, 'รวมไทยสร้างชาติ': 996, 'เศรษฐกิจ': 996, 'ไทยภักดี': 686, 'อนาคตไทย': 626, 'โอกาสใหม่': 585, 'ไทยสร้างไทย': 533, 'บ้านเมือง': 369, 'ไทยก้าวใหม่': 372, 'พลังประชารัฐ': 296, 'กล้าธรรม': 263, 'พลวัต': 185, 'ประชาธิปไตยใหม่': 188, 'วิชชั่นใหม่': 66}

Processing:   1%|▏         | 4/300 [00:27<32:47,  6.65s/doc]

constituency_10_12 {'ประชาชน': 49925, 'ภูมิใจไทย': 16106, 'เพื่อไทย': 15095, 'ประชาธิปัตย์': 9527, 'พลังประชารัฐ': 4142, 'รวมไทยสร้างชาติ': 1776, 'เศรษฐกิจ': 1770, 'ไทยสร้างไทย': 1183, 'กล้าธรรม': 945, 'ไทยก้าวใหม่': 721, 'พลวัต': 452, 'ประชาธิปไตยใหม่': 430, 'ประชากรไทย': 434, 'โอกาสใหม่': 368, 'รักชาติ': 298, 'ปวงชนไทย': 267}

Processing:   2%|▏         | 5/300 [00:33<31:29,  6.41s/doc]

constituency_10_13 {'พรรคประชาชน': 44511, 'พรรคภูมิใจไทย': 15227, 'พรรคประชาธิปัตย์': 11428, 'พรรคเพื่อไทย': 10752, 'พรรครวมไทยสร้างชาติ': 1887, 'พรรคเศรษฐกิจ': 1413, 'พรรครักชาติ': 1323, 'พรรคปวงชนไทย': 1082, 'พรรคไทยสร้างไทย': 807, 'พรรคไทยก้าวใหม่': 775, 'พรรคโอกาสใหม่': 438, 'พรรคพลวัต': 325, 'พรรคพลังประชารัฐ': 252, 'พรรคเพื่อบ้านเมือง': 157, 'พรรควิชชั่นใหม่': 131}

Processing:   2%|▏         | 6/300 [00:39<30:39,  6.26s/doc]

constituency_10_14 {'ประชาชน': 41528, 'ภูมิใจไทย': 25491, 'เพื่อไทย': 10848, 'ประชาธิปัตย์': 8186, 'รวมไทยสร้างชาติ': 1333, 'ไทยสร้างไทย': 1299, 'เศรษฐกิจ': 1199, 'ไทยภักดี': 694, 'กล้าธรรม': 571, 'ไทยก้าวใหม่': 485, 'รักชาติ': 477, 'ปวงชนไทย': 354, 'พลังประชารัฐ': 352, 'โอกาสใหม่': 291, 'พลวัด': 213, 'ไทยก้าวหน้า': 146}

Processing:   2%|▏         | 7/300 [00:44<28:28,  5.83s/doc]

constituency_10_16 {'ประชาชน': 46021, 'ภูมิใจไทย': 15424, 'เพื่อไทย': 15340, 'ประชาธิปัตย์': 8442, 'เศรษฐกิจ': 1660, 'รวมไทยสร้างชาติ': 1648, 'โอกาสใหม่': 1317, 'ไทยก้าวใหม่': 1112, 'กล้าธรรม': 824, 'ไทยสร้างไทย': 747, 'ไทยภักดี': 626, 'พลังประชารัฐ': 467, 'รักชาติ': 286, 'เพื่อบ้านเมือง': 153, 'ปวงชนไทย': 151}

Processing:   3%|▎         | 8/300 [00:50<28:54,  5.94s/doc]

constituency_10_17 {'พรรคประชาชน': 28587, 'พรรคภูมิใจไทย': 16132, 'พรรคเพื่อไทย': 12311, 'พรรคประชาธิปัตย์': 5611, 'พรรคไทยก้าวใหม่': 1967, 'พรรครวมไทยสร้าง': 1604, 'พรรคเศรษฐกิจ': 1382, 'พรรคพลังประชารัฐ': 864, 'พรรคไทยสร้างไทย': 773, 'พรรคแรงงานสร้างชาติ': 745, 'พรรคกล้าธรรม': 499, 'พรรคโอกาสใหม่': 419, 'พรรควิชชั่นใหม่': 358, 'พรรคปวงชนไทย': 246, 'พรรคเพื่อบ้านเมือง': 222}

Processing:   3%|▎         | 9/300 [00:54<26:36,  5.49s/doc]

constituency_10_18 {'ประชาชน': 34738, 'เพื่อไทย': 20414, 'ภูมิใจไทย': 8326, 'ประชาธิปัตย์': 6654, 'รวมไทยสร้างชาติ': 3260, 'ไทยก้าวใหม่': 1781, 'ไทยสร้างไทย': 1732, 'ทางเลือกใหม่': 496, 'พลวัต': 436, 'รักชาติ': 372, 'พลังประชาธิรัฐ': 359, 'ไทยชนะ': 338, 'แรงงานสร้างชาติ': 285, 'ปวงชนไทย': 225, 'โอกาสใหม่': 211, 'กล้าธรรม': 210, 'เพื่อบ้านเมือง': 196, 'พร้อม': 171}

Processing:   3%|▎         | 10/300 [01:01<28:17,  5.85s/doc]

constituency_10_19 {'ประชาชน': 42820, 'ภูมิใจไทย': 17802, 'เพื่อไทย': 13271, 'ประชาธิปัตย์': 10234, 'รวมไทยสร้างชาติ': 2415, 'เศรษฐกิจ': 1607, 'ไทยสร้างไทย': 924, 'กล้าธรรม': 772, 'ไทยก้าวใหม่': 579, 'ปวงชนไทย': 546, 'โอกาสใหม่': 177, 'พลวัต': 345, 'รักชาติ': 269, 'ทางเลือกใหม่': 230}

Processing:   4%|▎         | 11/300 [01:07<27:59,  5.81s/doc]

constituency_10_2 {'ประชาชน': 39499, 'ภูมิใจไทย': 15949, 'ประชาธิปไตย': 14613, 'เพื่อไทย': 5652, 'รวมไทยสร้างชาติ': 1684, 'ไทยก้าวใหม่': 1358, 'เศรษฐกิจ': 933, 'โอกาสใหม่': 844, 'ไทยภักดี': 807, 'กล้าธรรม': 737, 'ไทยสร้างไทย': 590, 'ปวงชนไทย': 402, 'รักชาติ': 385, 'พลังประชาธิรัฐ': 306, 'เพื่อบ้านเมือง': 115}

Processing:   4%|▍         | 12/300 [01:13<28:27,  5.93s/doc]

constituency_10_20 {'พรรคประชาชน': 34941, 'พรรคเพื่อไทย': 27474, 'พรรคภูมิใจไทย': 7771, 'พรรคประชาธิปัตย์': 4139, 'พรรคโอกาสใหม่': 1483, 'พรรครวมไทยสร้างชาติ': 1229, 'พรรคเศรษฐกิจ': 1221, 'พรรคไทยก้าวใหม่': 1135, 'พรรคไทยสร้างไทย': 1018, 'พรรคพลวัต': 424, 'พรรคกล้าธรรม': 308, 'พรรคพร้อม': 298, 'พรรคปวงชนไทย': 287, 'พรรคพลังประชารัฐ': 207}

Processing:   4%|▍         | 13/300 [01:18<26:55,  5.63s/doc]

constituency_10_21 {'เศรษฐกิจ': 1246, 'โอกาสใหม่': 201, 'ไทยก้าวใหม่': 636, 'ภูมิใจไทย': 10553, 'พลวัต': 297, 'รักชาติ': 1199, 'เพื่อไทย': 6039, 'ประชาชน': 45951, 'กล้าธรรม': 1060, 'รวมไทยสร้างชาติ': 1153, 'ไทยภักดี': 827, 'อนาคตไทย': 267, 'ปวงชนไทย': 217, 'ประชาธิปัตย์': 21155, 'ไทยสร้างไทย': 495}

Processing:   5%|▍         | 14/300 [01:24<26:51,  5.63s/doc]

constituency_10_22 {'ประชาชน': 42264, 'ภูมิใจไทย': 17486, 'ประชาธิปัตย์': 9244, 'เพื่อไทย': 7036, 'พลังประชารัฐ': 2983, 'รวมไทยสร้างชาติ': 1705, 'ไทยก้าวใหม่': 1491, 'เศรษฐกิจ': 1130, 'ไทยสร้างไทย': 786, 'พลวัต': 425, 'ปวงชนไทย': 368, 'กล้าธรรม': 253, 'วิชชั่นใหม่': 205, 'โอกาสใหม่': 182}

Processing:   5%|▌         | 15/300 [01:30<27:53,  5.87s/doc]

constituency_10_23 {'ประชาชน': 4678, 'ภูมิใจไทย': 1759, 'ประชาธิปัตย์': 1087, 'เพื่อไทย': 929, 'รวมไทยสร้างชาติ': 189, 'พลังประชารัฐ': 166, 'เศรษฐกิจ': 152, 'ไทยสร้างไทย': 1004, 'ไทยก้าวใหม่': 755, 'ไทยภักดี': 56, 'ประชาธิปไตยใหม่': 464, 'กล้าธรรม': 325, 'อนาคตไทย': 319, 'รักชาติ': 298, 'พลวัต': 290, 'วิชชั่นใหม่': 203, 'ปวงชนไทย': 201, 'โอกาสใหม่': 184}

Processing:   5%|▌         | 16/300 [01:36<28:06,  5.94s/doc]

constituency_10_24 {'ประชาชน': 46415, 'ภูมิใจไทย': 15300, 'ประชาธิปัตย์': 13371, 'เพื่อไทย': 6401, 'เศรษฐกิจ': 2509, 'รวมไทยสร้างชาติ': 1758, 'ไทยก้าวใหม่': 1001, 'ไทยสร้างไทย': 819, 'กล้าธรรม': 514, 'โอกาสใหม่': 492, 'ปวงชนไทย': 285, 'ประชาธิปไตยใหม่': 280, 'ทางเลือกใหม่': 211}

Processing:   6%|▌         | 17/300 [01:41<26:39,  5.65s/doc]

constituency_10_25 {'ประชาชน': 37035, 'เพื่อไทย': 21904, 'ภูมิใจไทย': 10493, 'ประชาธิปัตย์': 7071, 'รวมไทยสร้างชาติ': 2493, 'เศรษฐกิจ': 1335, 'พลวัต': 980, 'พลังประชารัฐ': 688, 'ไทยสร้างไทย': 581, 'อนาคตไทย': 424, 'ไทยก้าวใหม่': 407, 'กล้าธรรม': 357, 'โอกาสใหม่': 179, 'วิชชั่นใหม่': 165}

Processing:   6%|▌         | 18/300 [01:48<27:38,  5.88s/doc]

constituency_10_26 {'ประชาชน': 44271, 'เพื่อไทย': 16727, 'ภูมิใจไทย': 11584, 'ประชาธิปัตย์': 8425, 'ไทยสร้างไทย': 2506, 'รวมไทยสร้างชาติ': 1562, 'เศรษฐกิจ': 1422, 'กล้าธรรม': 1359, 'ไทยก้าวใหม่': 810, 'ปวงชนไทย': 486, 'พลวัต': 421, 'ประชาธิปไตยใหม่': 222, 'โอกาสใหม่': 124, 'ไทยพิทักษ์ธรรม': 118}

Processing:   6%|▋         | 19/300 [01:53<27:13,  5.81s/doc]

constituency_10_27 {'ประชาชน': 43046, 'เพื่อไทย': 26986, 'ประชาธิปัตย์': 7490, 'ภูมิใจไทย': 6640, 'รวมไทยสร้างชาติ': 2202, 'เศรษฐกิจ': 1422, 'ปวงชนไทย': 706, 'ไทยสร้างไทย': 524, 'ไทยก้าวใหม่': 493, 'กล้าธรรม': 384, 'โอกาสใหม่': 317, 'เพื่อบ้านเมือง': 171}

Processing:   7%|▋         | 20/300 [01:58<26:02,  5.58s/doc]

constituency_10_28 {'ประชาชน': 47692, 'ภูมิใจไทย': 13153, 'เพื่อไทย': 12310, 'ประชาธิปัตย์': 7586, 'เศรษฐกิจ': 2236, 'ไทยก้าวไทย': 2071, 'รวมไทยสร้างชาติ': 1831, 'รักชาติ': 1609, 'กล้าธรรม': 1033, 'ไทยสร้างไทย': 870, 'โอกาสใหม่': 688, 'ปวงชนไทย': 299, 'เพื่อบ้านเมือง': 182}

Processing:   7%|▋         | 21/300 [02:05<26:58,  5.80s/doc]

constituency_10_29 {'ประชาชน': 46402, 'เพื่อไทย': 16836, 'ภูมิใจไทย': 13062, 'ประชาธิปไตย': 287, 'เศรษฐกิจ': 2211, 'ไทยสร้างไทย': 1757, 'พลวัต': 865, 'กล้ารรม': 548, 'ไทยก้าวใหม่': 532, 'โอกาสใหม่': 373, 'รักชาติ': 370, 'ปวงชนไทย': 338, 'วิชชั้นใหม่': 162, 'พลังประชารัฐ': 139}

Processing:   7%|▋         | 22/300 [02:11<27:37,  5.96s/doc]

constituency_10_3 {'ประชาชน': 14653, 'ประชาธิปัตย์': 19167, 'ภูมิใจไทย': 10331, 'เพื่อไทย': 6665, 'รวมไทยสร้างชาติ': 1430, 'เศรษฐกิจ': 1308, 'ไทยก้าวใหม่': 665, 'ไทยสร้างไทย': 571, 'กล้าธรรม': 545, 'วิชชั่นใหม่': 589, 'พลังประชารัฐ': 375, 'รักชาติ': 235, 'พลวัต': 185, 'โอกาสใหม่': 156}

Processing:   8%|▊         | 23/300 [02:18<28:28,  6.17s/doc]

constituency_10_30 {'ประชาชน': 45992, 'เพื่อไทย': 14293, 'ภูมิใจไทย': 11593, 'ประชาธิปไตย': 8033, 'รวมไทยสร้างชาติ': 2513, 'ไทยก้าวไหม': 2341, 'เสรีรวมไทย': 1271, 'เศรษฐกิจ': 1258, 'ไทยสร้างไทย': 1072, 'ไทยภักดี': 687, 'เป็นธรรม': 630, 'กล้าธรรม': 456, 'ปวงชนไทย': 441, 'ประชาธิปไตยใหม่': 417, 'พลังประชาธิปไตย': 389, 'พลวัต': 388, 'รักชาติ': 334, 'โอกาสใหม่': 285, 'เพื่อบ้านเมือง': 140}

Processing:   8%|▊         | 24/300 [02:25<29:48,  6.48s/doc]

constituency_10_31 {'พรรคประชาชน': 4472, 'พรรคภูมิใจไทย': 15126, 'พรรคเพื่อไทย': 14455, 'พรรคประชาธิปไตย': 13012, 'พรรคเศรษฐกิจ': 2889, 'พรรครวมไทยสร้างชาติ': 1888, 'พรรคไทยสร้างไทย': 1147, 'พรรคไทยธรรม': 966, 'พรรคไทยก้าวใหม่': 727, 'พรรคพลวัต': 702, 'พรรคทางเลือกใหม่': 605, 'พรรคโอกาสใหม่': 561, 'พรรคกล้าธรรม': 485, 'พรรควิชชั่นใหม่': 435, 'พรรคไทยชนะ': 387, 'พรรครักชาติ': 384}

Processing:   8%|▊         | 25/300 [02:30<27:41,  6.04s/doc]

constituency_10_32 {'ประชาชน': 39727, 'ภูมิใจไทย': 13302, 'ประชาธิปัตย์': 11573, 'เพื่อไทย': 10257, 'รวมไทยสร้างชาติ': 3024, 'เศรษฐกิจ': 1429, 'ไทยสร้างไทย': 897, 'พลวัต': 873, 'เสรีรวมไทย': 775, 'ไทยก้าวใหม่': 700, 'กล้าธรรม': 681, 'รักชาติ': 559, 'เพื่อบ้านเมือง': 551, 'โอกาสใหม่': 497, 'ทางเลือกใหม่': 435, 'พลังประชารัฐ': 351}

Processing:   9%|▊         | 26/300 [02:35<25:51,  5.66s/doc]

constituency_10_33 {'ประชาชน': 44860, 'ประชาธิปัตย์': 16359, 'ภูมิใจไทย': 15046, 'เพื่อไทย': 7451, 'รวมไทยสร้างชาติ': 2503, 'เศรษฐกิจ': 2260, 'ไทยก้าวใหม่': 1541, 'กล้าธรรม': 1506, 'ไทยสร้างไทย': 768, 'เสรีรวมไทย': 626, 'วิชชั่นใหม่': 605, 'พลวัต': 404, 'โอกาสใหม่': 288, 'เพื่อบ้านเมือง': 199}

Processing:   9%|▉         | 27/300 [02:40<26:11,  5.75s/doc]

constituency_10_4 {'ประชาชน': 34405, 'ประชาธิปัตย์': 23594, 'ภูมิใจไทย': 10778, 'เพื่อไทย': 4343, 'รวมไทยสร้างชาติ': 1050, 'เศรษฐกิจ': 857, 'กล้าธรรม': 739, 'ไทยก้าวใหม่': 708, 'ไทยสร้างไทย': 418, 'รักชาติ': 364, 'พลังประชารัฐ': 337, 'ปวงชนไทย': 265, 'โอกาสใหม่': 124}

Processing:   9%|▉         | 28/300 [02:46<26:06,  5.76s/doc]

constituency_10_5 {'พรรคประชาชน': 45269, 'พรรคภูมิใจไทย': 22252, 'พรรคประชาธิปัตย์': 10035, 'พรรคเพื่อไทย': 6474, 'พรรครวมไทยสร้างชาติ': 1741, 'พรรคกล้าธรรม': 1056, 'พรรคเศรษฐกิจ': 987, 'พรรคไทยก้าวใหม่': 526, 'พรรครักชาติ': 569, 'พรรคไทยสร้างไทย': 507, 'พรรคปวงชนไทย': 409, 'พรรคพลวัต': 245, 'พรรคพลังประชารัฐ': 231, 'พรรคโอกาสใหม่': 220, 'พรรควิชชั้นใหม่': 159, 'พรรคเพื่อบ้านเมือง': 112}

Processing:  10%|▉         | 29/300 [02:53<26:55,  5.96s/doc]

constituency_10_6 {'ประชาชน': 43239, 'ประชาธิปัตย์': 12848, 'ภูมิใจไทย': 12088, 'โอกาสใหม่': 10856, 'เพื่อไทย': 6380, 'รวมไทยสร้างชาติ': 2568, 'เศรษฐกิจ': 1679, 'ไทยภักดี': 1388, 'ไทยสร้างไทย': 1306, 'ไทยก้าวใหม่': 764, 'พลวัต': 317, 'รักชาติ': 300, 'กล้าธรรม': 247, 'ประชาธิปไตยใหม่': 198, 'ปวงชนไทย': 186, 'พิวชน': 127}

Processing:  10%|█         | 30/300 [02:57<25:14,  5.61s/doc]

constituency_10_7 {'ประชาชน': 40962, 'ภูมิใจไทย': 12037, 'รวมไทยสร้างชาติ': 11163, 'ประชาธิปัตย์': 8012, 'เพื่อไทย': 6236, 'เศรษฐกิจ': 2062, 'พลังประชารัฐ': 1406, 'กล้าธรรม': 863, 'ไทยสร้างไทย': 700, 'ไทยก้าวใหม่': 594, 'ฟิวชัน': 535, 'โอกาสใหม่': 323, 'พลวัต': 288}

Processing:  10%|█         | 31/300 [03:03<24:58,  5.57s/doc]

constituency_10_8 {'ประชาชน': 45092, 'เพื่อไทย': 15868, 'ภูมิใจไทย': 14632, 'ประชาธิปัตย์': 11399, 'รวมไทยสร้างชาติ': 2266, 'ไทยสร้างไทย': 1469, 'เศรษฐกิจ': 1352, 'ไทยก้าวใหม่': 865, 'ไทยภักดี': 864, 'พลังประชารัฐ': 857, 'โอกาสใหม่': 607, 'รักชาติ': 462, 'กล้าธรรม': 385, 'ปวงชนไทย': 224, 'วิชชั่นใหม่': 210, 'พลวัต': 203}

Processing:  11%|█         | 32/300 [03:08<24:02,  5.38s/doc]

constituency_10_9 {'ประชาชน': 49366, 'ภูมิใจไทย': 17059, 'ประชาธิปไตย': 11282, 'เพื่อไทย': 9827, 'รวมไทยสร้างชาติ': 3308, 'ไทยสร้างไทย': 904, 'รวมพลังประชาชน': 666, 'รักชาติ': 615, 'ไทยก้าวใหม่': 583, 'พลวัต': 440, 'กล้าธรรม': 334, 'ประชาธิปไตยใหม่': 281, 'โอกาสใหม่': 254, 'เพื่อบ้านเมือง': 192}

Processing:  11%|█         | 33/300 [03:12<22:43,  5.11s/doc]

constituency_11_1 {'ประชาชน': 43463, 'เพื่อไทย': 24150, 'ภูมิใจไทย': 12409, 'ประชาธิปัตย์': 3159, 'เศรษฐกิจ': 2066, 'พลังประชารัฐ': 1065, 'กล้าธรรม': 805, 'ปวงชนไทย': 762}

Processing:  11%|█▏        | 34/300 [03:17<22:12,  5.01s/doc]

constituency_11_2 {'ประชาชน': 40979, 'เพื่อไทย': 29448, 'ภูมิใจไทย': 7905, 'ประชาธิปัตย์': 2957, 'รวมไทยสร้างชาติ': 2506, 'เศรษฐกิจ': 2135, 'แรงงานสร้างชาติ': 793, 'ปวงชนไทย': 730, 'พลังประชารัฐ': 668, 'กล้าธรรม': 559, 'ไทยก้าวใหม่': 455}

Processing:  12%|█▏        | 35/300 [03:22<22:19,  5.06s/doc]

constituency_11_3 {'ประชาชน': 45335, 'ประชาธิปัตย์': 13276, 'ภูมิใจไทย': 11651, 'เพื่อไทย': 11151, 'กล้าธรรม': 1755, 'เศรษฐกิจ': 1565, 'พลังประชาธิปไตย': 1328, 'ไทยภักดี': 870, 'แรงงานสร้างชาติ': 849, 'ปวงชนไทย': 708}

Processing:  12%|█▏        | 36/300 [03:27<22:15,  5.06s/doc]

constituency_11_4 {'ประชาชน': 48876, 'เพื่อไทย': 15476, 'ภูมิใจไทย': 15300, 'ประชาธิปัตย์': 5904, 'โอกาสใหม่': 1977, 'รวมไทยสร้างชาติ': 1717, 'พลังประชาธิรัฐ': 1102, 'ไทยก้าวใหม่': 706, 'กล้าธรรม': 686, 'ทางเลือกใหม่': 461, 'ปวงชนไทย': 415}

Processing:  12%|█▏        | 37/300 [03:32<21:12,  4.84s/doc]

constituency_11_5 {'ประชาชน': 57198, 'ภูมิใจไทย': 15156, 'เพื่อไทย': 12323, 'ประชาธิปัตย์': 4717, 'พลังประชารัฐ': 2410, 'รวมไทยสร้างชาติ': 2237, 'ไทยก้าวใหม่': 1789, 'เสรีรวมไทย': 1342, 'โอกาสใหม่': 1306, 'ปวงชนไทย': 981, 'กล้าธรรม': 796}

Processing:  13%|█▎        | 38/300 [03:36<20:29,  4.69s/doc]

constituency_11_6 {'ภูมิใจไทย': 35571, 'ประชาชน': 33018, 'เพื่อไทย': 8020, 'ประชาธิปัตย์': 2246, 'รวมไทยสร้างชาติ': 1932, 'ปวงชนไทย': 1289, 'พลังประชารัฐ': 889, 'เสรีรวมไทย': 707, 'ไทยก้าวใหม่': 556, 'กล้าธรรม': 286}

Processing:  13%|█▎        | 39/300 [03:42<21:43,  4.99s/doc]

constituency_11_7 {'ประชาชน': 46394, 'ภูมิใจไทย': 28922, 'เพื่อไทย': 15568, 'เศรษฐกิจ': 2645, 'ประชาธิปัตย์': 1780, 'กล้าธรรม': 796, 'พลังประชารัฐ': 714, 'ไทยก้าวใหม่': 495, 'ปวงชนไทย': 377}

Processing:  13%|█▎        | 40/300 [03:47<22:09,  5.11s/doc]

constituency_11_8 {'ประชาชน': 40230, 'เพื่อไทย': 27991, 'กล้าธรรม': 16768, 'ภูมิใจไทย': 7685, 'ประชาธิปัตย์': 3068, 'เศรษฐกิจ': 2464, 'พลังประชารัฐ': 2271, 'ไทยก้าวใหม่': 1118, 'แรงงานสร้างไทย': 765, 'ปวงชนไทย': 682}

Processing:  14%|█▎        | 41/300 [03:52<21:24,  4.96s/doc]

constituency_12_1 {'ประชาชน': 42123, 'ภูมิใจไทย': 19861, 'เพื่อไทย': 9587, 'กล้าธรรม': 8706, 'ประชาธิปัตย์': 6573, 'เศรษฐกิจ': 2230, 'รวมไทยสร้างชาติ': 2034, 'เสรีรวมไทย': 1184, 'พลวัต': 791, 'พิวชัน': 403, 'พลังประชารัฐ': 391}

Processing:  14%|█▍        | 42/300 [03:58<23:18,  5.42s/doc]

constituency_12_2 {'ประชาชน': 38013, 'ภูมิใจไทย': 20126, 'เพื่อไทย': 10730, 'ประชาธิปัตย์': 5756, 'เศรษฐกิจ': 1667, 'รวมไทยสร้างชาติ': 1210, 'ไทยภักดี': 1047, 'พลังประชารัฐ': 906, 'กล้าธรรม': 563, 'ทางเลือกใหม่': 518, 'พลวัต': 386, 'ทิวชัน': 201}

Processing:  14%|█▍        | 43/300 [04:03<22:58,  5.37s/doc]

constituency_12_3 {'ประชาชน': 47405, 'เพื่อไทย': 17748, 'ภูมิใจไทย': 15854, 'ประชาธิปไตย': 7291, 'รวมไทยสร้างชาติ': 1873, 'กล้าธรรม': 1160, 'ทางเลือกใหม่': 957, 'เสรีรวมไทย': 778, 'พลวัต': 774, 'พลังประชารัฐ': 474}

Processing:  15%|█▍        | 44/300 [04:07<20:24,  4.78s/doc]

constituency_12_4 {'ประชาชน': 33461, 'ภูมิใจไทย': 27997, 'เพื่อไทย': 14692, 'ประชาธิปัตย์': 4054, 'เศรษฐกิจ': 1501, 'รวมไทยสร้างชาติ': 1279, 'พลวัต': 868, 'ทางเลือกใหม่': 646, 'ไทยพิทักษ์ธรรม': 359, 'กล้าธรรม': 346}

Processing:  15%|█▌        | 45/300 [04:12<21:20,  5.02s/doc]

constituency_12_5 {'ประชาชน': 41888, 'ภูมิใจไทย': 31985, 'เพื่อไทย': 8802, 'ประชาธิปัตย์': 5854, 'รวมไทยสร้างชาติ': 2424, 'เศรษฐกิจ': 1689, 'พลังประชารัฐ': 1507, 'กล้าธรรม': 1237, 'ทางเลือกใหม่': 520, 'ฟิวชัน': 201}

Processing:  15%|█▌        | 46/300 [04:17<20:29,  4.84s/doc]

constituency_12_6 {}

Processing:  16%|█▌        | 47/300 [04:22<20:29,  4.86s/doc]

constituency_12_7 {'ประชาชน': 41267, 'กล้าธรรม': 18873, 'ภูมิใจไทย': 13141, 'เพื่อไทย': 9933, 'ประชาธิปัตย์': 4932, 'รวมไทยสร้างชาติ': 2686, 'เศรษฐกิจ': 1683, 'ทางเลือกใหม่': 1006, 'พลวัต': 472}

Processing:  16%|█▌        | 48/300 [04:27<20:53,  4.97s/doc]

constituency_12_8 {'ประชาชน': 36631, 'ภูมิใจไทย': 26446, 'เพื่อไทย': 9038, 'กล้าธรรม': 5349, 'ประชาธิปัตย์': 4255, 'รวมไทยสร้างชาติ': 2172, 'เศรษฐกิจ': 1957, 'ประชากรไทย': 969, 'พลังประชารัฐ': 852, 'ฟิวชัน': 460, 'ทางเลือกใหม่': 331}

Processing:  16%|█▋        | 49/300 [04:32<21:09,  5.06s/doc]

constituency_13_1 {'ประชาชน': 32835, 'เพื่อไทย': 24558, 'กล้าธรรม': 24365, 'ภูมิใจไทย': 6562, 'ประชาธิปัตย์': 3508, 'รวมไทยสร้างชาติ': 1586, 'เศรษฐกิจ': 1487, 'พลังประชารัฐ': 300}

Processing:  17%|█▋        | 50/300 [04:36<19:46,  4.75s/doc]

constituency_13_2 {'พรรคเพื่อไทย': 36340, 'พรรคประชาชน': 31579, 'พรรคภูมิใจไทย': 23496, 'พรรคประชาธิปัตย์': 1651, 'พรรคเศรษฐกิจ': 1037, 'พรรครวมไทยสร้างชาติ': 991, 'พรรครักชาติ': 773, 'พรรคกล้าธรรม': 727, 'พรรคพลังประชารัฐ': 438}

Processing:  17%|█▋        | 51/300 [04:41<19:19,  4.66s/doc]

constituency_13_3 {'ประชาชน': 42004, 'ภูมิใจไทย': 22852, 'เพื่อไทย': 8637, 'ประชาธิปัตย์': 3891, 'เศรษฐกิจ': 3108, 'รวมไทยสร้างชาติ': 1499, 'ไทยก้าวใหม่': 1155, 'พลังประชารัฐ': 1007}

Processing:  17%|█▋        | 52/300 [04:46<19:44,  4.78s/doc]

constituency_13_4 {'พรรคประชาชน': 41039, 'พรรคเพื่อไทย': 17512, 'พรรคกล้าธรรม': 1522, 'พรรคภูมิใจไทย': 8216, 'พรรคประชาธิปัตย์': 3900, 'พรรคเศรษฐกิจ': 1903, 'พรรครวมไทยสร้างชาติ': 1495, 'พรรคพลังประชารัฐ': 1150, 'พรรครักชาติ': 399}

Processing:  18%|█▊        | 53/300 [04:51<20:26,  4.97s/doc]

constituency_13_5 {'ประชาชน': 35383, 'กล้าธรรม': 12941, 'เพื่อไทย': 12043, 'ภูมิใจไทย': 10418, 'ประชาธิปัตย์': 4424, 'เศรษฐกิจ': 2063, 'รวมไทยสร้างชาติ': 1559, 'ประชาธิปไตยใหม่': 1185, 'ไทยก้าวใหม่': 930, 'พลังประชารัฐ': 899, 'รักชาติ': 674}

Processing:  18%|█▊        | 54/300 [04:55<19:15,  4.70s/doc]

constituency_13_6 {'ประชาชน': 42684, 'เพื่อไทย': 10079, 'ภูมิใจไทย': 9739, 'กล้าธรรม': 8530, 'ประชาธิปัตย์': 6809, 'เศรษฐกิจ': 2767, 'รวมไทยสร้างชาติ': 2017, 'ไทยก้าวใหม่': 689, 'พลังประชารัฐ': 564, 'เสรีรวมไทย': 504}

Processing:  18%|█▊        | 55/300 [05:00<19:22,  4.74s/doc]

constituency_13_7 {'ภูมิใจไทย': 46202, 'ประชาชน': 27814, 'เพื่อไทย': 5324, 'เศรษฐกิจ': 2488, 'ประชาธิปัตย์': 1538, 'รวมไทยสร้างชาติ': 999, 'ไทยก้าวใหม่': 806, 'รักชาติ': 489, 'พลังประชารัฐ': 415}

Processing:  19%|█▊        | 56/300 [05:04<18:23,  4.52s/doc]

constituency_13_8 {'ภูมิใจไทย': 42730, 'ประชาชน': 26551, 'เพื่อไทย': 10865, 'ประชาธิปัตย์': 1978, 'รวมไทยสร้างชาติ': 1276, 'พลังประชารัฐ': 663, 'รักชาติ': 655, 'ประชาธิปไตยใหม่': 628}

Processing:  19%|█▉        | 57/300 [05:08<17:50,  4.40s/doc]

constituency_14_1 {'ภูมิใจไทย': 46696, 'ประชาชน': 37335, 'เพื่อไทย': 5895, 'ประชาธิปัตย์': 3557, 'เศรษฐกิจ': 1556, 'รวมไทยสร้างชาติ': 1512, 'เสรีรวมไทย': 673, 'ไทยสร้างชาติ': 326}

Processing:  19%|█▉        | 58/300 [05:15<20:07,  4.99s/doc]

constituency_14_2 {'ภูมิใจไทย': 53474, 'ประชาชน': 25836, 'เพื่อไทย': 9030, 'เศรษฐกิจ': 1953, 'รวมไทยสร้างชาติ': 1356, 'ประชาธิปัตย์': 1144, 'ไทยก้าวใหม่': 699, 'กล้าธรรม': 662, 'พลังประชารัฐ': 244}

Processing:  20%|█▉        | 59/300 [05:19<18:42,  4.66s/doc]

constituency_14_3 {'ภูมิใจไทย': 58072, 'ประชาชน': 31983, 'เพื่อไทย': 5768, 'เศรษฐกิจ': 2104, 'ประชาธิปัตย์': 1489, 'รวมไทยสร้างชาติ': 915}

Processing:  20%|██        | 60/300 [05:23<17:57,  4.49s/doc]

constituency_14_4 {'ภูมิใจไทย': 51469, 'ประชาชน': 31956, 'โอกาสใหม่': 13512, 'เพื่อไทย': 5682, 'เศรษฐกิจ': 1547, 'รวมไทยสร้างชาติ': 1104, 'ประชาธิปัตย์': 1034, 'พลังประชารัฐ': 609}

Processing:  20%|██        | 61/300 [05:26<16:49,  4.22s/doc]

constituency_14_5 {'ภูมิใจไทย': 46623, 'เพื่อไทย': 27374, 'ประชาชน': 21135, 'ประชาธิปัตย์': 1048, 'ไทยสร้างชาติ': 905, 'เศรษฐกิจ': 795, 'ไทยสร้างไทย': 503}

Processing:  21%|██        | 62/300 [05:31<17:09,  4.33s/doc]

constituency_15_1 {'ภูมิใจไทย': 56130, 'ประชาชน': 17910, 'เพื่อไทย': 4270, 'ประชาธิปัตย์': 795, 'กล้าธรรม': 366, 'พลังประชารัฐ': 304}

Processing:  21%|██        | 63/300 [05:35<17:03,  4.32s/doc]

constituency_15_2 {'ภูมิใจไทย': 60611, 'ประชาชน': 13876, 'เพื่อไทย': 4149, 'ประชาธิปัตย์': 1202}

Processing:  21%|██▏       | 64/300 [05:41<19:14,  4.89s/doc]

constituency_16_1 {'ภูมิใจไทย': 38126, 'ประชาชน': 25593, 'โอกาสใหม่': 15617, 'เพื่อไทย': 9992, 'เศรษฐกิจ': 2172, 'กล้าธรรม': 1842, 'พลังประชารัฐ': 1666, 'ประชาธิปัตย์': 1571, 'รวมไทยสร้างชาติ': 1498, 'ไทยสร้างไทย': 1379, 'ปวงชนไทย': 653}

Processing:  22%|██▏       | 65/300 [05:47<19:46,  5.05s/doc]

constituency_16_2 {'ภูมิใจไทย': 58141, 'ประชาชน': 24499, 'เพื่อไทย': 21604, 'ประชาธิปัตย์': 1650, 'เศรษฐกิจ': 1216, 'รวมไทยสร้างชาติ': 962, 'พลังประชาธิรัฐ': 833, 'ไทยสร้างชาติ': 823, 'ปวงชนชาวไทย': 317}

Processing:  22%|██▏       | 66/300 [05:53<21:28,  5.50s/doc]

constituency_16_3 {'ภูมิใจไทย': 49264, 'เพื่อไทย': 27504, 'ประชาชน': 15294, 'พลังประชารัฐ': 2527, 'เศรษฐกิจ': 1816, 'รวมไทยสร้างชาติ': 882, 'ปวงชนไทย': 801, 'ประชาธิปัตย์': 670, 'กล้าธรรม': 467}

Processing:  22%|██▏       | 67/300 [05:58<19:54,  5.13s/doc]

constituency_16_4 {'พรรคเพื่อไทย': 50031, 'พรรคกล้าธรรม': 33738, 'พรรคประชาชน': 18256, 'พรรคภูมิใจไทย': 2318, 'พรรคประชาธิปัตย์': 1354, 'พรรครวมไทยสร้างชาติ': 1279, 'พรรคเศรษฐกิจ': 1079, 'พรรคพลังประชารัฐ': 222}

Processing:  23%|██▎       | 68/300 [06:02<18:48,  4.86s/doc]

constituency_17_1 {'ภูมิใจไทย': 65555, 'ประชาชน': 31864, 'เพื่อไทย': 13763, 'ประชาธิปัตย์': 1523, 'พลังประชารัฐ': 1037, 'กล้าธรรม': 966}

Processing:  23%|██▎       | 69/300 [06:07<19:01,  4.94s/doc]

constituency_18_1 {'เพื่อไทย': 36058, 'ประชาชน': 28737, 'ประชาธิปัตย์': 7271, 'ภูมิใจไทย': 6221, 'กล้าธรรม': 1284, 'พลังประชารัฐ': 1199}

Processing:  23%|██▎       | 70/300 [06:10<16:37,  4.34s/doc]

constituency_18_2 {'ภูมิใจไทย': 54585, 'ประชาชน': 16933, 'เพื่อไทย': 8937, 'ประชาธิปไตย': 2819, 'พลังประชารัฐ': 747, 'กล่าธรรม': 463}

Processing:  24%|██▎       | 71/300 [06:14<16:38,  4.36s/doc]

constituency_19_1 {'ภูมิใจไทย': 31958, 'ประชาชน': 31087, 'เพื่อไทย': 14572, 'เศรษฐกิจ': 2942, 'ประชาธิปัตย์': 2737, 'ไทยก้าวใหม่': 1423, 'รวมไทยสร้างชาติ': 1156, 'กล้าธรรม': 1106, 'พลังประชารัฐ': 1072}

Processing:  24%|██▍       | 72/300 [06:19<17:18,  4.55s/doc]

constituency_19_2 {'พรรคภูมิใจไทย': 37225, 'พรรคเพื่อไทย': 27805, 'พรรคประชาชน': 25187, 'พรรคไทยก้าวใหม่': 3291, 'พรรคเศรษฐกิจ': 1836, 'พรรครวมไทยสร้างชาติ': 1782, 'พรรคประชาธิปัตย์': 1094, 'พรรคปวงชนไทย': 926}

Processing:  24%|██▍       | 73/300 [06:23<16:51,  4.46s/doc]

constituency_19_3 {'ภูมิใจไทย': 53967, 'ประชาชน': 28831, 'เพื่อไทย': 4647, 'รวมไทยสร้างชาติ': 1247, 'ประชาธิปัตย์': 1230, 'ปวงชนไทย': 643, 'กล้าธรรม': 515, 'ประชากรไทย': 371}

Processing:  25%|██▍       | 74/300 [06:28<16:41,  4.43s/doc]

constituency_19_4 {'พรรคกล้าธรรม': 48159, 'พรรคประชาชน': 28119, 'พรรคภูมิใจไทย': 5163, 'พรรคเพื่อไทย': 3452, 'พรรคประชาธิปัตย์': 2402, 'พรรคเศรษฐกิจ': 1950, 'พรรคไทยก้าวใหม่': 822}

Processing:  25%|██▌       | 75/300 [06:32<16:44,  4.46s/doc]

constituency_20_1 {'ภูมิใจไทย': 46253, 'ประชาชน': 42057, 'ประชาธิปัตย์': 2935, 'เพื่อไทย': 2435, 'เศรษฐกิจ': 1411, 'รวมไทยสร้างชาติ': 1311, 'ไทยสร้างไทย': 673, 'พลังประชารัฐ': 327, 'ปวงชนไทย': 183}

Processing:  25%|██▌       | 76/300 [06:38<18:02,  4.83s/doc]

constituency_20_10 {'ประชาชน': 27129, 'ภูมิใจไทย': 23571, 'กล้าธรรม': 23062, 'เพื่อไทย': 3326, 'ประชาธิปัตย์': 1853, 'เศรษฐกิจ': 1324, 'รวมไทยสร้างชาติ': 1108, 'ไทยสร้างไทย': 420, 'พลังประชารัฐ': 336, 'ปวงชนไทย': 328}

Processing:  26%|██▌       | 77/300 [06:42<16:48,  4.52s/doc]

constituency_20_2 {'ประชาชน': 30061, 'ภูมิใจไทย': 28820, 'ประชาธิปัตย์': 14341, 'เพื่อไทย': 3085, 'เศรษฐกิจ': 1131, 'ไทยภักดี': 827, 'ปวงชนไทย': 281, 'พลังประชารัฐ': 279}

Processing:  26%|██▌       | 78/300 [06:45<15:26,  4.18s/doc]

constituency_20_3 {'ภูมิใจไทย': 42501, 'ประชาชน': 37164, 'เพื่อไทย': 3641, 'ประชาธิปัตย์': 2967, 'เศรษฐกิจ': 2055, 'ไทยภักดี': 1199, 'พลังประชารัฐ': 774}

Processing:  26%|██▋       | 79/300 [06:51<17:00,  4.62s/doc]

constituency_20_4 {'ภูมิใจไทย': 45751, 'ประชาชน': 24213, 'ประชาธิปัตย์': 6426, 'เพื่อไทย': 2151, 'พลังประชาธิปไตย': 987, 'ไทยภักดี': 850, 'ปวงชนไทย': 392}

Processing:  27%|██▋       | 80/300 [06:56<16:57,  4.63s/doc]

constituency_20_5 {'ภูมิใจไทย': 52767, 'ประชาชน': 24749, 'เพื่อไทย': 7729, 'ประชาธิปัตย์': 3766, 'เศรษฐกิจ': 2846, 'รวมไทยสร้างชาติ': 917, 'พลังประชาธิปไตย': 855, 'แรงงานสร้างชาติ': 803, 'ปวงชนไทย': 660, 'ไทยภักดี': 372}

Processing:  27%|██▋       | 81/300 [07:01<18:00,  4.93s/doc]

constituency_20_6 {'ประชาชน': 41248, 'ภูมิใจไทย': 34860, 'เพื่อไทย': 3877, 'ประชาธิปัตย์': 3241, 'พรรคไทยภักดี': 1647, 'เศรษฐกิจ': 1530, 'กล้าธรรม': 910, 'แรงงานสร้างชาติ': 685, 'พลังประชารัฐ': 674, 'สังคมประชาธิปไตยไทย': 321, 'ปวงชนไทย': 268, 'คลองไทย': 163}

Processing:  27%|██▋       | 82/300 [07:06<18:05,  4.98s/doc]

constituency_20_7 {'ประชาชน': 39986, 'ภูมิใจไทย': 31986, 'เพื่อไทย': 3003, 'ประชาธิปไตย': 2584, 'เศรษฐกิจ': 2100, 'รวมไทยสร้างชาติ': 1412, 'ปวงชนไทย': 494, 'ไทยภักดี': 451, 'สังคมประชาธิปไตยไทย': 386, 'พลังประชารัฐ': 352}

Processing:  28%|██▊       | 83/300 [07:11<17:24,  4.81s/doc]

constituency_20_8 {'ภูมิใจไทย': 37623, 'ประชาชน': 34702, 'เพื่อไทย': 4471, 'ประชาธิปัตย์': 3430, 'เศรษฐกิจ': 2046, 'เสรีรวมไทย': 1181, 'พลังประชารัฐ': 1086, 'ปวงชนไทย': 1043, 'ไทยสร้างไทย': 722, 'ไทยภักดี': 690}

Processing:  28%|██▊       | 84/300 [07:14<15:29,  4.30s/doc]

constituency_20_9 {'ประชาชน': 27602, 'ภูมิใจไทย': 23698, 'เพื่อไทย': 5600, 'ประชาธิปัตย์': 2665, 'รวมไทยสร้างชาติ': 1157, 'ไทยภักดี': 940, 'พลังประชาธิปไตย': 407, 'ปวงชนไทย': 340}

Processing:  28%|██▊       | 85/300 [07:19<16:04,  4.49s/doc]

constituency_21_1 {'ประชาชน': 36934, 'ภูมิใจไทย': 27277, 'ประชาธิปัตย์': 15357, 'เพื่อไทย': 2917, 'รวมไทยสร้างชาติ': 1093, 'พลังประชารัฐ': 664, 'ไทยสร้างไทย': 428, 'ไทยก้าวใหม่': 421}

Processing:  29%|██▊       | 86/300 [07:22<14:58,  4.20s/doc]

constituency_21_2 {'ประชาชน': 33687, 'ประชาธิปไตย': 26878, 'เพื่อไทย': 4268, 'ไทยสร้างไทย': 1981, 'ไทยก้าวใหม่': 1737}

Processing:  29%|██▉       | 87/300 [07:27<15:46,  4.44s/doc]

constituency_21_3 {'ประชาธิปัตย์': 26873, 'ประชาชน': 24801, 'รวมไทยสร้างชาติ': 15572, 'เพื่อไทย': 5580, 'ภูมิใจไทย': 2454, 'ไทยสร้างไทย': 788, 'ไทยก้าวใหม่': 395}

Processing:  29%|██▉       | 88/300 [07:31<14:51,  4.20s/doc]

constituency_21_4 {'ภูมิใจไทย': 46134, 'ประชาชน': 32496, 'ประชาธิปัตย์': 3744, 'เพื่อไทย': 3433, 'รวมไทยสร้างชาติ': 1036, 'ไทยก้าวใหม่': 366, 'กล้าธรรม': 317}

Processing:  30%|██▉       | 89/300 [07:35<14:35,  4.15s/doc]

constituency_21_5 {'ประชาชน': 37569, 'ภูมิใจไทย': 29469, 'ประชาธิปัตย์': 6244, 'เพื่อไทย': 5120, 'รวมไทยสร้างชาติ': 1672, 'ไทยสร้างไทย': 1215}

Processing:  30%|███       | 90/300 [07:40<15:28,  4.42s/doc]

constituency_22_1 {'ภูมิใจไทย': 32984, 'ประชาชน': 29390, 'เพื่อไทย': 23506, 'ประชาธิปัตย์': 6271, 'เศรษฐกิจ': 3460, 'รวมไทยสร้างชาติ': 2115, 'กล้าธรรม': 1736, 'ไทยก้าวใหม่': 1133, 'ปวงชนไทย': 271}

Processing:  30%|███       | 91/300 [07:43<14:10,  4.07s/doc]

constituency_22_2 {'พรรคภูมิใจไทย': 39979, 'พรรคประชาชน': 29466, 'พรรคเพื่อไทย': 9940, 'พรรคประชาธิปัตย์': 6708, 'พรรคเศรษฐกิจ': 4672, 'พรรคกล้าธรรม': 1042}

Processing:  31%|███       | 92/300 [07:49<15:48,  4.56s/doc]

constituency_22_3 {'ภูมิใจไทย': 31798, 'พลังประชารัฐ': 26664, 'ประชาชน': 20697, 'เพื่อไทย': 4138, 'กล้าธรรม': 2924, 'ประชาธิปัตย์': 2830, 'รักชาติ': 1030, 'ไทยก้าวใหม่': 856, 'ปวงชนไทย': 239}

Processing:  31%|███       | 93/300 [07:54<16:24,  4.75s/doc]

constituency_23_1 {'ภูมิใจไทย': 66399, 'ประชาชน': 27911, 'ประชาธิปัตย์': 7665, 'เพื่อไทย': 4716, 'กล้าธรรม': 4084, 'พลังประชารัฐ': 3857, 'ไทยสร้างไทย': 944}

Processing:  31%|███▏      | 94/300 [07:59<16:29,  4.81s/doc]

constituency_24_1 {'พรรคเพื่อไทย': 38717, 'พรรคประชาชน': 34889, 'พรรคภูมิใจไทย': 13705, 'พรรคประชาธิปัตย์': 5677, 'พรรคกล้าธรรม': 1889, 'พรรคปวงชนไทย': 1127}

Processing:  32%|███▏      | 95/300 [08:03<15:49,  4.63s/doc]

constituency_24_2 {'กล้าธรรม': 50833, 'เพื่อไทย': 32111, 'ประชาชน': 20063, 'ภูมิใจไทย': 3019, 'ปวงชนไทย': 1000}

Processing:  32%|███▏      | 96/300 [08:07<15:14,  4.48s/doc]

constituency_24_3 {'กล้าธรรม': 52758, 'ประชาชน': 21616, 'พรรคเพื่อไทย': 14500, 'พรรคภูมิใจไทย': 2003, 'พรรคประชาธิปัตย์': 1377, 'พรรคปวงชนไทย': 929, 'พรรคพลังประชาธิรัฐ': 570}

Processing:  32%|███▏      | 97/300 [08:12<15:36,  4.61s/doc]

constituency_24_4 {'กล้าธรรม': 47969, 'ประชาชน': 35257, 'เพื่อไทย': 19940, 'ภูมิใจไทย': 4399, 'ประชาธิปัตย์': 2574, 'ปวงชนไทย': 806}

Processing:  33%|███▎      | 98/300 [08:16<14:09,  4.21s/doc]

constituency_25_1 {'ภูมิใจไทย': 42309, 'ประชาชน': 28549, 'เพื่อไทย': 6144, 'กล้าธรรม': 2124, 'ประชาธิปัตย์': 1661, 'โอกาสใหม่': 1413, 'ไทยภักดี': 723}

Processing:  33%|███▎      | 99/300 [08:19<13:25,  4.01s/doc]

constituency_25_3 {'ภูมิใจไทย': 45193, 'ประชาชน': 24795, 'เพื่อไทย': 10575, 'ประชาธิปไตย': 2724, 'ไทยภักดี': 1060}

Processing:  33%|███▎      | 100/300 [08:23<12:56,  3.88s/doc]

constituency_26_1 {'กล้าธรรม': 33707, 'ภูมิใจไทย': 29822, 'ประชาชน': 11054, 'รวมไทยสร้างชาติ': 1290, 'ประชาธิปัตย์': 908}

Processing:  34%|███▎      | 101/300 [08:27<12:44,  3.84s/doc]

constituency_26_2 {'พรรคภูมิใจไทย': 34897, 'พรรคกล้าธรรม': 29375, 'พรรคประชาชน': 13388, 'พรรคประชาธิปัตย์': 1404, 'พรรคพลังประชารัฐ': 964, 'พรรคแรงงานสร้างชาติ': 769}

Processing:  34%|███▍      | 102/300 [08:31<13:42,  4.15s/doc]

constituency_27_1 {'พลังประชารัฐ': 56083, 'ประชาชน': 19172, 'ไทยก้าวใหม่': 299, 'ภูมิใจไทย': 2751, 'ประชาธิปไตย': 2661, 'เพื่อไทย': 2510, 'เศรษฐกิจ': 2489, 'กล้าธรรม': 731, 'ประชาธิปไตยใหม่': 217}

Processing:  34%|███▍      | 103/300 [08:37<14:54,  4.54s/doc]

constituency_27_2 {'พลังประชารัฐ': 60370, 'ประชาชน': 17343, 'เศรษฐกิจ': 3362, 'เพื่อไทย': 2986, 'ประชาธิปัตย์': 1835, 'ภูมิใจไทย': 1823, 'ไทยก้าวใหม่': 647, 'กล้าธรรม': 533, 'ประชาธิปไตยใหม่': 452}

Processing:  35%|███▍      | 104/300 [08:42<15:12,  4.65s/doc]

constituency_27_3 {'กล้าธรรม': 38812, 'เพื่อไทย': 32848, 'ประชาชน': 13842, 'เศรษฐกิจ': 2378, 'ภูมิใจไทย': 2324, 'ประชาธิปัตย์': 1937, 'ไทยก้าวใหม่': 484, 'ประชาธิปไตยใหม่': 243}

Processing:  35%|███▌      | 105/300 [08:48<16:20,  5.03s/doc]

constituency_30_1 {'ประชาชน': 32534, 'เพื่อไทย': 23435, 'ภูมิใจไทย': 14417, 'เศรษฐกิจ': 3168, 'รวมไทยสร้างชา': 1838, 'ประชาธิปัตย์': 1672, 'ไทยก้าวใหม่': 1294, 'พลังประชารัฐ': 757, 'กล้าธรรม': 552, 'โอกาสใหม่': 517, 'รวมใจไทย': 358, 'ปวงชนไทย': 252, 'รักษ์ธรรม': 191}

Processing:  35%|███▌      | 106/300 [08:52<15:37,  4.83s/doc]

constituency_30_10 {'พรรคภูมิใจไทย': 43185, 'พรรคเพื่อไทย': 37863, 'พรรคประชาชน': 15343, 'พรรคโอกาสใหม่': 4824, 'พรรคเศรษฐกิจ': 1261, 'พรรคกล้าธรรม': 1050, 'พรรคประชาธิปัตย์': 560, 'พรรคพลังประชารัฐ': 222}

Processing:  36%|███▌      | 107/300 [08:56<15:08,  4.71s/doc]

constituency_30_11 {'เพื่อไทย': 53069, 'ประชาชน': 15952, 'ภูมิใจไทย': 7697, 'เศรษฐกิจ': 3168, 'กล้าธรรม': 2708, 'ประชาธิปัตย์': 1260, 'ทางเลือกใหม่': 560, 'ไทยก้าวใหม่': 470, 'เพื่อบ้านเมือง': 132}

Processing:  36%|███▌      | 108/300 [09:00<14:15,  4.45s/doc]

constituency_30_12 {'เพื่อไทย': 47794, 'ภูมิใจไทย': 16572, 'ประชาชน': 16493, 'เศรษฐกิจ': 1527, 'โอกาสใหม่': 1288, 'ประชาธิปัตย์': 1229, 'กล้าธรรม': 830, 'รักชาติ': 273}

Processing:  36%|███▋      | 109/300 [09:05<14:37,  4.59s/doc]

constituency_30_13 {'เพื่อไทย': 28157, 'ประชาชน': 25404, 'ภูมิใจไทย': 5887, 'เศรษฐกิจ': 3028, 'พลังประชารัฐ': 1944, 'ประชาธิปัตย์': 1775, 'เพื่อบ้านเมือง': 310, 'กล้าธรรม': 0}

Processing:  37%|███▋      | 110/300 [09:10<14:35,  4.61s/doc]

constituency_30_14 {'พรรคประชาชน': 29003, 'พรรคเพื่อไทย': 28220, 'พรรคภูมิใจไทย': 9673, 'พรรคเศรษฐกิจ': 2150, 'พรรครวมไทยสร้างชาติ': 2079, 'พรรคประชาธิปัตย์': 2064}

Processing:  37%|███▋      | 111/300 [09:15<15:23,  4.89s/doc]

constituency_30_15 {'พรรคเพื่อไทย': 37242, 'พรรคภูมิใจไทย': 26946, 'พรรคกล้าธรรม': 15641, 'พรรคประชาชน': 12635, 'พรรคเศรษฐกิจ': 1283, 'พรรคพลังประชารัฐ': 549, 'พรรคประชาธิปัตย์': 491, 'พรรคไทยก้าวใหม่': 286, 'พรรคทางเลือกใหม่': 126}

Processing:  37%|███▋      | 112/300 [09:19<14:05,  4.50s/doc]

constituency_30_16 {'ภูมิใจไทย': 32139, 'เพื่อไทย': 31496, 'ประชาชน': 14870, 'กล้าธรรม': 1215, 'พลังประชารัฐ': 1095, 'เศรษฐกิจ': 982, 'เพื่อบ้านเมือง': 916, 'ประชาธิปัตย์': 586, 'ไทยธรรม': 435, 'ไทยภักดี': 265}

Processing:  38%|███▊      | 113/300 [09:25<15:05,  4.84s/doc]

constituency_30_2 {'เพื่อไทย': 39980, 'ประชาชน': 39142, 'ภูมิใจไทย': 9871, 'เศรษฐกิจ': 3023, 'ชาติ': 1432, 'ประชาธิปัตย์': 1195, 'พลังประชารัฐ': 668, 'ไทยก้าวใหม่': 652, 'กล้าธรรม': 412, 'รักชาติ': 335}

Processing:  38%|███▊      | 114/300 [09:30<15:44,  5.08s/doc]

constituency_30_3 {'ประชาชน': 3769, 'เพื่อไทย': 37400, 'ภูมิใจไทย': 7864, 'เศรษฐกิจ': 3174, 'ชาติ': 2153, 'ประชาธิปัตย์': 199, 'กล้าธรรม': 1166, 'พลังประชารัฐ': 81, 'ไทยก้าวใหม่': 36}

Processing:  38%|███▊      | 115/300 [09:36<15:50,  5.14s/doc]

constituency_30_4 {'เพื่อไทย': 34719, 'ประชาชน': 26339, 'ภูมิใจไทย': 15649, 'รวมไทยสร้างชาติ': 1605, 'เศรษฐกิจ': 1551, 'ประชาธิปัตย์': 1550, 'ไทยก้าวหน้า': 1271, 'กล้าธรรม': 745, 'ปวงชนไทย': 691, 'ไทยพร้อม': 182}

Processing:  39%|███▊      | 116/300 [09:41<15:54,  5.19s/doc]

constituency_30_5 {'เพื่อไทย': 38845, 'ภูมิใจไทย': 30864, 'ประชาชน': 13546, 'เศรษฐกิจ': 1490, 'พลังประชารัฐ': 1171, 'ประชาธิปัตย์': 831, 'กล้าธรรม': 595, 'ไทยภักดี': 302, 'ไทยก้าวใหม่': 0}

Processing:  39%|███▉      | 117/300 [09:46<16:05,  5.28s/doc]

constituency_30_6 {'เพื่อไทย': 27973, 'ภูมิใจไทย': 19113, 'กล้าธรรม': 17378, 'ประชาชน': 11687, 'พลังประชารัฐ': 2065, 'รวมไทยสร้างชาติ': 888, 'ปวงชนไทย': 737, 'เศรษฐกิจ': 629, 'เพื่อบ้านเมือง': 456, 'ประชาธิปัตย์': 439, 'ไทยพร้อม': 366, 'ไทยก้าวใหม่': 80}

Processing:  39%|███▉      | 118/300 [09:50<14:49,  4.89s/doc]

constituency_30_7 {'เพื่อไทย': 40228, 'ภูมิใจไทย': 21229, 'ประชาชน': 12032, 'เศรษฐกิจ': 1483, 'ประชาธิปัตย์': 897, 'ไทยก้าวใหม่': 417, 'กล้าธรรม': 387, 'ไทยธรรม': 208, 'เพื่อบ้านเมือง': 37}

Processing:  40%|███▉      | 119/300 [09:55<14:39,  4.86s/doc]

constituency_30_8 {'เพื่อไทย': 51840, 'ประชาชน': 14747, 'ภูมิใจไทย': 10250, 'เศรษฐกิจ': 1490, 'ประชาธิปัตย์': 1194}

Processing:  40%|████      | 120/300 [10:01<15:40,  5.22s/doc]

constituency_30_9 {'ภูมิใจไทย': 41235, 'กล้าธรรม': 24623, 'ประชาชน': 14731, 'เพื่อไทย': 4320, 'เศรษฐกิจ': 1150, 'รวมไทยสร้างชาติ': 617, 'ประชาธิปัตย์': 570, 'ไทยภักดี': 258, 'ไทยก้าวใหม่': 151}

Processing:  40%|████      | 121/300 [10:05<14:44,  4.94s/doc]

constituency_31_1 {'ภูมิใจไทย': 57074, 'ประชาชน': 14995, 'เพื่อไทย': 3301, 'ประชาธิปัตย์': 1052, 'เศรษฐกิจ': 754, 'รวมไทยสร้างชาติ': 722, 'ประชากรไทย': 501, 'กล้าธรรม': 490}

Processing:  41%|████      | 122/300 [10:11<15:32,  5.24s/doc]

constituency_31_10 {'ภูมิใจไทย': 52091, 'ประชาชน': 9229, 'เพื่อไทย': 4221, 'ประชาธิปัตย์': 1489, 'เศรษฐกิจ': 852, 'รวมไทยสร้างชาติ': 485, 'ประชากรไทย': 469, 'ปวงชนไทย': 226, 'กล้าธรรม': 114}

Processing:  41%|████      | 123/300 [10:17<15:29,  5.25s/doc]

constituency_31_2 {'ภูมิใจไทย': 56479, 'ประชาชน': 11395, 'เพื่อไทย': 3555, 'เศรษฐกิจ': 1043, 'ประชากรไทย': 691, 'ประชาธิปัตย์': 653, 'ปวงชนไทย': 549, 'รวมไทยสร้างชาติ': 491, 'กล้าธรรม': 199}

Processing:  41%|████▏     | 124/300 [10:21<14:13,  4.85s/doc]

constituency_31_3 {'ภูมิใจไทย': 56210, 'ประชาชน': 10630, 'เพื่อไทย': 3054, 'รวมไทยสร้างชาติ': 325, 'ประชากรไทย': 507, 'กล้าธรรม': 459, 'ปวงชนไทย': 295, 'ประชาธิปัตย์': 295}

Processing:  42%|████▏     | 125/300 [10:25<13:20,  4.57s/doc]

constituency_31_4 {'ภูมิใจไทย': 51536, 'ประชาชน': 11667, 'เพื่อไทย': 3699, 'ประชาธิปัตย์': 846, 'รวมไทยสร้างชาติ': 683, 'เศรษฐกิจ': 678, 'กล้าธรรม': 336}

Processing:  42%|████▏     | 126/300 [10:30<14:12,  4.90s/doc]

constituency_31_5 {'ภูมิใจไทย': 53732, 'ประชาชน': 10694, 'เพื่อไทย': 7914, 'เศรษฐกิจ': 1238, 'ประชาธิปัตย์': 1052, 'ไทยสร้างไทย': 807, 'รวมไทยสร้างชาติ': 714, 'ประชากรไทย': 305, 'กล้าธรรม': 194}

Processing:  42%|████▏     | 127/300 [10:36<15:03,  5.22s/doc]

constituency_31_6 {'ภูมิใจไทย': 51523, 'ประชาชน': 11551, 'เพื่อไทย': 5419, 'ประชาธิปัตย์': 1239, 'รวมไทยสร้างชาติ': 1211, 'เศรษฐกิจ': 851, 'ประชากรไทย': 682, 'ปวงชนไทย': 462, 'กล้าธรรม': 433, 'ไทยสร้างไทย': 237}

Processing:  43%|████▎     | 128/300 [10:41<14:28,  5.05s/doc]

constituency_31_7 {'ภูมิใจไทย': 45919, 'เพื่อไทย': 13982, 'ประชาชน': 11091, 'เศรษฐกิจ': 880, 'ประชากรไทย': 734, 'ประชาธิปัตย์': 621, 'รวมไทยสร้างชาติ': 522, 'กล้าธรรม': 406, 'ปวงชนไทย': 382}

Processing:  43%|████▎     | 129/300 [10:46<14:13,  4.99s/doc]

constituency_31_8 {'ภูมิใจไทย': 53217, 'ประชาชน': 15367, 'เพื่อไทย': 4664, 'เศรษฐกิจ': 1396, 'ประชาธิปัตย์': 1050, 'ประชากรไทย': 742, 'รวมไทยสร้างชาติ': 647, 'กล้าธรรม': 584, 'ปวงชนไทย': 484, 'ประชาธิปไตยใหม่': 277}

Processing:  43%|████▎     | 130/300 [10:50<13:35,  4.80s/doc]

constituency_31_9 {'ภูมิใจไทย': 57197, 'ประชาชน': 8695, 'เพื่อไทย': 4068, 'เศรษฐกิจ': 1393, 'รวมไทยสร้างชาติ': 887, 'ปวงชนไทย': 513, 'ประชาธิปัตย์': 491, 'ประชากรไทย': 299, 'กล้าธรรม': 152}

Processing:  44%|████▎     | 131/300 [10:54<12:56,  4.60s/doc]

constituency_32_1 {'พรรคภูมิใจไทย': 46167, 'พรรคประชาชน': 23104, 'พรรคเพื่อไทย': 9423, 'พรรคกล้าธรรม': 2528, 'พรรคเศรษฐกิจ': 1813, 'พรรคประชาธิปัตย์': 1312, 'พรรครวมไทยสร้างชาติ': 984, 'พรรคพลังประชารัฐ': 650}

Processing:  44%|████▍     | 132/300 [10:59<13:02,  4.66s/doc]

constituency_32_2 {'ภูมิใจไทย': 53228, 'เพื่อไทย': 17069, 'ประชาชน': 14307, 'เศรษฐกิจ': 1114, 'รวมไทยสร้างชาติ': 1064, 'ประชาธิปัตย์': 970, 'กล้าธรรม': 613, 'ประชาธิปไตยใหม่': 474, 'พลังประชารัฐ': 463, 'ปวงชนไทย': 131}

Processing:  44%|████▍     | 133/300 [11:04<13:17,  4.77s/doc]

constituency_32_3 {'ภูมิใจไทย': 50333, 'ประชาชน': 14826, 'เพื่อไทย': 10467, 'พลังประชารัฐ': 1002, 'ปวงชนไทย': 993, 'เศรษฐกิจ': 971, 'ประชาธิปัตย์': 413, 'รวมไทยสร้างชาติ': 326, 'กล้าธรรม': 308}

Processing:  45%|████▍     | 134/300 [11:10<14:13,  5.14s/doc]

constituency_32_4 {'ภูมิใจไทย': 44913, 'เพื่อไทย': 14672, 'ประชาชน': 14535, 'กล้าธรรม': 1877, 'พลังประชารัฐ': 1118, 'เศรษฐกิจ': 913, 'ประชาธิปัตย์': 740, 'แรงงานสร้างชาติ': 588, 'ปวงชนไทย': 407, 'สร้างชาติ': 399}

Processing:  45%|████▌     | 135/300 [11:15<14:17,  5.20s/doc]

constituency_32_5 {'ภูมิใจไทย': 41671, 'กล้าธรรม': 17798, 'ประชาชน': 11273, 'เพื่อไทย': 6095, 'แรงงานสร้างชาติ': 828, 'เศรษฐกิจ': 476, 'ประชาธิปัตย์': 302, 'พลังสังคมใหม่': 290, 'ปวงชนไทย': 288, 'สร้างอุทกภ์ตไทย': 246, 'รวมไทยสร้างชาติ': 173}

Processing:  45%|████▌     | 136/300 [11:22<15:17,  5.59s/doc]

constituency_32_6 {'ภูมิใจไทย': 52005, 'ประชาชน': 10955, 'เพื่อไทย': 9122, 'เศรษฐกิจ': 1211, 'กล้าธรรม': 1024, 'ประชาธิปัตย์': 791, 'ปวงชนไทย': 739, 'รวมไทยสร้างชาติ': 479, 'ไทยทรัพย์ทวี': 224}

Processing:  46%|████▌     | 137/300 [11:26<14:20,  5.28s/doc]

constituency_32_7 {'ภูมิใจไทย': 43239, 'เพื่อไทย': 24474, 'ประชาชน': 13352, 'เศรษฐกิจ': 1844, 'กล้าธรรม': 768, 'ประชาธิปัตย์': 735, 'ปวงชนไทย': 428}

Processing:  46%|████▌     | 138/300 [11:32<14:54,  5.52s/doc]

constituency_32_8 {'ภูมิใจไทย': 52673, 'ประชาชน': 15302, 'เพื่อไทย': 5899, 'เศรษฐกิจ': 2794, 'กล้าธรรม': 1007, 'รวมไทยสร้างชาติ': 521, 'ประชาธิปัตย์': 408, 'ปวงชนไทย': 315}

Processing:  46%|████▋     | 139/300 [11:37<14:17,  5.32s/doc]

constituency_33_1 {'ภูมิใจไทย': 53220, 'เพื่อไทย': 25401, 'ประชาชน': 13456, 'ปวงชนไทย': 868, 'ประชาธิปัตย์': 460, 'เศรษฐกิจ': 438, 'ประชาธิปไตยใหม่': 394, 'กล้าธรรม': 222, 'รวมไทยสร้างชาติ': 207}

Processing:  47%|████▋     | 140/300 [11:42<13:55,  5.22s/doc]

constituency_33_2 {'ภูมิใจไทย': 35712, 'เพื่อไทย': 30103, 'ประชาชน': 10448, 'รวมพลังประชาชน': 1392, 'กล้าธรรม': 1166, 'เศรษฐกิจ': 868, 'ทางเลือกใหม่': 310, 'ประชาธิปัตย์': 283, 'ประชาธิปไตยใหม่': 201, 'ไทยก้าวใหม่': 153, 'ปวงชนไทย': 81}

Processing:  47%|████▋     | 141/300 [11:47<13:23,  5.06s/doc]

constituency_33_3 {'พรรคภูมิใจไทย': 51942, 'พรรคประชาชน': 9196, 'พรรคเพื่อไทย': 8230, 'พรรคพลังประชารัฐ': 2931, 'พรรคเศรษฐกิจ': 1611, 'พรรคกล้าธรรม': 1059, 'พรรคประชาธิปัตย์': 1041, 'พรรคประชาธิปไตยใหม่': 341, 'พรรคประชากรไทย': 122, 'พรรครวมพลัง': 113}

Processing:  47%|████▋     | 142/300 [11:53<14:20,  5.45s/doc]

constituency_33_4 {'ภูมิใจไทย': 43534, 'กล้าธรรม': 20190, 'ประชาชน': 8100, 'เพื่อไทย': 3428, 'เศรษฐกิจ': 969, 'รวมไทยสร้างชาติ': 789, 'ประชากรไทย': 372, 'ประชาธิปัตย์': 293, 'พลังประชารัฐ': 96, 'ปวงชนไทย': 93}

Processing:  48%|████▊     | 143/300 [11:57<13:05,  5.00s/doc]

constituency_33_5 {'ภูมิใจไทย': 39108, 'เพื่อไทย': 25755, 'ประชาชน': 11077, 'เศรษฐกิจ': 1091, 'ประชากรไทย': 887, 'ประชาธิปัตย์': 652, 'กล้าธรรม': 619, 'รวมไทยสร้างชาติ': 395, 'ปวงชนไทย': 87}

Processing:  48%|████▊     | 144/300 [12:03<13:42,  5.27s/doc]

constituency_33_6 {'เพื่อไทย': 31345, 'ภูมิใจไทย': 31072, 'ประชาชน': 13132, 'เศรษฐกิจ': 1724, 'กล้าธรรม': 502, 'ประชาธิปไตยใหม่': 438, 'ประชาธิปไตย': 435, 'รวมไทยสร้างชาติ': 415}

Processing:  48%|████▊     | 145/300 [12:09<13:40,  5.30s/doc]

constituency_33_7 {'เพื่อไทย': 36190, 'ภูมิใจไทย': 31642, 'ประชาชน': 9181, 'พลังประชารัฐ': 544, 'ประชาธิปัตย์': 441, 'กล้าธรรม': 263, 'ประชาธิปไตยใหม่': 278, 'ประชากรไทย': 92}

Processing:  49%|████▊     | 146/300 [12:14<13:49,  5.39s/doc]

constituency_33_8 {'ภูมิใจไทย': 59873, 'ประชาชน': 12268, 'เพื่อไทย': 10201, 'ปวงชนไทย': 435, 'เศรษฐกิจ': 503, 'กล้าธรรม': 415, 'ประชาธิปัตย์': 334, 'ประชาธิปไตยใหม่': 146}

Processing:  49%|████▉     | 147/300 [12:19<13:28,  5.29s/doc]

constituency_33_9 {'ภูมิใจไทย': 39667, 'เพื่อไทย': 19391, 'ประชาชน': 14525, 'กล้าธรรม': 12281, 'พลังประชารัฐ': 1069, 'เศรษฐกิจ': 555, 'ประชาธิปัตย์': 368, 'รวมไทยสร้างชาติ': 359, 'ประชาธิปไตยใหม่': 214, 'ปวงชนไทย': 137}

Processing:  49%|████▉     | 148/300 [12:24<12:57,  5.11s/doc]

constituency_34_1 {'เพื่อไทย': 32328, 'ประชาชน': 27314, 'ประชาธิปัตย์': 9184, 'ไทยสร้างไทย': 7869, 'ภูมิใจไทย': 7327, 'เศรษฐกิจ': 2283, 'พลวัต': 1098, 'พลังประชารัฐ': 588}

Processing:  50%|████▉     | 149/300 [12:27<11:08,  4.43s/doc]

constituency_34_10 {'ไทรวมพลัง': 66909, 'ประชาชน': 7494, 'เพื่อไทย': 6973, 'ภูมิใจไทย': 3026, 'ประชาธิปัตย์': 612, 'พลังประชารัฐ': 542}

Processing:  50%|█████     | 150/300 [12:31<10:54,  4.36s/doc]

constituency_34_11 {'ภูมิใจไทย': 58379, 'ประชาชน': 11868, 'เพื่อไทย': 4521, 'ไทยสร้างไทย': 2690, 'รวมไทยสร้างชาติ': 1047, 'ประชาธิปัตย์': 781, 'กล้าธรรม': 746}

Processing:  50%|█████     | 151/300 [12:41<15:02,  6.06s/doc]

party_list_10_1 {'เพื่อขาดไทย': 130, 'รวมไอไทย': 226, 'รวมไทยสร้างชาติ': 1857, 'พลรัต': 103, 'ประชาธิปไตยไทย': 323, 'เพื่อไทย': 6338, 'เศรษฐกิจ': 1242, 'เสรันรวมไทย': 174, 'รวมพลังประชาชน': 160, 'ช่องที่ไทย': 7, 'อนาคตไทย': 29, 'พยังเชื่อไทย': 47, 'ไทยชนิด': 47, 'พลังสังคมไทย': 10, 'สังคมประชาธิปไตยไทย': 8, 'ปวงชนไทย': 43, 'เพื่อชีวิตไทย': 7, 'ประชาธิปไตย': 11745, 'ไทยก้าวหน้า': 55, 'ไทยภักดี': 2173, 'แรงงานสร้างชาติ': 14, 'ประชากรไทย': 40, 'ครูไทยเพื่อประชาชน': 19, 'ประชาชาติ': 38, 'สร้างอนาคตไทย': 17, 'ไทยพร้อม': 43, 'ภูมิใจไทย': 16471, 'กรีน': 74, 'ไทยธรรม': 11, 'แผ่นดินธรรม': 8, 'กล้าธรรม': 115, 'พลังประชาธิปไตย': 64, 'เป็นธรรม': 42, 'ประชาชน': 66, 'ไทยสร้างไทย': 635, 'ไทยก้าวไทย': 650, 'ประชากรสาขาต': 2, 'พร้อม': 13, 'เครือข่าวชาวนาแห่งประเทศไทย': 6, 'ไทยพิทักษ์ธรรม': 3, 'ไทยรวมไทย': 6, 'เพื่อบ้านเมือง': 12, 'พลังไทยรักษาดี': 8}

Processing:  51%|█████     | 152/300 [12:52<18:24,  7.46s/doc]

party_list_10_10 {'ไลยพรัชย์ทวี': 57, 'เพื่อชาติไทย': 339, 'รวมใจไทย': 792, 'รวมไทยสร้างชาติ': 2583, 'ประชาธิปไตยไทม์': 229, 'เพื่อไทย': 13051, 'เศรษฐกิจ': 2414, 'เสร็จรวมไทย': 456, 'รวมพลังประชาชน': 270, 'ท้องฟื้ไทย': 31, 'อนาคตไทย': 46, 'พลังเพื่อไทย': 110, 'ไทยชนม': 34, 'พลังสังคมไทม์': 17, 'สังคมประชาธิปไตยไทย': 41, 'ไทยรวมพลัง': 57, 'ก้าวอิสระ': 23, 'ปวงชนไทย': 27, 'เพื่อชีวิตไทม์': 3, 'คลองไทย': 35, 'ประชาธิปไตย': 7084, 'ไทยก้าวหน้า': 105, 'ไทยภักดี': 1296, 'แรงงานสร้างชาติ': 42, 'ประชากรไทย': 65, 'ครูไทยเพื่อประชาชน': 15, 'ประชาชาติ': 60, 'สร้างอนาคตไทย': 53, 'รักชาติ': 168, 'ไทยพร้อม': 39, 'ภูมิใจไทย': 16002, 'กรีน': 107, 'ไทยธรรม': 21, 'แผ่นดินธรรม': 10, 'กล้าธรรม': 238, 'พลังประชารัฐ': 101, 'เป็นธรรม': 48, 'ประชาชน': 44894, 'ประชาไทย': 79, 'ไทยสร้างไทย': 1163, 'ไทยก้าวไทม์': 785, 'ประชาอาสาชาติ': 6, 'พร้อม': 30, 'เครือข่ายชาวนามส่งประเทศไทย': 16, 'ไทยพิทักษ์ธรรม': 4, 'ความหวังไทม์': 39, 'ไทยรวมไทย': 11, 'เพื่อบ้านเมือง': 13, 'พลังไทยรักชาติ': 28}

Processing:  51%|█████     | 153/300 [13:01<19:22,  7.91s/doc]

party_list_10_11 {'เพื่อชาติไอย': 251, 'รวมไอไทย': 167, 'รวมไอยสร้างชาติ': 2061, 'ประชาธิปไตยใหม่': 172, 'เพื่อไอย': 18901, 'ทางเลือกใหม่': 167, 'เศรษฐกิจ': 1113, 'เสรีรวมไอย': 152, 'รวมพลังประชาชน': 162, 'ห้องที่ไอย': 50, 'อนาคตไอย': 218, 'พลังเพื่อไอย': 38, 'พลังสังคมใหม่': 9, 'สังคมประชาธิปไตยไอย': 28, 'ไอรวมพลัง': 42, 'ก้าวอิสระ': 17, 'ปวดชนไอย': 42, 'วิชชั่นใหม่': 25, 'เพื่อชีวิตใหม่': 25, 'ประชาธิปไตย': 2273, 'ไอยก้าวหน้า': 22, 'ไอยภัยดี': 2272, 'แรงงานสร้างชาติ': 18, 'ประชากรไอย': 22, 'ครูไอยเพื่อประชาชน': 23, 'ประชาชาติ': 50, 'สร้างอนาคตไอย': 55, 'รักชาติ': 666, 'ไอยพร้อม': 55, 'ภูมิใจไอย': 38503, 'พลังธรรมใหม่': 38, 'กรีน': 38, 'ไอยธรรม': 2, 'แผ่นดินธรรม': 38, 'กล้าวรวม': 423, 'พลังประชาธิปู': 173, 'โอกาสใหม่': 82, 'เป็นธรรม': 53, 'ประชาชน': 44940, 'ประชาไทย': 85, 'ไอยสร้างไอย': 825, 'ไอยก้าวใหม่': 687, 'ประชาชาสาชาติ': 5, 'พร้อม': 82, 'เครือข่ายชารมามส่งประเทศไทย': 59, 'ความหรีย์ใหม่': 59, 'ไอยรวมไอย': 59, 'เพื่อบ้านเมือง': 59, 'พลังไอยรักชาติ': 59}

Processing:  51%|█████▏    | 154/300 [13:10<20:25,  8.39s/doc]

party_list_10_12 {'ไทยทรัพย์ทวี': 48, 'เพื่อชาติไทย': 215, 'มิติใหม่': 29, 'รวมใจไทย': 103, 'รวมไทยสร้างชาติ': 2247, 'พลวัต': 153, 'ประชาธิปไตยใหม่': 205, 'เพื่อไทย': 12943, 'ทางเลือกใหม่': 440, 'เศรษฐกิจ': 2000, 'เสร็จรวมไทย': 836, 'รวมพลังประชาชน': 319, 'ท้องที่ไทย': 37, 'อนาคตไทย': 214, 'พลังเพื่อไทย': 120, 'ไทยชนะ': 36, 'พลังสังคมใหม่': 7, 'สังคมประชาธิปไตยไทย': 17, 'พิวชั่น': 9, 'ไทรวมพลัง': 43, 'ก้าวอิสระ': 13, 'ปวงชนไทย': 60, 'วิชั่นใหม่': 18, 'เพื่อชีวิตใหม่': 10, 'คลองไทย': 28, 'ประชาธิปไตย': 9745, 'ไทยก้าวหน้า': 70, 'ไทยภักดี': 1587, 'แรงงานสร้างชาติ': 27, 'ประชากรไทย': 48, 'ครูไทยเพื่อประชาชน': 30, 'ประชาชาติ': 61, 'สร้างอนาคตไทย': 34, 'ไทยพร้อม': 47, 'ภูมิใจไทย': 19124, 'พลังธรรมใหม่': 48, 'กรีน': 94, 'ไทยธรรม': 17, 'แผ่นดินธรรม': 25, 'กล้าธรรม': 397, 'พลังประชารัฐ': 247, 'โอกาสใหม่': 123, 'เป็นธรรม': 81, 'ประชาชน': 52294, 'ประชาไทย': 88, 'ไทยสร้างไทย': 1140, 'ไทยก้าวใหม่': 943, 'ประชาอาสาชาติ': 6, 'พร้อม': 18, 'เครือข่ายชาวนาแห่งประเทศไทย': 10, 'ไทยพิทักษ์ธรรม': 10, 'ความหวังใหม่': 14, 'ไทยรวมไทย': 8, 'เพื่อบ้านเมือง': 11, 'พลังไทยรักชาติ': 22}

Processing:  52%|█████▏    | 155/300 [13:21<21:50,  9.04s/doc]

party_list_10_13 {'ไทยทรัพย์ทวี': 32, 'เพื่อชาติไทย': 455, 'มิติใหม่': 29, 'รวมใจไทย': 86, 'รวมใดอสร้างชาติ': 2377, 'พลวัด': 252, 'ประชาธิปไตยใหม่': 379, 'เพื่อไทย': 9014, 'เศรษฐกิจ': 1621, 'เสร็จรวมไทย': 367, 'รวมพลังประชาชน': 203, 'ท้องที่ไทย': 14, 'อนาคตไทย': 35, 'พลังเพื่อไทย': 63, 'ไทยชนะ': 29, 'พลังสังคมใหม่': 7, 'สังคมประชาธิปไตยไทย': 19, 'ทิวชัน': 6, 'ไทรวมพลัง': 27, 'ก้าวอิสระ': 15, 'ปวจชนไทย': 75, 'วิชชั่นใหม่': 26, 'เพื่อชีวิตใหม่': 7, 'คลองไทย': 20, 'ประชาธิปัตย์': 10006, 'ไทยก้าวหน้า': 68, 'ไทยเก๊กดี': 1742, 'แรงงานสร้างชาติ': 23, 'ประชากรไทย': 31, 'ครูไทยเพื่อประชาชน': 15, 'ประชาชาติ': 53, 'สร้างอนาคตไทย': 24, 'รักชาติ': 185, 'ไทยพร้อม': 161, 'ภูมิใจไทย': 17477, 'พลังธรรมใหม่': 35, 'กรีน': 63, 'ไทยธรรม': 14, 'แผ่นดินธรรม': 10, 'กล้าธรรม': 170, 'พลังประชารัฐ': 112, 'โอกาสใหม่': 96, 'เป็นธรรม': 32, 'ประชาชน': 44989, 'ประชาไทย': 128, 'ไทยสร้างไทย': 1091, 'ไทยก้าวใหม่': 782, 'ประชาอาสาชาติ': 4, 'พร้อม': 15, 'เครือข่ายชาวนาแห่งประเทศไทย': 5, 'ไทยพิทักษ์ธรรม': 5, 'ความหวังใหม่': 7, 'ไทยรวมไทย': 7, 'เพื่อบ้านเมือง': 7, 'พลังไทยรักชาติ': 19}

Processing:  52%|█████▏    | 156/300 [13:30<21:42,  9.04s/doc]

party_list_10_14 {'เพื่อชาติไทย': 574, 'มิติใหม่': 16, 'รวมใจไทย': 108, 'รวมไทยสร้างชาติ': 2087, 'พลวัต': 45, 'ประชาธิปไตยใหม่': 215, 'เพื่อไทย': 8714, 'เสร็จรวมไทย': 176, 'รวมพลังประชาชน': 447, 'ท้องที่ไทย': 82, 'อนาคตไทย': 55, 'พลังเพื่อไทย': 60, 'ไทยชนม': 18, 'พลังสังคมใหม่': 6, 'สังคมประชาธิปไตยไทย': 18, 'ไทรวมพลัง': 12, 'ก้าวอิสระ': 16, 'ปวงชนไทย': 57, 'วิชชั้นใหม่': 21, 'เพื่อชีวิตใหม่': 4, 'คลองไทย': 20, 'ประชาธิปไตย': 10762, 'ไทยก้าวหน้า': 64, 'ไทยภักดี': 1764, 'แรงงานสร้างชาติ': 20, 'ประชากรไทย': 50, 'ครูไทยเพื่อประชาชน': 22, 'ประชาชาติ': 208, 'สร้างอนาคตไทย': 26, 'รักชาติ': 147, 'ไทยพร้อม': 57, 'ภูมิใจไทย': 17646, 'พลังธรรมใหม่': 16, 'กรีน': 82, 'ไทยธรรม': 4, 'แม่เดินธรรม': 6, 'กล้าธรรม': 186, 'พลังประชาธิปไตย': 106, 'โอกาสใหม่': 48, 'เป็นธรรม': 34, 'ประชาชน': 44641, 'ประชาไทย': 37, 'ไทยสร้างไทย': 1102, 'ไทยก้าวใหม่': 725, 'พร้อม': 23, 'เครือข่ายชาวนาแห่ง': 5, 'ไทยพิทักษ์ธรรม': 1, 'ความหวังใหม่': 11, 'ไทยรวมไทย': 8, 'เพื่อบ้านเมือง': 22, 'พลังไทยรักชาติ': 7}

Processing:  52%|█████▏    | 157/300 [13:42<23:51, 10.01s/doc]

party_list_10_16 {'มิติใหม่': 52, 'รวมใจไทย': 165, 'รวมไทยสร้างชาติ': 2134, 'ประชาธิปไตยใหม่': 462, 'เพื่อไทย': 10027, 'ทางเลือกใหม่': 681, 'เศรษฐกิจ': 2220, 'รวมพลังประชาชน': 318, 'ท้องที่ไทย': 18, 'อนาคตไทย': 55, 'พลังเพื่อไทย': 18, 'ไทยชนะ': 14, 'พลังสังคมใหม่': 14, 'สังคมประชาธิปไตยไทย': 17, 'โทรวมพลัง': 18, 'ก้าวอีสระ': 18, 'ประชนไทย': 31, 'วิชชั้นใหม่': 11, 'เพื่อชีวิตใหม่': 9, 'ประชาธิปไตย': 9034, 'ไทยก้าวหน้า': 163, 'ไทยภักดี': 1185, 'แรงงานสร้างชาติ': 12, 'ประชากรไทย': 37, 'ครูไทยเพื่อประชาชน': 25, 'ประชาชาติ': 37, 'สร้างอนาคตไทย': 26, 'รักชาติ': 110, 'ไทยพร้อม': 16, 'ภูมิใจไทย': 16586, 'พลังธรรมใหม่': 14, 'กรีน': 82, 'ไทยธรรม': 18, 'แผ่นดินธรรม': 10, 'พลังประชาชน': 129, 'โอกาสใหม่': 65, 'เป็นธรรม': 34, 'ประชาชน': 44131, 'ประชาไทย': 18, 'ไทยสร้างไทย': 704, 'ไทยก้าวใหม่': 715, 'ประชาอาศรชาติ': 6, 'พร้อม': 65, 'เครือข่ายชาวนาแฟงประเทศไทย': 8, 'ความพร้อม': 18, 'ไทยรวมไทย': 8, 'เพื่อบ้านเมือง': 21, 'พลังไทยรักชาติ': 24}

Processing:  53%|█████▎    | 158/300 [13:53<24:18, 10.27s/doc]

party_list_10_17 {'ไทยทรัพย์ทวี': 141, 'เพื่อชาติไทย': 440, 'รวมใจไทย': 725, 'รวมไทยสร้างชาติ': 2475, 'ประชาธิปไตยไทย': 453, 'เพื่อไทย': 8742, 'เศรษฐกิจ': 2535, 'รวมพลังประชาชน': 375, 'ท้องที่ไทย': 26, 'อนาคตไทย': 17, 'พลังเพื่อไทย': 167, 'พลังสังคมไทย': 13, 'สังคมประชาธิปไตยไทย': 35, 'ฟิวชัน': 16, 'ไทรรมพลัง': 30, 'ก้าวอิสระ': 29, 'ปวงชนไทย': 103, 'เพื่อชีวิตไทย': 14, 'คลองไทย': 31, 'ประชาธิปไตย': 111, 'ไทยก้าวหน้า': 117, 'ไทยภักดี': 700, 'แรงงานสร้างชาติ': 72, 'ประชากรไทย': 63, 'ครูไทยเพื่อประชาชน': 36, 'ประชาชาติ': 377, 'สร้างอนาคตไทย': 65, 'รักชาติ': 78, 'ไทยพร้อม': 62, 'ภูมิใจไทย': 13309, 'กรีน': 61, 'ไทยธรรม': 37, 'แผ่นดินธรรม': 20, 'กล้าธรรม': 257, 'พลังประชาธิปไตย': 181, 'เป็นธรรม': 48, 'ประชาชน': 31155, 'ไทยสร้างไทย': 677, 'ไทยก้าวไทย': 477, 'พร้อม': 34, 'เครือข่ายชาวนาแห่งประเทศไทย': 10, 'ไทยพิทักษ์ธรรม': 11, 'ไทยรวมไทย': 11, 'เพื่อบ้านเมือง': 31, 'พลังไทยรักชาติ': 23}

Processing:  53%|█████▎    | 159/300 [14:02<23:27,  9.98s/doc]

party_list_10_18 {'เพื่อชาติไทย': 419, 'มิติใหม่': 738, 'รวมใจไทย': 337, 'รวมไทยสร้างชาติ': 2480, 'พลรัต': 229, 'ประชาธิปไตยใหม่': 365, 'เพื่อไทย': 10197, 'ทางเลือกใหม่': 760, 'เศรษฐกิจ': 2474, 'เสรีรวมไทย': 416, 'รวมพลังประชาชน': 425, 'ท้องที่ไทย': 26, 'พลังเพื่อไทย': 171, 'พลังสังคมใหม่': 19, 'สังคมประชาธิปไตยไทย': 43, 'ฟิวชัน': 29, 'ไท่รวมพลัง': 51, 'ก้าวอิสระ': 25, 'ปวงชนไทย': 47, 'วิชชั่นใหม่': 40, 'เพื่อชีวิตใหม่': 11, 'คลองไทย': 43, 'ประชาธิปไตย': 8233, 'ไทยก้าวหน้า': 88, 'ไทยภักดี': 885, 'แรงงานสร้างชาติ': 87, 'ประชากรไทย': 66, 'ครูไทยเพื่อประชาชน': 39, 'ประชาชาติ': 225, 'สร้างอนาคตไทย': 47, 'รักชาติ': 136, 'ไทยพร้อม': 53, 'ภูมิใจไทย': 12842, 'พลังธรรมใหม่': 63, 'กรีน': 56, 'ไทยธรรม': 26, 'แผ่นดินธรรม': 18, 'กล้าธรรม': 240, 'พลังประชาธิปไตย': 159, 'โอกาสใหม่': 80, 'เป็นธรรม': 53, 'ประชาชน': 36742, 'ประชาไทย': 108, 'ไทยสร้างไทย': 746, 'ไทยก้าวใหม่': 803, 'ประชาอาสาชาติ': 8, 'พร้อม': 54, 'เครือข่ายชาวบ้านต่อประเทศไทย': 7, 'ไทยพิทักษ์ธรรม': 5, 'ความทวีปใหม่': 22, 'ไทยรวมไทย': 7, 'เพื่อบ้านเมือง': 15, 'พลังไทยรักชาติ': 26}

Processing:  53%|█████▎    | 160/300 [14:11<22:20,  9.58s/doc]

party_list_10_19 {'ไทยพร้อมทวี': 260, 'เพื่อชาติไทย': 247, 'มิติใหม่': 61, 'รวมใจไทย': 629, 'รวมไทยสร้างชาติ': 1412, 'พลวัต': 138, 'ประชาธิปไตยใหม่': 221, 'เพื่อไทย': 9349, 'ทางเลือกใหม่': 467, 'เศรษฐกิจ': 1345, 'เสร็จรวมไทย': 359, 'พรรครวมพลังประชาชน': 244, 'ท้องที่ไทย': 16, 'อนาคตไทย': 32, 'พลังเพื่อไทย': 36, 'ไทยชนะ': 26, 'พลังสังคมใหม่': 8, 'สังคมประชาธิปไตย': 67, 'ฟิวชั่น': 18, 'ใครบมพลัง': 11, 'ก้าวอิสระ': 10, 'ปวงชนไทย': 29, 'วิชชั่นใหม่': 32, 'เพื่อชีวิตใหม่': 9, 'คลองไทย': 37, 'ประชาธิปัตย์': 10147, 'ไทยก้าวหน้า': 62, 'ไทยภักดี': 1537, 'แรงงานสร้างชาติ': 35, 'ประชากรไทย': 52, 'ครูไทยเพื่อประชาชน': 18, 'พรรคประชาชาติ': 156, 'สร้างอนาคตไทย': 19, 'รักชาติ': 152, 'ไทยพร้อม': 53, 'ภูมิใจไทย': 18317, 'พลังธรรมใหม่': 61, 'กรีน': 38, 'ไทยธรรม': 13, 'แผ่นดินธรรม': 7, 'กล้าธรรม': 193, 'พลังประชารัฐ': 89, 'โอกาสใหม่': 80, 'เป็นธรรม': 42, 'ประชาชน': 44830, 'ประชาไทย': 70, 'ไทยสร้างไทย': 987, 'ไทยก้าวใหม่': 821, 'ประชาอาสาชาติ': 8, 'พร้อม': 62, 'เครือข่ายชาวนาแห่งประเทศไทย': 9, 'ไทยพิทักษ์ธรรม': 6, 'ความหวังใหม่': 11, 'ไทยรวมไทย': 3, 'เพื่อป่านเมือง': 19, 'พลังไทยรักชาติ': 13}

Processing:  54%|█████▎    | 161/300 [14:20<21:58,  9.48s/doc]

party_list_10_2 {'ไดอทรัพย์ทวี': 39, 'เพื่อขาติไทย': 280, 'มิติใหม่': 129, 'รวมใจไทย': 215, 'รวมไทยสร้างขาตี': 1819, 'พลวัต': 116, 'ประชาธิปไตยใหม่': 211, 'เพื่อไทย': 6226, 'เศรษฐกิจ': 1578, 'เสรีรวมไทย': 388, 'รวมพลังประชาชน': 189, 'ท้องที่ไทย': 16, 'อนาคตไทย': 37, 'พลังเพื่อไทย': 51, 'ไทยชนล': 33, 'พลังสังคมใหม่': 9, 'สังคมประชาธิปไตยไทย': 46, 'ไตรมพลัง': 32, 'ก้าวอิสระ': 17, 'ปวงชนไทย': 76, 'วิชชั้นใหม่': 27, 'เพื่อชีวิตใหม่': 6, 'ประชาธิปัตย์': 11048, 'ไทยก้าวหน้า': 47, 'ไทยภักดี': 2050, 'แรงงานสร้างขาตี': 17, 'ประชากรไทย': 34, 'ครูไทยเพื่อประชาชน': 23, 'ประชาชาติ': 65, 'สร้างอนาคตไทย': 31, 'รักชาติ': 146, 'ไทยพร้อม': 32, 'ภูมิใจไทย': 18021, 'พลังธรรมใหม่': 37, 'กรีน': 108, 'ไทยธรรม': 4, 'แผ่นดินธรรม': 12, 'กล้าธรรม': 270, 'พลังประชาธิปไตย': 99, 'โอกาสใหม่': 114, 'เป็นธรรม': 154, 'ประชาชน': 40383, 'ประชาไทย': 76, 'ไทยสร้างไทย': 707, 'ไทยก้าวใหม่': 637, 'ประชาชาตาชาติ': 3, 'พร้อม': 17, 'เครือข่ายชาวนามห์อประเพศไทย': 11, 'ไทยพิทักษ์ธรรม': 3, 'ความหวังใหม่': 12, 'ไทยรวมไทย': 7, 'เพื่อบ้านเมือง': 21, 'พลังไทยรักชาติ': 17}

Processing:  54%|█████▍    | 162/300 [14:30<22:23,  9.74s/doc]

party_list_10_20 {'ไทยทรัพย์ทวี': 72, 'เพื่อชาติไทย': 503, 'มิติใหม่': 44, 'รวมใจไทย': 219, 'รวมไทยสร้างชาติ': 1851, 'พลวัต': 114, 'ประชาธิปไตยใหม่': 262, 'เพื่อไทย': 12703, 'ทางเลือกใหม่': 372, 'เศรษฐกิจ': 2741, 'เสรีรวมไทย': 415, 'รวมพลังประชาชน': 411, 'ท่องที่ไทย': 49, 'อนาคตไทย': 41, 'พลังเพื่อไทย': 138, 'ไทยชนะ': 58, 'พลังสังคมใหม่': 12, 'สังคมประชาธิปไตยไทย': 50, 'ไทรวมพลัง': 43, 'การยิสระ': 24, 'ปวงชนไทย': 50, 'วิชชนใหม่': 24, 'เพื่อชีวิตใหม่': 12, 'คลองไทย': 24, 'ประชาธิปไตย': 6062, 'ไทยการหน้า': 103, 'ไทยกักดี': 851, 'แรงงานสร้างชาติ': 57, 'ประชากรไทย': 60, 'ครูไทยเพื่อประชาชน': 34, 'ประชาชาติ': 86, 'สร้างอนาคตไทย': 36, 'รักชาติ': 34, 'ไทยพร้อม': 135, 'ภูมิใจไทย': 12402, 'พลังธรรมใหม่': 31, 'กรีน': 69, 'ไทยธรรม': 32, 'แผนดินธรรม': 17, 'กล่าวธรรม': 135, 'พลังประชารัฐ': 123, 'โอกาสใหม่': 70, 'เป็นธรรม': 283, 'ประชาชน': 39717, 'ประชาไทย': 155, 'ไทยสร้างไทย': 711, 'ไทยการใหม่': 884, 'ประชาอ่าอ่าชาติ': 5, 'พร้อม': 64, 'เครือข่ายชาวนาแห่งประเทศไทย': 7, 'ไทยพิทักษ์ธรรม': 9, 'ความหวังใหม่': 19, 'ไทยรวมไทย': 17, 'เพื่อบ้านเมือง': 9, 'พลังไทยรักชาติ': 26}

Processing:  54%|█████▍    | 163/300 [14:44<24:57, 10.93s/doc]

party_list_10_21 {'ไทยทรัพย์ทวี': 63, 'เพื่อชาติไทย': 215, 'มิติใหม่': 84, 'รวมใจไทย': 165, 'รวมไทยสร้างชาติ': 197, 'พลวัต': 180, 'ประชาธิปไตยใหม่': 566, 'เพื่อไทย': 7078, 'ทางเลือกใหม่': 409, 'เศรษฐกิจ': 1860, 'เสรีรวมไทย': 408, 'รวมพลังประชาชน': 320, 'ท้องที่ไทย': 337, 'อนาคตไทย': 96, 'พลังเพื่อไทย': 92, 'ไทยชนะ': 37, 'พลังสังคมใหม่': 12, 'สังคมประชาธิปไตยไทย': 34, 'ฟิวชัน': 19, 'ไทรวมพลัง': 19, 'ก๊าวอิสระ': 20, 'ปวงชนไทย': 69, 'วิชชั่นใหม่': 65, 'เพื่อชีวิตใหม่': 9, 'คลองไทย': 31, 'ประชาธิปไตย': 1197, 'ไทยก้าวหน้า': 101, 'ไทยภักดี': 1281, 'แรงงานสร้างชาติ': 39, 'ประชากรไทย': 30, 'ครูไทยเพื่อประชาชน': 22, 'ประชาชาติ': 233, 'สร้างอนาคตไทย': 46, 'รักชาติ': 166, 'ไทยพร้อม': 42, 'ภูมิใจไทย': 15843, 'พลังธรรมใหม่': 42, 'กรีน': 62, 'ไทยธรรม': 12, 'แผ่นดินธรรม': 12, 'กล้าธรรม': 129, 'พลังประชารัฐ': 136, 'โยกาลใหม่': 66, 'เป็นธรรม': 54, 'ประชาชน': 56471, 'ประชาไทย': 78, 'ไทยสร้างไทย': 717, 'ไทยก้าวใหม่': 801, 'ประชาอาสาชาติ': 7, 'พร้อม': 34, 'เครือข่ายชาวนาแห่งประเทศไทย': 8, 'ไทยพิทักษ์ธรรม': 4, 'ไทยรวมไทย': 10, 'เพื่อบ้านเมือง': 20, 'พลังไทยรักชาติ': 22}

Processing:  55%|█████▍    | 164/300 [14:55<24:43, 10.91s/doc]

party_list_10_22 {'ไทยพร้อมทวี': 114, 'เพื่อชาติไทย': 122, 'รวมใจไทย': 112, 'รวมไทยสร้างชาติ': 2123, 'พลรัต': 223, 'ประชาธิปไตยไทม์': 462, 'เพื่อไทย': 6522, 'ทางเลือกไทม์': 160, 'เศรษฐกิจ': 1714, 'เสร็จรถไทย': 415, 'รวมพลังประชาชน': 221, 'ท้องที่ไทย': 14, 'อนาคตไทย': 54, 'พลังเพื่อไทย': 54, 'ไทยชนธ': 57, 'พลังสังคมไทม์': 3, 'สังคมประชาธิปไตยไทย': 15, 'ฟิวชัน': 10, 'ไทรรมพลัง': 24, 'ก้าวอิสระ': 14, 'ปวงชนไทย': 167, 'เพื่อชีวิตไทย': 8, 'คลองไทย': 11, 'ประชาธิปัตย์': 13243, 'ไทยก้าวหน้า': 12, 'ไทยภักดี': 1564, 'แรงงานสร้างชาติ': 17, 'ประชากรไทย': 18, 'ครูไทยเพื่อประชาชน': 12, 'ประชาชาติ': 160, 'สร้างธนาคตไทย': 24, 'รักชาติ': 168, 'ไทยพร้อม': 60, 'ภูมิใจไทย': 17746, 'พลังธรรมไทม์': 48, 'กรีน': 56, 'ไทยธรรม': 14, 'แผ่นดินธรรม': 11, 'กล้าอรรม': 156, 'พลังประชารัฐ': 268, 'เป็นธรรม': 47, 'ประชาชน': 46846, 'ประชาไทย': 84, 'ไทยสร้างไทย': 754, 'ไทยก้าวไทม์': 754, 'ประชาอาสาชาติ': 3, 'พร้อม': 14, 'เครือข่ายชาวนาแห่งประเทศไทย': 6, 'ไทยพิทักษ์ธรรม': 6, 'ความหวังไทม์': 7, 'ไทยรวมไทย': 7, 'เพื่อบ้านเมือง': 11, 'พลังไทยรักชาติ': 15}

Processing:  55%|█████▌    | 165/300 [15:06<24:32, 10.91s/doc]

party_list_10_23 {'ไทยทรัพย์ทวี': 305, 'เพื่อชาติไทย': 160, 'มิติใหม่': 67, 'รวมไอไทย': 141, 'รวมไทยสร้างชาติ': 2220, 'ประชาธิปไตยใหม่': 211, 'เพื่อไทย': 7888, 'เศรษฐกิจ': 1442, 'รวมหลังประชาชน': 605, 'ท้องฟีไทย': 35, 'อนาคตไทย': 341, 'หลังเพื่อไทย': 38, 'ไทยชนอ': 38, 'หลังสังคมใหม่': 16, 'สังคมประชาธิปไตยไทย': 18, 'ฟิวชัน': 12, 'ก้าวอิสระ': 9, 'ปวงชนไทย': 36, 'วิชชั่นใหม่': 21, 'เพื่อชีวิตใหม่': 7, 'ตลอดไทย': 26, 'ประชาธิปไตย': 10166, 'ไทยก้าวหน้า': 69, 'ไทยภักดี': 1879, 'แรงงานสร้างชาติ': 46, 'ประชากรไทย': 46, 'ครูไทยเพื่อประชาชน': 17, 'ประชาชาติ': 44, 'สร้างอนาคตไทย': 26, 'รักชาติ': 166, 'ไทยพร้อม': 44, 'ภูมิใจไทย': 14146, 'หลังธรรมใหม่': 44, 'กรีน': 52, 'ไทยธรรม': 18, 'แผ่นดินธรรม': 9, 'กล้าธรรม': 101, 'หลังประชาธิปไตย': 142, 'โอกาสใหม่': 59, 'เป็นธรรม': 49, 'ประชาชน': 8788, 'ประชาไทย': 83, 'ไทยสร้างไทย': 730, 'ไทยก้าวใหม่': 759, 'ประชาอาสาชาติ': 6, 'พร้อม': 30, 'เครือข่ายชาวบางแห่งประเภทไทย': 8, 'ไทยพิทักษ์ธรรม': 6, 'ความพร้อม': 35, 'ไทยรวมไทย': 10, 'เพื่อบ้านเมือง': 9, 'หลังไทยรักชาติ': 12}

Processing:  55%|█████▌    | 166/300 [15:17<24:29, 10.97s/doc]

party_list_10_24 {'ประชาชาติ': 1, 'ประชาชน': 1}

Processing:  56%|█████▌    | 167/300 [15:27<23:56, 10.80s/doc]

party_list_10_25 {'ไทยทรัพย์ทวี': 52, 'เพื่อชาติไทย': 311, 'มิติใหม่': 420, 'รวมใจไทย': 147, 'รวมไทยสร้างชาติ': 2013, 'พลวัต': 246, 'ประชาธิปไตยใหม่': 269, 'เพื่อไทย': 9264, 'ทางเลือกใหม่': 364, 'เศรษฐกิจ': 1780, 'เสรีรวมไทย': 600, 'รวมพลังประชาชน': 308, 'ท้องที่ไทย': 17, 'อนาคตไทย': 85, 'พลังเพื่อไทย': 84, 'ไทยชนะ': 48, 'พลังสังคมใหม่': 9, 'สังคมประชาธิปไตยไทย': 19, 'ฟิวชัน': 12, 'ไทรวมพลัง': 35, 'ก้าวอิสระ': 10, 'ปวงชนไทย': 36, 'วิชชั่นใหม่': 21, 'เพื่อชีวิตใหม่': 15, 'คลองไทย': 35, 'ประชาธิปไตย': 8749, 'ไทยก้าวหน้า': 60, 'ไทยภักดี': 1226, 'แรงงานสร้างชาติ': 30, 'ประชากรไทย': 58, 'ครูไทยเพื่อประชาชน': 20, 'ประชาชาติ': 192, 'สร้างอนาคตไทย': 37, 'รักชาติ': 121, 'ไทยพร้อม': 19, 'ภูมิใจไทย': 15076, 'พลังธรรมใหม่': 43, 'กรีน': 56, 'ไทยธรรม': 14, 'แผ่นดินธรรม': 12, 'กล้าธรรม': 129, 'พลังประชารัฐ': 81, 'โอกาสใหม่': 56, 'เป็นธรรม': 28, 'ประชาชน': 51485, 'ประชาไทย': 147, 'ไทยสร้างไทย': 660, 'ไทยก้าวใหม่': 591, 'ประชาชนสาขาต': 5, 'พร้อม': 18, 'เครือข่ายชาวนาแห่งประเทศไทย': 11, 'ไทยพิทักษ์ธรรม': 3, 'ความหวังใหม่': 16, 'ไทยรวมไทย': 6, 'เพื่อบ้านเมือง': 21, 'พลังไทยรักชาติ': 35}

Processing:  56%|█████▌    | 168/300 [15:37<22:45, 10.34s/doc]

party_list_10_26 {'ไทยทรัพย์ทวี': 202, 'เพื่อชาติไทย': 290, 'มิติใหม่': 111, 'รวมใจไทย': 161, 'รวมไทยสร้างชาติ': 2033, 'พลวัต': 547, 'ประชาธิปไตยใหม่': 291, 'เพื่อไทย': 10607, 'ทางเลือกใหม่': 467, 'เศรษฐกิจ': 1862, 'เสร็จรวมไทย': 520, 'รวมพลังประชาชน': 297, 'ท้องที่ไทย': 36, 'อนาคตไทย': 40, 'พลังเพื่อไทย': 93, 'ไทยชนะ': 56, 'พลังสังคมใหม่': 7, 'สังคมประชาธิปไตยไทย': 22, 'ไทรวมพลัง': 30, 'ก้าวอิสระ': 16, 'ปวงชนไทย': 56, 'วิชชั่นใหม่': 24, 'เพื่อชีวิตใหม่': 10, 'ประชาธิปัตย์': 8548, 'ไทยก้าวหน้า': 105, 'ไทยเก้าดี': 1403, 'แรงงานสร้างชาติ': 31, 'ประชากรไทย': 51, 'ครูไทยเพื่อประชาชน': 28, 'ประชาชาติ': 60, 'สร้างอนาคตไทย': 29, 'รักชาติ': 104, 'ไทยพร้อม': 76, 'ภูมิใจไทย': 15036, 'พลังธรรมใหม่': 53, 'กรีน': 54, 'ไทยธรรม': 8, 'แผ่นดินธรรม': 21, 'กล้าธรรม': 164, 'พลังประชารัฐ': 80, 'โอกาสใหม่': 49, 'เป็นธรรม': 60, 'ประชาชน': 46203, 'ประชาไทย': 287, 'ไทยสร้างไทย': 1313, 'ไทยก้าวใหม่': 647, 'ประชาอาสาชาติ': 6, 'พร้อม': 25, 'เครือข่ายชาวมาแห่งประเทศไทย': 6, 'ไทยพิทักษ์ธรรม': 14, 'ความหวังใหม่': 10, 'ไทยรวมไทย': 13, 'เพื่อป่านเมือง': 12, 'พลังไทยรักชาติ': 17}

Processing:  56%|█████▋    | 169/300 [15:50<24:11, 11.08s/doc]

party_list_10_27 {'เพื่อชาติไทย': 454, 'รวมใจไทย': 622, 'รวมไทยสร้างชาติ': 2031, 'ประชาธิปไตยไทม์': 284, 'เพื่อไทย': 12715, 'ทางเลือกไทม์': 423, 'เศรษฐกิจ': 2266, 'เสร็จรวมไทย': 620, 'รวมพยักประชาชน': 333, 'ห้องที่ไทย': 72, 'อนาคตไทย': 42, 'พลังเพื่อไทย': 36, 'ไทยชนะ': 32, 'สังคมประชาธิปไตยไทย': 24, 'ไทรวมพลัง': 72, 'ก้าวอิสระ': 19, 'วิชชั่นไทม์': 21, 'เพื่อชีวิตไทม์': 13, 'คอยอไทย': 38, 'ประชาธิปไตย': 8223, 'ไทยก้าวหน้า': 74, 'ไทยภักดี': 1273, 'แรงงานสร้างชาติ': 42, 'ประชากรไทย': 53, 'ครูไทยเพื่อประชาชน': 16, 'ประชาชาติ': 54, 'สร้างอนาคตไทย': 24, 'รักชาติ': 117, 'ไทยพร้อม': 47, 'ภูมิใจไทย': 13474, 'พลังธรรมไทม์': 80, 'กรีน': 66, 'ไทยธรรม': 10, 'แต่เดินธรรม': 13, 'กล้าธรรม': 105, 'พยักประชารัฐ': 30, 'เป็นธรรม': 46, 'ประชาชน': 46186, 'ประชาไทย': 184, 'ไทยสร้างไทย': 344, 'ไทยก้าวไทม์': 615, 'ประชาอาสาชาติ': 5, 'พร้อม': 15, 'เครือข่ายชายงานต่อประเทศไทย': 4, 'ไทยพิพิทษ์ธรรม': 4, 'ความหวังไทม์': 14, 'ไทยรวมไทย': 4, 'เพื่อบ้านเมือง': 20, 'พลังไทยรักชาติ': 20}

Processing:  57%|█████▋    | 170/300 [16:01<24:08, 11.14s/doc]

party_list_10_28 {'ไทยจรดิษย์ทวี': 105, 'เพื่อชาติไทย': 842, 'มิติใหม่': 119, 'รวมใจไทย': 191, 'รวมไทยสร้างชาติ': 2115, 'พลวัต': 123, 'ประชาธิปไตยใหม่': 241, 'เพื่อไทย': 9850, 'ทางเลือกใหม่': 495, 'เศรษฐกิจ': 2101, 'เสร็จรถไทย': 574, 'รวมพลังประชาชน': 304, 'ท้องที่ไทย': 12, 'อนาคตไทย': 31, 'พลังเพื่อไทย': 91, 'พลังสังคมใหม่': 6, 'สังคมประชาธิปไตยไทย': 23, 'ฟิวชัน': 21, 'โทรวมพลัง': 27, 'ก้าวอิสระ': 24, 'ปวงชนไทย': 36, 'วิชชั่นใหม่': 14, 'เพื่อชีวิตใหม่': 10, 'คลองไทย': 28, 'ประชาธิปไตย': 8185, 'ไทยก้าวหน้า': 106, 'ไทยภักดี': 1399, 'แรงงานสร้างชาติ': 30, 'ประชากรไทย': 113, 'ครูไทยเพื่อประชาชน': 31, 'ประชาชาติ': 57, 'สร้างอนาคตไทย': 35, 'รักชาติ': 146, 'ไทยพร้อม': 68, 'ภูมิใจไทย': 1568, 'พลังธรรมใหม่': 61, 'กรีน': 132, 'ไทยธรรม': 9, 'แผ่นดินธรรม': 12, 'กล้าธรรม': 162, 'พลังประเสริฐ': 114, 'โอกาสใหม่': 71, 'เป็นธรรม': 62, 'ประชาชน': 58581, 'ประชาไทย': 89, 'ไทยสร้างไทย': 893, 'ไทยก้าวใหม่': 801, 'ประชาอาสาชาติ': 5, 'พร้อม': 19, 'เครือข่ายชาวนาแห่งประเทศไทย': 10, 'ไทยพิทักษ์ธรรม': 10, 'ความหวังใหม่': 12, 'ไทยรวมไทย': 5, 'เพื่อบ้านเมือง': 20, 'พลังไทยรักชาติ': 14}

Processing:  57%|█████▋    | 171/300 [16:12<23:42, 11.03s/doc]

party_list_10_29 {'พรรคไทยทรัพย์ทวี': 59, 'พรรคเพื่อชาติไทย': 336, 'พรรคใหม่': 28, 'พรรคมิติใหม่': 557, 'พรรครวมใจไทย': 259, 'พรรครวมไทยสร้างชาติ': 2447, 'พรรคพลวัต': 206, 'พรรคประชาธิปไตยใหม่': 44, 'พรรคเพื่อไทย': 11768, 'พรรคทางเลือกใหม่': 42, 'พรรคเศรษฐกิจ': 237, 'พรรคเสรีรวมไทย': 529, 'พรรครวมพลังประชาชน': 318, 'พรรคท้องที่ไทย': 23, 'พรรคอนาคตไทย': 52, 'พรรคพลังเพื่อไทย': 83, 'พรรคไทยชนะ': 75, 'พรรคพลังสังคมใหม่': 22, 'พรรคสังคมประชาธิปไตย': 32, 'พรรคไทรวมพลัง': 42, 'พรรคก้าวอิสระ': 31, 'พรรคปวงชนไทย': 27, 'พรรควิชชั่นใหม่': 14, 'พรรคเพื่อชีวิตใหม่': 12, 'พรรคคลองไทย': 29, 'พรรคประชาธิปไตย': 9128, 'พรรคไทยก้าวหน้า': 76, 'พรรคไทยภักดี': 159, 'พรรคแรงงานสร้างชาติ': 28, 'พรรคประชากรไทย': 64, 'พรรคครูไทยเพื่อประชาชน': 35, 'พรรคประชาชาติ': 75, 'พรรคสร้างอนาคตไทย': 44, 'พรรครักชาติ': 201, 'พรรคไทยพร้อม': 56, 'พรรคภูมิใจไทย': 1670, 'พรรคพลังธรรมใหม่': 65, 'พรรคไทยธรรม': 20, 'พรรคแผ่นดินธรรม': 10, 'พรรคกล้าธรรม': 129, 'พรรคพลังประชารัฐ': 126, 'พรรคโอกาสใหม่': 62, 'พรรคเป็นธรรม': 39, 'พรรคประชาชน': 47605, 'พรรคประชาไทย': 70, 'พรรคไทยสร้างไทย': 1116, 'พรรคไทยก้าวใหม่': 666, 'พรรคประชาอาสาชาติ': 6, 'พรรคพร้อม': 23, 'พรรคเครือข่ายชาวนาแห่งประเทศไทย': 5, 'พรรคไทยพิทักษ์ธรรม': 10, 'พรรคความหวังใหม่': 12, 'พรรคไทยรวมไทย': 9, 'พรรคเพื่อบ้านเมือง': 14, 'พรรคพลังไทยรักชาติ': 20}

Processing:  57%|█████▋    | 172/300 [16:24<24:08, 11.31s/doc]

party_list_10_3 {'ไทยทรัพย์ทวี': 31, 'เพื่อชาติไทย': 376, 'มิติใหม่': 48, 'รวมใจไทย': 112, 'รวมไทยสร้างชาติ': 1613, 'พลวัต': 101, 'ประชาธิปไตยใหม่': 274, 'เพื่อไทย': 5700, 'ทางเลือกใหม่': 286, 'เศรษฐกิจ': 1304, 'เสรีรวมไทย': 524, 'รวมพลังประชาชน': 200, 'ท้องที่ไทย': 10, 'อนาคตไทย': 34, 'พลังเพื่อไทย': 38, 'ไทยชนะ': 33, 'พลังสังคมใหม่': 6, 'สังคมประชาธิปไตยไทย': 19, 'พิวชัน': 15, 'ไทรวมพลัง': 23, 'ก้าวอิสระ': 31, 'ปวงชนไทย': 39, 'วิชชั่นใหม่': 16, 'เพื่อชีวิตใหม่': 10, 'คลองไทย': 33, 'ประชาธิปไตย': 12667, 'ไทยก้าวหน้า': 60, 'ไทยก้าดี': 1669, 'แรงงานสร้างชาติ': 13, 'ประชากรไทย': 35, 'ครูไทยเพื่อประชาชน': 21, 'ประชาชาติ': 68, 'สร้างอนาคตไทย': 20, 'รักชาติ': 118, 'ไทยพร้อม': 42, 'ภูมิใจไทย': 15604, 'พลังธรรมใหม่': 39, 'กรีน': 64, 'ไทยธรรม': 7, 'แผ่นดินธรรม': 10, 'กล้าธรรม': 153, 'พลังประชารัฐ': 83, 'โอกาสใหม่': 44, 'เป็นธรรม': 44, 'ประชาชน': 35819, 'ประชาไทย': 89, 'ไทยสร้างไทย': 583, 'ไทยก้าวใหม่': 618, 'ประชาอาสาชาติ': 1, 'พร้อม': 24, 'เครือข่ายชาวนาแห่งประเทศไทย': 7, 'ไทยพิทักษ์ธรรม': 10, 'ความหวังใหม่': 6, 'ไทยรวมไทย': 8, 'เพื่อบ้านเมือง': 14, 'พลังไทยรักชาติ': 10}

Processing:  58%|█████▊    | 173/300 [16:36<24:47, 11.72s/doc]

party_list_10_30 {'พรรคเพื่อขาติไทย': 276, 'พรรคใหม่': 73, 'พรรครวมใจไทย': 165, 'พรรครวมไทยสร้างชาติ': 2242, 'พรรคประชาธิปไตยใหม่': 265, 'พรรคเพื่อไทย': 11023, 'พรรคทานเลือกใหม่': 888, 'พรรคเศรษฐกิจ': 1980, 'พรรคเสรีรวมไทย': 742, 'พรรครวมหลังประชาชน': 319, 'พรรคอนาคตไทย': 278, 'พรรคหลังเพื่อไทย': 126, 'พรรคไทยชนะ': 92, 'พรรคหลังสังคมใหม่': 36, 'พรรคสังคมประชาธิปไตยไทย': 23, 'พรรคฟิวชั่น': 53, 'พรรคไทรวมหลัง': 45, 'พรรคก้าวอิสระ': 17, 'พรรคเพื่อชีวิตใหม่': 6, 'พรรคคลองไทย': 31, 'พรรคประชาธิปัตย์': 8679, 'พรรคไทยก้าวหน้า': 64, 'พรรคไทยภักดี': 1453, 'พรรคแรงงานสร้างชาติ': 33, 'พรรคประชากรไทย': 138, 'พรรคครูไทยเพื่อประชาชน': 18, 'พรรคประชาชาติ': 30, 'พรรคสร้างอนาคตไทย': 29, 'พรรครักชาติ': 160, 'พรรคไทยพร้อม': 46, 'พรรคภูมิใจไทย': 15715, 'พรรคหลังธรรมใหม่': 55, 'พรรคไทยธรรม': 11, 'พรรคแผ่นดินธรรม': 26, 'พรรคกล้าอรรม': 107, 'พรรคโอกาสใหม่': 50, 'พรรคเป็นธรรม': 91, 'พรรคประชาชน': 46986, 'พรรคไทยสร้างไทย': 983, 'พรรคไทยก้าวใหม่': 646, 'พรรคประชาอาสาชาติ': 1, 'พรรคพร้อม': 31, 'พรรคไทยพิทักษ์ธรรม': 5, 'พรรคความหวังใหม่': 25, 'พรรคไทยรวมไทย': 16, 'พรรคเพื่อบ้านเมือง': 14, 'พรรคหลังไทยรักชาติ': 21}

Processing:  58%|█████▊    | 174/300 [16:48<24:21, 11.60s/doc]

party_list_10_31 {}

Processing:  58%|█████▊    | 175/300 [16:58<23:45, 11.41s/doc]

party_list_10_32 {'พรรคเพื่อชาติไทย': 784, 'พรรคใหม่': 81, 'พรรครวมใจไทย': 151, 'พรรครวมไทยสร้างชาติ': 6078, 'พรรคประชาธิปไตยใหม่': 266, 'พรรคเพื่อไทย': 8901, 'พรรคทางเลือกใหม่': 167, 'พรรคเศรษฐกิจ': 1915, 'พรรคเสรีรวมไทย': 806, 'พรรครวมพลังประชาชน': 287, 'พรรคอนาคตไทย': 231, 'พรรคพลังเพื่อไทย': 87, 'พรรคไทยชนะ': 47, 'พรรคพลังสังคมใหม่': 12, 'พรรคสังคมประชาธิปไตยไทย': 45, 'พรรคฟิวชั่น': 11, 'พรรคโทรวมพลัง': 38, 'พรรคก้าวอิสระ': 22, 'พรรคปวเชนไทย': 39, 'พรรควิชชั่นใหม่': 30, 'พรรคเพื่อชีวิตใหม่': 33, 'พรรคประชาธิปัตย์': 30053, 'พรรคไทยก้าวหน้า': 70, 'พรรคแรงงานสร้างชาติ': 27, 'พรรคสนุ้ไทยเพื่อประชาชน': 21, 'พรรคสร้างอนาคตไทย': 28, 'พรรครักชาติ': 351, 'พรรคไทยพร้อม': 44, 'พรรคภูมิใจไทย': 26304, 'พรรคพลังธรรมใหม่': 50, 'พรรคไทยธรรม': 24, 'พรรคแผ่นดินธรรม': 9, 'พรรคพลังประชารัฐ': 121, 'พรรคโอกาสใหม่': 66, 'พรรคเป็นธรรม': 55, 'พรรคประชาชน': 51492, 'พรรคประชาไทย': 76, 'พรรคไทยสร้างไทย': 877, 'พรรคไทยก้าวใหม่': 638, 'พรรคพร้อม': 26, 'พรรคเครือข่ายชาวนาแห่งประเทศไทย': 8, 'พรรคไทยพิทักษ์ธรรม': 5, 'พรรคพลังไทยรักชาติ': 17}

Processing:  59%|█████▊    | 176/300 [17:11<24:09, 11.69s/doc]

party_list_10_33 {'พรรคเพื่อชาติไทย': 2017, 'พรรคใหม่': 615, 'พรรคอิติใหม่': 82, 'พรรครวมไทยสร้างชาติ': 25880, 'พรรคพลวัต': 162, 'พรรคประชาธิปไตยใหม่': 6600, 'พรรคเพื่อไทย': 8982, 'พรรคทางเมืองใหม่': 4811, 'พรรคเศรษฐกิจ': 2271, 'พรรคเสรีรวมไทย': 7160, 'พรรครวมพลังประชาชน': 1721, 'พรรคท้องที่ไทย': 26, 'พรรคพลังเพื่อไทย': 66, 'พรรคพลังสังคมใหม่': 7, 'พรรคสังคมประชาธิปไตยไทย': 28, 'พรรคฟิวชั่น': 111, 'พรรคไทรวมพลัง': 88, 'พรรคก้าวอิสระ': 21, 'พรรคปวงชนไทย': 16, 'พรรคริชชันใหม่': 71, 'พรรคเพื่อชีวิตใหม่': 8, 'พรรคคลองไทย': 28, 'พรรคประชาธิปัตย์': 12080, 'พรรคไทยก้าวหน้า': 1011, 'พรรคไทยภักดี': 2025, 'พรรคแรงงานสร้างชาติ': 16, 'พรรคประชากรไทย': 60, 'พรรคครูไทยเพื่อประชาชน': 27, 'พรรคประชาชาติ': 100, 'พรรคสร้างธนาครไทย': 34, 'พรรครักชาติ': 168, 'พรรคไทยพร้อม': 196, 'พรรคภูมิใจไทย': 18582, 'พรรคพลังธรรมใหม่': 47, 'พรรคไทยธรรม': 28, 'พรรคแผ่นดินธรรม': 18, 'พรรคกล้าธรรม': 194, 'พรรคพลังประชาธิฐ': 84, 'พรรคโอกาสใหม่': 82, 'พรรคเป็นธรรม': 417, 'พรรคประชาชน': 44987, 'พรรคประชาไทย': 102, 'พรรคไทยสร้างไทย': 904, 'พรรคไทยก้าวใหม่': 1101, 'พรรคประชาสาสาชาติ': 6, 'พรรคพร้อม': 30, 'พรรคเครือข่ายชาวยาและประเทศไทย': 10, 'พรรคไทยพิทักษ์ธรรม': 10, 'พรรคความหวังใหม่': 7, 'พรรคไทยรวมไทย': 11, 'พรรคเพื่อบ้านเมือง': 21, 'พรรคพลังไทยรักชาติ': 20}

Processing:  59%|█████▉    | 177/300 [17:22<23:54, 11.66s/doc]

party_list_10_4 {'ไทยทรัพย์ทวี': 353, 'เพื่อชาติไทย': 306, 'มิติใหม่': 88, 'รวมใจไทย': 101, 'รวมไทยสร้างชาติ': 1674, 'พลวัต': 34, 'ประชาธิปไตยใหม่': 268, 'เพื่อไทย': 549, 'ทางเลือกใหม่': 298, 'เศรษฐกิจ': 139, 'รวมพลังประชาชน': 186, 'ท้องที่ไทย': 12, 'อนาคตไทย': 48, 'พลังเพื่อไทย': 44, 'ไทยชนะ': 39, 'พลังสังคมใหม่': 4, 'สังคมประชาธิปไตยไทย': 12, 'พิวชัน': 13, 'โทรมพลัง': 35, 'ก้าวอิสระ': 6, 'ปวงชนไทย': 50, 'วิชชั่นใหม่': 52, 'เพื่อชีวิตใหม่': 12, 'คลองไทย': 40, 'ประชาธิปัตย์': 11540, 'ไทยก้าวหน้า': 53, 'ไทยภักดี': 1480, 'แรงงานสร้างชาติ': 27, 'ประชากรไทย': 39, 'ครูไทยเพื่อประชาชน': 16, 'ประชาชาติ': 72, 'สร้างอนาคตไทย': 20, 'รักชาติ': 107, 'ไทยพร้อม': 43, 'ภูมิใจไทย': 16202, 'พลังธรรมใหม่': 46, 'กรีน': 67, 'ไทยธรรม': 4, 'แผ่นดินธรรม': 9, 'กล้าธรรม': 861, 'พลังประชารัฐ': 93, 'โอกาสใหม่': 47, 'เป็นธรรม': 40, 'ประชาชน': 36150, 'ประชาไทย': 72, 'ไทยสร้างไทย': 655, 'ไทยก้าวใหม่': 565, 'ประชาอาสาชาติ': 4, 'พร้อม': 21, 'เครือข่ายชาวนาแห่งประเทศไทย': 4, 'ไทยพิทักษ์ธรรม': 3, 'ความหวังใหม่': 12, 'ไทยรวมไทย': 7, 'เพื่อบ้านเมือง': 8, 'พลังไทยรักชาติ': 13}

Processing:  59%|█████▉    | 178/300 [17:34<23:24, 11.51s/doc]

party_list_10_5 {'ไทยพร้อมทวี': 14, 'เพื่อชาติไทย': 345, 'รวมใจไทย': 102, 'รวมไทยสร้างชาติ': 2234, 'พลวัต': 108, 'ประชาธิปไตยไหม้': 192, 'เสื้อไทย': 7684, 'ทางเลือกไหม้': 310, 'เศรษฐกิจ': 1307, 'รวมพลังประชาชน': 176, 'ท้องที่ไทย': 14, 'อนาคตไทย': 28, 'พลังเพื่อไทย': 80, 'ไทยชนะ': 33, 'พลังสังคมไทย': 2, 'สังคมประชาธิปไตยไทย': 19, 'ฟิวชัน': 15, 'ไทรวมพลัง': 32, 'ก้าวอิสระ': 10, 'ปวงชนไทย': 54, 'เพื่อชีวิตไทย': 29, 'ประชาธิปไตย': 9790, 'ไทยก้าวหน้า': 70, 'ไทยภักดี': 1554, 'แรงงานสร้างชาติ': 13, 'ประชากรไทย': 39, 'ครูไทยเพื่อประชาชน': 14, 'ประชาชาติ': 125, 'สร้างอนาคตไทย': 35, 'รักชาติ': 155, 'ไทยพร้อม': 53, 'ภูมิใจไทย': 19324, 'กรีน': 64, 'ไทยธรรม': 10, 'แผ่นดินธรรม': 6, 'กล้าธรรม': 161, 'พลังประชารัฐ': 97, 'เป็นธรรม': 41, 'ประชาชน': 46080, 'ประชาไทย': 82, 'ไทยสร้างไทย': 795, 'ไทยก้าวใหม่': 682, 'ประชาชนสาขาต': 5, 'พร้อม': 16, 'ไทยพิทักษ์ธรรม': 5, 'ไทยรวมไทย': 5, 'เพื่อบ้านเมือง': 12, 'พลังไทยรักชาติ': 13}

Processing:  60%|█████▉    | 179/300 [17:43<21:51, 10.84s/doc]

party_list_10_6 {'ไทยทรัพย์ทวี': 40, 'เพื่อชาติไทย': 141, 'มิติใหม่': 122, 'รวมใจไทย': 213, 'รวมไทยสร้างชาติ': 2942, 'พลวัด': 256, 'ประชาธิปไตยใหม่': 259, 'เพื่อไทย': 8914, 'ทางเลือกใหม่': 401, 'เศรษฐกิจ': 2620, 'เสรีรวมไทย': 332, 'รวมพลังประชาชน': 293, 'ท้องที่ไทย': 51, 'อนาคตไทย': 50, 'พลังเพื่อไทย': 55, 'ไทยชนะ': 48, 'พลังสังคมใหม่': 15, 'สังคมประชาธิปไตยไทย': 23, 'ทิวชัน': 14, 'ไทรวมพลัง': 21, 'ก้าวอิสระ': 20, 'ปวงชนไทย': 45, 'วิชชั่นใหม่': 16, 'เพื่อชีวิตใหม่': 16, 'คลองไทย': 81, 'ประชาธิปไตย': 10980, 'ไทยก้าวหน้า': 81, 'ไทยภักดี': 1924, 'แรงงานสร้างชาติ': 25, 'ประชากรไทย': 41, 'ครูไทยเพื่อประชาชน': 17, 'ประชาชาติ': 57, 'สร้างอนาคตไทย': 24, 'รักชาติ': 112, 'ไทยพร้อม': 212, 'ภูมิใจไทย': 17561, 'พลังธรรมใหม่': 145, 'กรีน': 91, 'ไทยธรรม': 23, 'แผ่นดินธรรม': 16, 'กล้าธรรม': 211, 'พลังประชารัฐ': 110, 'โอกาสใหม่': 1950, 'เป็นธรรม': 45, 'ประชาชน': 44984, 'ประชาไทย': 148, 'ไทยสร้างไทย': 758, 'ไทยก้าวใหม่': 715, 'ประชาอาสาชาติ': 2, 'พร้อม': 22, 'เครือข่ายชาวนาแห่งประเทศไทย': 7, 'ไทยพิทักษ์ธรรม': 7, 'ความหวังใหม่': 24, 'ไทยรวมไทย': 6, 'เพื่อบ้านเมือง': 13, 'พลังไทยรักชาติ': 14}

Processing:  60%|██████    | 180/300 [17:53<21:28, 10.73s/doc]

party_list_10_7 {'ไทยทรัพย์ทวี': 79, 'เพื่อชาติไทย': 225, 'มิติใหม่': 257, 'รวมใจไทย': 177, 'รวมไทยสร้างชาติ': 5162, 'พลวัต': 158, 'ประชาธิปไตยใหม่': 400, 'เพื่อไทย': 8129, 'ทางเลือกใหม่': 454, 'เศรษฐกิจ': 2261, 'เสรีรวมไทย': 367, 'รวมพลังประชาชน': 313, 'ท้องที่ไทย': 20, 'อนาคตไทย': 41, 'พลังเพื่อไทย': 81, 'ไทยชนะ': 42, 'พลังสังคมใหม่': 11, 'สังคมประชาธิปไตยไทย': 24, 'ไทรวมพลัง': 52, 'ก้าวอิสระ': 9, 'ปวงชนไทย': 42, 'วิชชั่นใหม่': 17, 'เพื่อชีวิตใหม่': 9, 'คลองไทย': 17, 'ประชาธิปัตย์': 7869, 'ไทยก้าวหน้า': 75, 'ไทยภักดี': 1466, 'แรงงานสร้างชาติ': 33, 'ประชากรไทย': 51, 'ครูไทยเพื่อประชาชน': 15, 'ประชาชาติ': 52, 'สร้างอนาคตไทย': 18, 'รักชาติ': 149, 'ไทยพร้อม': 54, 'ภูมิใจไทย': 16552, 'พลังธรรมใหม่': 46, 'กรีน': 74, 'ไทยธรรม': 18, 'แผ่นดินธรรม': 15, 'กล้าธรรม': 153, 'พลังประชารัฐ': 142, 'โอกาสใหม่': 103, 'เป็นธรรม': 274, 'ประชาชน': 40808, 'ประชาไทย': 90, 'ไทยสร้างไทย': 730, 'ไทยก้าวใหม่': 674, 'ประชาอาสาชาติ': 12, 'พร้อม': 18, 'เครือข่ายชาวนาแห่งประเทศไทย': 5, 'ไทยพิทักษ์ธรรม': 12, 'ความหรังใหม่': 10, 'ไทยรวมไทย': 11, 'เพื่อบ้านเมือง': 23, 'พลังไทยรักชาติ': 18}

Processing:  60%|██████    | 181/300 [18:08<23:25, 11.81s/doc]

party_list_10_8 {'ไทยทรัพย์ทวี': 151, 'เพื่อชาติไทย': 199, 'มิติใหม่': 49, 'รวมใจไทย': 385, 'รวมไทยสร้างชาติ': 2695, 'พลวัต': 132, 'ประชาธิปไตยใหม่': 179, 'เพื่อไทย': 10503, 'ทางเลือกใหม่': 468, 'เศรษฐกิจ': 1693, 'เสรี่ร่วมไทย': 409, 'รวมพลังประชาชน': 235, 'ท้องที่ไทย': 45, 'อนาคตไทย': 87, 'พลังเพื่อไทย': 81, 'ไทยชนะ': 32, 'พลังสังคมใหม่': 10, 'สังคมประชาธิปไตยไทย': 88, 'ทิวชัน': 28, 'ไทรวมพลัง': 29, 'ก้าวอิสระ': 18, 'ปวงชนไทย': 47, 'วิชชั่นใหม่': 24, 'เพื่อชีวิตใหม่': 17, 'คลองไทย': 19, 'ประชาธิปัตย์': 10313, 'ไทยก้าวหน้า': 37, 'ไทยกักดี': 2065, 'แรงงานสร้างชาติ': 28, 'ประชากรไทย': 45, 'ครูไทยเพื่อประชาชน': 19, 'ประชาชาติ': 51, 'สร้างอนาคตไทย': 27, 'รักชาติ': 233, 'ไทยพร้อม': 49, 'ภูมิใจไทย': 20176, 'พลังธรรมใหม่': 53, 'กรีน': 105, 'ไทยธรรม': 9, 'แผ่นดินธรรม': 15, 'กล้าธรรม': 176, 'พลังประชารัฐ': 115, 'โอกาสใหม่': 174, 'เป็นธรรม': 47, 'ประชาชน': 46772, 'ประชาไทย': 73, 'ไทยสร้างไทย': 923, 'ไทยก้าวใหม่': 926, 'ประชาอาสาชาติ': 1, 'พร้อม': 22, 'เครือข่าวชาวนาแห่งประเทศไทย': 10, 'ไทยพิทักษ์ธรรม': 5, 'ความหวังใหม่': 19, 'ไทยรวมไทย': 11, 'เพื่อบ้านเมือง': 12, 'พลังไทยรักชาติ': 20}

Processing:  61%|██████    | 182/300 [18:21<23:56, 12.17s/doc]

party_list_10_9 {}

Processing:  61%|██████    | 183/300 [18:31<22:46, 11.68s/doc]

party_list_11_1 {'ไทยพรัพย์ทวี': 35, 'เพื่อชาติไทย': 581, 'รวมใจไทย': 231, 'รวมไทยสร้างชาติ': 1877, 'พลวัค': 277, 'ประชาธิปไตยใหม่': 356, 'เพื่อไทย': 15344, 'ทางเลือกใหม่': 416, 'เศรษฐกิจ': 2588, 'เสร็จรวมไทย': 447, 'รวมพลังประชาชน': 437, 'ท้องที่ไทย': 17, 'อนาคตไทย': 52, 'พลังเพื่อไทย': 104, 'พลังสังคมใหม่': 7, 'สังคมประชาธิปไตยไทย': 22, 'ฟิวชัน': 15, 'ไทรวมพลัง': 34, 'ก้าวอิสระ': 14, 'ปวงชนไทย': 133, 'วิชชั้นใหม่': 11, 'เพื่อชีวิตใหม่': 12, 'คลองไทย': 25, 'ประชาธิปไตย': 5471, 'ไทยก้าวหน้า': 85, 'ไทยภักดี': 1036, 'แรงงานสร้างชาติ': 76, 'ประชากรไทย': 56, 'ครูไทยเพื่อประชาชน': 50, 'ประชาชาติ': 63, 'สร้างอนาคตไทย': 58, 'รักชาติ': 107, 'ไทยพร้อม': 53, 'ภูมิใจไทย': 14160, 'พลังธรรมใหม่': 80, 'กรีน': 59, 'ไทยธรรม': 30, 'แม่เดินธรรม': 17, 'พลังประชาธิปไตย': 247, 'โอกาสใหม่': 30, 'เป็นธรรม': 42, 'ประชาชน': 43207, 'ประชาไทย': 178, 'ไทยสร้างไทย': 370, 'ไทยก้าวใหม่': 366, 'ประชาอาสาชาติ': 7, 'พร้อม': 33, 'เครือข่ายชาวนาแห่งประเทศไทย': 7, 'ไทยพิทักษ์ธรรม': 7, 'ความหวังใหม่': 21, 'ไทยรวมไทย': 8, 'เพื่อบ้านเมือง': 11, 'พลังไทยรักชาติ': 25}

Processing:  61%|██████▏   | 184/300 [18:42<22:06, 11.43s/doc]

party_list_11_2 {'ไทยพร้อมทัว': 124, 'เพื่อชาติไทย': 626, 'มิติไหม': 73, 'รวมใจไทย': 305, 'รวมไทยสร้างชาติ': 1902, 'พลวัต': 322, 'ประชาธิปไตยไหม': 1947, 'เพื่อไทย': 16377, 'ทางเลือกไหม': 522, 'เศรษฐกิจ': 1080, 'เสร็จรวมไทย': 605, 'รวมพลังประชาชน': 533, 'ท้องที่ไทย': 35, 'อนาคตไทย': 60, 'พลังเพื่อไทย': 196, 'พลังสังคมไหม': 27, 'สังคมประชาธิปไตยไทย': 26, 'ฟิวชัน': 18, 'ไทรวมพลัง': 60, 'ก้าวอิสระ': 31, 'ปวดชนไทย': 137, 'วิชชั่นไหม': 29, 'เพื่อชีวิตไหม': 19, 'คลองไทย': 46, 'ประชาธิปไตย': 4662, 'ไทยก้าวหน้า': 149, 'ไทยภักดี': 625, 'แรงงานสร้างชาติ': 153, 'ประชากรไทย': 61, 'ครูไทยเพื่อประชาชน': 40, 'ประชาชาติ': 65, 'สร้างอนาคตไทย': 43, 'รักชาติ': 65, 'ไทยพร้อม': 42, 'ภูมิใจไทย': 11880, 'พลังธรรมไหม': 103, 'กรีน': 61, 'ไทยธรรม': 45, 'แผ่นดินธรรม': 15, 'กล้าอรรม': 96, 'พลังประชาธิปไตย': 154, 'โอกาสไหม': 32, 'เป็นธรรม': 49, 'ประชาชน': 43068, 'ประชาไทย': 211, 'ไทยสร้างไทย': 423, 'ไทยก้าวไหม': 310, 'ประชาอากรชาติ': 2, 'พร้อม': 44, 'เครือข่ายชาวนาแห่งประเทศไทย': 11, 'ไทยพิทักษ์ธรรม': 8, 'ความหวังไหม': 25, 'ไทยรวมไทย': 7, 'เพื่อบ้านเมือง': 21, 'พลังไทยรักชาติ': 25}

Processing:  62%|██████▏   | 185/300 [18:51<20:33, 10.73s/doc]

party_list_11_3 {'ไทยทรัพย์ทวี': 74, 'เพื่อชาติไทย': 501, 'รวมใจไทย': 234, 'รวมไทยสร้างชาติ': 2050, 'พลวัต': 121, 'ประชาธิปไตยไทม์': 819, 'เพื่อไทย': 9982, 'ทางเลือกไทม์': 380, 'เศรษฐกิจ': 2267, 'เสร็จรวมไทย': 407, 'รวมพลังประชาชน': 411, 'ห้องที่ไทย': 15, 'อนาคตไทย': 44, 'พลังเพื่อไทย': 105, 'ไทยชนะ': 62, 'พลังสังคมไทม์': 12, 'สังคมประชาธิปไตยไทย': 27, 'ฟิวชัน': 17, 'โทรวมพลัง': 29, 'ก้าวอิสระ': 17, 'ปวงชนไทย': 265, 'วิชชั่นไทม์': 35, 'เพื่อชีวิตไทม์': 12, 'คลองไทย': 65, 'ประชาธิปัตย์': 8372, 'ไทยก้าวหน้า': 123, 'ไทยภักดี': 1246, 'แรงงานสร้างชาติ': 77, 'ประชากรไทย': 52, 'ครูไทยเพื่อประชาชน': 42, 'ประชาชาติ': 67, 'สร้างอนาคตไทย': 40, 'รักชาติ': 85, 'ไทยพร้อม': 44, 'ภูมิใจไทย': 14946, 'พลังธรรมไทม์': 126, 'กรีน': 76, 'ไทยธรรม': 41, 'แผ่นดินธรรม': 8, 'กล้าธรรม': 262, 'พลังประชาธิปไตย': 155, 'เป็นธรรม': 44, 'ประชาชน': 45185, 'ประชาไทย': 125, 'ไทยสร้างไทย': 508, 'ไทยก้าวไทม์': 367, 'ประชาอาสาชาติ': 4, 'พร้อม': 35, 'เครือข่ายชาวนาแห่งประเทศไทย': 11, 'ไทยพิทักษ์ธรรม': 8, 'ความหวังไทม์': 17, 'ไทยรวมไทย': 6, 'เพื่อบ้านเมือง': 22, 'พลังไทยรักชาติ': 25}

Processing:  62%|██████▏   | 186/300 [19:00<19:30, 10.27s/doc]

party_list_11_4 {'ไทยพร้อมโฟก': 146, 'เพื่อชาติไทย': 556, 'รวมใจไทย': 236, 'รวมไทยสร้างชาติ': 1873, 'พลวัต': 617, 'ประชาธิปไตยไทม์': 243, 'เพื่อไทย': 9839, 'เศรษฐกิจ': 2046, 'เสร็จรวมไทย': 536, 'รวมพลังประชาชน': 379, 'ท้องที่ไทย': 26, 'อนาคตไทย': 45, 'พลังเพื่อไทย': 121, 'พลังสังคมไทม์': 11, 'สังคมประชาธิปไตยไทย': 16, 'ฟิวชัน': 15, 'ไทรวมพลัง': 47, 'ก้าวอิสระ': 17, 'ปวงชนไทย': 136, 'วิชชั่นไทม์': 21, 'เพื่อชีวิตไทม์': 14, 'ตลอดไทย': 25, 'ประชาธิปไตย': 6746, 'ไทยก้าวหน้า': 92, 'ไทยภักดี': 1100, 'แรงงานสร้างชาติ': 336, 'ประชากรไทย': 54, 'ครูไทยเพื่อประชาชน': 28, 'ประชาชาติ': 57, 'สร้างอนาคตไทย': 38, 'รักชาติ': 93, 'ไทยพร้อม': 64, 'ภูมิใจไทย': 16280, 'พลังธรรมไทม์': 51, 'กรีน': 34, 'ไทยธรรม': 35, 'แม่มตินธรรม': 10, 'กล้าธรรม': 172, 'พลังประชาธิปไตย': 153, 'เป็นธรรม': 45, 'ประชาชน': 50487, 'ประชาไทย': 390, 'ไทยสร้างไทย': 487, 'ไทยก้าวไทม์': 549, 'ประชาอาสาชาติ': 6, 'พร้อม': 38, 'เครือข่ายชาวนาแห่งประเทศไทย': 12, 'ไทยพิทักษ์ธรรม': 9, 'ความหวังไทม์': 21, 'ไทยรวมไทย': 10, 'เพื่อบ้านเมือง': 11, 'พลังไทยรักชาติ': 23}

Processing:  62%|██████▏   | 187/300 [19:09<18:34,  9.86s/doc]

party_list_11_5 {'ไทยทรัพย์ทวี': 149, 'เพื่อชาติไทย': 538, 'รวมใจไทย': 335, 'รวมไทยสร้างชาติ': 2110, 'พลวัต': 130, 'ประชาธิปไตยไทม์': 361, 'เพื่อไทย': 11530, 'ทางเลือกไทม์': 588, 'เศรษฐกิจ': 3249, 'รวมพลังประชาชน': 614, 'ท้องที่ไทย': 51, 'อนาคตไทย': 70, 'พลังเพื่อไทย': 150, 'ไทยชนะ': 72, 'พลังสังคมไทม์': 21, 'สังคมประชาธิปไตยไทย': 34, 'ฟิวชัน': 22, 'ไทรวมพลัง': 30, 'ก้าวอิสระ': 18, 'ปวงชนไทย': 137, 'วิชชั่นไทม์': 19, 'เพื่อชีวิตไทม์': 21, 'คลองไทย': 30, 'ประชาธิปไตย': 6261, 'ไทยก้าวหน้า': 162, 'ไทยภักดี': 880, 'แรงงานสร้างชาติ': 101, 'ประชากรไทย': 80, 'ครูไทยเพื่อประชาชน': 42, 'ประชาชาติ': 134, 'สร้างอนาคตไทย': 70, 'รักชาติ': 82, 'ไทยพร้อม': 130, 'ภูมิใจไทย': 16262, 'พลังธรรมไทม์': 89, 'กรีน': 58, 'ไทยธรรม': 40, 'แผ่นดินธรรม': 30, 'กล้าวธรรม': 137, 'พลังประชารัฐ': 407, 'เป็นธรรม': 52, 'ประชาชน': 56547, 'ประชาไทย': 178, 'ไทยสร้างไทย': 534, 'ไทยก้าวไทม์': 724, 'พร้อม': 66, 'เครือข่ายชาวนาแห่งประเทศไทย': 13, 'ไทยพิทักษ์ธรรม': 9, 'ความหวังไทม์': 30, 'ไทยรวมไทย': 9, 'เพื่อบ้านเมือง': 24, 'พลังไทยรักชาติ': 32}

Processing:  63%|██████▎   | 188/300 [19:17<17:12,  9.22s/doc]

party_list_11_6 {'ไทยพร้พย์ทวี': 113, 'เพื่อชาติไทย': 529, 'มิติใหม่': 1333, 'รวมใจไทย': 403, 'รวมไทยสร้างชาติ': 1841, 'พลวัต': 333, 'ประชาธิปไตยใหม่': 633, 'เพื่อไทย': 8913, 'ทางเลือกใหม่': 420, 'เศรษฐกิจ': 2359, 'เสร็จรวมไทย': 699, 'รวมพลังประชาชน': 488, 'ท้องที่ไทย': 41, 'อนาคตไทย': 48, 'พลังเพื่อไทย': 123, 'ไทยชนะ': 72, 'พลังสังคมใหม่': 27, 'สังคมประชาธิปไตยไทย': 22, 'ไทรวมพลัง': 33, 'ก้าวอิสระ': 23, 'ปวงชนไทย': 278, 'วิชชนใหม่': 41, 'เพื่อชีวิตใหม่': 18, 'คลองไทย': 39, 'ประชาธิปไตย': 4671, 'ไทยก้าวหน้า': 115, 'ไทยภักดี': 800, 'แรงงานสร้างชาติ': 66, 'ประชากรไทย': 68, 'ครูไทยเพื่อประชาชน': 49, 'ประชาชาติ': 149, 'สร้างอนาคตไทย': 152, 'รักชาติ': 85, 'ไทยพร้อม': 90, 'ภูมิใจไทย': 22294, 'พลังธรรมใหม่': 72, 'กรีน': 53, 'ไทยธรรม': 53, 'แผ่นดินธรรม': 17, 'กล้าธรรม': 100, 'พลังประชาธิปไตย': 141, 'โอกาสใหม่': 40, 'เป็นธรรม': 51, 'ประชาชน': 35615, 'ประชาไทย': 275, 'ไทยสร้างไทย': 468, 'ไทยก้าวใหม่': 439, 'ประชาอาสาชาติ': 15, 'พร้อม': 37, 'เครือข่ายชาวบ้านหงประเทศไทย': 11, 'ไทยพิทักษ์ธรรม': 15, 'ความหวังใหม่': 16, 'ไทยรวมไทย': 14, 'เพื่อบ้านเมือง': 15, 'พลังไทยรักชาติ': 37}

Processing:  63%|██████▎   | 189/300 [19:27<17:28,  9.44s/doc]

party_list_11_7 {'รวมโดยสร้างชาติ': 1740, 'ประชาธิปไตยใหม่': 849, 'เพื่อโดย': 12155, 'ทางเลือกใหม่': 516, 'เศรษฐกิจ': 2334, 'เสรีรวมโดย': 586, 'รวมพลังประชาชน': 623, 'ท้องที่โดย': 26, 'พลังเพื่อโดย': 164, 'พลังสังคมใหม่': 20, 'สังคมประชาธิปไตยโดย': 18, 'ใครวมพลัง': 44, 'ก้าวอิสระ': 27, 'วิชชั่นใหม่': 38, 'เพื่อชีวิตใหม่': 15, 'ประชาธิปไตย': 161, 'โดยก้าวหน้า': 163, 'โดยภักดี': 686, 'แรงงานสร้างชาติ': 162, 'ประชากรโดย': 142, 'ครูโดยเพื่อประชาชน': 123, 'ประชาชาติ': 34, 'รักชาติ': 38, 'ไทยพร้อม': 46, 'ภูมิใจโดย': 16854, 'พลังธรรมใหม่': 88, 'กรีน': 60, 'โดยธรรม': 29, 'แผ่นดินธรรม': 19, 'กล้าธรรม': 238, 'พลังประชาธิปไตย': 161, 'โอกาสใหม่': 31, 'เป็นธรรม': 263, 'ประชาชน': 16816, 'โดยก้าวใหม่': 413, 'ประชากรสาขาต': 9, 'พร้อม': 52, 'โดยพิทักษ์ธรรม': 9, 'ความหวังใหม่': 12, 'เพื่อบ้านเมือง': 21, 'พลังโดยรักชาติ': 43}

Processing:  63%|██████▎   | 190/300 [19:36<17:11,  9.38s/doc]

party_list_11_8 {'ไทยพรัพย์ทวี': 182, 'เพื่อชาติไทย': 1091, 'มิติใหม่': 179, 'รวมใจไทย': 545, 'รวมไทยสร้างชาติ': 2216, 'พลวัต': 3489, 'ประชาธิปไตยใหม่': 578, 'เพื่อไทย': 15086, 'ทางเลือกใหม่': 697, 'เศรษฐกิจ': 3840, 'เสร็จรวมไทย': 863, 'รวมพลังประชาชน': 711, 'ท้องที่ไทย': 37, 'อนาคตไทย': 107, 'พลังเพื่อไทย': 273, 'ไทยชนะ': 87, 'พลังสังคมใหม่': 27, 'สังคมประชาธิปไตยไทย': 70, 'ฟิวชัน': 31, 'ไทรวมพลัง': 69, 'ก้าวอิสระ': 49, 'ปวงชนไทย': 189, 'วิชชั่นใหม่': 32, 'เพื่อชีวิตใหม่': 17, 'คลองไทย': 53, 'ประชาธิปัตย์': 5659, 'ไทยก้าวหน้า': 218, 'ไทยภักดี': 328, 'แรงงานสร้างชาติ': 183, 'ประชากรไทย': 122, 'ครูไทยเพื่อประชาชน': 108, 'ประชาชาติ': 156, 'สร้างอนาคตไทย': 88, 'รักชาติ': 124, 'ไทยพร้อม': 168, 'ภูมิใจไทย': 15076, 'พลังธรรมใหม่': 163, 'กรีน': 57, 'ไทยธรรม': 67, 'แผ่นดินธรรม': 46, 'กล้าธรรม': 3784, 'พลังประชารัฐ': 434, 'โอกาสใหม่': 46, 'เป็นธรรม': 88, 'ประชาชน': 47267, 'ประชาไทย': 207, 'ไทยสร้างไทย': 369, 'ไทยก้าวใหม่': 646, 'ประชาอาสาชาติ': 17, 'พร้อม': 52, 'เครือข่ายชาวนาแห่งประเทศไทย': 19, 'ไทยพิทักษ์ธรรม': 17, 'ความหวังใหม่': 41, 'ไทยรวมไทย': 17, 'เพื่อบ้านเมือง': 24, 'พลังไทยรักชาติ': 50}

Processing:  64%|██████▎   | 191/300 [19:46<17:04,  9.40s/doc]

party_list_12_1 {'เพื่อขาดไทย': 290, 'รวมใจไทย': 249, 'รวมไทยสร้างชาติ': 3740, 'พลวัด': 265, 'ประชาธิปไตยไหม': 358, 'เพื่อไทย': 9120, 'เศรษฐกิจ': 2063, 'เสรีรวมไทย': 586, 'รวมพลังประชาชน': 296, 'ท้องที่ไทย': 24, 'อนาคตไทย': 38, 'พลังเพื่อไทย': 83, 'ไทยชนะ': 40, 'พลังสังคมไหม': 12, 'สังคมประชาธิปไตยไทย': 38, 'ฟิวชัน': 174, 'ก้าวอิสระ': 66, 'ปวงชนไทย': 32, 'วิชชั่นไหม': 32, 'เพื่อชีวิตไหม': 9, 'คลองไทย': 28, 'ประชาธิปัตย์': 8340, 'ไทยก้าวหน้า': 105, 'ไทยก้าดี': 1961, 'แรงงานสร้างชาติ': 34, 'ประชากรไทย': 58, 'ครูไทยเพื่อประชาชน': 34, 'ประชาชาติ': 85, 'สร้างอนาคตไทย': 38, 'รักชาติ': 159, 'ไทยพร้อม': 66, 'ภูมิใจไทย': 19003, 'พลังธรรมไหม': 34, 'กรีน': 35, 'ไทยธรรม': 18, 'แผ่นดินธรรม': 6, 'กล้าธรรม': 825, 'พลังประชารัฐ': 162, 'โอกาสไหม': 59, 'เป็นธรรม': 31, 'ประชาชน': 56908, 'ประชาไทย': 94, 'ไทยสร้างไทย': 2125, 'ไทยก้าวไหม': 960, 'ประชาอาสาชาติ': 8, 'พร้อม': 17, 'เครือข่ายชาวนาแห่งประเทศไทย': 21, 'ไทยพิทักษ์ธรรม': 9, 'ความหวังไหม': 9, 'ไทยรวมไทย': 3, 'เพื่อบ้านเมือง': 8, 'พลังไทยรักชาติ': 25}

Processing:  64%|██████▍   | 192/300 [19:53<16:03,  8.92s/doc]

party_list_12_2 {'เพื่อชาติไทย': 282, 'รวมใจไทย': 526, 'รวมไทยสร้างชาติ': 2092, 'พลวัต': 727, 'ประชาธิปไตยไทม์': 170, 'เพื่อไทย': 4236, 'ทางเลือกไทม์': 474, 'เศรษฐกิจ': 1877, 'เสร็จรวมไทย': 535, 'รวมพลังประชาชน': 284, 'ท้องที่ไทย': 18, 'อนาคตไทย': 29, 'พลังเพื่อไทย': 80, 'พลังสังคมไทม์': 8, 'สังคมประชาธิปไตยไทย': 27, 'ไทรรมพลัง': 52, 'ก้าวอิสระ': 31, 'ปวงชนไทย': 29, 'วิชชั่นไทม์': 13, 'เพื่อชีวิตไทม์': 8, 'คลองไทย': 32, 'ประชาธิปัตย์': 6874, 'ไทยก้าวหน้า': 74, 'ไทยภักดี': 1851, 'แรงงานสร้างชาติ': 23, 'ประชากรไทย': 45, 'ครูไทยเพื่อประชาชน': 30, 'ประชาชาติ': 71, 'สร้างอนาคตไทย': 35, 'รักชาติ': 259, 'ไทยพร้อม': 51, 'ภูมิใจไทย': 16577, 'พลังธรรมไทม์': 135, 'กรีน': 71, 'ไทยธรรม': 14, 'แผ่นดินธรรม': 6, 'กล้าธรรม': 105, 'พลังประชาธิปไตย': 129, 'เป็นธรรม': 214, 'ประชาชน': 18205, 'ประชาไทย': 130, 'ไทยสร้างไทย': 1321, 'ไทยก้าวไทม์': 526, 'ประชาอาสาชาติ': 5, 'พร้อม': 27, 'เครือข่ายชาวบ้านหง่าวมเทศไทย': 9, 'ไทยพิทักษ์ธรรม': 13, 'ความหวังไทม์': 20, 'ไทยรวมไทย': 13, 'เพื่อบ้านเมือง': 12, 'พลังไทยรักชาติ': 27}

Processing:  64%|██████▍   | 193/300 [20:05<17:28,  9.80s/doc]

party_list_12_3 {'ไทยพร้อมทัวร์': 86, 'เพื่อชาติไทย': 1848, 'รวมใจไทย': 254, 'รวมไทยสร้างชาติ': 2345, 'พลวัต': 366, 'ประชาธิปไตยไหม': 357, 'เพื่อไทย': 10922, 'ทางเลือกไหม': 311, 'เศรษฐกิจ': 2331, 'เสร็จรวมไทย': 605, 'รวมพลังประชาชน': 377, 'ท้องที่ไทย': 20, 'อนาคตไทย': 52, 'พลังเพื่อไทย': 114, 'ไทยชนะ': 52, 'พลังสังคมไหม': 13, 'สังคมประชาธิปไตยไทย': 28, 'ทิวชัน': 23, 'ไทยรวมพลัง': 37, 'ก้าวอิสระ': 21, 'ปวงชนไทย': 47, 'วิชชั่นไหม': 31, 'เพื่อชีวิตไหม': 17, 'คลองไทย': 31, 'ประชาธิปไตย': 8407, 'ไทยก้าวหน้า': 95, 'แรงงานสร้างชาติ': 50, 'ประชากรไทย': 83, 'ครูไทยเพื่อประชาชน': 36, 'ประชาชาติ': 54, 'สร้างอนาคตไทย': 38, 'รักชาติ': 114, 'ไทยพร้อม': 52, 'ภูมิใจไทย': 18327, 'พลังธรรมไหม': 69, 'กรีน': 34, 'ไทยธรรม': 24, 'แผ่นดินธรรม': 9, 'กล้าธรรม': 167, 'พลังประชารัฐ': 554, 'โอกาสไหม': 86, 'เป็นธรรม': 42, 'ประชาชน': 47312, 'ประชาไทย': 185, 'ไทยสร้างไทย': 1162, 'ไทยก้าวไหม': 632, 'พร้อม': 33, 'เครือข่ายชาวบ้านพังประเทศไทย': 6, 'ไทยพิทักษ์ธรรม': 9, 'ความหวังไหม': 12, 'ไทยรวมไทย': 13, 'เพื่อบ้านเมือง': 12, 'พลังไทยรักชาติ': 17}

Processing:  65%|██████▍   | 194/300 [20:15<17:14,  9.76s/doc]

party_list_12_4 {'ไทยทรัพย์ทวี': 71, 'เพื่อชาติไทย': 449, 'มิติใหม่': 88, 'รวมใจไทย': 699, 'รวมไทยสร้างชาติ': 2232, 'พลวัต': 676, 'ประชาธิปไตยใหม่': 310, 'เพื่อไทย': 10348, 'ทางเลือกใหม่': 486, 'เศรษฐกิจ': 2118, 'เสรีรวมไทย': 511, 'รวมพลังประชาชน': 259, 'ท้องที่ไทย': 19, 'อนาคตไทย': 31, 'พลังเพื่อไทย': 88, 'พลังสังคมใหม่': 6, 'สังคมประชาธิปไตยไทย': 23, 'ทิวชัน': 33, 'ไทรวมพลัง': 50, 'ก้าวอิสระ': 22, 'ปวงชนไทย': 25, 'วิชชั้นใหม่': 25, 'เพื่อชีวิตใหม่': 12, 'คลองไทย': 20, 'ประชาธิปไตย': 6672, 'ไทยก้าวหน้า': 102, 'ไทยภักดี': 1542, 'แรงงานสร้างชาติ': 38, 'ประชากรไทย': 53, 'ครูไทยเพื่อประชาชน': 28, 'ประชาชาติ': 48, 'สร้างอนาคตไทย': 37, 'รักชาติ': 125, 'ไทยพร้อม': 67, 'ภูมิใจไทย': 20330, 'พลังธรรมใหม่': 51, 'กรีน': 103, 'ไทยธรรม': 18, 'แผ่นดินธรรม': 10, 'กล้าธรรม': 206, 'พลังประชารัฐ': 123, 'โอกาสใหม่': 84, 'เป็นธรรม': 24, 'ประชาชน': 38204, 'ประชาไทย': 90, 'ไทยสร้างไทย': 692, 'ไทยก้าวใหม่': 529, 'ประชาชนสาขาต': 5, 'พร้อม': 19, 'เครือข่ายชาวนาแห่งประเทศไทย': 10, 'ไทยพิทักษ์ธรรม': 24, 'ความหรังใหม่': 13, 'ไทยรวมไทย': 7, 'เพื่อบ้านเมือง': 15, 'พลังไทยรักชาติ': 25}

Processing:  65%|██████▌   | 195/300 [20:24<16:40,  9.53s/doc]

party_list_12_5 {'ไทยทรัพย์บวี': 97, 'เพื่อชาติไทย': 456, 'มีติใหม่': 152, 'รวมใจไทย': 198, 'รวมไทยสร้างชาติ': 292, 'พลวัต': 124, 'ประชาธิปไตยใหม่': 530, 'เพื่อไทย': 9299, 'ทางเลือกใหม่': 570, 'เศรษฐกิจ': 2264, 'เสรีรวมไทย': 448, 'รวมพลังประชาชน': 334, 'ท้องที่ไทย': 32, 'อนาคตไทย': 50, 'พลังเพื่อไทย': 110, 'ไทยชนะ': 40, 'พลังสังคมใหม่': 12, 'สังคมประชาธิปไตยไทย': 43, 'ไทรวมพลัง': 33, 'ก้าวสิสระ': 139, 'ปวงชนไทย': 32, 'วิชชั่นใหม่': 41, 'เพื่อชีวิตใหม่': 10, 'คลองไทย': 29, 'ประชาธิปัตย์': 7653, 'ไทยก้าวหน้า': 83, 'ไทยภักดี': 1490, 'แรงงานสร้างชาติ': 44, 'ประชากรไทย': 64, 'ครูไทยเพื่อประชาชน': 45, 'ประชาชาติ': 242, 'สร้างอนาคตไทย': 80, 'ไทยพร้อม': 182, 'ภูมิใจไทย': 22453, 'พลังธรรมใหม่': 88, 'กรีน': 72, 'ไทยธรรม': 14, 'แผ่นดินธรรม': 12, 'กล้าธรรม': 309, 'พลังประชาธิปไตย': 224, 'โอกาสใหม่': 75, 'เป็นธรรม': 53, 'ประชาชน': 53742, 'ประชาไทย': 109, 'ไทยสร้างไทย': 1432, 'ไทยก้าวใหม่': 571, 'พร้อม': 34, 'ไทยพิทักษ์ธรรม': 11, 'ความหวังใหม่': 12, 'ไทยรวมไทย': 13, 'เพื่อบ้านเมือง': 18, 'พลังไทยรักษาดี': 29}

Processing:  65%|██████▌   | 196/300 [20:34<16:49,  9.71s/doc]

party_list_12_6 {'รวมโคมสร้างชาติ': 6083, 'ประชาธิปไตยใหม่': 556, 'เศรษฐกิจ': 2756, 'เสรีรวมโคม': 575, 'รวมพลังประชาชน': 563, 'พลังเพื่อโคม': 161, 'พลังดังคมใหม่': 26, 'โครรวมพลัง': 21, 'ก้าวอิสระ': 58, 'เพื่อชีวิตใหม่': 567, 'ประชาธิปัตย์': 3585, 'โคมก้าวหน้า': 78, 'แรงงานสร้างชาติ': 26, 'ประชากรโคม': 186, 'ครูโคมเพื่อประชาชน': 56, 'ประชาชาติ': 35, 'สร้างอนาคตโคม': 56, 'รักชาติ': 187, 'โคมพร้อม': 96, 'พลังธรรมใหม่': 78, 'กล้าวธรรม': 210, 'พลังประชาธิปู': 21, 'โอกาสใหม่': 29, 'เป็นธรรม': 56, 'ประชาชน': 56631, 'ประชาธิปต': 172, 'โคมก้าวใหม่': 507, 'พร้อม': 96, 'ความจริงใหม่': 27, 'เพื่อบ้านเมือง': 35, 'พลังโคมรักชาติ': 32}

Processing:  66%|██████▌   | 197/300 [20:48<18:38, 10.86s/doc]

party_list_12_7 {'ไพยทรัพย์ทวี': 286, 'เพื่อชาติไทย': 548, 'มิติใหม่': 132, 'รวมใจไทย': 511, 'รวมไทยสร้างชาติ': 3764, 'พลวัต': 212, 'ประชาธิปไตยใหม่': 409, 'เพื่อไทย': 10132, 'ทางเลือกใหม่': 619, 'เศรษฐกิจ': 2619, 'เสรีรวมไทย': 625, 'รวมพลังประชาชน': 166, 'ท้องที่ไทย': 29, 'อนาคตไทย': 36, 'พลังเพื่อไทย': 144, 'ไทยชนม': 36, 'พลังสังคมใหม่': 15, 'สังคมประชาธิปไตยไทย': 25, 'ฟิวชัน': 17, 'ไทรวิมพลัง': 44, 'ก้าวอิสระ': 26, 'ปวงชนไทย': 32, 'วิชชั่นใหม่': 52, 'เพื่อชีวิตใหม่': 11, 'คลองไทย': 42, 'ประชาธิปไตย': 7764, 'ไทยก้าวหน้า': 142, 'ไทยภักดี': 1180, 'แรงงานสร้างชาติ': 45, 'ประชากรไทย': 75, 'ครูไทยเพื่อประชาชน': 54, 'ประชาชาติ': 132, 'สร้างอนาคตไทย': 57, 'รักชาติ': 134, 'ไทยพร้อม': 156, 'ภูมิใจไทย': 16712, 'พลังธรรมใหม่': 77, 'กรีน': 81, 'ไทยธรรม': 32, 'แผ่นดินธรรม': 55, 'กล้าระรม': 3714, 'พลังประชาธิปไตย': 159, 'โอกาสใหม่': 55, 'เป็นธรรม': 59, 'ประชาชน': 54379, 'ประชากร': 557, 'ไทยสร้างไทย': 581, 'ไทยก้าวใหม่': 564, 'ประชาอาสาชาติ': 14, 'พร้อม': 59, 'เครือข่ายชาวนาแห่งประเทศไทย': 18, 'ไทยพิทักษ์ธรรม': 12, 'ความพรังใหม่': 20, 'ไทยรวมไทย': 15, 'เพื่อบ้านเมือง': 32, 'พลังไทยรักชาติ': 42}

Processing:  66%|██████▌   | 198/300 [20:58<18:24, 10.83s/doc]

party_list_12_8 {'ไทยทรัพย์ทวี': 101, 'เพื่อชาติไทย': 1016, 'มิติไหม่': 323, 'รวมใจไทย': 353, 'รวมไทยสร้างชาติ': 2171, 'พลวัต': 962, 'ประชาธิปไตยไหม่': 357, 'เพื่อไทย': 9903, 'ทางเลือกไหม่': 487, 'เศรษฐกิจ': 2538, 'รวมพลังประชาชน': 431, 'ท้องที่ไทย': 27, 'อนาคตไทย': 41, 'พลังเพื่อไทย': 115, 'ไทยชนต': 61, 'พลังสังคมไหม่': 16, 'สังคมประชาธิปไตยไทย': 27, 'พิวชัน': 33, 'ก้าวอิสระ': 28, 'ปวชนไทย': 37, 'วิชชั่นไหม่': 32, 'เพื่อชีวิตไหม่': 18, 'คลองไทย': 38, 'ประชาธิปไตย': 6441, 'ไทยก้าวหน้า': 121, 'ไทยภักดี': 1144, 'แรงงานสร้างชาติ': 41, 'ประชากรไทย': 113, 'ครูไทยเพื่อประชาชน': 57, 'ประชาชาติ': 91, 'สร้างอนาคตไทย': 64, 'รักชาติ': 133, 'ไทยพร้อม': 97, 'ภูมิใจไทย': 20401, 'พลังธรรมไหม่': 188, 'กรีน': 82, 'ไทยธรรม': 29, 'แผ่นดินธรรม': 9, 'กล้าธรรม': 429, 'พลังประชาธิปไตย': 164, 'โอกาสไหม่': 47, 'เป็นธรรม': 44, 'ประชาชน': 39512, 'ประชาไทย': 131, 'ไทยสร้างไทย': 767, 'ไทยก้าวไหม่': 375, 'ประชาชนสาขาต': 1, 'พร้อม': 36, 'เครือข่ายชาวบนแห่งประเทศไทย': 13, 'ไทยพิทักษ์ธรรม': 15, 'ความหวังไหม่': 19, 'ไทยรวมไทย': 7, 'เพื่อบ้านเมือง': 19, 'พลังไทยรักชาติ': 42}

Processing:  66%|██████▋   | 199/300 [21:08<17:51, 10.61s/doc]

party_list_13_1 {'ไทยพรัพย์ทวี': 208, 'เพื่อชาติไทย': 3344, 'มิติไหม่': 165, 'รวมใจไทย': 501, 'รวมไทยสร้างชาติ': 2320, 'พลวัต': 170, 'ประชาธิปไตยไหม่': 435, 'เพื่อไทย': 14101, 'ทางเลือกใหม่': 679, 'เศรษฐกิจ': 3552, 'เสร็จมไทย': 585, 'รวมพลังประชาชน': 634, 'ท้องที่ไทย': 55, 'อนาคตไทย': 87, 'พลังเพื่อไทย': 174, 'ไทยชนะ': 69, 'พลังสังคมใหม่': 15, 'สังคมประชาธิปไตยไทย': 30, 'ฟิวชัน': 25, 'ไทรวมพลัง': 43, 'ก้าวอิสระ': 52, 'ปวงชนไทย': 31, 'วิชชั่นใหม่': 41, 'เพื่อชีวิตใหม่': 17, 'คลองไทย': 37, 'ประชาธิปัตย์': 5973, 'ไทยก้าวหน้า': 161, 'ไทยภักดี': 887, 'แรงงานสร้างชาติ': 66, 'ประชากรไทย': 152, 'ครูไทยเพื่อประชาชน': 91, 'ประชาชาติ': 459, 'สร้างอนาคตไทย': 76, 'รักชาติ': 97, 'ไทยพร้อม': 72, 'ภูมิใจไทย': 14877, 'พลังธรรมใหม่': 101, 'กรีน': 85, 'ไทยธรรม': 37, 'แผ่นดินธรรม': 35, 'กล้าธรรม': 1640, 'พลังประชาธิปไตย': 200, 'โอกาสใหม่': 59, 'เป็นธรรม': 200, 'ประชาชน': 40343, 'ประชาไทย': 134, 'ไทยสร้างไทย': 511, 'ไทยก้าวใหม่': 383, 'ประชาอาสาชาติ': 7, 'พร้อม': 56, 'เครือข่ายชาวนาแห่งประเทศไทย': 9, 'ไทยพิทักษ์ธรรม': 9, 'ความหวังใหม่': 27, 'ไทยรวมไทย': 8, 'เพื่อบ้านเมือง': 22, 'พลังไทยรักชาติ': 47}

Processing:  67%|██████▋   | 200/300 [21:17<16:34,  9.95s/doc]

party_list_13_2 {'เพื่อขาดไทย': 16116, 'รวมไอไทย': 3618, 'รวมไทยสร้างชาติ': 22002, 'พลวัด': 6760, 'ประชาธิปไตยใหม่': 3500, 'เพื่อไทย': 174613, 'ทางเลือกใหม่': 535, 'เศรษฐกิจ': 2742, 'เสรีรวมไทย': 5013, 'รวมพลังประชาชน': 4760, 'ท้องฟีไทย': 34, 'อนาคตไทย': 54, 'พลังเพื่อไทย': 154, 'ไทยชนะ': 67, 'พลังสังคมใหม่': 18, 'สังคมประชาธิปไตยไทย': 42, 'ฟิวชัน': 63, 'ไตรวมพลัง': 35, 'ปวงชนไทย': 30, 'วิชชั่นใหม่': 22, 'เพื่อชีวิตใหม่': 30, 'คลองไทย': 35, 'ประชาธิปัตย์': 4638, 'ไทยก้าวหน้า': 114, 'ไทยก้าดี': 837, 'แรงงานสร้างชาติ': 88, 'ประชากรไทย': 37, 'ครูไทยเพื่อประชาชน': 45, 'ประชาชาติ': 172, 'สร้างอนาคตไทย': 44, 'รักชาติ': 129, 'ไทยพร้อม': 110, 'ภูมิใจไทย': 18817, 'พลังธรรมใหม่': 31, 'กรีน': 69, 'ไทยธรรม': 18, 'แผ่นดินธรรม': 16, 'กล้าธรรม': 187, 'พลังประชาธิปไตย': 140, 'โอกาสใหม่': 60, 'เป็นธรรม': 48, 'ประชาชน': 39803, 'ประชาไทย': 133, 'ไทยสร้างไทย': 544, 'ไทยก้าวใหม่': 362, 'ประชาอาชญากร': 9, 'พร้อม': 45, 'เครือข่ายชาวบนแห่งประเทศไทย': 11, 'ไทยพิทักษ์ธรรม': 11, 'ความหวังใหม่': 18, 'ไทยรวมไทย': 19, 'เพื่อบ้านเมือง': 19, 'พลังไทยรักชาติ': 38}

Processing:  67%|██████▋   | 201/300 [21:24<15:11,  9.21s/doc]

party_list_13_3 {'ไทยทรัพย์ทวี - -': 121, 'เพื่อชาติไทย': 494, 'มิติใหม่': 69, 'รวมใจไทย': 308, 'รวมไทยสร้างชาติ': 1919, 'พลวัต': 254, 'ประชาธิปไตยใหม่': 383, 'เพื่อไทย': 10892, 'ทางเลือกใหม่': 411, 'เศรษฐกิจ': 2688, 'เสรีรวมไทย': 403, 'รวมพลังประชาชน': 482, 'ท้องที่ไทย': 22, 'อนาคตไทย': 42, 'พลังเพื่อไทย': 93, 'ไทยชนะ': 44, 'พลังสังคมใหม่': 19, 'สังคมประชาธิปไตยไทย': 25, 'พิวชั่น': 21, 'ไทรวมพลัง': 46, 'ก้าวอิสระ': 20, 'ปวงชนไทย': 33, 'วิชชั่นใหม่': 26, 'เพื่อชีวิตใหม่': 9, 'คลองไทย': 28, 'ประชาธิปัตย์': 4461, 'ไทยก้าวหน้า': 131, 'ไทยภักดี': 698, 'แรงงานสร้างชาติ': 49, 'ประชากรไทย': 49, 'ครูไทยเพื่อประชาชน': 46, 'ประชาชาติ': 66, 'สร้างอนาคตไทย': 37, 'รักชาติ - -': 38, 'ไทยพร้อม': 30, 'ภูมิใจไทย': 16287, 'พลังธรรมใหม่': 58, 'กรีน': 53, 'ไทยธรรม': 19, 'แผ่นดินธรรม': 43, 'กล้าธรรม': 125, 'พลังประชารัฐ': 130, 'โอกาสใหม่': 57, 'เป็นธรรม': 45, 'ประชาชน': 45220, 'ประชาไทย - -': 216, 'ไทยสร้างไทย': 421, 'ไทยก้าวใหม่': 420, 'ประชาอาสาชาติ': 8, 'พร้อม': 40, 'เครือข่ายชาวนาแห่งประเทศไทย': 13, 'ไทยพิทักษ์ธรรม': 10, 'ความหวังใหม่': 16, 'ไทยรวมไทย': 11, 'เพื่อบ้านเมือง': 12, 'พลังไทยรักชาติ': 47}

Processing:  67%|██████▋   | 202/300 [21:35<15:32,  9.51s/doc]

party_list_13_4 {'พรรคเพื่อชาติไทย': 556, 'พรรคใหม่': 117, 'พรรคมิติใหม่': 840, 'พรรครวมไทยสร้างชาติ': 2206, 'พรรคพลวัต': 1026, 'พรรคประชาธิปไตยใหม่': 391, 'พรรคเพื่อไทย': 12634, 'พรรคเศรษฐกิจ': 2725, 'พรรคเสรีรวมไทย': 533, 'พรรครวมพลังประชาชน': 466, 'พรรคอนาคตไทย': 55, 'พรรคพลังเพื่อไทย': 132, 'พรรคไทยชนะ': 52, 'พรรคพลังสังคมใหม่': 17, 'พรรคสังคมประชาธิปไตยไทย': 43, 'พรรคใครวมพลัง': 57, 'พรรคปวเชนไทย': 37, 'พรรควิชชั้นใหม่': 41, 'พรรคเพื่อชีวิตใหม่': 14, 'พรรคประชาธิปัตย์': 5790, 'พรรคไทยก้าวหน้า': 131, 'พรรคแรงงานสร้างชาติ': 37, 'พรรคประชากรไทย': 56, 'พรรคครูไทยเพื่อประชาชน': 40, 'พรรคประชาชาติ': 230, 'พรรคสร้างอนาคตไทย': 50, 'พรรครักชาติ': 130, 'พรรคไทยพร้อม': 88, 'พรรคภูมิใจไทย': 14450, 'พรรคพลังธรรมใหม่': 67, 'พรรคไทยธรรม': 18, 'พรรคกล้าธรรม': 1638, 'พรรคโอกาสใหม่': 54, 'พรรคเป็นธรรม': 54, 'พรรคประชาชน': 44830, 'พรรคประชาไทย': 127, 'พรรคไทยสร้างไทย': 528, 'พรรคไทยก้าวใหม่': 527, 'พรรคพร้อม': 38, 'พรรคเครือข่ายชาปนาแห่งประเทศไทย': 10, 'พรรคไทยพิทักษ์ธรรม': 21, 'พรรคความหวังใหม่': 18, 'พรรคไทยรวมไทย': 13, 'พรรคเพื่อบ้านเมือง': 11, 'พรรคพลังไทยรักชาติ': 20}

Processing:  68%|██████▊   | 203/300 [21:44<15:32,  9.62s/doc]

party_list_13_5 {'พรรคเพื่อชาติไทย': 1271, 'พรรคใหม่': 237, 'พรรคมิติใหม่': 54, 'พรรครวมใจไทย': 250, 'พรรครวมไทยสร้างชาติ': 2143, 'พรรคพลวัต': 120, 'พรรคประชาธิปไตยใหม่': 744, 'พรรคเพื่อไทย': 11410, 'พรรคทางเลือกใหม่': 482, 'พรรคเศรษฐกิจ': 2367, 'พรรครวมพลังประชาชน': 362, 'พรรคท้องที่ไทย': 24, 'พรรคอนาคตไทย': 52, 'พรรคพลังเพื่อไทย': 103, 'พรรคไทยชนะ': 41, 'พรรคพลังสังคมใหม่': 13, 'พรรคสังคมประชาธิปไตย': 24, 'พรรคไทรวมพลัง': 37, 'พรรคก้าวอิสระ': 14, 'พรรคปวงชนไทย': 22, 'พรรควิชชั่นใหม่': 30, 'พรรคเพียชีวิตใหม่': 16, 'พรรคคลองไทย': 21, 'พรรคประชาธิปัตย์': 5633, 'พรรคไทยก้าวหน้า': 120, 'พรรคไทยภักดี': 1192, 'พรรคแรงงานสร้างชาติ': 41, 'พรรคประชากรไทย': 64, 'พรรคครูไทยเพื่อประชาชน': 47, 'พรรคประชาชาติ': 49, 'พรรคสร้างอนาคตไทย': 34, 'พรรครักชาติ': 129, 'พรรคไทยพร้อม': 47, 'พรรคภูมิใจไทย': 14717, 'พรรคพลังธรรมใหม่': 68, 'พรรคไทยธรรม': 23, 'พรรคแผ่นดินธรรม': 23, 'พรรคกล้าอรรม': 1587, 'พรรคพลังประชารัฐ': 173, 'พรรคโอกาสใหม่': 58, 'พรรคเป็นธรรม': 55, 'พรรคประชาชน': 38966, 'พรรคประชาไทย': 83, 'พรรคไทยสร้างไทย': 639, 'พรรคไทยก้าวใหม่': 527, 'พรรคประชาอาสาชาติ': 5, 'พรรคพร้อม': 23, 'พรรคไทยพิทักษ์ธรรม': 2, 'พรรคความหวังใหม่': 15, 'พรรคไทยรวมไทย': 7, 'พรรคเพื่อบ้านเมือง': 18, 'พรรคพลังไทยรักชาติ': 23}

Processing:  68%|██████▊   | 204/300 [21:52<14:35,  9.12s/doc]

party_list_13_6 {'ไทยพร้อมโพร': 58, 'เพื่อชาติไทย': 174, 'มิติใหม่': 614, 'รวมใจไทย': 182, 'รวมไทยสร้างชาติ': 2167, 'พลวัต': 117, 'ประชาธิปไตยใหม่': 178, 'เพื่อไทย': 9878, 'ทางเลือกใหม่': 410, 'เศรษฐกิจ': 2498, 'รวมพลังประชาชน': 150, 'ท้องที่ไทย': 20, 'อนาคตไทย': 35, 'พลังเพื่อไทย': 38, 'ไทยชนะ': 39, 'พลังสังคมใหม่': 9, 'สังคมประชาธิปไตยไทย': 28, 'ไตร่รวมพลัง': 10, 'ก้าวอิสระ': 10, 'ปวงชนไทย': 32, 'วิชชั้นใหม่': 28, 'เพื่อชีวิตใหม่': 11, 'คลองไทย': 29, 'ประชาธิปไตย': 6150, 'ไทยก้าวหน้า': 116, 'ไทยภักดี': 910, 'แรงงานสร้างชาติ': 42, 'ประชากรไทย': 45, 'ครูไทยเพื่อประชาชน': 37, 'ประชาชาติ': 60, 'สร้างอนาคตไทย': 34, 'รักชาติ': 91, 'ไทยพร้อม': 45, 'ภูมิใจไทย': 13846, 'พลังธรรมใหม่': 50, 'กรีน': 54, 'ไทยธรรม': 22, 'แผ่นดินธรรม': 12, 'กล้าอรรม': 1024, 'พลังประชารัฐ': 167, 'โอกาสใหม่': 55, 'เป็นธรรม': 40, 'ประชาชน': 44639, 'ประชาไทย': 31, 'ไทยสร้างไทย': 567, 'ไทยก้าวใหม่': 556, 'ประชาอาสาชาติ': 7, 'พร้อม': 35, 'เครือข่ายชาวนาแห่งประเทศไทย': 10, 'ไทยพิทักษ์ธรรม': 10, 'ความหวังใหม่': 21, 'ไทยรวมไทย': 12, 'เพื่อบ้านเมือง': 10, 'พลังไทยรักชาติ': 20}

Processing:  68%|██████▊   | 205/300 [22:02<14:27,  9.13s/doc]

party_list_13_7 {'ไทยพร้อมทวี': 39, 'เพื่อชาติไทย': 505, 'มิติใหม่': 1449, 'รวมใจไทย': 439, 'รวมไทยสร้างชาติ': 1818, 'พลวัต': 245, 'ประชาธิปไตยใหม่': 438, 'เพื่อไทย': 9713, 'ทางเลือกใหม่': 431, 'เศรษฐกิจ': 3542, 'เสร็จรวมไทย': 477, 'รวมพลังประชาชน': 476, 'ท้องที่ไทย': 25, 'อนาคตไทย': 68, 'พลังเพื่อไทย': 119, 'ไทยชนะ': 80, 'พลังสังคมใหม่': 17, 'สังคมประชาธิปไตย': 20, 'ฟิวชัน': 23, 'ไทรวมพลัง': 45, 'ก้าวอิสระ': 23, 'ปวงชนไทย': 42, 'วิชชั่นใหม่': 38, 'เพื่อชีวิตใหม่': 13, 'คลองไทย': 41, 'ประชาธิปไตย': 3831, 'ไทยก้าวหน้า': 133, 'ไทยภักดี': 625, 'แรงงานสร้างชาติ': 41, 'ประชากรไทย': 86, 'ครูไทยเพื่อประชาชน': 69, 'ประชาชาติ': 128, 'สร้างอนาคตไทย': 133, 'รักชาติ': 35, 'ไทยพร้อม': 120, 'ภูมิใจไทย': 23403, 'พลังธรรมเนียม': 35, 'กรีน': 61, 'ไทยธรรม': 28, 'แผ่นดินธรรม': 17, 'กล้าธรรม': 235, 'พลังประชารัฐ': 145, 'โอกาสใหม่': 51, 'เป็นธรรม': 43, 'ประชาชน': 35826, 'ประชาไทย': 200, 'ไทยสร้างไทย': 341, 'ไทยก้าวใหม่': 296, 'ประชาอาสาชาติ': 7, 'พร้อม': 54, 'เครือข่ายชาวนาแห่งประเทศไทย': 47, 'ไทยพิทักษ์ธรรม': 7, 'ความหวังใหม่': 17, 'ไทยรวมไทย': 8, 'เพื่อบ้านเมือง': 13, 'พลังไทยรักชาติ': 32}

Processing:  69%|██████▊   | 206/300 [22:11<14:27,  9.22s/doc]

party_list_13_8 {'ไทยทรัพย์ทวี': 158, 'เพื่อชาติไทย': 364, 'มิติใหม่': 508, 'รวมใจไทย': 519, 'รวมไทยสร้างชาติ': 2111, 'ประชาธิปไตยใหม่': 713, 'เพื่อไทย': 12012, 'ทางเลือกใหม่': 168, 'เศรษฐกิจ': 3309, 'เสร็จรวมไทย': 538, 'รวมพลังประชาชน': 561, 'ท้องที่ไทย': 30, 'อนาคตไทย': 67, 'พลังเพื่อไทย': 162, 'ไทยชนะ': 110, 'พลังสังคมใหม่': 16, 'สังคมประชาธิปไตย': 23, 'ฟิวชัน': 29, 'ไทยรวมพลัง': 43, 'ก้าวอิสระ': 18, 'ปวงชนไทย': 47, 'วิชชั่นใหม่': 29, 'เพื่อชีวิตใหม่': 17, 'คลองไทย': 37, 'ประชาธิปไตย': 4266, 'ไทยก้าวหน้า': 99, 'ไทยภักดี': 563, 'แรงงานสร้างชาติ': 36, 'ประชากรไทย': 38, 'ครูไทยเพื่อประชาชน': 104, 'ประชาชาติ': 210, 'สร้างอนาคตไทย': 89, 'รักชาติ': 181, 'ไทยพร้อม': 119, 'ภูมิใจไทย': 21685, 'พลังธรรมใหม่': 109, 'กรีน': 55, 'ไทยธรรม': 30, 'แผ่นดินธรรม': 21, 'กล้าธรรม': 143, 'พลังประชารัฐ': 160, 'โอกาสใหม่': 30, 'เป็นธรรม': 33, 'ประชาชน': 32473, 'ประชาไทย': 101, 'ไทยสร้างไทย': 402, 'ไทยก้าวใหม่': 248, 'ประชาอาสาชาติ': 7, 'พร้อม': 42, 'เครือข่ายชาวนาแห่งประเทศไทย': 63, 'ไทยพิทักษ์ธรรม': 13, 'ความหวังใหม่': 38, 'ไทยรวมไทย': 6, 'เพื่อบ้านเมือง': 21, 'พลังไทยรักชาติ': 28}

Processing:  69%|██████▉   | 207/300 [22:22<15:04,  9.73s/doc]

party_list_14_1 {'ไทยทรัพย์ทวี': 435, 'เพื่อชาติไทย': 1015, 'มิติใหม่': 158, 'รวมใจไทย': 681, 'รวมไทยสร้างชาติ': 4898, 'พลวัต': 204, 'ประชาธิปไตยใหม่': 537, 'เพื่อไทย': 8930, 'ทางเลือกใหม่': 504, 'เศรษฐกิจ': 3154, 'เสรีรวมไทย': 572, 'รวมพลังประชาชน': 707, 'ท้องที่ไทย': 265, 'อนาคตไทย': 67, 'พลังเพื่อไทย': 186, 'ไทยชนะ': 107, 'พลังสังคมใหม่': 29, 'สังคมประชาธิปไตยไทย': 35, 'ฟิวชัน': 35, 'ไทรวมพลัง': 48, 'ก้าวอิสระ': 24, 'ปวงชนไทย': 55, 'วิชชั่นใหม่': 29, 'เพื่อชีวิตใหม่': 19, 'คลองไทย': 75, 'ประชาธิปัตย์': 5160, 'ไทยก้าวหน้า': 132, 'ไทยภักดี': 1029, 'แรงงานสร้างชาติ': 91, 'ประชากรไทย': 104, 'ครูไทยเพื่อประชาชน': 83, 'ประชาชาติ': 206, 'สร้างอนาคตไทย': 120, 'รักชาติ': 216, 'ไทยพร้อม': 250, 'ภูมิใจไทย': 25327, 'พลังธรรมใหม่': 98, 'กรีน': 55, 'ไทยธรรม': 32, 'แผ่นดินธรรม': 21, 'กล้าธรรม': 95, 'พลังประชาธิรัฐ': 209, 'โอกาสใหม่': 230, 'เป็นธรรม': 71, 'ประชาชน': 39154, 'ประชาไทย': 170, 'ไทยสร้างไทย': 450, 'ไทยก้าวใหม่': 312, 'ประชาอาสาชาติ': 9, 'พร้อม': 151, 'เครือข่ายชาวนาแห่งประเทศไทย': 17, 'ไทยพิทักษ์ธรรม': 9, 'ความหวังใหม่': 15, 'ไทยรวมไทย': 17, 'เพื่อบ้านเมือง': 20, 'พลังไทยรักชาติ': 51}

Processing:  69%|██████▉   | 208/300 [22:32<14:57,  9.76s/doc]

party_list_14_2 {}

Processing:  70%|██████▉   | 209/300 [22:43<15:19, 10.10s/doc]

party_list_14_3 {'ไทยทรัพย์ทวี': 276, 'เพื่อชาติไทย': 1211, 'มิติใหม่': 560, 'รวมใจไทย': 4603, 'รวมไทยสร้างชาติ': 1757, 'พลวัต': 118, 'ประชาธิปไตยใหม่': 896, 'เพื่อไทย': 10642, 'ทางเลือกใหม่': 525, 'เศรษฐกิจ': 4025, 'เสรีรวมไทย': 625, 'รวมพลังประชาชน': 766, 'ท้องที่ไทย': 62, 'อนาคตไทย': 85, 'พลังเพื่อไทย': 218, 'ไทยชนะ': 128, 'พลังสังคมใหม่': 29, 'สังคมประชาธิปไตยไทย': 30, 'หิวชัน': 22, 'ไทรวมพลัง': 87, 'ก้าวอิสระ': 28, 'ปวงชนไทย': 51, 'วิชชั่นใหม่': 58, 'เพื่อชีวิตใหม่': 48, 'คลองไทย': 72, 'ประชาธิปัตย์': 3785, 'ไทยก้าวหน้า': 171, 'ไทยภักดี': 581, 'แรงงานสร้างชาติ': 102, 'ประชากรไทย': 119, 'ครูไทยเพื่อประชาชน': 78, 'ประชาชาติ': 156, 'สร้างอนาคตไทย': 257, 'รักชาติ': 200, 'ไทยพร้อม': 157, 'ภูมิใจไทย': 24058, 'พลังธรรมใหม่': 276, 'กรีน': 63, 'ไทยธรรม': 59, 'แผ่นดินธรรม': 25, 'กล้าธรรม': 113, 'พลังประชาธิปไตย': 162, 'โอกาสใหม่': 97, 'เป็นธรรม': 98, 'ประชาชน': 40508, 'ประชาไทย': 207, 'ไทยสร้างไทย': 301, 'ไทยก้าวใหม่': 279, 'ประชาอาสาชาติ': 11, 'พร้อม': 57, 'เครือข่ายชาวนาแห่งประเทศไทย': 111, 'ไทยพิทักษ์ธรรม': 13, 'ความหวังใหม่': 36, 'ไทยรวมไทย': 19, 'เพื่อบ้านเมือง': 32, 'พลังไทยรักชาติ': 69}

Processing:  70%|███████   | 210/300 [22:53<15:19, 10.22s/doc]

party_list_14_4 {'ไทยทรัพย์ทวี': 350, 'เพื่อชาติไทย': 1572, 'มิติใหม่': 2612, 'รวมใจไทย': 959, 'รวมไทยสร้างชาติ': 2114, 'พลวัต': 159, 'ประชาธิปไตยใหม่': 591, 'เพื่อไทย': 10342, 'ทางเลือกใหม่': 653, 'เศรษฐกิจ': 3898, 'เสรีรวมไทย': 571, 'รวมพลังประชาชน': 712, 'ท้องที่ไทย': 41, 'อนาคตไทย': 100, 'พลังเพื่อไทย': 166, 'ไทยชนะ': 111, 'พลังสังคมใหม่': 34, 'สังคมประชาธิปไตยไทย': 33, 'พิวชัน': 44, 'ไทรวมพลัง': 61, 'ก้าวอิสระ': 34, 'ปวงชนไทย': 53, 'วิชชั่นใหม่': 54, 'เพื่อชีวิตใหม่': 25, 'คลองไทย': 45, 'ประชาธิปไตย': 3649, 'ไทยก้าวหน้า': 174, 'ไทยภักดี': 575, 'แรงงานสร้างชาติ': 115, 'ประชากรไทย': 141, 'ครูไทยเพื่อประชาชน': 115, 'ประชาชาติ': 238, 'สร้างอนาคตไทย': 243, 'รักชาติ': 106, 'ไทยพร้อม': 296, 'ภูมิใจไทย': 29154, 'พลังธรรมใหม่': 118, 'กรีน': 69, 'ไทยธรรม': 45, 'แผ่นดินธรรม': 32, 'กล้าธรรม': 137, 'พลังประชารัฐ': 213, 'โอกาสใหม่': 1233, 'เป็นธรรม': 65, 'ประชาชน': 42043, 'ประชาไทย': 222, 'ไทยสร้างไทย': 384, 'ไทยก้าวใหม่': 318, 'ประชาอาสาชาติ': 9, 'พร้อม': 86, 'เครือข่ายชาวนาแห่งประเทศไทย': 34, 'ไทยพิทักษ์ธรรม': 16, 'ความหวั่งใหม่': 51, 'ไทยรวมไทย': 14, 'เพื่อบ้านเมือง': 24, 'พลังไทยรักชาติ': 57}

Processing:  70%|███████   | 211/300 [23:06<16:10, 10.90s/doc]

party_list_14_5 {'ไทยทรัพย์ทวี': 278, 'เพื่อชาติไทย': 1531, 'มิติไพม่': 431, 'รวมใจไทย': 464, 'รวมไทยสร้างชาติ': 3644, 'พลวัด': 1778, 'ประชาธิปไตยไพม่': 535, 'เพื่อไทย': 16684, 'ทางเลือกไพม่': 569, 'เศรษฐกิจ': 2363, 'รวมพลังประชาชน': 700, 'ท้องที่ไทย': 384, 'อนาคตไทย': 87, 'พลังเพื่อไทย': 303, 'ไทยชนะ': 137, 'พลังสังคมไพม่': 23, 'สังคมประชาธิปไตยไทย': 39, 'พิวชั่น': 34, 'ไทยรวมพลัง': 41, 'ก้าวอิสระ': 35, 'ปวงชนไทย': 68, 'วิชชั่นไพม่': 61, 'เพื่อชีวิตไพม่': 31, 'คลองไทย': 74, 'ประชาธิปไตย': 3487, 'ไทยก้าวหน้า': 148, 'ไทยภักดี': 510, 'แรงงานสร้างชาติ': 73, 'ประชากรไทย': 161, 'ครูไทยเพื่อประชาชน': 105, 'ประชาชาติ': 172, 'สร้างอนาคตไทย': 143, 'รักชาติ': 178, 'ไทยพร้อม': 721, 'ภูมิใจไทย': 27038, 'พลังประชาชน': 185, 'ไทยธรรม': 42, 'แผ่นดินธรรม': 26, 'กล้าครรรม': 121, 'พลังประชารัฐ': 177, 'โอกาสไพม่': 80, 'เป็นธรรม': 54, 'ประชาชน': 30671, 'ประชาไทย': 234, 'ไทยสร้างไทย': 428, 'ไทยก้าวใหม่': 185, 'ประชาอาสาชาติ': 10, 'พร้อม': 96, 'เครือข่ายชาวนาแห่งประเทศไทย': 83, 'ไทยพิทักษ์ธรรม': 14, 'ความหวังไพม่': 18, 'ไทยรวมไทย': 30, 'เพื่อบ้านเมือง': 25, 'พลังไทยรักชาติ': 79}

Processing:  71%|███████   | 212/300 [23:17<16:23, 11.17s/doc]

party_list_15_1 {'เพื่อขายไทย': 12015, 'มิติใหม่': 1518, 'รวมใจไทย': 574, 'รวมไทยสร้างชาติ': 1493, 'ประชาธิปไตยใหม่': 473, 'เพื่อไทย': 7404, 'เศรษฐกิจ': 2239, 'เสรีรวมไทย': 456, 'รวมพลังประชาชน': 414, 'ท้องที่ไทย': 35, 'อนาคตไทย': 56, 'พลังเพื่อไทย': 719, 'ไทยชนง': 100, 'สังคมประชาธิปไตยไทย': 27, 'ฟิวชัน': 30, 'ไตรวมพลัง': 52, 'ก๊าวอิสระ': 21, 'ปวดชนไทย': 43, 'วิชชั้นใหม่': 31, 'เพื่อชีวิตใหม่': 46, 'ประชาธิปไตย': 2743, 'ไทยก้าวหน้า': 39, 'ไทยภัยดี': 561, 'แรงงานสร้างชาติ': 63, 'ประชากรไทย': 130, 'ครูไทยเพื่อประชาชน': 87, 'ประชาชาติ': 211, 'สร้างอนาคตไทย': 214, 'รักชาติ': 172, 'ไทยพร้อม': 170, 'ภูมิใจไทย': 29240, 'พลังธรรมใหม่': 124, 'กรีน': 50, 'ไทยธรรม': 34, 'แผ่นดินธรรม': 22, 'กล้าวธรรม': 102, 'พลังประชาธิปไตย': 153, 'โอกาสใหม่': 210, 'เป็นธรรม': 44, 'ประชาชน': 25348, 'ประชาไทย': 177, 'ไทยสร้างไทย': 256, 'ไทยก้าวใหม่': 186, 'ประชาอาสาชาติ': 6, 'พร้อม': 44, 'ไทยพิทักษ์ธรรม': 5, 'ความหวังใหม่': 15, 'ไทยรวมไทย': 13, 'เพื่อบ้านเมือง': 34, 'พลังไทยรักชาติ': 42}

Processing:  71%|███████   | 213/300 [23:27<15:22, 10.60s/doc]

party_list_15_2 {'ไทยพร้อมทิวี': 421, 'เพื่อชาติไทย': 4104, 'มิติใหม่': 190, 'รวมใจไทย': 573, 'รวมไทยสร้างชาติ': 1316, 'พลวัต': 33, 'ประชาธิปไตยใหม่': 535, 'เพื่อไทย': 8274, 'ทางเลือกใหม่': 418, 'เศรษฐกิจ': 2314, 'รวมพลังประชาชน': 413, 'ท้องที่ไทย': 55, 'อนาคตไทย': 58, 'พลังเพื่อไทย': 160, 'พลังสังคมใหม่': 17, 'สังคมประชาธิปไตยไทย': 23, 'ฟิวชัน': 31, 'ใครวมพลัง': 100, 'ก้าวอิสระ': 35, 'ปวดชนไทย': 72, 'วิชชั่นใหม่': 59, 'เพื่อชีวิตใหม่': 28, 'คลองไทย': 57, 'ประชาธิปไตย': 2461, 'ไทยก้าวหน้า': 172, 'ไทยภักดี': 413, 'แรงงานสร้างชาติ': 159, 'ประชากรไทย': 314, 'ครูไทยเพื่อประชาชน': 268, 'ประชาชาติ': 314, 'สร้างอนาคตไทย': 359, 'รักชาติ': 167, 'ไทยพร้อม': 174, 'ภูมิใจไทย': 29687, 'พลังธรรมใหม่': 191, 'กรีน': 67, 'ไทยธรรม': 59, 'แผ่นดินธรรม': 26, 'กล้าอรวม': 88, 'พลังประชาธิปไตย': 125, 'โอกาสใหม่': 46, 'เป็นธรรม': 524, 'ประชาชน': 21563, 'ประชาไทย': 165, 'ไทยสร้างไทย': 205, 'ไทยก้าวใหม่': 148, 'ประชาลาสาขาติ': 8, 'พร้อม': 41, 'เครือข่ายชาวบ้านต่างประเทศไทย': 55, 'ไทยพิทักษ์ธรรม': 10, 'ความหวังใหม่': 17, 'ไทยรวมไทย': 8, 'เพื่อบ้านเมือง': 41, 'พลังไทยรักชาติ': 63}

Processing:  71%|███████▏  | 214/300 [23:38<15:32, 10.85s/doc]

party_list_16_1 {'ประชาชน': 32064, 'ภูมิใจไทย': 22112, 'เพื่อไทย': 12861, 'เศรษฐกิจ': 5012, 'ประชาธิปไตย': 4144, 'ประชาธิปไตยใหม่': 1440, 'ทางเลือกใหม่': 2444, 'รวมไทยสร้างชาติ': 2688, 'โอกาสใหม่': 2114, 'เพื่อชาติไทย': 1111, 'ไทยเกิดดี': 741, 'รวมใจไทย': 722, 'รวมพลังประชาชน': 658, 'ไทยสร้างไทย': 581, 'กล้ากรรม': 544, 'พลังประชาธิปไตย': 526, 'ไทยก้าวใหม่': 481, 'เสร็จรวมไทย': 560, 'ไทยพรัพย์ทวี': 116, 'พลังธรรมใหม่': 126, 'ไทยพร้อม': 285, 'พลังเพื่อไทย': 276, 'มิติใหม่': 224, 'ไทยก้าวหน้า': 208, 'พลวัต': 205, 'ประชากรไทย': 189, 'ประชาไทย': 177, 'ไทยชนะ': 171, 'แรงงานสร้างชาติ': 167, 'อนาคตไทย': 166, 'รักชาติ': 166, 'ประชาชาติ': 156, 'กรีน': 150, 'สร้างอนาคตไทย': 149, 'ครูไทยเพื่อประชาชน': 137, 'ห้องพี่ไทย': 137, 'ปวงชนไทย': 109, 'พร้อม': 100, 'วิชชั่นใหม่': 46, 'ไทยธรรม': 44, 'พลังไทยรักชาติ': 82, 'คอยงไทย': 75, 'เป็นธรรม': 71, 'ก้าวอิสระ': 68, 'พลังสังคมใหม่': 60, 'ความหวังใหม่': 60, 'ฟิวชัน': 56, 'สังคมประชาธิปไตยไทย': 51, 'แผ่นดินธรรม': 50, 'เพื่อชีวิตใหม่': 47, 'เพื่อบ้านเมือง': 46, 'เครือช่วยชาวนาแห่ลประเพณีไทย': 29, 'ไทยพิทักษ์ธรรม': 22, 'ไทยรวมไทย': 17, 'ประชาชนชาติ': 16}

Processing:  72%|███████▏  | 215/300 [23:49<15:29, 10.94s/doc]

party_list_16_2 {'ไทยพร้อมลำไส้': 573, 'เพื่อชาติต่อ': 1611, 'มิติใหม่': 254, 'รวมใจไทย': 2562, 'รวมไทยสร้างชาติ': 2614, 'ประชาธิปไตยใหม่': 687, 'เพื่อไทย': 15317, 'เศรษฐกิจ': 4064, 'เสร็จรวมไทย': 172, 'รวมพลังประชาชน': 577, 'ท้องที่ไทย': 176, 'อนาคตไทย': 92, 'พลังเพื่อไทย': 218, 'ไทยชนะ': 119, 'พลังสังคมใหม่': 29, 'สังคมประชาธิปไตยไทย': 48, 'ฟิวชัน': 52, 'ไทรวมพลัง': 69, 'ก้าวอิสระ': 29, 'ปวงชนไทย': 136, 'วิชชั่นใหม่': 48, 'เพื่อชีวิตใหม่': 29, 'คลองไทย': 81, 'ประชาธิปัตย์': 5174, 'ไทยก้าวหน้า': 187, 'ไทยภักดี': 767, 'แรงงานสร้างชาติ': 108, 'ประชากรไทย': 162, 'ครูไทยเพื่อประชาชน': 266, 'ประชาชาติ': 208, 'สร้างอนาคตไทย': 209, 'รักชาติ': 250, 'ไทยพร้อม': 173, 'ภูมิใจไทย': 30490, 'พลังธรรมใหม่': 222, 'กรีน': 133, 'ไทยธรรม': 40, 'แผ่นดินธรรม': 12, 'กล้าอรรม': 127, 'พลังประชาธิปไตย': 442, 'โอกาสใหม่': 300, 'เป็นธรรม': 150, 'ประชาชน': 33148, 'ประชาไทย': 174, 'ไทยสร้างไทย': 464, 'ไทยกาวใหม่': 284, 'ประชาอาสาชาติ': 14, 'พร้อม': 94, 'เครือขายชาวนาแทเประเทศไทย': 21, 'ไทยพิทักษ์ธรรม': 14, 'ความหวังใหม่': 23, 'ไทยรวมไทย': 29, 'เพื่อบ้านเมือง': 49, 'พลังไทยรักชาติ': 69}

Processing:  72%|███████▏  | 216/300 [23:59<14:50, 10.60s/doc]

party_list_16_3 {'ไอยพรัพย์ทวี': 150, 'เพื่อชาติโดย': 4526, 'รวมใจไทย': 755, 'รวมไทยสร้างชาติ': 5153, 'ประชาธิปไตยใหม่': 866, 'พรรคเพื่อไทย': 17577, 'พรรคทางเลือกใหม่': 541, 'เศรษฐกิจ': 1760, 'เสรีรวมไทย': 187, 'รวมพลังประชาชน': 647, 'ท้องที่ไทย': 117, 'อนาคตไทย': 34, 'พลังเพื่อไทย': 289, 'ไทยชนะ': 188, 'พรรคสังคมใหม่': 48, 'สังคมประชาธิปไตยไทย': 46, 'ไตรวมพลัง': 56, 'ปวเชนไทย': 118, 'วิชชั่นใหม่': 72, 'เพื่อชีวิตใหม่': 26, 'ประชาธิปัตย์': 3535, 'ไทยก้าวหน้า': 145, 'ไทยภักดี': 468, 'แรงงานสร้างชาติ': 170, 'ประชากรไทย': 310, 'ครูไทยเพื่อประชาชน': 353, 'ประชาชาติ': 358, 'สร้างอนาคตไทย': 338, 'รักชาติ': 357, 'ไตรพร้อม': 720, 'ภูมิใจไทย': 23534, 'พลังธรรมใหม่': 382, 'กรีน': 86, 'ไทยธรรม': 64, 'แผ่นดินธรรม': 25, 'กล้ารรรณ': 231, 'พลังประชารัฐ': 457, 'โยกาศใหม่': 245, 'เป็นธรรม': 87, 'ประชาชน': 25904, 'ประชาไทย': 164, 'ไทยสร้างไทย': 381, 'ไทยก้าวใหม่': 263, 'ประชาดาสาขาติ': 8, 'พร้อม': 74, 'เครือข่ายชาวนามส่งประเพศไทย': 91, 'ความพร้อม': 26, 'ไทยรวมไทย': 18, 'เพื่อบ้านเมือง': 50, 'พลังไทยรักชาติ': 80}

Processing:  72%|███████▏  | 217/300 [24:10<14:54, 10.78s/doc]

party_list_16_4 {'ไทยทวีพย์ทวี': 346, 'เพื่อชาติไทย': 1313, 'มิติใหม่': 224, 'รวมใจไทย': 722, 'รวมไทยสร้างชาติ': 2688, 'พลวัต': 205, 'ประชาธิปไตยใหม่': 3440, 'เพื่อไทย': 12883, 'ทางเลือกใหม่': 2759, 'เศรษฐกิจ': 5012, 'เสร็จรวมไทย': 460, 'รวมพลังประชาชน': 658, 'ท้องที่ไทย': 117, 'อนาคตไทย': 166, 'พลังเพื่อไทย': 276, 'พลังสังคมใหม่': 60, 'สังคมประชาธิปไตยไทย': 51, 'ทิวชัน': 56, 'โทรวมพลัง': 92, 'ก้าวอิสระ': 68, 'ปวงชนไทย': 109, 'วิชชั่นใหม่': 96, 'เพื่อชีวิตใหม่': 47, 'คลองไทย': 35, 'ประชาธิปัตย์': 4149, 'ไทยก้าวหน้า': 208, 'ไทยภักดี': 343, 'แรงงานสร้างชาติ': 169, 'ประชากรไทย': 189, 'ครูไทยเพื่อประชาชน': 137, 'ประชาชาติ': 156, 'สร้างอนาคตไทย': 149, 'รักชาติ': 166, 'ไทยพร้อม': 235, 'ภูมิใจไทย': 22112, 'พลังธรรมใหม่': 320, 'กรีน': 150, 'ไทยธรรม': 94, 'แม่แดินธรรม': 50, 'กล้าธรรม': 544, 'พลังประชาธิปไตย': 526, 'โอกาสใหม่': 2134, 'เป็นธรรม': 31, 'ประชาชน': 32064, 'ประชาไทย': 177, 'ไทยสร้างไทย': 581, 'ไทยก้าวใหม่': 483, 'ประชาอาสาชาติ': 16, 'พร้อม': 100, 'เครือข่ายชาวนาแห่งประเทศไทย': 27, 'ไทยพิทักษ์ธรรม': 22, 'ความหวังใหม่': 60, 'ไทยรวมไทย': 17, 'เพื่อบ้านเมือง': 46, 'พลังไทยรักชาติ': 82}

Processing:  73%|███████▎  | 218/300 [24:22<15:13, 11.14s/doc]

party_list_17_1 {'ไทยพรัพย์ทวี': 308, 'เพื่อชาติไทย': 1357, 'มีติใหม่': 604, 'รวมใจไทย': 4215, 'รวมไทยสร้างชาติ': 278, 'พลวัต': 130, 'ประชาธิปไตยใหม่': 551, 'เพื่อไทย': 13590, 'ทางเลือกใหม่': 672, 'เศรษฐกิจ': 4179, 'รวมพลังประชาชน': 589, 'ท้องที่ไทย': 318, 'อนาคตไทย': 148, 'พลังเพื่อไทย': 226, 'พลังสังคมใหม่': 41, 'สังคมประชาธิปไตยไทย': 58, 'ฟิวชัน': 41, 'ไทรวมพลัง': 56, 'ก้าวอิสระ': 45, 'ปวงชนไทย': 160, 'วิชชั่นใหม่': 80, 'เพื่อชีวิตใหม่': 127, 'คลองไทย': 80, 'ประชาธิปไตย': 4553, 'ไทยก้าวหน้า': 134, 'ไทยภักดี': 882, 'แรงงานสร้างชาติ': 125, 'ประชากรไทย': 175, 'ครูไทยเพื่อประชาชน': 181, 'ประชาชาติ': 433, 'สร้างอนาคตไทย': 481, 'รักชาติ': 10196, 'ไทยพร้อม': 342, 'ภูมิใจไทย': 25435, 'พลังธรรมใหม่': 232, 'กรีน': 82, 'ไทยธรรม': 70, 'แผ่นดินธรรม': 44, 'กล้าธรรม': 200, 'พลังประชาธิปไตย': 307, 'โอกาสใหม่': 116, 'เป็นธรรม': 139, 'ประชาชน': 36568, 'ประชาไทย': 353, 'ไทยสร้างไทย': 439, 'ไทยก้าวใหม่': 304, 'ประชาอาสาชาติ': 11, 'พร้อม': 78, 'เครือข่ายชาวนาแห่งประเทศไทย': 174, 'ไทยพิทักษ์ธรรม': 64, 'ความหวังใหม่': 44, 'ไทยรวมไทย': 44, 'เพื่อบ้านเมือง': 62, 'พลังไทยรักชาติ': 734}

Processing:  73%|███████▎  | 219/300 [24:36<15:55, 11.79s/doc]

party_list_18_1 {'ไทยทรัพย์ทวี': 328, 'เพื่อชาติไทย': 1836, 'รวมใจไทย': 1235, 'รวมไทยสร้างชาติ': 2344, 'พลวัต': 138, 'ประชาธิปไตยไทม์': 762, 'เพื่อไทย': 14355, 'ทางเลือกไทม์': 616, 'เศรษฐกิจ': 3403, 'เสรีรวมไทย': 616, 'รวมพลังประชาชน': 842, 'ห้องที่ไทย': 180, 'อนาคตไทย': 37, 'พลังเพื่อไทย': 223, 'ไทยชนะ': 146, 'พลังสังคมไทม์': 30, 'สังคมประชาธิปไตยไทย': 38, 'ฟิวชัน': 33, 'ไทรวิมพลัง': 46, 'ก้าวอิสระ': 44, 'ปวงชนไทย': 35, 'วิชชั่นไทม์': 82, 'เพื่อชีวิตไทม์': 44, 'คลองไทย': 105, 'ประชาธิปัตย์': 7788, 'ไทยก้าวหน้า': 146, 'ไทยภักดี': 701, 'แรงงานสร้างชาติ': 114, 'ประชากรไทย': 181, 'ครูไทยเพื่อประชาชน': 241, 'ประชาชาติ': 223, 'สร้างอนาคตไทย': 161, 'รักชาติ': 184, 'ไทยพร้อม': 123, 'ภูมิใจไทย': 14665, 'พลังธรรมไทม์': 189, 'กรีน': 72, 'ไทยธรรม': 53, 'แผ่นดินธรรม': 33, 'กล้าธรรม': 136, 'พลังประชารัฐ': 253, 'เป็นธรรม': 119, 'ประชาชน': 27137, 'ประชาไทย': 169, 'ไทยสร้างไทย': 328, 'ไทยก้าวไทม์': 206, 'ประชาอาสาชาติ': 12, 'พร้อม': 34, 'เครือข่ายชาวบ้านเร่งประเพศไทย': 36, 'ไทยพิทักษ์ธรรม': 14, 'ความหวังไทม์': 24, 'ไทยรวมไทย': 21, 'เพื่อบ้านเมือง': 38, 'พลังไทยรักชาติ': 85}

Processing:  73%|███████▎  | 220/300 [24:46<15:04, 11.31s/doc]

party_list_18_2 {'ไทยทรัพย์ทวี': 3159, 'เพื่อชาติไทย': 2469, 'มิติใหม่': 616, 'รวมใจไทย': 825, 'รวมไทยสร้างชาติ': 3564, 'พลวัต': 134, 'ประชาธิปไตยใหม่': 758, 'เพื่อไทย': 9073, 'ทางเลือกใหม่': 470, 'เศรษฐกิจ': 3154, 'เสรีรวมไทย': 585, 'รวมพลังประชาชน': 628, 'ท้องที่ไทย': 104, 'อนาคตไทย': 77, 'พลังเพื่อไทย': 185, 'ไทยชนะ': 212, 'พลังสังคมใหม่': 48, 'สังคมประชาธิปไตยไทย': 24, 'ทิวชัน': 29, 'ไทรวมพลัง': 33, 'ก้าวอิสระ': 39, 'ปวงชนไทย': 104, 'วิชชนใหม่': 78, 'เพื่อชีวิตใหม่': 12, 'คลองไทย': 105, 'ประชาธิปไตย': 5061, 'ไทยก้าวหน้า': 227, 'ไทยภักดี': 483, 'แรงงานสร้างชาติ': 440, 'ประชากรไทย': 394, 'ครูไทยเพื่อประชาชน': 196, 'ประชาชาติ': 209, 'สร้างอนาคตไทย': 226, 'รักชาติ': 204, 'ไทยพร้อม': 196, 'ภูมิใจไทย': 26315, 'พลังธรรมใหม่': 229, 'กรีน': 64, 'ไทยธรรม': 78, 'แผ่นดินธรรม': 41, 'กล้าธรรม': 245, 'พลังประชารัฐ': 268, 'โอกาสใหม่': 60, 'เป็นธรรม': 88, 'ประชาชน': 22973, 'ประชาไทย': 212, 'ไทยสร้างไทย': 365, 'ไทยก้าวใหม่': 205, 'ประชาอาสาชาติ': 19, 'พร้อม': 51, 'เครือข่ายชาวนาแห่งประเทศไทย': 29, 'ไทยพิทักษ์ธรรม': 11, 'ความหวังใหม่': 23, 'ไทยรวมไทย': 28, 'เพื่อป้านเมือง': 63, 'พลังไทยรักชาติ': 72}

Processing:  74%|███████▎  | 221/300 [24:59<15:37, 11.86s/doc]

party_list_19_1 {'พรรคเพื่อชาติไทย': 956, 'พรรคใหม่': 903, 'พรรครวมใจไทย': 3784, 'พรรครวมไทยเสร็จชาติ': 2182, 'พรรคประชาธิปไตยใหม่': 456, 'พรรคเพื่อไทย': 12778, 'พรรคทางเลือกใหม่': 504, 'พรรคเศรษฐกิจ': 4263, 'พรรครวมพลังประชาชน': 541, 'พรรคธนาคตไทย': 76, 'พรรคพลังเพื่อไทย': 161, 'พรรคพลังสังคมใหม่': 26, 'พรรคสังคมประชาธิปไตยไทย': 29, 'พรรคฟิวชัน': 33, 'พรรคไตรวมพลัง': 45, 'พรรควิชชั่นใหม่': 51, 'พรรคเพื่อชีวิตใหม่': 34, 'พรรคตลองไทย': 55, 'พรรคประชาธิปัตย์': 4434, 'พรรคไทยก้าวหน้า': 180, 'พรรคไทยภักดี': 730, 'พรรคแรงงานสร้างชาติ': 101, 'พรรคประชากรไทย': 140, 'พรรคครูไทยเพื่อประชาชน': 69, 'พรรคประชาชาติ': 115, 'พรรคสร้างธนาคตไทย': 150, 'พรรครักชาติ': 154, 'พรรคไทยพร้อม': 96, 'พรรคภูมิใจไทย': 18236, 'พรรคพลังธรรมใหม่': 196, 'พรรคไทยธรรม': 35, 'พรรคกล้าถรรม': 185, 'พรรคโอกาสใหม่': 57, 'พรรคเป็นธรรม': 69, 'พรรคประชาชน': 34618, 'พรรคประชาธิปไตย': 278, 'พรรคไทยสร้างไทย': 481, 'พรรคพร้อม': 61, 'พรรคเครือข่ายชาวนาแห่งประเทศไทย': 21, 'พรรคไทยพิทักษ์ธรรม': 14, 'พรรคความหวังใหม่': 13, 'พรรคไทยรวมไทย': 20, 'พรรคเพื่อบ้านเมือง': 41, 'พรรคพลังไทยรักชาติ': 80}

Processing:  74%|███████▍  | 222/300 [25:09<14:43, 11.33s/doc]

party_list_19_2 {}

Processing:  74%|███████▍  | 223/300 [25:21<14:42, 11.47s/doc]

party_list_19_3 {'ไทยทรัพย์ทวี': 241, 'เพื่อชาติไทย': 1896, 'รวมใจไทย': 4914, 'รวมไทยสร้างชาติ': 2094, 'พลวัต': 106, 'ประชาธิปไตยไทม์': 784, 'เพื่อไทย': 9516, 'ทางเลือกไทม์': 541, 'เศรษฐกิจ': 3977, 'รวมพลังประชาชน': 733, 'ท้องฟีไทย': 68, 'อนาคตไทย': 96, 'หลังเพื่อไทย': 210, 'สังคมประชาธิปไตยไทย': 43, 'ฟิวชัน': 38, 'ไทรวมพลัง': 31, 'ก้าวอิสระ': 42, 'ปวงชนไทย': 80, 'วิชชั่นไทม์': 47, 'เพื่อชีวิตไทม์': 55, 'คลองไทย': 66, 'ประชาธิปไตย': 4543, 'ไทยก้าวหน้า': 132, 'ไทยภักดี': 595, 'แรงงานสร้างชาติ': 118, 'ประชากรไทย': 195, 'ครูไทยเพื่อประชาชน': 117, 'ประชาชาติ': 125, 'สร้างอนาคตไทย': 269, 'รักชาติ': 183, 'ไทยพร้อม': 116, 'ภูมิใจไทย': 20026, 'พลังธรรมไทม์': 132, 'กรีน': 65, 'ไทยธรรม': 37, 'แผ่นดินธรรม': 21, 'กล้าธรรม': 162, 'พลังประชาธิปไตย': 175, 'เป็นธรรม': 83, 'ประชาชน': 34702, 'ประชาไทย': 153, 'ไทยสร้างไทย': 373, 'ไทยก้าวไทม์': 266, 'ประชาอาสาชาติ': 12, 'พร้อม': 66, 'เครือข่ายชาวนาแห่งประเทศไทย': 79, 'ไทยพิทักษ์ธรรม': 17, 'ความหวังไทม์': 29, 'ไทยรวมไทย': 18, 'เพื่อบ้านเมือง': 32, 'พลังไทยรักชาติ': 90}

Processing:  75%|███████▍  | 224/300 [25:33<14:37, 11.54s/doc]

party_list_19_4 {'ไทยพร้อมทัวร์': 116, 'เพื่อชาติไทย': 1580, 'มิติไหม่': 172, 'รวมใจไทย': 5400, 'รวมไทยสร้างชาติ': 2422, 'ประชาธิปไตยไหม่': 572, 'เพื่อไทย': 10301, 'ทางเลือกไหม่': 643, 'เศรษฐกิจ': 4162, 'เสร็จรวมไทย': 577, 'รวมพลังประชาชน': 969, 'ท้องที่ไทย': 80, 'อนาคตไทย': 147, 'พลังเพื่อไทย': 271, 'พลังสังคมไหม่': 36, 'สังคมประชาธิปไตยไทย': 41, 'พิวชัน': 42, 'ใครวมพลัง': 60, 'ก้าวอิสระ': 76, 'ปวงชนไทย': 67, 'วิชั่นไหม่': 88, 'เพื่อชีวิตไหม่': 54, 'ตลอดไทย': 91, 'ประชาธิปไตย': 5280, 'ไทยก้าวหน้า': 221, 'ไทยภักดี': 711, 'แรงงานสร้างชาติ': 147, 'ประชากรไทย': 172, 'ครูไทยเพื่อประชาชน': 128, 'ประชาชาติ': 159, 'สร้างอนาคตไทย': 288, 'รักชาติ': 257, 'ไทยพร้อม': 150, 'ภูมิใจไทย': 12817, 'พลังธรรมไหม่': 177, 'กรีน': 56, 'ไทยธรรม': 91, 'แผ่นดินธรรม': 47, 'กล้าธรรม': 2238, 'พลังประชารัฐ': 285, 'โอกาสไหม่': 77, 'เป็นธรรม': 252, 'ประชาชน': 34034, 'ประชาไทย': 174, 'ไทยสร้างไทย': 479, 'ไทยก้าวไหม่': 358, 'ประชาอาสาชาติ': 17, 'พร้อม': 110, 'เครือข่ายชาวนาแห่งประเทศไทย': 27, 'ไทยพิทักษ์ธรรม': 10, 'ความหวังไหม่': 37, 'ไทยรวมไทย': 33, 'เพื่อบ้านเมือง': 48, 'พลังไทยรักชาติ': 120}

Processing:  75%|███████▌  | 225/300 [25:45<14:38, 11.71s/doc]

party_list_20_1 {}

Processing:  75%|███████▌  | 226/300 [25:54<13:38, 11.06s/doc]

party_list_20_10 {'เพื่อขาดไทย': 1671, 'รวมใจไทย': 674, 'รวมไทยสร้างชาติ': 2517, 'พลวัต': 872, 'ประชาธิปไตยไหม': 724, 'เพื่อไทย': 7353, 'ทางเลือกไหม': 572, 'เศรษฐกิจ': 4210, 'เสรีรวมไทย': 682, 'รวมพลังประชาชน': 488, 'ท้องที่ไทย': 41, 'อนาคตไทย': 72, 'พลังเพื่อไทย': 134, 'ไทยชนะ': 76, 'พลังสังคมไหม': 34, 'สังคมประชาธิปไตยไทย': 24, 'ฟิวชัน': 45, 'ก้าวอิสระ': 26, 'ปวงชนไทย': 52, 'วิชชั่นไหม': 28, 'เพื่อชีวิตไหม': 10, 'ประชาธิปัตย์': 4540, 'ไทยก้าวหน้า': 127, 'ไทยภักดี': 880, 'แรงงานสร้างชาติ': 62, 'ประชากรไทย': 108, 'ครูไทยเพื่อประชาชน': 82, 'ประชาชาติ': 106, 'สร้างอนาคตไทย': 69, 'รักชาติ': 125, 'ไทยพร้อม': 105, 'ภูมิใจไทย': 19065, 'พลังธรรมไหม': 63, 'กรีน': 50, 'ไทยธรรม': 39, 'แผ่นดินธรรม': 33, 'กล้าธรรม': 1508, 'พลังประชารัฐ': 244, 'โอกาสไหม': 27, 'ปรับธรรม': 30, 'ประชาชน': 33067, 'ประชาไทย': 133, 'ไทยสร้างไทย': 544, 'ไทยก้าวไหม': 309, 'ประชาอาสาชาติ': 6, 'พร้อม': 63, 'เครือข่ายชาวนาแห่งประเทศไทย': 24, 'ไทยพิทักษ์ธรรม': 12, 'ความหวังไหม': 28, 'ไทยรวมไทย': 11, 'เพื่อบ้านเมือง': 18, 'พลังไทยรักชาติ': 30}

Processing:  76%|███████▌  | 227/300 [26:03<12:36, 10.36s/doc]

party_list_20_2 {'เพื่อชาติไทย': 410, 'รวมใจไทย': 722, 'รวมไทยสร้างชาติ': 2049, 'พลวัต': 80, 'ประชาธิปไตยไหม่': 458, 'เพื่อไทย': 4571, 'ทางเลือกไหม่': 402, 'เศรษฐกิจ': 2204, 'เสรีรวมไทย': 470, 'รวมพลังประชาชน': 289, 'ท้องที่ไทย': 20, 'อนาคตไทย': 34, 'พลังเพื่อไทย': 63, 'ไทยชนะ': 59, 'พลังสังคมไหม่': 11, 'สังคมประชาธิปไตยไทย': 136, 'หิวชัน': 11, 'ไทรวมพลัง': 32, 'ก้าวอิสระ': 14, 'ปวงชนไทย': 35, 'วิชชั่นไหม่': 17, 'เพื่อชีวิตไหม่': 11, 'คลองไทย': 12, 'ประชาธิปไตย': 7294, 'ไทยก้าวหน้า': 69, 'ไทยภักดี': 1146, 'แรงงานสร้างชาติ': 47, 'ประชากรไทย': 49, 'ครูไทยเพื่อประชาชน': 36, 'ประชาชาติ': 75, 'สร้างอนาคตไทย': 66, 'รักชาติ': 63, 'ไทยพร้อม': 81, 'ภูมิใจไทย': 21207, 'พลังธรรมไหม่': 49, 'กรีน': 34, 'ไทยธรรม': 17, 'แผ่นดินธรรม': 10, 'กล้าธรรม': 67, 'พลังประชาธิปไตย': 451, 'เป็นธรรม': 33, 'ประชาชน': 34047, 'ประชาไทย': 46, 'ไทยสร้างไทย': 330, 'ไทยก้าวไหม่': 255, 'ประชาอาสาชาติ': 1, 'พร้อม': 10, 'เครือข่ายชาวนาแท่งประเทศไทย': 15, 'ไทยพิทักษ์ธรรม': 5, 'ความหวังไหม่': 12, 'ไทยรวมไทย': 7, 'เพื่อบ้านเมือง': 12, 'พลังไทยรักชาติ': 27}

Processing:  76%|███████▌  | 228/300 [26:13<12:23, 10.32s/doc]

party_list_20_3 {'ไทยพร็พย์ทวี': 377, 'เพื่อชาติไทย': 3637, 'มิติใหม่': 156, 'รวมใจไทย': 674, 'รวมไทยสร้างชาติ': 2222, 'พลวัต': 105, 'ประชาธิปไตยใหม่': 470, 'เพื่อไทย': 5574, 'ทางเลือกใหม่': 481, 'เศรษฐกิจ': 3702, 'เสรีรวมไทย': 573, 'รวมพลังประชาชน': 506, 'ท้องที่ไทย': 110, 'อนาคตไทย': 59, 'พลังเพื่อไทย': 81, 'ไทยชนะ': 119, 'พลังสังคมใหม่': 19, 'สังคมประชาธิปไตยไทย': 192, 'ฟิวชัน': 25, 'ไทรวมพลัง': 56, 'ก้าวอิสระ': 40, 'ปวเชนไทย': 42, 'วิชชั่นใหม่': 41, 'เพื่อชีวิตใหม่': 17, 'คลองไทย': 64, 'ประชาธิปัตย์': 6541, 'ไทยก้าวหน้า': 121, 'ไทยภักดี': 718, 'แรงงานสร้างชาติ': 79, 'ประชากรไทย': 188, 'ครูไทยเพื่อประชาชน': 107, 'ประชาชาติ': 87, 'สร้างอนาคตไทย': 97, 'รักชาติ': 95, 'ไทยพร้อม': 111, 'ภูมิใจไทย': 21635, 'พลังธรรมใหม่': 62, 'กรีน': 45, 'ไทยธรรม': 27, 'แผ่นดินธรรม': 16, 'กล้าธรรม': 117, 'พลังประชาธิปไตย': 209, 'โอกาสใหม่': 19, 'เป็นธรรม': 48, 'ประชาชน': 40642, 'ประชาไทย': 166, 'ไทยสร้างไทย': 441, 'ไทยก้าวใหม่': 267, 'ประชาชนสาขาต': 3, 'พร้อม': 58, 'เครือข่ายชาวนาแห่งประเทศไทย': 6, 'ไทยพิทักษ์ธรรม': 11, 'ความหวังใหม่': 20, 'ไทยรวมไทย': 18, 'เพื่อบ้านเมือง': 46, 'พลังไทยรักชาติ': 39}

Processing:  76%|███████▋  | 229/300 [26:24<12:19, 10.42s/doc]

party_list_20_4 {'ไทเทรจิพย์ทวี': 245, 'เพื่อชาติไทย': 1341, 'รวมไอไทย': 4257, 'รวมไทยสร้างชาติ': 2246, 'พลวัค': 108, 'ประชาธิปไตยไทม์': 709, 'เพื่อไทย': 4918, 'ทางเลือกไทม์': 462, 'เศรษฐกิจ': 3589, 'เสรี่รวมไทย': 472, 'รวมพลังประชาชน': 548, 'ท้องที่ไทย': 41, 'อนาคตไทย': 64, 'พลังเพื่อไทย': 160, 'ไทยชนะ': 146, 'พลังสังคมไทม์': 31, 'สังคมประชาธิปไตยไทย': 64, 'ฟิวชัน': 29, 'ไทรวมพลัง': 59, 'ก้าวอิสระ': 48, 'ปวงชนไทย': 81, 'วิชชั่นไทม์': 59, 'เพื่อชีวิตไทม์': 44, 'คอองไทย': 116, 'ประชาธิปัตย์': 9646, 'ไทยก้าวหน้า': 109, 'ไทยภักดี': 748, 'แรงงานสร้างชาติ': 310, 'ประชากรไทย': 165, 'ครูไทยเพื่อประชาชน': 81, 'ประชาชาติ': 96, 'สร้างอนาคตไทย': 234, 'รักชาติ': 237, 'ไทยพร้อม': 110, 'ภูมิใจไทย': 20031, 'พลังธรรมไทม์': 88, 'กรีน': 42, 'ไทยธรรม': 66, 'แผ่นดินธรรม': 18, 'กล้าอรวม': 198, 'พลังประชาธิปไตย': 435, 'เป็นธรรม': 71, 'ประชาชน': 27214, 'ประชาไทย': 117, 'ไทยสร้างไทย': 205, 'ไทยก้าวไทม์': 201, 'ประชาชนชาติ': 8, 'พร้อม': 60, 'เครือข่ายชาวนาแห่งประเทศไทย': 16, 'ไทยพิทักษ์ธรรม': 9, 'ความหวังไทม์': 27, 'ไทยรวมไทย': 19, 'เพื่อบ้านเมือง': 55, 'พลังไทยรักชาติ': 61}

Processing:  77%|███████▋  | 230/300 [26:33<11:49, 10.14s/doc]

party_list_20_5 {}

Processing:  77%|███████▋  | 231/300 [26:43<11:32, 10.04s/doc]

party_list_20_6 {'เพื่อชาติไทย': 457, 'รวมใจไทย': 428, 'รวมไทยสร้างชาติ': 2468, 'พลวัต': 278, 'ประชาธิปไตยไทม์': 1814, 'เพื่อไทย': 5757, 'ทางเลือกไทม์': 435, 'เศรษฐกิจ': 3001, 'เสรีรวมไทย': 564, 'รวมพลังประชาชน': 508, 'ท้องฟีไทย': 24, 'อนาคตไทย': 65, 'พลังเพื่อไทย': 121, 'ไทยชนะ': 50, 'พลังสังคมไทม์': 38, 'สังคมประชาธิปไตยไทย': 76, 'ฟิวชัน': 19, 'ไทรวมพลัง': 52, 'ก้าวอิสระ': 27, 'ปวงชนไทย': 31, 'วิชชั่นไทม์': 37, 'เพื่อชีวิตไทม์': 17, 'คลองไทย': 38, 'ประชาธิปไตย': 5072, 'ไทยก้าวหน้า': 100, 'ไทยภักดี': 1306, 'แรงงานสร้างชาติ': 67, 'ประชากรไทย': 75, 'ครูไทยเพื่อประชาชน': 172, 'ประชาชาติ': 81, 'สร้างอนาคตไทย': 77, 'รักชาติ': 252, 'ไทยพร้อม': 114, 'ภูมิใจไทย': 22453, 'พลังธรรมไทม์': 117, 'กรีน': 35, 'ไทยธรรม': 34, 'แผ่นดินธรรม': 22, 'กล้าธรรม': 175, 'พลังประชาธิปไตย': 262, 'เป็นธรรม': 42, 'ประชาชน': 42133, 'ประชาไทย': 267, 'ไทยสร้างไทย': 425, 'ไทยก้าวไทม์': 325, 'พร้อม': 41, 'เครือข่ายชาวนาแห่งประเทศไทย': 13, 'ไทยพิทักษ์ธรรม': 6, 'ไทยรวมไทย': 13, 'เพื่อบ้านเมือง': 34, 'พลังไทยรักชาติ': 33}

Processing:  77%|███████▋  | 232/300 [26:53<11:11,  9.87s/doc]

party_list_20_7 {}

Processing:  78%|███████▊  | 233/300 [27:02<10:53,  9.76s/doc]

party_list_20_8 {'ไทยทรัพย์ทวี': 178, 'เพื่อชาติไทย': 704, 'รวมใจไทย': 3357, 'รวมไทยสร้างชาติ': 3876, 'ประชาธิปไตยไหม้': 442, 'เพื่อไทย': 6745, 'ทางเลือกไหม้': 418, 'เศรษฐกิจ': 3317, 'เสรีรวมไทย': 914, 'รวมพลังประชาชน': 538, 'ท้องฟีไทย': 44, 'อนาคตไทย': 71, 'พลังเพื่อไทย': 133, 'พลังสังคมไหม้': 27, 'สังคมประชาธิปไตยไทย': 38, 'ฟิวชัน': 20, 'สารวมพลัง': 46, 'ก้าวอิสระ': 66, 'ปวงชนไทย': 35, 'วิชชั่นไหม้': 37, 'เพื่อชีวิตไหม้': 25, 'คลองไทย': 49, 'ประชาธิปัตย์': 4521, 'ไทยก้าวหน้า': 135, 'ไทยภักดี': 835, 'แรงงานสร้างชาติ': 63, 'ประชากรไทย': 83, 'ครูไทยเพื่อประชาชน': 77, 'ประชาชาติ': 68, 'สร้างอนาคตไทย': 144, 'รักชาติ': 167, 'ไทยพร้อม': 208, 'ภูมิใจไทย': 21336, 'พลังธรรมไหม้': 88, 'กรีน': 55, 'ไทยธรรม': 27, 'แผ่นดินธรรม': 16, 'กล้าธรรม': 76, 'พลังประชารัฐ': 187, 'โอกาสไหม้': 29, 'เงินธรรม': 58, 'ประชาชน': 38807, 'ประชาไทย': 260, 'ไทยสร้างไทย': 407, 'ไทยก้าวไหม้': 266, 'ประชาอาสาชาติ': 10, 'พร้อม': 64, 'เครือข่ายชาวนาแห่งประเทศไทย': 10, 'ความหวังไหม้': 22, 'ไทยรวมไทย': 17, 'เพื่อบ้านเมือง': 28, 'พลังไทยรักชาติ': 46}

Processing:  78%|███████▊  | 234/300 [27:11<10:33,  9.59s/doc]

party_list_20_9 {'ไทยทรัพย์ทวี': 65, 'เพื่อชาติไทย': 373, 'รวมใจไทย': 516, 'รวมไทยสร้างชาติ': 1764, 'พลวัต': 62, 'ประชาธิปไตยใหม่': 1164, 'เพื่อไทย': 6067, 'ทางเลือกใหม่': 310, 'เศรษฐกิจ': 2314, 'เสรีรวมไทย': 442, 'รวมพลังประชาชน': 407, 'ท้องที่ไทย': 15, 'อนาคตไทย': 57, 'พลังเพื่อไทย': 111, 'ไทยชนะ': 39, 'พลังสังคมใหม่': 21, 'สังคมประชาธิปไตยไทย': 15, 'โทรวมพลัง': 24, 'ก้าวอิสระ': 19, 'ปวงชนไทย': 40, 'วิชชั้นใหม่': 13, 'เพื่อชีวิตใหม่': 20, 'ตลอดไทย': 30, 'ประชาธิปัตย์': 3508, 'ไทยก้าวหน้า': 112, 'ไทยภักดี': 741, 'แรงงานสร้างชาติ': 23, 'ประชากรไทย': 49, 'ครูไทยเพื่อประชาชน': 33, 'ประชาชาติ': 89, 'สร้างอนาคตไทย': 44, 'รักชาติ': 35, 'ไทยพร้อม': 58, 'ภูมิใจไทย': 14834, 'พลังธรรมใหม่': 77, 'กรีน': 32, 'แผ่นดินธรรม': 11, 'กล้าธรรม': 45, 'พลังประชารัฐ': 126, 'โอกาสใหม่': 31, 'เป็นธรรม': 55, 'ประชาชน': 30288, 'ประชาไทย': 70, 'ไทยสร้างไทย': 275, 'ไทยก้าวใหม่': 231, 'ประชาอาสาชาติ': 8, 'พร้อม': 44, 'เครือข่ายชาวนาแห่งประเทศไทย': 7, 'ไทยพิทักษ์ธรรม': 3, 'ความหรือใหม่': 18, 'โดยรวมไทย': 15, 'เพื่อบ้านเมือง': 9, 'พลังไทยรักชาติ': 21}

Processing:  78%|███████▊  | 235/300 [27:21<10:23,  9.59s/doc]

party_list_21_1 {'ไทยทรัพย์ทวี': 224, 'เพื่อชาติไทย': 445, 'รวมใจไทย': 3328, 'รวมไทยสร้างชาติ': 3357, 'ประชาธิปไตยใหม่': 629, 'เพื่อไทย': 4942, 'ทางเลือกใหม่': 423, 'เศรษฐกิจ': 2501, 'รวมพลังประชาชน': 346, 'ท้องที่ไทย': 13, 'อนาคตไทย': 53, 'พลังเพื่อไทย': 76, 'ไทยชนะ': 71, 'พลังสังคมใหม่': 11, 'สังคมประชาธิปไตยไทย': 28, 'ก้าวอิสระ': 11, 'ปวดชนไทย': 22, 'วิชชั่นใหม่': 48, 'เพื่อชีวิตใหม่': 34, 'ประชาธิปัตย์': 13500, 'ไทยก้าวหน้า': 112, 'ไทยเก้าดี': 658, 'แรงงานสร้างชาติ': 52, 'ประชากรไทย': 57, 'ครูไทยเพื่อประชาชน': 56, 'ประชาชาติ': 82, 'สร้างอนาคตไทย': 103, 'รักชาติ': 117, 'ไทยพร้อม': 32, 'ภูมิใจไทย': 17260, 'พลังธรรมใหม่': 154, 'กรีน': 37, 'ไทยธรรม': 17, 'แผ่นดินธรรม': 12, 'กล้าธรรม': 34, 'พลังประชาธิปไตย': 132, 'โอกาสใหม่': 31, 'เป็นธรรม': 38, 'ประชาชน': 40117, 'ประชาไทย': 120, 'ไทยสร้างไทย': 313, 'ไทยก้าวใหม่': 606, 'พร้อม': 53, 'ไทยพิทักษ์ธรรม': 8, 'ความหวังใหม่': 21, 'ไทยรวมไทย': 7, 'เพื่อบ้านเมือง': 62, 'พลังไทยรักชาติ': 62}

Processing:  79%|███████▊  | 236/300 [27:31<10:17,  9.65s/doc]

party_list_21_2 {'ไทยทรัพย์ทวี': 354, 'เพื่อชาติไทย': 666, 'มิติใหม่': 119, 'รวมใจไทย': 252, 'รวมไทยสร้างชาติ': 1689, 'พลวัต': 49, 'ประชาธิปไตยใหม่': 620, 'เพื่อไทย': 4021, 'ทางเลือกใหม่': 358, 'เศรษฐกิจ': 2249, 'เสรีรวมไทย': 355, 'รวมพลังประชาชน': 314, 'ท้องที่ไทย': 20, 'อนาคตไทย': 41, 'พลังเพื่อไทย': 31, 'ไทยชนะ': 68, 'พลังสังคมใหม่': 13, 'สังคมประชาธิปไตยไทย': 36, 'พิวชั่น': 17, 'ไทยรวมพลัง': 33, 'ก้าวอิสระ': 12, 'ปวงชนไทย': 52, 'วิชชั่นใหม่': 30, 'เพื่อชีวิตใหม่': 16, 'คลองไทย': 30, 'ประชาธิปไตย': 17477, 'ไทยก้าวหน้า': 110, 'ไทยภักดี': 695, 'แรงงานสร้างชาติ': 61, 'ประชากรไทย': 40, 'ครูไทยเพื่อประชาชน': 56, 'ประชาชาติ': 66, 'สร้างอนาคตไทย': 48, 'รักชาติ': 53, 'ไทยพร้อม': 85, 'ภูมิใจไทย': 9002, 'พลังธรรมใหม่': 32, 'กรีน': 23, 'ไทยธรรม': 22, 'แผ่นดินธรรม': 18, 'กล้าธรรม': 69, 'พลังประชารัฐ': 89, 'โอกาสใหม่': 28, 'เป็นธรรม': 48, 'ประชาชน': 31608, 'ประชาไทย': 93, 'ไทยสร้างไทย': 423, 'ไทยก้าวใหม่': 549, 'ประชาอาสาชาติ': 9, 'พร้อม': 48, 'เครือข่ายชาวนาแห่งประเทศไทย': 9, 'ไทยพิทักษ์ธรรม': 6, 'ความหวังใหม่': 7, 'ไทยรวมไทย': 15, 'เพื่อบ้านเมือง': 52, 'พลังไทยรักชาติ': 22}

Processing:  79%|███████▉  | 237/300 [27:41<10:15,  9.76s/doc]

party_list_21_3 {'ไทยขวัชย์ทวี': 467, 'เพื่อชาติไทย': 921, 'มิติใหม่': 177, 'รวมใจไทย': 1489, 'รวมไทยสร้างชาติ': 4608, 'พลวัต': 97, 'ประชาธิปไตยใหม่': 993, 'เพื่อไทย': 5066, 'ทางเลือกใหม่': 472, 'เศรษฐกิจ': 3420, 'เสรีรวมไทย': 321, 'รวมพลังประชาชน': 478, 'ท้องที่ไทย': 50, 'อนาคตไทย': 49, 'พลังเพื่อไทย': 148, 'ไทยชนะ': 130, 'พลังสังคมใหม่': 23, 'สังคมประชาธิปไตยไทย': 66, 'ฟิวชัน': 42, 'ไทรวมพลัง': 32, 'ก้าวอิสระ': 17, 'ปวงชนไทย': 50, 'วิชชั้นใหม่': 52, 'เพื่อชีวิตใหม่': 55, 'คลองไทย': 132, 'ประชาธิปไตย': 17400, 'ไทยก้าวหน้า': 144, 'แรงงานสร้างชาติ': 143, 'ประชากรไทย': 90, 'ครูไทยเพื่อประชาชน': 37, 'ประชาชาติ': 109, 'สร้างอนาคตไทย': 117, 'รักชาติ': 185, 'ไทยพร้อม': 96, 'ภูมิใจไทย': 9301, 'พลังธรรมใหม่': 80, 'กรีน': 34, 'ไทยธรรม': 33, 'แผ่นดินธรรม': 14, 'กล้าธรรม': 82, 'พลังประชารัฐ': 131, 'โอกาสใหม่': 39, 'เป็นธรรม': 146, 'ประชาชน': 27801, 'ประชาไทย': 116, 'ไทยสร้างไทย': 402, 'ไทยก้าวใหม่': 269, 'ประชาอาสาชาติ': 10, 'พร้อม': 60, 'เครือข่ายชาวบ้านแห่งประเทศไทย': 14, 'ไทยพิทักษ์ธรรม': 12, 'ความหวังใหม่': 18, 'ไทยรวมไทย': 17, 'เพื่อบ้านเมือง': 34, 'พลังไทยรักชาติ': 54}

Processing:  79%|███████▉  | 238/300 [27:51<10:07,  9.80s/doc]

party_list_21_4 {'ไทยพร้พย์ทวี': 173, 'เพื่อขาดไทย': 3818, 'มิติใหม่': 149, 'รวมใจไทย': 489, 'รวมไทยสร้างชาติ': 1924, 'พลวัต': 84, 'ประชาธิปไตยใหม่': 746, 'เพื่อไทย': 5374, 'ทางเลือกใหม่': 417, 'เศรษฐกิจ': 3275, 'เสรีรวมไทย': 351, 'รวมพลังประชาชน': 419, 'ท้องที่ไทย': 31, 'อนาคตไทย': 81, 'พลังเพื่อไทย': 110, 'ไทยชนะ': 119, 'พลังสังคมใหม่': 16, 'สังคมประชาธิปไตยไทย': 133, 'ฟิวชัน': 25, 'ไทรวมพลัง': 47, 'ก้าวอิสระ': 38, 'ปวงชนไทย': 56, 'วิชชั่นใหม่': 40, 'เพื่อชีวิตใหม่': 51, 'คลองไทย': 67, 'ประชาธิปัตย์': 11305, 'ไทยก้าวหน้า': 134, 'ไทยภักดี': 482, 'แรงงานสร้างชาติ': 109, 'ประชากรไทย': 233, 'ครูไทยเพื่อประชาชน': 136, 'ประชาชาติ': 112, 'สร้างอนาคตไทย': 86, 'รักชาติ': 304, 'ไทยพร้อม': 116, 'ภูมิใจไทย': 19236, 'พลังธรรมใหม่': 92, 'กรีน': 47, 'ไทยธรรม': 34, 'กล้าธรรม': 154, 'พลังประชารัฐ': 141, 'โอกาสใหม่': 56, 'เป็นธรรม': 47, 'ประชาชน': 36093, 'ประชาไทย': 165, 'ไทยสร้างไทย': 259, 'ไทยก้าวใหม่': 361, 'ประชาอาสาชาติ': 6, 'พร้อม': 51, 'เครือข่ายชาวบ้านแห่งประเทศไทย': 12, 'ไทยพิทักษ์ธรรม': 9, 'ความหวังใหม่': 16, 'ไทยรวมไทย': 14, 'เพื่อบ้านเมือง': 47, 'พลังไทยรักชาติ': 49}

Processing:  80%|███████▉  | 239/300 [27:59<09:36,  9.46s/doc]

party_list_21_5 {}

Processing:  80%|████████  | 240/300 [28:11<10:01, 10.02s/doc]

party_list_22_1 {'ไทยทรัพย์ทวี': 1614, 'เพื่อชาติไทย': 1033, 'รวมใจไทย': 673, 'รวมไทยสร้างชาติ': 2924, 'พลวัต': 166, 'ประชาธิปไตยใหม่': 646, 'เพื่อไทย': 8687, 'ทางเลือกใหม่': 534, 'เศรษฐกิจ': 6091, 'เสรีรวมไทย': 498, 'รวมพลังประชาชน': 525, 'ท้องที่ไทย': 61, 'อนาคตไทย': 54, 'พลังเพื่อไทย': 136, 'ไทยชนะ': 73, 'พลังสังคมใหม่': 18, 'สังคมประชาธิปไตยไทย': 41, 'พิวชั่น': 30, 'ไทรวมพลัง': 37, 'ก้าวอิสระ': 18, 'ปวงชนไทย': 69, 'วิชชั่นใหม่': 41, 'เพื่อชีวิตใหม่': 23, 'คลองไทย': 48, 'ประชาธิปไตย': 8816, 'ไทยก้าวหน้า': 94, 'ไทยภักดี': 1193, 'แรงงานสร้างชาติ': 121, 'ประชากรไทย': 133, 'ครูไทยเพื่อประชาชน': 86, 'ประชาชาติ': 115, 'สร้างอนาคตไทย': 100, 'รักชาติ': 141, 'ไทยพร้อม': 122, 'ภูมิใจไทย': 25749, 'พลังธรรมใหม่': 94, 'กรีน': 60, 'ไทยธรรม': 39, 'แผ่นดินธรรม': 15, 'กล้าระรม': 218, 'พลังประชาธิปไตย': 188, 'โอกาสใหม่': 34, 'เป็นธรรม': 47, 'ประชาชน': 36381, 'ประชาไทย': 137, 'ไทยสร้างไทย': 789, 'ไทยก้าวใหม่': 336, 'ประชาอาสาชาติ': 12, 'พร้อม': 40, 'เครือข่ายชาวนาแห่งประเทศไทย': 10, 'ไทยพิทักษ์ธรรม': 5, 'ความหวังใหม่': 10, 'ไทยรวมไทย': 15, 'เพื่อบ้านเมือง': 68, 'พลังไทยรักชาติ': 39}

Processing:  80%|████████  | 241/300 [28:19<09:20,  9.50s/doc]

party_list_22_2 {}

Processing:  81%|████████  | 242/300 [28:28<09:13,  9.55s/doc]

party_list_22_3 {'ไทยทวีพยัทวี': 679, 'รวมใจไทย': 1142, 'รวมไทยสร้างชาติ': 4718, 'พลวัต': 392, 'ประชาธิปไตยไทม์': 708, 'ทางเลือกไทม์': 613, 'เศรษฐกิจ': 7377, 'เสร็จรวมไทย': 193, 'รวมพลังประชาชน': 613, 'ท้องฟ้ไทย': 163, 'อนาคตไทย': 17, 'พลังเพื่อไทย': 210, 'พลังสังคมไทม์': 26, 'สังคมประชาธิปไตยไทย': 52, 'พิวชัน': 37, 'โทรวมพลัง': 36, 'ก้าวอิสระ': 33, 'ปวดชนไทย': 91, 'วิชชั่นไทม์': 78, 'เพื่อชีวิตไทม์': 22, 'ตลอดไทย': 94, 'ประชาธิปัตย์': 6784, 'ไทยก้าวหน้า': 132, 'ไทยภักดี': 579, 'แรงงานสร้างชาติ': 146, 'ประชากรไทย': 132, 'ครูไทยเพื่อประชาชน': 177, 'ประชาชาติ': 148, 'สร้างอนาคตไทย': 135, 'รักชาติ': 269, 'ไทยพร้อม': 184, 'ภูมิใจไทย': 21523, 'พลังธรรมไทม์': 136, 'กรีน': 48, 'ไทยธรรม': 95, 'แผ่นดินธรรม': 38, 'กล้าธรรม': 467, 'พลังประชาธิปไตย': 2000, 'เป็นธรรม': 91, 'ประชาชน': 26341, 'ประชาไทย': 170, 'ไทยสร้างไทย': 651, 'ไทยก้าวไทม์': 244, 'ประชาอาสาชาติ': 21, 'พร้อม': 49, 'เครือข่ายชาวบ้านเล่าประเทศไทย': 16, 'ไทยพิทักษ์ธรรม': 22, 'ความหวังไทม์': 25, 'ไทยรวมไทย': 16, 'เพื่อป้ามเมือง': 45, 'พลังไทยรักชาติ': 85}

Processing:  81%|████████  | 243/300 [28:39<09:15,  9.74s/doc]

party_list_23_1 {'ไทยทรัพย์ทวี': 7279, 'เพื่อชาติไทย': 1379, 'มิติใหม่': 112, 'รวมใจไทย': 811, 'รวมไทยสร้างชาติ': 3333, 'พลวัต': 488, 'ประชาธิปไตยใหม่': 1122, 'เพื่อไทย': 6678, 'ทางเลือกใหม่': 650, 'เศรษฐกิจ': 7915, 'เสร็จรวมไทย': 518, 'รวมพลังประชาชน': 567, 'ข้อสร้างไทย': 113, 'อนาคตไทย': 63, 'พลังเพื่อไทย': 168, 'ไทยชนะ': 175, 'พลังสังคมใหม่': 28, 'สังคมประชาธิปไตยไทย': 44, 'ฟิวชัน,': 52, 'ไทรวมพลัง,': 54, 'ก้าวอิสระ': 38, 'ปวงชนไทย': 50, 'วิชชั่นใหม่': 83, 'เพื่อชีวิตใหม่': 34, 'คลองไทย': 148, 'ประชาธิปัตย์': 13504, 'ไทยก้าวหน้า': 136, 'ไทยภักดี': 833, 'แรงงานสร้างชาติ': 311, 'ประชากรไทย': 203, 'ครูไทยเพื่อประชาชน': 134, 'ประชาชาติ': 211, 'สร้างอนาคตไทย': 168, 'รักชาติ': 177, 'ไทยพร้อม': 251, 'ภูมิใจไทย': 34158, 'พลังธรรมใหม่': 164, 'กรีน': 55, 'ไทยธรรม': 73, 'แผ่นดินธรรม': 41, 'กล้าธรรม': 1307, 'พลังประชารัฐ': 711, 'โอกาสใหม่': 47, 'เป็นธรรม': 87, 'ประชาชน': 32353, 'ประชาไทย': 371, 'ไทยสร้างไทย': 533, 'ไทยก้าวใหม่': 235, 'พร้อม': 51, 'เครือข่ายชาวนาแห่งประเทศไทย': 36, 'ไทยพิทักษ์ธรรม': 11, 'ความหวังใหม่': 22, 'ไทยรวมไทย': 23, 'เพื่อบ้านเมือง': 90, 'พลังไทยรักชาติ': 72}

Processing:  81%|████████▏ | 244/300 [28:50<09:40, 10.37s/doc]

party_list_24_1 {'ไพยพรัพย์ทวี': 560, 'เพื่อชาติไทย': 4176, 'มิติไหม่': 227, 'รวมใจไทย': 556, 'รวมไทยสร้างชาติ': 3168, 'ประชาธิปไตยไหม่': 540, 'เพื่อไทย': 34528, 'ทางเลือกไหม่': 763, 'เศรษฐกิจ': 3740, 'เสร็จรวมไทย': 570, 'รวมพลังประชาชน': 659, 'ท้องที่ไทย': 58, 'อนาคตไทย': 64, 'พลังเพื่อไทย': 201, 'ไทยชนะ': 126, 'พลังสังคมไหม่': 15, 'สังคมประชาธิปไตยไทย': 57, 'ฟิวชัน': 32, 'ใยรวมพลัง': 45, 'ก้าวอิสระ': 36, 'ปวงชนไทย': 103, 'วิชชั่นไหม่': 36, 'เพื่อชีวิตไหม่': 30, 'ประชาธิปไตย': 7342, 'ไทยก้าวหน้า': 128, 'ไทยภักดี': 346, 'แรงงานสร้างชาติ': 114, 'ประชากรไทย': 233, 'ครูไทยเพื่อประชาชน': 47, 'ประชาชาติ': 186, 'ภูมิใจไทย': 36774, 'พลังธรรมไหม่': 114, 'กรีน': 60, 'ไทยธรรม': 124, 'แผ่นดินธรรม': 27, 'กล้ากรรม': 508, 'พลังประชาธิปไตย': 226, 'โอกาสไหม่': 51, 'เป็นธรรม': 67, 'ประชาชน': 50400, 'ประชาไทย': 114, 'ไทยสร้างไทย': 563, 'ไทยก้าวไหม่': 586, 'ประชาอาสาชาติ': 7, 'พร้อม': 52, 'เครือข่ายชาวนาแห่งประเทศไทย': 55, 'ไทยพิทักษ์ธรรม': 17, 'ความหวังไหม่': 36, 'ไทยรวมไทย': 19, 'เพื่อบ้านเมือง': 14, 'พลังไทยรักชาติ': 89}

Processing:  82%|████████▏ | 245/300 [29:02<09:50, 10.74s/doc]

party_list_24_2 {'ไทยทรัพย์ทวี': 336, 'เพื่อชาติไทย': 1922, 'รวมใจไทย': 1049, 'รวมไทยสร้างชาติ': 3154, 'พลวัต': 130, 'ประชาธิปไตยไทย': 859, 'เพื่อไทย': 17413, 'เศรษฐกิจ': 5121, 'เสรีรวมไทย': 792, 'รวมพลังประชาชน': 933, 'ท้องที่ไทย': 110, 'อนาคตไทย': 110, 'พลังเพื่อไทย': 281, 'พลังสังคมไทย': 32, 'สังคมประชาธิปไตยไทย': 74, 'ฟิวชัน': 43, 'ไทยรวมพลัง': 63, 'ก้าวอิสระ': 43, 'ปวงชนไทย': 162, 'เพื่อชีวิตไทย': 62, 'คลองไทย': 123, 'ประชาธิปไตย': 9619, 'ไทยก้าวหน้า': 130, 'ไทยภักดี': 724, 'แรงงานสร้างชาติ': 141, 'ประชากรไทย': 172, 'ครูไทยเพื่อประชาชน': 179, 'ประชาชาติ': 632, 'สร้างอนาคตไทย': 214, 'รักชาติ': 206, 'ไทยพร้อม': 154, 'ภูมิใจไทย': 14684, 'กรีน': 98, 'ไทยธรรม': 411, 'แผ่นดินธรรม': 52, 'กล้าธรรม': 4950, 'พลังประชาธิปไตย': 723, 'เป็นธรรม': 207, 'ประชาชน': 32949, 'ประชาไทย': 155, 'ไทยสร้างไทย': 412, 'ไทยก้าวไทย': 298, 'ประชาชนสาขาต': 7, 'พร้อม': 79, 'ไทยพิทักษ์ธรรม': 21, 'ไทยรวมไทย': 22, 'เพื่อบ้านเมือง': 63, 'พลังไทยรักชาติ': 35}

Processing:  82%|████████▏ | 246/300 [29:10<08:57,  9.96s/doc]

party_list_24_3 {'ไทยทรัพย์ทวี': 1117, 'เพื่อชาติไทย': 2171, 'รวมใจไทย': 708, 'รวมไทม์สร้างชาติ': 2209, 'พลวัต': 161, 'ประชาธิปไตยไทม์': 501, 'เพื่อไทย': 14171, 'ทางเลือกไทม์': 658, 'เศรษฐกิจ': 5683, 'เสรีรวมไทย': 741, 'รวมพลังประชาชน': 884, 'ท้องที่ไทย': 127, 'อนาคตไทย': 130, 'พลังเพื่อไทย': 253, 'ไทยชนะ': 169, 'พลังสังคมไทม์': 42, 'สังคมประชาธิปไตยไทย': 70, 'ไทรวมพลัง': 86, 'ก้าวอิสระ': 66, 'ปวงชนไทย': 83, 'วิชชั่นไทม์': 417, 'เพื่อชีวิตไทม์': 49, 'คลองไทย': 128, 'ประชาธิปไตย': 4576, 'ไทยก้าวหน้า': 174, 'ไทยภักดี': 496, 'แรงงานสร้างชาติ': 267, 'ประชากรไทย': 204, 'ครูไทยเพื่อประชาชน': 153, 'ประชาชาติ': 360, 'สร้างอนาคตไทย': 174, 'รักชาติ': 141, 'ไทยพร้อม': 123, 'ภูมิใจไทย': 9840, 'พลังธรรมไทม์': 231, 'กรีน': 60, 'ไทยธรรม': 764, 'แผ่นดินธรรม': 103, 'กล้าธรรม': 7835, 'พลังประชาธิปไตย': 362, 'เป็นธรรม': 121, 'ประชาชน': 31106, 'ประชาไทย': 178, 'ไทยสร้างไทย': 417, 'ไทยก้าวไทม์': 246, 'ประชาอาสาชาติ': 13, 'พร้อม': 32, 'เครือข่ายชาวนาแห่งประเทศไทย': 28, 'ไทยพิทักษ์ธรรม': 35, 'ไทยรวมไทย': 25, 'เพื่อบ้านเมือง': 17, 'พลังไทยรักชาติ': 109}

Processing:  82%|████████▏ | 247/300 [29:19<08:28,  9.60s/doc]

party_list_24_4 {'เพื่อชาติไทย': 191, 'มิติใหม่': 3077, 'รวมใจไทย': 2205, 'รวมไทยสร้างชาติ': 3188, 'ประชาธิปไตยใหม่': 602, 'เพื่อไทย': 12923, 'ทางเลือกใหม่': 1600, 'เศรษฐกิจ': 5042, 'เสร็จรถไทย': 1001, 'รวมพลังประชาชน': 311, 'ท้องที่ไทย': 59, 'อนาคตไทย': 113, 'พลังเพื่อไทย': 249, 'ไทยชนล': 149, 'พลังดังคมใหม่': 15, 'สังคมประชาธิปไตยไทย': 134, 'ฟิวชัน': 45, 'ไทยรวมพลัง': 74, 'ก้าวอิสระ': 70, 'ปวเชนไทย': 119, 'วิชชั้นใหม่': 172, 'เพื่อชีวิตใหม่': 46, 'คอยงไทย': 80, 'ประชาธิปไตย': 7012, 'ไทยก้าวหน้า': 216, 'ไทยภักดี': 841, 'แรงงานสร้างชาติ': 274, 'ประชากรไทย': 154, 'ครูไทยเพื่อประชาชน': 134, 'ประชาชาติ': 273, 'สร้างอนาคตไทย': 226, 'รักชาติ': 184, 'ไทยพร้อม': 135, 'ภูมิใจไทย': 15260, 'พลังธรรมใหม่': 144, 'กรีน': 30, 'ไทยธรรม': 107, 'แผ่นดินธรรม': 72, 'กล้าธรรม': 5650, 'พลังประชาธิปไตย': 258, 'โอกาสใหม่': 82, 'เป็นธรรม': 112, 'ประชาชน': 44634, 'ประชาไทย': 135, 'ไทยสร้างไทย': 477, 'ไทยก้าวใหม่': 752, 'ประชาชาตาชาติ': 8, 'พร้อม': 83, 'แผ่นดิน': 74, 'ไทยรวมไทย': 29, 'เพื่อบ้านเมือง': 56, 'พลังไทยรักชาติ': 104}

Processing:  83%|████████▎ | 248/300 [29:28<08:11,  9.46s/doc]

party_list_25_1 {'ไทยทรัพย์ทวี': 2250, 'เพื่อชาติไทย': 2244, 'มิติใหม่': 468, 'พรรครวมใจไทย': 796, 'รวมไทยสร้างชาติ': 2466, 'พลวัต': 98, 'ประชาธิปไตยใหม่': 450, 'เพื่อไทย': 8898, 'ทางเลือกใหม่': 712, 'เศรษฐกิจ': 4310, 'เสรีรวมไทย': 658, 'รวมพลังประชาชน': 608, 'ท้องที่ไทย': 105, 'พลังเพื่อไทย': 169, 'ไทยชนะ': 138, 'พลังสังคมใหม่': 28, 'สังคมประชาธิปไตยไทย': 38, 'ฟิวชัน': 47, 'ไทยรวมพลัง': 71, 'ก้าวอิสระ': 40, 'ปวงชนไทย': 52, 'วิชชั้นใหม่': 58, 'เพื่อชีวิตใหม่': 99, 'คลองไทย': 55, 'ประชาธิปปัตย์': 4202, 'ไทยก้าวหน้า': 160, 'ไทยภักดี': 941, 'แรงงานสร้างชาติ': 254, 'ประชากรไทย': 220, 'ครูไทยเพื่อประชาชน': 91, 'ประชาชาติ': 147, 'สร้างอนาคตไทย': 126, 'รักชาติ': 140, 'ไทยพร้อม': 123, 'ภูมิใจไทย': 19725, 'พลังธรรมใหม่': 103, 'กรีน': 57, 'ไทยธรรม': 134, 'แผ่นดินธรรม': 31, 'กล้าธรรม': 500, 'พลังประชารัฐ': 358, 'โอกาสใหม่': 104, 'เป็นธรรม': 83, 'ประชาชน': 30816, 'ประชาไทย': 136, 'ไทยสร้างไทย': 389, 'ไทยก้าวใหม่': 276, 'ประชาอาสาชาติ': 13, 'พร้อม': 75, 'เครือข่ายชาวนาแห่งประเทศไทย': 53, 'ไทยพิทักษ์ธรรม': 11, 'ความหวังใหม่': 30, 'ไทยรวมไทย': 18, 'เพื่อบ้านเมือง': 50, 'พลังไทยรักชาติ': 118}

Processing:  83%|████████▎ | 249/300 [29:38<08:01,  9.44s/doc]

party_list_25_3 {'พรรคไทยทรัพย์ทวี': 1015, 'พรรคเพื่อชาติไทย': 5858, 'พรรคใหม่': 792, 'พรรคมิติใหม่': 338, 'พรรครวมใจไทย': 804, 'พรรครวมไทยสร้างชาติ': 1712, 'พรรคพลวัต': 125, 'พรรคประชาธิปไตยใหม่': 630, 'พรรคเพื่อไทย': 9599, 'พรรคทางเลือกใหม่': 488, 'พรรคเศรษฐกิจ': 4554, 'พรรคเสรีรวมไทย': 567, 'พรรครวมพลังประชาชน': 782, 'พรรคท้องที่ไทย': 66, 'พรรคอนาคตไทย': 82, 'พรรคพลังเพื่อไทย': 212, 'พรรคไทยชนะ': 227, 'พรรคพลังสังคมใหม่': 36, 'พรรคสังคมประชาธิปไตยไทย': 70, 'พรรคฟิวชั้น': 41, 'พรรคไทรวมพลัง': 57, 'พรรคก้าวอิสระ': 56, 'พรรคปวงชนไทย': 82, 'พรรควิชชั้นใหม่': 57, 'พรรคเพื่อชีวิตใหม่': 43, 'พรรคคลองไทย': 102, 'พรรคประชาธิปไตย': 4890, 'พรรคไทยก้าวหน้า': 201, 'พรรคไทยภักดี': 552, 'พรรคแรงงานสร้างชาติ': 254, 'พรรคประชากรไทย': 473, 'พรรคครูไทยเพื่อประชาชน': 269, 'พรรคสร้างอนาคตไทย': 189, 'พรรครักชาติ': 122, 'พรรคไทยพร้อม': 176, 'พรรคภูมิใจไทย': 18183, 'พรรคพลังธรรมใหม่': 154, 'พรรคไทยธรรม': 86, 'พรรคแผ่นดินธรรม': 39, 'พรรคกล้าวธรรม': 129, 'พรรคโอกาสใหม่': 55, 'พรรคเป็นธรรม': 75, 'พรรคประชาชน': 29333, 'พรรคประชาไทย': 188, 'พรรคไทยสร้างชาติ': 347, 'พรรคไทยก้าวใหม่': 211, 'พรรคประชาอาสาชาติ': 9, 'พรรคพร้อม': 77, 'พรรคไทยพิทักษ์ธรรม': 21, 'พรรคความหวังใหม่': 28, 'พรรคไทยรวมไทย': 20, 'พรรคเพื่อบ้านเมือง': 52, 'พรรคพลังไทยรักชาติ': 122}

Processing:  83%|████████▎ | 250/300 [29:46<07:31,  9.02s/doc]

party_list_26_1 {'เพื่อขาดไทย': 4207, 'อิติใหม่': 201, 'รวมใจไทย': 761, 'รวมไทยสร้างชาติ': 2601, 'ประชาธิปไตยใหม่': 482, 'เพื่อไทย': 7775, 'ทางเลือกใหม่': 638, 'เศรษฐกิจ': 3870, 'เสร็จรถไทย': 654, 'รวมหลักประชาชน': 486, 'ท้องที่ไทย': 72, 'อนาคตไทย': 75, 'พลังเพื่อไทย': 152, 'ไทยชนะ': 102, 'หลังสังคมใหม่': 15, 'สังคมประชาธิปไตยไทย': 25, 'ก้าวอิสระ': 43, 'ปงเขนไทย': 36, 'วิชชั่นใหม่': 88, 'เพื่อชีวิตใหม่': 27, 'ททองไทย': 65, 'ประชาธิปัตย์': 6018, 'ไทยก้าวหน้า': 159, 'ไทยภักดี': 640, 'แรงงานสร้างชาติ': 231, 'ประชากรไทย': 254, 'ครูไทยเพื่อประชาชน': 158, 'ประชาชาติ': 141, 'สร้างอนาคตไทย': 117, 'รักชาติ': 110, 'ไทยพร้อม': 101, 'ภูมิใจไทย': 15677, 'พลังธรรมใหม่': 116, 'กรีน': 45, 'ไทยธรรม': 86, 'แผ่นดินธรรม': 33, 'กล้าธรรม': 2261, 'หลักประชาธิปไตย': 207, 'โอกาสใหม่': 56, 'เป็นธรรม': 74, 'ประชาชน': 22427, 'ประชาไทย': 542, 'ไทยสร้างไทย': 355, 'ไทยก้าวใหม่': 252, 'พร้อม': 68, 'เครือขายข่าวนานทั้งประเทศไทย': 23, 'ไทยพิทักษ์ธรรม': 7, 'ความหวังใหม่': 43, 'ไทยรวมไทย': 22, 'เพื่อบ้านเมือง': 62, 'หลังไทยรักชาติ': 74}

Processing:  84%|████████▎ | 251/300 [29:58<08:11, 10.02s/doc]

party_list_26_2 {'เพื่อชาติไทย': 1660, 'รวมใจไทย': 744, 'รวมไทยสร้างชาติ': 5089, 'ประชาธิปไตยใหม่': 662, 'เพื่อไทย': 8738, 'ทางเลือกใหม่': 671, 'เศรษฐกิจ': 3859, 'เสร็จรถไทย': 466, 'รวมพลังประชาชน': 652, 'ช่องที่ไทย': 164, 'อนาคตไทย': 95, 'พลังเพื่อไทย': 248, 'ไทยชนล': 117, 'สังคมประชาธิปไตยไทย': 63, 'ไทรรมพลัง': 55, 'ก้าวอิสระ': 76, 'ปวงชนไทย': 110, 'วิชชั่นใหม่': 111, 'เพื่อชีวิตใหม่': 36, 'คอยงไทย': 84, 'ประชาธิปไตย': 6609, 'ไทยก้าวหน้า': 188, 'ไทยภักดี': 605, 'แรงงานสร้างชาติ': 296, 'ประชากรไทย': 148, 'ครูไทยเพื่อประชาชน': 117, 'ประชาชาติ': 330, 'สร้างอนาคตไทย': 157, 'รักชาติ': 231, 'ไทยพร้อม': 661, 'ภูมิใจไทย': 16575, 'พลังธรรมใหม่': 109, 'กรีน': 61, 'ไทยธรรม': 67, 'แผ่นดินธรรม': 26, 'กล้าสรรม': 1963, 'พลังประชาธิปไตย': 266, 'โอกาสใหม่': 65, 'เป็นธรรม': 54, 'ประชาชน': 23579, 'ประชาไทย': 154, 'ไทยสร้างไทย': 349, 'ไทยก้าวใหม่': 216, 'ประชากรสาขาติ': 7, 'พร้อม': 66, 'เครือข่ายชาวบานต่อประเทศไทย': 18, 'ไทยพิทักษ์ธรรม': 12, 'ความหวังใหม่': 45, 'ไทยรวมไทย': 30, 'เพื่อบ้านเมือง': 67, 'พลังไทยรักชาติ': 100}

Processing:  84%|████████▍ | 252/300 [30:10<08:30, 10.64s/doc]

party_list_27_1 {'โดยทรัพย์ทวี': 460, 'มิติใหม่': 315, 'รวมใจโดย': 4216, 'รวมโดยสร้างชาติ': 2116, 'ประชาธิปไตยใหม่': 588, 'เพื่อโดย': 7889, 'ทางเลือกใหม่': 479, 'เศรษฐกิจ': 6019, 'รวมพลังประชาชน': 764, 'ท้องที่โดย': 474, 'อนาคตโดย': 140, 'พลังเพื่อโดย': 105, 'พลังสังคมใหม่': 51, 'สังคมประชาธิปไตยโดย': 71, 'ใครวมพลัง': 34, 'วิชชั่นใหม่': 124, 'เพื่อชีวิตใหม่': 34, 'คลองโดย': 34, 'ประชาธิปไตย': 3078, 'โดยก้าวหน้า': 381, 'โดยภักดี': 379, 'แรงงานสร้างชาติ': 130, 'ประชากรโดย': 131, 'ครูโดยเพื่อประชาชน': 147, 'ประชาชาติ': 185, 'สร้างอนาคตโดย': 3076, 'รักชาติ': 635, 'โดยพร้อม': 346, 'ภูมิใจโดย': 30781, 'พลังธรรมใหม่': 358, 'กรีน': 67, 'โดยธรรม': 88, 'แผ่นดินธรรม': 62, 'กล้าอรวม': 118, 'พลังประชาธิปไตย': 17510, 'โอกาสใหม่': 118, 'เป็นธรรม': 241, 'ประชาชน': 24351, 'ประชาไทย': 272, 'โดยก้าวใหม่': 482, 'ประชาอาสาชาติ': 19, 'พร้อม': 68, 'เครือข่ายชาวบ้านพังประเทศไทย': 18, 'โดยพิทักษ์ธรรม': 41, 'ความหวังใหม่': 29, 'เพื่อบ้านเมือง': 42, 'พลังโดยรักชาติ': 78}

Processing:  84%|████████▍ | 253/300 [30:19<07:52, 10.06s/doc]

party_list_27_2 {'ไทยพรัพย์ทวี': 171, 'เพื่อชาติไทย': 1182, 'รวมใจไทย': 785, 'รวมไทยสร้างชาติ': 4677, 'พลวัค': 173, 'ประชาธิปไตยไทม์': 687, 'เพื่อไทย': 7954, 'ทางเลือกไทม์': 488, 'เศรษฐกิจ': 6516, 'เสรีรวมไทย': 567, 'รวมพลังประชาชน': 670, 'ท้องที่ไทย': 489, 'อนาคตไทย': 101, 'พลังเพื่อไทย': 366, 'พลังสังคมไทม์': 41, 'สังคมประชาธิปไตยไทย': 33, 'ฟิวชัน': 35, 'ไทรวมพลัง': 224, 'ก้าวอิสระ': 47, 'ปวงชนไทย': 327, 'วิชชั่นไทม์': 189, 'เพื่อชีวิตไทม์': 42, 'ตลอดไทย': 84, 'ประชาธิปัตย์': 2659, 'ไทยก้าวหน้า': 187, 'ไทยภักดี': 320, 'แรงงานสร้างชาติ': 151, 'ประชากรไทย': 153, 'ครูไทยเพื่อประชาชน': 131, 'ประชาชาติ': 126, 'สร้างอนาคตไทย': 860, 'รักชาติ': 343, 'ไทยพร้อม': 249, 'ภูมิใจไทย': 9796, 'พลังธรรมไทม์': 357, 'กรีน': 36, 'ไทยธรรม': 31, 'แผ่นดินธรรม': 44, 'กล้าอรวม': 454, 'พลังประชารัฐ': 22924, 'เป็นธรรม': 122, 'ประชาชน': 22827, 'ประชาไทย': 190, 'ไทยสร้างไทย': 289, 'ไทยก้าวไทม์': 320, 'ประชาอาสาชาติ': 19, 'พร้อม': 62, 'เครือข่ายชาวนาแห่งประเทศไทย': 26, 'ไทยพิทักษ์ธรรม': 18, 'ความหวังไทม์': 38, 'ไทยรวมไทย': 13, 'เพื่อบ้านเมือง': 33, 'พลังไทยรักชาติ': 34}

Processing:  85%|████████▍ | 254/300 [30:29<07:40, 10.01s/doc]

party_list_27_3 {'เพื่อชาติไทย': 2088, 'รวมใจไทย': 669, 'รวมไทยสร้างชาติ': 2041, 'ประชาธิปไตยไทม์': 709, 'เพื่อไทย': 17135, 'ทางเลือกไทม์': 529, 'เศรษฐกิจ': 8894, 'เสร็จรวมไทย': 469, 'รวมพลังประชาชน': 545, 'ท้องที่ไทย': 65, 'อนาคตไทย': 62, 'พลังเพื่อไทย': 215, 'ไทยชนะ': 115, 'พลังสังคมไทม์': 23, 'สังคมประชาธิปไตยไทย': 56, 'ฟิวชัน': 18, 'ไทรวมพลัง': 91, 'ก้าวอิสระ': 48, 'ปวงชนไทย': 84, 'เพื่อชีวิตไทม์': 34, 'คลองไทย': 83, 'ประชาธิปัตย์': 3924, 'ไทยก้าวหน้า': 134, 'ไทยภักดี': 467, 'แรงงานสร้างชาติ': 348, 'ประชากรไทย': 243, 'ครูไทยเพื่อประชาชน': 311, 'ประชาชาติ': 155, 'สร้างอนาคตไทย': 205, 'รักชาติ': 140, 'ไทยพร้อม': 171, 'ภูมิใจไทย': 17896, 'พลังธรรมไทม์': 315, 'กรีน': 69, 'ไทยธรรม': 151, 'แผ่นดินธรรม': 83, 'กล้าธรรม': 5200, 'พลังประชารัฐ': 545, 'เป็นธรรม': 69, 'ประชาชน': 20087, 'ประชาไทย': 158, 'ไทยสร้างไทย': 266, 'ไทยก้าวไทม์': 287, 'ประชายาสาขาตี': 8, 'พร้อม': 49, 'เครือข่ายชาวนาแห่งประเทศไทย': 19, 'ไทยพิทักษ์ธรรม': 28, 'ความหวังไทม์': 64, 'ไทยรวมไทย': 16, 'เพื่อบ้านเมือง': 68, 'พลังไทยรักชาติ': 85}

Processing:  85%|████████▌ | 255/300 [30:39<07:36, 10.14s/doc]

party_list_30_1 {'ไทยพร้อมโพร': 101, 'เพื่อชาติไทย': 514, 'รวมใจไทย': 296, 'รวมไทยสร้างชาติ': 2660, 'ประชาธิปไตยไทม์': 244, 'เพื่อไทย': 16125, 'ทางเลือกไทม์': 513, 'เศรษฐกิจ': 4856, 'เสร็จรวมไทย': 411, 'รวมหลังประชาชน': 329, 'ท้องที่ไทย': 21, 'อนาคตไทย': 68, 'พลังเพื่อไทย': 107, 'ไทยชนะ': 59, 'พลังสังคมไทม์': 21, 'สังคมประชาธิปไตยไทย': 59, 'พิวชั่น': 33, 'ไทรวิมพลัง': 101, 'ก้าวอิสระ': 18, 'ปวงชนไทย': 53, 'วิชชั่นไทม์': 24, 'เพื่อชีวิตไทม์': 16, 'คลองไทย': 23, 'ประชาธิปไตย': 3063, 'ไทยก้าวหน้า': 82, 'ไทยภักดี': 1393, 'แรงงานสร้างชาติ': 41, 'ประชากรไทย': 56, 'ครูไทยเพื่อประชาชน': 65, 'ประชาชาติ': 80, 'สร้างอนาคตไทย': 53, 'รักชาติ': 151, 'ไทยพร้อม': 31, 'ภูมิใจไทย': 16001, 'พลังธรรมไทม์': 127, 'กรีน': 42, 'ไทยธรรม': 64, 'แผ่นดินธรรม': 12, 'กล้าธรรม': 149, 'พลังประชาธิปไตย': 203, 'เป็นธรรม': 37, 'ประชาชน': 33044, 'ประชาไทย': 140, 'ไทยสร้างไทย': 468, 'ไทยก้าวไทม์': 410, 'ประชาอาสาชาติ': 8, 'พร้อม': 32, 'เครือข่ายชาวมาแห่งประเทศไทย': 12, 'ไทยพิทักษ์ธรรม': 3, 'ความหวังไทม์': 24, 'ไทยรวมไทย': 35, 'เพื่อบ้านเมือง': 7, 'พลังไทยรักชาติ': 33}

Processing:  85%|████████▌ | 256/300 [30:46<06:50,  9.33s/doc]

party_list_30_10 {}

Processing:  86%|████████▌ | 257/300 [30:56<06:37,  9.25s/doc]

party_list_30_11 {'เพื่อชาติไทย': 2049, 'มิติใหม่': 644, 'รวมไรไทย': 752, 'รวมไทยสร้างชาติ': 1413, 'พลวัต': 130, 'ประชาธิปไตยใหม่': 449, 'เพื่อไทย': 27568, 'ทางเลือกใหม่': 448, 'เศรษฐกิจ': 6046, 'เสรีรวมไทย': 448, 'รวมพลังประชาชน': 547, 'ท้องที่ไทย': 62, 'อนาคตไทย': 82, 'พลังเพื่อไทย': 149, 'ไทยชนะ': 146, 'พลังสังคมใหม่': 26, 'สังคมประชาธิปไตยไทย': 50, 'ไตรมพลัง': 311, 'ก้าวอิสระ': 36, 'ปวงชนไทย': 52, 'ใหชันใหม่': 58, 'เพื่อชีวิตใหม่': 30, 'คอองไทย': 65, 'ประชาธิปัตย์': 2114, 'ไทยก้าวหน้า': 111, 'ไทยภักดี': 328, 'แรงงานสร้างชาติ': 138, 'ประชากรไทย': 182, 'ครูไทยเต็มประชาชน': 258, 'ประชาชาติ': 160, 'สร้างอนาคตไทย': 132, 'รักชาติ': 100, 'ไทยพร้อม': 117, 'ภูมิใจไทย': 11444, 'พลังธรรมใหม่': 422, 'กรีน': 81, 'ไทยธรรม': 80, 'แผ่นดินธรรม': 31, 'กล้าธรรม': 239, 'พลังประชาธิปไตย': 144, 'โอกาสใหม่': 34, 'เป็นธรรม': 106, 'ประชาชน': 20168, 'ประชาไทย': 138, 'ไทยสร้างไทย': 369, 'ไทยก้าวใหม่': 130, 'ประชายาสาขาตี': 9, 'พร้อม': 46, 'เครือข่ายชาวนาแต่กประเทศไทย': 12, 'ไทยพิทักษ์ธรรม': 7, 'ความหวังใหม่': 38, 'ไทยรวมไทย': 19, 'เพื่อบ้านเมือง': 44, 'พลังไทยรักชาติ': 105}

Processing:  86%|████████▌ | 258/300 [31:06<06:48,  9.72s/doc]

party_list_30_12 {'เพื่อชาติไทย': 1907, 'รวมไทย': 668, 'รวมไทยสร้างชาติ': 1753, 'พลวัย': 897, 'ประชาธิปไตยไทย': 458, 'เพื่อไทย': 17486, 'เศรษฐกิจ': 4900, 'เสรีรวมไทย': 388, 'รวมพลังประชาชน': 593, 'ท้องที่ไทย': 86, 'อนาคตไทย': 225, 'พลังเพื่อไทย': 228, 'ไทยชนะ': 177, 'พลังสังคมไทย': 36, 'สังคมประชาธิปไตยไทย': 31, 'ฟิวชัน': 25, 'ไทรวมพลัง': 79, 'ก้าวอิสระ': 46, 'ปวลชนไทย': 58, 'เพื่อชีวิตไทย': 36, 'ตลอดไทย': 112, 'ประชาธิปัตย์': 2491, 'ไทยก้าวหน้า': 124, 'แรงงานสร้างชาติ': 124, 'ประชากรไทย': 190, 'ครูไทยเพื่อประชาชน': 223, 'ประชาชาติ': 166, 'สร้างอนาคตไทย': 116, 'รักชาติ': 156, 'ไทยพร้อม': 212, 'ภูมิใจไทย': 15416, 'กรีน': 77, 'ไทยธรรม': 89, 'แผ่นดินธรรม': 35, 'กล้าธรรม': 206, 'พลังประชาธิปไตย': 195, 'เป็นธรรม': 92, 'ประชาชน': 24403, 'ประชาไทย': 162, 'ไทยสร้างไทย': 394, 'ไทยก้าวไทย': 214, 'ประชากรสาขาต': 10, 'พร้อม': 47, 'เครือขายชาวนาและประเทศไทย': 11, 'ไทยพิทักษ์ธรรม': 16, 'ไทยรวมไทย': 38, 'เพื่อบ้านเมือง': 36, 'พลังไทยรักชาติ': 83}

Processing:  86%|████████▋ | 259/300 [31:15<06:30,  9.51s/doc]

party_list_30_13 {'ไทยทรัพย์ทวี': 511, 'เพื่อชาติต่อ': 1275, 'มิติใหม่': 276, 'รวมไอไทย': 3234, 'รวมไทยสร้างชาติ': 3346, 'พลวัส': 343, 'ประชาธิปไตยไหม': 468, 'เพื่อไทย': 18963, 'ทางเลือกไหม': 383, 'เศรษฐกิจ': 5131, 'เสรีรวมไทย': 296, 'รวมพลังประชาชน': 616, 'ท้องที่ไทย': 56, 'อนาคตไทย': 37, 'พลังเพื่อไทย': 211, 'ไทยชนะ': 133, 'พลังสังคมไหม': 34, 'สังคมประชาธิปไตยไทย': 54, 'พิวชั่น': 39, 'ไทรวมพลัง': 56, 'ก้าวอิสระ': 26, 'ปวเชนไทย': 31, 'วิชชั่นใหม่': 58, 'เพื่อชีวิตไหม': 31, 'คลองไทย': 119, 'ประชาธิปไตย': 2423, 'ไทยก้าวหน้า': 153, 'แรงงานสร้างชาติ': 131, 'ประชากรไทย': 147, 'ครูไทยเพื่อประชาชน': 34, 'ประชาชาติ': 128, 'สร้างอนาคตไทย': 354, 'อีกชาติ': 357, 'ไทยพร้อม': 113, 'ภูมิใจไทย': 3415, 'พลังธรรมไหม': 214, 'กรีน': 48, 'ไทยธรรม': 61, 'แผนดินธรรม': 31, 'กล้าธรรม': 124, 'พลังประชาธิปไตย': 135, 'โอกาสไหม': 192, 'เป็นธรรม': 64, 'ประชาชน': 53462, 'ประชาไทย': 149, 'ไทยสร้างไทย': 133, 'ไทยก้าวไหม': 218, 'ประชาอาสาชาติ': 14, 'พร้อม': 53, 'ไทยพิทักษ์ธรรม': 36, 'ความหวังไหม': 29, 'ไทยรวมไทย': 19, 'เพื่อบ้านเมือง': 54, 'พลังไทยรักชาติ': 53}

Processing:  87%|████████▋ | 260/300 [31:24<06:11,  9.30s/doc]

party_list_30_14 {'ไทยพร้อมทวี': 767, 'เพื่อชาติไทย': 1377, 'มิติไหม': 1363, 'รวมใจไทย': 624, 'รวมไทยสร้างชาติ': 2173, 'พลวัต': 106, 'ประชาธิปไตยไหม': 344, 'เพื่อไทย': 12276, 'ทางเลือกไหม': 422, 'เศรษฐกิจ': 3360, 'รวมพลังประชาชน': 576, 'ท้องที่ไทย': 51, 'อนาคตไทย': 101, 'พลังเพื่อไทย': 216, 'ไทยชนะ': 119, 'พลังสังคมไหม': 24, 'สังคมประชาธิปไตยไทย': 30, 'ฟิวชัน': 22, 'ไทรวมพลัง': 51, 'ก้าวอิสระ': 31, 'ปวงชนไทย': 52, 'วิชชั่นไหม': 54, 'เพื่อชีวิตไหม': 15, 'คลองไทย': 36, 'ประชาธิปไตย': 2935, 'ไทยก้าวหน้า': 140, 'ไทยภักดี': 651, 'แรงงานสร้างชาติ': 139, 'ประชากรไทย': 99, 'ครูไทยเพื่อประชาชน': 83, 'ประชาชาติ': 139, 'สร้างอนาคตไทย': 150, 'รักชาติ': 106, 'ไทยพร้อม': 117, 'ภูมิใจไทย': 13130, 'พลังธรรมไหม': 131, 'กรีน': 54, 'ไทยธรรม': 41, 'แผ่นดินธรรม': 28, 'กล้าธรรม': 97, 'พลังประชารัฐ': 155, 'โอกาสไหม': 1718, 'เป็นธรรม': 67, 'ประชาชน': 29452, 'ประชาไทย': 127, 'ไทยสร้างไทย': 378, 'ไทยก้าวไหม': 223, 'ประชาอาสาชาติ': 9, 'พร้อม': 63, 'เครือข่ายชาวนาแห่งประเทศไทย': 14, 'ไทยพิทักษ์ธรรม': 9, 'ความหวังไหม': 20, 'ไทยรวมไทย': 17, 'เพื่อบ้านเมือง': 27, 'พลังไทยรักชาติ': 56}

Processing:  87%|████████▋ | 261/300 [31:35<06:14,  9.61s/doc]

party_list_30_15 {'ไทยพร้อมโพร': 1837, 'เพื่อขาดไทย': 4281, 'รวมใจไทย': 3653, 'รวมไทยสร้างชาติ': 3634, 'พลวัต': 146, 'ประชาธิปไตยไหน': 870, 'เพื่อไทย': 23134, 'เศรษฐกิจ': 4239, 'เสรีรวมไทย': 548, 'รวมพลังประชาชน': 680, 'ห้องฟีไทย': 102, 'อนาคตไทย': 145, 'พลังเพื่อไทย': 292, 'ไทยชนะ': 139, 'พลังสังคมไหน': 40, 'สังคมประชาธิปไตยไทย': 56, 'ฟิวชัน': 36, 'ไทรวมพลัง': 69, 'ก้าวถิสระ': 54, 'ปวงชนไทย': 60, 'วิชชั่นไหน': 186, 'เพื่อชีวิตไหน': 34, 'คลองไทย': 87, 'ประชาธิปไตย': 2391, 'ไทยก้าวหน้า': 153, 'ไทยเกิดดี': 328, 'แรงงานสร้างชาติ': 224, 'ประชากรไทย': 323, 'ครูไทยเพื่อประชาชน': 134, 'ประชาชาติ': 117, 'สร้างอนาคตไทย': 279, 'รักชาติ': 146, 'ไทยพร้อม': 225, 'ภูมิใจไทย': 13578, 'พลังธรรมไหน': 388, 'กรีน': 118, 'ไทยธรรม': 107, 'แผ่นดินธรรม': 36, 'กล้าธรรม': 3424, 'พลังประชารัฐ': 242, 'โอกาสไหน': 1473, 'เป็นธรรม': 109, 'ประชาชน': 24078, 'ประชาไทย': 161, 'ไทยสร้างไทย': 321, 'ไทยก้าวไหน': 255, 'ประชาอาสาชาติ': 13, 'พร้อม': 60, 'เครือข่ายชาวนาแห่งประเทศไทย': 22, 'ไทยพิทักษ์ธรรม': 19, 'ความหวังไหน': 30, 'ไทยรวมไทย': 27, 'เพื่อบ้านเมือง': 33, 'พลังไทยรักชาติ': 30}

Processing:  87%|████████▋ | 262/300 [31:46<06:22, 10.07s/doc]

party_list_30_16 {'เพื่อชาติไทย': 4759, 'มิติใหม่': 216, 'รวมใจไทย': 747, 'รวมไทยสร้างชาติ': 3340, 'ประชาธิปไตยใหม่': 613, 'เพื่อไทย': 18961, 'ทางเลือกใหม่': 167, 'เศรษฐกิจ': 4171, 'เสร็จรวมไทย': 341, 'รวมพลังประชาชน': 592, 'ห้องที่ไทย': 54, 'อนาคตไทย': 121, 'พลังเพื่อไทย': 187, 'พลังสังคมใหม่': 28, 'สังคมประชาธิปไตยไทย': 48, 'ฟิวชัน': 29, 'ไตรมพลัง': 41, 'ก้าวสีสระ': 25, 'ปวดทุนไทย': 56, 'วิชชั่นใหม่': 58, 'เพื่อชีวิตใหม่': 28, 'คลองไทย': 63, 'ประชาธิปัตย์': 1670, 'ไทยก้าวหน้า': 127, 'ไทยภักดี': 368, 'แรงงานสร้างชาติ': 172, 'ประชากรไทย': 394, 'ครูไทยเพื่อประชาชน': 272, 'ประชาชาติ': 131, 'สร้างอนาคตไทย': 168, 'รักชาติ': 125, 'ไทยพร้อม': 142, 'ภูมิใจไทย': 17651, 'พลังธรรมใหม่': 391, 'กรีน': 68, 'ไทยธรรม': 115, 'แม่มตินธรรม': 17, 'กล้าธรรม': 201, 'พลังประชารัฐ': 405, 'โอกาสใหม่': 1882, 'เป็นธรรม': 105, 'ประชาชน': 20331, 'ประชาไทย': 102, 'ไทยสร้างไทย': 371, 'ไทยก้าวใหม่': 161, 'ประชาอาสาชาติ': 8, 'พร้อม': 45, 'เครือข่ายชาวนาแห่งประเทศไทย': 35, 'ไทยพิทักษ์ธรรม': 16, 'ความหรังใหม่': 15, 'ไทยรวมไทย': 17, 'เพื่อบ้านเมือง': 41, 'พลังไทยรักชาติ': 59}

Processing:  88%|████████▊ | 263/300 [31:55<05:59,  9.73s/doc]

party_list_30_2 {}

Processing:  88%|████████▊ | 264/300 [31:56<04:20,  7.24s/doc]

API error occurred: Status 404. Body: {"detail": "No file matches the given query."}
party_list_30_3 {}

Processing:  88%|████████▊ | 265/300 [32:07<04:51,  8.33s/doc]

party_list_30_4 {}

Processing:  89%|████████▊ | 266/300 [32:18<05:07,  9.05s/doc]

party_list_30_5 {'ไทยทรัพย์ทวี': 3264, 'เพื่อชาติไทย': 2075, 'มิติใหม่': 341, 'รวมใจไทย': 617, 'รวมไทยสร้างชาติ': 1517, 'พลวัต': 1749, 'ประชาธิปไตยใหม่': 524, 'เพื่อไทย': 18807, 'ทางเลือกใหม่': 448, 'เศรษฐกิจ': 4181, 'เสร็จรวมไทย': 356, 'รวมพลังประชาชน': 464, 'ท้องที่ไทย': 58, 'อนาคตไทย': 31, 'พลังเพื่อไทย': 219, 'ไทยชนะ': 124, 'พลังสังคมใหม่': 27, 'สังคมประชาธิปไตยไทย': 34, 'ฟิวชัน': 26, 'ไทรวมพลัง': 56, 'ก้าวอิสระ': 29, 'ปวงชนไทย': 59, 'วิชชั่นใหม่': 56, 'เพื่อชีวิตใหม่': 29, 'ตลอดไทย': 45, 'ประชาธิปัตย์': 2005, 'ไทยก้าวหน้า': 117, 'ไทยภักดี': 438, 'แรงงานสร้างชาติ': 322, 'ประชากรไทย': 214, 'ครูไทยเพื่อประชาชน': 115, 'ประชาชาติ': 107, 'สร้างอนาคตไทย': 125, 'รักชาติ': 355, 'ไทยพร้อม': 278, 'ภูมิใจไทย': 22285, 'พลังธรรมใหม่': 284, 'กรีน': 49, 'ไทยธรรม': 30, 'แผ่นดินธรรม': 30, 'กล้าธรรม': 115, 'พลังประชาธิปไตย': 175, 'โอกาสใหม่': 455, 'เป็นธรรม': 54, 'ประชาชน': 22017, 'ประชาไทย': 156, 'ไทยสร้างไทย': 287, 'ไทยก้าวใหม่': 178, 'ประชาอาสาชาติ': 4, 'พร้อม': 56, 'เสถียร้ายชาวบ้านแห่งประเทศไทย': 25, 'ไทยพิทักษ์ธรรม': 38, 'ความหวังใหม่': 36, 'ไทยรวมไทย': 27, 'เพื่อบ้านเมือง': 36, 'พลังไทยรักชาติ': 87}

Processing:  89%|████████▉ | 267/300 [32:27<05:00,  9.11s/doc]

party_list_30_6 {'เชื้อชาติไทย': 1414, 'รวมใจไทย': 516, 'รวมไทยสร้างชาติ': 2762, 'พลวัต': 210, 'ประชาธิปไตยไทย': 516, 'เพื่อไทย': 21489, 'เศรษฐกิจ': 3600, 'รวมพลังประชาชน': 461, 'ท้องที่ไทย': 57, 'อนาคตไทย': 88, 'พลังเพื่อไทย': 258, 'ไทยชนอ': 114, 'พลังสังคมไทย': 30, 'สังคมประชาธิปไตยไทย': 19, 'ฟิวชัน': 19, 'ไพรวมพลัง': 45, 'ก้าวอิสระ': 24, 'ปวเชนไทย': 59, 'เพื่อชีวิตไทย': 30, 'ประชาธิปัตย์': 1310, 'ไทยก้าวหน้า': 117, 'ไทยภักดี': 318, 'แรงงานสร้างชาติ': 289, 'ประชากรไทย': 231, 'ครูไทยเพื่อประชาชน': 150, 'ประชาชาติ': 148, 'สร้างอนาคตไทย': 219, 'รักชาติ': 188, 'ไทยพร้อม': 245, 'ภูมิใจไทย': 14801, 'กรีน': 47, 'ไทยธรรม': 90, 'แผ่นดินธรรม': 31, 'กล้าธรรม': 1314, 'พลังประชารัฐ': 466, 'เป็นธรรม': 61, 'ประชาชน': 19770, 'ประชาไทย': 145, 'ไทยสร้างไทย': 548, 'ไทยก้าวไทย': 146, 'ประชาอาสาชาติ': 8, 'พร้อม': 41, 'เครือข่ายชาวนาแห่ลประเทศไทย': 6, 'ไทยพิทักษ์ธรรม': 7, 'ไทยรวมไทย': 18, 'เพื่อบ้านเมือง': 60, 'พลังไทยรักชาติ': 59}

Processing:  89%|████████▉ | 268/300 [32:39<05:24, 10.15s/doc]

party_list_30_7 {'**รวมหลักประชาชน**': 528, '**ห้าวอิสระ**': 26, '**กล้าธรรม**': 114, '**หลักประชารัฐ**': 113, '**เป็นธรรม**': 46, '**ประชาชน**': 11224}

Processing:  90%|████████▉ | 269/300 [32:50<05:20, 10.34s/doc]

party_list_30_8 {'เดือชาติไทย': 1772, 'มิติไหม่': 674, 'รวมใจไทย': 846, 'รวมไทยสร้างชาติ': 1546, 'ประชาธิปไตยไหม่': 471, 'เพื่อไทย': 25725, 'ทางเลือกไหม': 379, 'เศรษฐกิจ': 4078, 'รวมพลังประชาชน': 528, 'ท้องที่ไทย': 41, 'อนาคตไทย': 48, 'หลังเดือไทย': 186, 'หลังสังคมไหม่': 17, 'สังคมประชาธิปไตยไทย': 44, 'ฟิวชัน': 34, 'ไทรวงเพลิง': 34, 'ก้าวอิสระ': 34, 'ปวงชนไทย': 40, 'วิชชั่นไหม่': 41, 'เพื่อชีวิตไหม่': 31, 'คลองไทย': 55, 'ประชาธิปไตย': 2744, 'ไทยก้าวหน้า': 31, 'ไทยภักดี': 515, 'แรงงานสร้างชาติ': 356, 'ประชากรไทย': 187, 'ครูไทยเพื่อประชาชน': 80, 'ประชาชาติ': 131, 'สร้างอนาคตไทย': 124, 'รักชาติ': 35, 'ไทยพร้อม': 107, 'ภูมิใจไทย': 13529, 'พลังธรรมไหม่': 488, 'กรีน': 77, 'ไทยธรรม': 59, 'แผ่นดินธรรม': 22, 'กล้าธรรม': 38, 'พลังประชาธิปไตย': 148, 'โอกาสไหม่': 342, 'เป็นธรรม': 36, 'ประชาชน': 20201, 'ประชาไทย': 104, 'ไทยสร้างไทย': 288, 'ไทยกาวไหม่': 153, 'ประชาอาสาชาติ': 1, 'พร้อม': 27, 'ไทยพิทักษ์ธรรม': 11, 'ความหวังไหม่': 23, 'ไทยรวมไทย': 20, 'เพื่อบ้านเมือง': 34, 'พลังไทยรักชาติ': 35}

Processing:  90%|█████████ | 270/300 [33:00<05:07, 10.26s/doc]

party_list_30_9 {'ไทยขรุพย์ทวี': 418, 'เพื่อชาติไทย': 1484, 'อิสีใหม่': 453, 'รวมใจไทย': 1124, 'รวมไทยเสร้างชาติ': 3334, 'พลวัต': 156, 'ประชาธิปไตยใหม่': 526, 'เพื่อไทย': 12757, 'ทางเลือกใหม่': 328, 'เศรษฐกิจ': 1074, 'เสร็จรวมไทย': 422, 'รวมพลังประชาชน': 653, 'ท้องที่ไทย': 64, 'อนาคตไทย': 72, 'พลังเพื่อไทย': 256, 'พลังสังคมใหม่': 24, 'สังคมประชาธิปไตยไทย': 35, 'ฟิวชัน': 50, 'ไทรวมพลัง': 56, 'ก้าวอิสระ': 37, 'ปวงชนไทย': 76, 'วิชชั่นใหม่': 112, 'เพื่อชีวิตใหม่': 48, 'คลองไทย': 97, 'ประชาธิปัตย์': 2105, 'ไทยก้าวหน้า': 131, 'ไทยภักดี': 415, 'แรงงานสร้างชาติ': 157, 'ประชากรไทย': 237, 'ครูไทยเพื่อประชาชน': 277, 'ประชาชาติ': 183, 'สร้างอนาคตไทย': 184, 'รักชาติ': 286, 'ไทยพร้อม': 303, 'ภูมิใจไทย': 26202, 'พลังธรรมใหม่': 312, 'กรีน': 32, 'ไทยธรรม': 115, 'แผ่นดินธรรม': 45, 'กล้าธรรม': 3030, 'พลังประชารัฐ': 168, 'โอกาสใหม่': 48, 'เป็นธรรม': 112, 'ประชาชน': 20305, 'ประชาไทย': 138, 'ไทยสร้างไทย': 156, 'ไทยก้าวใหม่': 174, 'ประชาอาสาชาติ': 9, 'พร้อม': 53, 'เครือข่ายชาวนาแห่งประเทศไทย': 18, 'ไทยพิทักษ์ธรรม': 17, 'ความหวังใหม่': 25, 'ไทยรวมไทย': 17, 'เพื่อบ้านเมือง': 54, 'พลังไทยรักชาติ': 94}

Processing:  90%|█████████ | 271/300 [33:11<04:57, 10.24s/doc]

party_list_31_1 {'ไทยทรัพย์ทวี': 137, 'เพื่อชาติไทย': 534, 'มิติใหม่': 91, 'รวมใจไทย': 1967, 'รวมไทยสร้างชาติ': 632, 'พลวัต': 88, 'ประชาธิปไตยใหม่': 646, 'เพื่อไทย': 498, 'ทางเลือกใหม่': 202, 'เศรษฐกิจ': 1607, 'เสรีรวมไทย': 164, 'รวมพลังประชาชน': 234, 'ท้องที่ไทย': 23, 'อนาคตไทย': 49, 'พลังเพื่อไทย': 83, 'พลังสังคมใหม่': 17, 'สังคมประชาธิปไตยไทย': 19, 'พิวชัน': 17, 'ใครวมพลัง': 30, 'ก้าวอิสระ': 78, 'ปวงชนไทย': 52, 'วิชชั่นใหม่': 20, 'เพื่อชีวิตใหม่': 33, 'คลองไทย': 34, 'ประชาธิปัตย์': 1114, 'ไทยก้าวหน้า': 49, 'ไทยภักดี': 337, 'แรงงานสร้างชาติ': 81, 'ประชากรไทย': 188, 'ครูไทยเพื่อประชาชน': 39, 'ประชาชาติ': 68, 'สร้างอนาคตไทย': 237, 'รักชาติ': 300, 'ไทยพร้อม': 192, 'ภูมิใจไทย': 47358, 'พลังธรรมใหม่': 168, 'กรีน': 43, 'ไทยธรรม': 26, 'แผ่นดินธรรม': 16, 'กล้าธรรม': 58, 'พลังประชาธิปไตย': 68, 'โอกาสใหม่': 39, 'เป็นธรรม': 88, 'ประชาชน': 16650, 'ประชาไทย': 124, 'ไทยสร้างไทย': 168, 'ไทยก้าวใหม่': 125, 'ประชาอาสาชาติ': 13, 'พร้อม': 30, 'เครือข่ายชาวบ้านแห่งประเทศไทย': 11, 'ไทยพิทักษ์ธรรม': 8, 'ความหวังใหม่': 8, 'ไทยรวมไทย': 19, 'เพื่อบ้านเมือง': 22, 'พลังไทยรักชาติ': 83}

Processing:  91%|█████████ | 272/300 [33:20<04:44, 10.15s/doc]

party_list_31_10 {'ไทยทรัพย์ทวี': 386, 'เพื่อชาติไทย': 2758, 'รวมใจไทย': 289, 'รวมไทยสร้างชาติ': 538, 'พลวัต': 169, 'ประชาธิปไตยใหม่': 625, 'เพื่อไทย': 4641, 'ทางเลือกใหม่': 172, 'เศรษฐกิจ': 2087, 'เสรีรวมไทย': 211, 'รวมพลังประชาชน': 190, 'ท้องที่ไทย': 15, 'อนาคตไทย': 37, 'พลังเพื่อไทย': 37, 'ไทยชนะ': 32, 'พลังสังคมใหม่': 22, 'สังคมประชาธิปไตยไทย': 28, 'ฟิวชัน': 22, 'ไทรวมพลัง': 51, 'ก้าวอิสระ': 112, 'ปวงชนไทย': 87, 'วิชชั่นใหม่': 27, 'เพื่อชีวิตใหม่': 13, 'คลองไทย': 29, 'ประชาธิปไตย': 1743, 'ไทยก้าวหน้า': 53, 'ไทยภักดี': 216, 'แรงงานสร้างชาติ': 127, 'ประชากรไทย': 340, 'ครูไทยเพื่อประชาชน': 211, 'ประชาชาติ': 83, 'สร้างอนาคตไทย': 95, 'ไทยพร้อม': 392, 'ภูมิใจไทย': 40255, 'พลังธรรมใหม่': 170, 'กรีน': 42, 'ไทยธรรม': 38, 'แผ่นดินธรรม': 15, 'กล้าอรรม': 56, 'พลังประชารัฐ': 48, 'โอกาสใหม่': 16, 'เป็นธรรม': 22, 'ประชาชน': 12025, 'ประชาไทย': 121, 'ไทยสร้างไทย': 131, 'ไทยก้าวใหม่': 67, 'ประชาอาสาชาติ': 6, 'พร้อม': 24, 'เครือข่ายชาวนาแห่งประเทศไทย': 16, 'ไทยพิทักษ์ธรรม': 12, 'ความหวังใหม่': 14, 'ไทยรวมไทย': 16, 'เพื่อบ้านเมือง': 19, 'พลังไทยรักชาติ': 50}

Processing:  91%|█████████ | 273/300 [33:29<04:23,  9.76s/doc]

party_list_31_2 {'ไทยทรัพย์ทวี': 173, 'เพื่อชาติไทย': 576, 'รวมใจไทย': 2300, 'รวมไทยสร้างชาติ': 595, 'พลวัด': 105, 'ประชาธิปไตยไทม์': 655, 'เพื่อไทย': 4714, 'ทางเลือกไทม์': 187, 'เศรษฐกิจ': 1609, 'เสร็จรณไทย': 169, 'รวมพลังประชาชน': 281, 'ท้องที่ไทย': 28, 'อนาคตไทย': 52, 'พลังเพื่อไทย': 92, 'พลังสังคมไทม์': 21, 'สังคมประชาธิปไตยไทย': 16, 'ฟิวชัน': 16, 'ไทรวมพลัง': 37, 'ก้าวอิสระ': 280, 'ปวงชนไทย': 73, 'วิชชั่นไทม์': 45, 'เพื่อชีวิตไทม์': 38, 'คลองไทย': 45, 'ประชาธิปไตย': 1006, 'ไทยก้าวหน้า': 51, 'ไทยภักดี': 269, 'แรงงานสร้างชาติ': 111, 'ประชากรไทย': 244, 'ครูไทยเพื่อประชาชน': 123, 'ประชาชาติ': 88, 'สร้างอนาคตไทย': 199, 'รักชาติ': 356, 'ไทยพร้อม': 319, 'ภูมิใจไทย': 45437, 'พลังธรรมไทม์': 178, 'กรีน': 53, 'ไทยธรรม': 36, 'กล้าธรรม': 83, 'พลังประชาธิปไตย': 66, 'เป็นธรรม': 64, 'ประชาชน': 13822, 'ประชาไทย': 107, 'ไทยสร้างไทย': 167, 'ไทยก้าวไทม์': 92, 'ประชาอาสาชาติ': 9, 'พร้อม': 24, 'เครือข่ายชาวนาแห่งประเทศไทย': 14, 'ไทยพิทักษ์ธรรม': 17, 'ความหวังไทม์': 10, 'ไทยรวมไทย': 15, 'เพื่อป่านเมือง': 28, 'พลังไทยรักชาติ': 92}

Processing:  91%|█████████▏| 274/300 [33:38<04:07,  9.50s/doc]

party_list_31_3 {'ไทยทรัพย์ทวี': 1784, 'เพื่อชาติไทย': 568, 'รวมใจไทย': 373, 'รวมไทยสร้างชาติ': 650, 'พลวัต': 100, 'ประชาธิปไตยไทม์': 602, 'เพื่อไทย': 4805, 'ทางเลือกไทม์': 158, 'เศรษฐกิจ': 1276, 'เสร็จรวมไทย': 115, 'รวมพลังประชาชน': 237, 'ท้องที่ไทย': 24, 'อนาคตไทย': 35, 'พลังเพื่อไทย': 81, 'ไทยชนะ': 167, 'พลังสังคมไทม์': 17, 'สังคมประชาธิปไตยไทย': 17, 'ฟิวชัน': 13, 'ไทรวมพลัง': 32, 'ก้าวอิสระ': 43, 'ปวงชนไทย': 52, 'วิชชั่นไทม์': 25, 'เพื่อชีวิตไทม์': 18, 'คลองไทย': 48, 'ประชาธิปไตย': 858, 'ไทยก้าวหน้า': 76, 'ไทยภักดี': 163, 'แรงงานสร้างชาติ': 314, 'ประชากรไทย': 305, 'ครูไทยเพื่อประชาชน': 112, 'ประชาชาติ': 73, 'สร้างอนาคตไทย': 100, 'รักชาติ': 127, 'ไทยพร้อม': 213, 'ภูมิใจไทย': 44617, 'พลังธรรมไทม์': 200, 'กรีน': 46, 'ไทยธรรม': 33, 'แผ่นดินธรรม': 18, 'กล้าธรรม': 85, 'พลังประชารัฐ': 41, 'เป็นธรรม': 55, 'ประชาชน': 13202, 'ประชาไทย': 156, 'ไทยสร้างไทย': 117, 'ไทยก้าวไทม์': 78, 'ประชาชนสาขาต': 6, 'พร้อม': 29, 'เครือข่ายชาวบ้านหงประเทศไทย': 10, 'ไทยพิทักษ์ธรรม': 5, 'ความหวังไทม์': 18, 'ไทยรวมไทย': 11, 'เพื่อบ้านเมือง': 55, 'พลังไทยรักชาติ': 51}

Processing:  92%|█████████▏| 275/300 [33:49<04:04,  9.78s/doc]

party_list_31_4 {'ไทยพร้อมรักไ': 268, 'เพื่อชาติไทย': 1156, 'รวมไกไทย': 728, 'รวมไทยสร้างชาติ': 726, 'ประชาธิปไตยไหม้': 515, 'เพื่อไทย': 3364, 'ทางเลือกไหม้': 134, 'เศรษฐกิจ': 1881, 'รวมพลังประชาชน': 382, 'ท้องฟีไทย': 23, 'อนาคตไทย': 15, 'พลังเพื่อไทย': 128, 'พลังสังคมไทย': 15, 'สังคมประชาธิปไตยไทย': 19, 'ไทยรวมพลัง': 15, 'ก้าวอิสระ': 33, 'ปวงชนไทย': 38, 'วิชชั้นไหม้': 37, 'เพื่อชีวิตไหม้': 22, 'คะองไทย': 55, 'ประชาธิปไตย': 3405, 'ไทยก้าวหน้า': 68, 'ไทยภักดี': 183, 'แรงงานสร้างชาติ': 104, 'ประชากรไทย': 265, 'ครูไทยเพื่อประชาชน': 279, 'ประชาชาติ': 138, 'สร้างอนาคตไทย': 145, 'รักชาติ': 107, 'ไทยพร้อม': 625, 'ภูมิใจไทย': 35235, 'พลังธรรมไหม้': 218, 'กรีน': 87, 'ไทยธรรม': 33, 'แผ่นดินธรรม': 20, 'กล้าธรรม': 87, 'พลังประชาธิปไตย': 36, 'โอกาสไหม้': 60, 'เป็นธรรม': 104, 'ประชาชน': 13215, 'ไทยสร้างไทย': 204, 'ไทยก้าวไหม้': 66, 'พร้อม': 33, 'ไทยพิทักษ์ธรรม': 3, 'ความหวังไหม้': 18, 'ไทยรวมไทย': 13, 'เพื่อบ้านเมือง': 66, 'พลังไทยรักชาติ': 47}

Processing:  92%|█████████▏| 276/300 [33:58<03:49,  9.57s/doc]

party_list_31_5 {'โคมทรัพย์ทวี': 6600, 'เพื่อขาตีไทย': 728, 'มิติใหม่': 285, 'รวมใจไทย': 467, 'รวมไทยสร้างชาติ': 63004, 'พลวัต': 1300, 'ประชาธิปไตยใหม่': 688, 'เชื่อไทย': 8952, 'ทางเลือกใหม่': 172, 'เศรษฐกิจ': 1786, 'เสรีรวมไทย': 2100, 'รวมพลังประชาชน': 272, 'ท้องที่ไทย': 12, 'อนาคตไทย': 12, 'พลังเพื่อไทย': 1661, 'ไทยชนม': 175, 'พลังดังคมใหม่': 22, 'สังคมประชาธิปไตยไทย': 18, 'ฟิวชัน': 20, 'โทรวมพลัง': 30, 'ก้าวอิสระ': 28, 'ปวงชนไทย': 55, 'วิชชั่นใหม่': 39, 'เพื่อชีวิตใหม่': 18, 'ประชาธิปัตย์': 1480, 'ไทยก้าวหน้า': 77, 'ไทยภักดี': 185, 'แรงงานสร้างชาติ': 161, 'ประชากรไทย': 191, 'ครูไทยเพื่อประชาชน': 177, 'ประชาชาติ': 108, 'สร้างอนาคตไทย': 139, 'รักชาติ': 251, 'ไทยพร้อม': 708, 'ภูมิใจไทย': 40081, 'พลังธรรมใหม่': 252, 'กรีน': 35, 'แม่แดินธรรม': 10, 'กล้ารถรม': 70, 'พลังประชาธิฐ': 86, 'เป็นธรรม': 58, 'ประชาชน': 34587, 'ประชาไทย': 102, 'ไทยสร้างไทย': 966, 'ไทยก้าวใหม่': 107, 'พร้อม': 29, 'เครือข่ายชาวนาแฟคประเภทไทย': 13, 'ไทยพิทักษ์ธรรม': 15, 'ความหรือใหม่': 11, 'เพื่อบ้านเมือง': 33, 'พลังไทยรักชาติ': 53}

Processing:  92%|█████████▏| 277/300 [34:06<03:33,  9.29s/doc]

party_list_31_6 {'ไทยทรัพย์ทวี': 636, 'เพื่อชาติไทย': 1026, 'มิติใหม่': 1538, 'รวมใจไทย': 463, 'รวมไทยสร้างชาติ': 626, 'พลวัต': 77, 'ประชาธิปไตยใหม่': 639, 'เพื่อไทย': 6726, 'ทางเลือกใหม่': 246, 'เศรษฐกิจ': 2001, 'เสรีรวมไทย': 179, 'รวมพลังประชาชน': 297, 'ท้องที่ไทย': 60, 'อนาคตไทย': 54, 'พลังเพื่อไทย': 117, 'ไทยชนะ': 141, 'พลังสังคมใหม่': 24, 'สังคมประชาธิปไตยไทย': 21, 'โทรมพลัง': 60, 'ก้าวอิสระ': 22, 'ปวงชนไทย': 35, 'วิชชั่นใหม่': 53, 'เพื่อชีวิตใหม่': 20, 'คลองไทย': 50, 'ประชาธิปไตย': 1171, 'ไทยก้าวหน้า': 56, 'แรงงานสร้างชาติ': 126, 'ประชากรไทย': 249, 'ครูไทยเพื่อประชาชน': 117, 'ประชาชาติ': 236, 'สร้างอนาคตไทย': 313, 'รักชาติ': 31, 'ไทยพร้อม': 208, 'ภูมิใจไทย': 41500, 'พลังธรรมใหม่': 241, 'กรีน': 53, 'ไทยธรรม': 52, 'แผ่นดินธรรม': 28, 'กล้าธรรม': 113, 'พลังประชารัฐ': 100, 'โอกาสใหม่': 28, 'เป็นธรรม': 51, 'ประชาชน': 13468, 'ประชาไทย': 164, 'ไทยสร้างไทย': 299, 'ไทยก้าวใหม่': 78, 'ประชาอาสาชาติ': 6, 'พร้อม': 16, 'เครือข่ายชาวนาแห่งประเทศไทย': 10, 'ไทยพิทักษ์ธรรม': 10, 'ความหวังใหม่': 13, 'ไทยรวมไทย': 19, 'เพื่อบ้านเมือง': 35, 'พลังไทยรักชาติ': 66}

Processing:  93%|█████████▎| 278/300 [34:16<03:24,  9.31s/doc]

party_list_31_7 {'พรรคไทยพรัพถ์ทวี': 371, 'พรรคเพื่อชาติไทย': 687, 'พรรคมิติใหม่': 115, 'พรรครวมใจไทย': 2574, 'พรรครวมไทยสร้างชาติ': 695, 'พรรคประชาธิปไตยใหม่': 575, 'พรรคเพื่อไทย': 10682, 'พรรคทางเลือกใหม่': 208, 'พรรคเศรษฐกิจ': 2518, 'พรรครวมพลังประชาชน': 292, 'พรรคอนาคตไทย': 57, 'พรรคพลังเพื่อไทย': 138, 'พรรคพลังสังคมใหม่': 22, 'พรรคสังคมประชาธิปไตยไทย': 26, 'พรรคฟิวชัน': 16, 'พรรคไทรวมพลัง': 30, 'พรรคก้าวอิสระ': 29, 'พรรคปวงชนไทย': 63, 'พรรควิชชั่นใหม่': 41, 'พรรคเพื่อชีวิตใหม่': 29, 'พรรคคลองไทย': 29, 'พรรคประชาธิปไตย': 882, 'พรรคไทยก้าวหน้า': 76, 'พรรคไทยภักดี': 862, 'พรรคแรงงานสร้างชาติ': 101, 'พรรคประชากรไทย': 285, 'พรรคครูไทยเพื่อประชาชน': 356, 'พรรคประชาชาติ': 34, 'พรรคสร้างอนาคตไทย': 274, 'พรรครักชาติ': 274, 'พรรคไทยพร้อม': 208, 'พรรคภูมิใจไทย': 36407, 'พรรคพลังธรรมใหม่': 292, 'พรรคไทยธรรม': 53, 'พรรคแผ่นดินธรรม': 75, 'พรรคกล้าถรรม': 68, 'พรรคโอกาสใหม่': 24, 'พรรคเป็นธรรม': 57, 'พรรคประชาชน': 13949, 'พรรคประชาไทย': 174, 'พรรคไทยสร้างไทย': 200, 'พรรคไทยก้าวใหม่': 76, 'พรรคประชาอาสาชาติ': 13, 'พรรคพร้อม': 32, 'พรรคเครือข่ายชาวมาแห่งประเทศไทย': 19, 'พรรคไทยพิทักษ์ธรรม': 16, 'พรรคความหวังใหม่': 14, 'พรรคไทยรวมไทย': 15, 'พรรคเพื่อบ้านเมือง': 27, 'พรรคพลังไทยรักชาติ': 82}

Processing:  93%|█████████▎| 279/300 [34:24<03:10,  9.06s/doc]

party_list_31_8 {}

Processing:  93%|█████████▎| 280/300 [34:32<02:52,  8.64s/doc]

party_list_31_9 {'เพ็ชชาติไทย': 534, 'มิติไหม่': 111, 'รวมใจไทย': 2406, 'รวมไทยสร้างชาติ': 330, 'พลวัต': 88, 'ประชาธิปไตยไหม่': 672, 'เพื่อไทย': 6089, 'ทางเลือกไหม่': 230, 'เศรษฐกิจ': 3448, 'รวมพลังประชาชน': 272, 'ท้องที่ไทย': 16, 'อนาคตไทย': 30, 'พลังเพื่อไทย': 134, 'ไทยชนะ': 133, 'พลังสังคมไหม่': 27, 'สังคมประชาธิปไตยไทย': 25, 'ฟิวชัน': 21, 'ไทรวมพลัง': 101, 'ก้าวอิสระ': 45, 'บางชนไทย': 88, 'วิชชั่นไหม่': 28, 'เพื่อชีวิตไหม่': 32, 'คลองไทย': 42, 'ประชาธิปัตย์': 1134, 'ไทยก้าวหน้า': 67, 'ไตยภักดี': 230, 'แรงงานสร้างชาติ': 115, 'ประชากรไทย': 245, 'ครูไทยเพื่อประชาชน': 112, 'ประชาชาติ': 66, 'สร้างอนาคตไทย': 172, 'รักชาติ': 276, 'ไทยพร้อม': 214, 'ภูมิใจไทย': 41216, 'พลังธรรมไหม่': 187, 'กรีน': 40, 'ไทยธรรม': 48, 'แผ่นดินธรรม': 18, 'กล้าธรรม': 61, 'พลังประชารัฐ': 80, 'โอกาสไหม่': 320, 'เป็นธรรม': 40, 'ประชาชน': 12065, 'ประชาไทย': 106, 'ไทยสร้างไทย': 155, 'ไทยก้าวไหม่': 83, 'ประชาอาสาชาติ': 9, 'พร้อม': 67, 'เครือข่ายชาวนาแห่งประเทศไทย': 12, 'ไทยพิทักษ์ธรรม': 25, 'ความหวังไหม่': 11, 'ไทยรวมไทย': 19, 'เพื่อบ้านเมือง': 29, 'พลังไทยรักชาติ': 87}

Processing:  94%|█████████▎| 281/300 [34:41<02:47,  8.80s/doc]

party_list_32_1 {'ไทยทรัพย์ทวี': 307, 'เพื่อชาติไทย': 724, 'มิติใหม่': 155, 'รวมใจไทย': 2816, 'รวมไทยสร้างชาติ': 1680, 'พลวัต': 124, 'ประชาธิปไตยใหม่': 676, 'เพื่อไทย': 11451, 'ทางเลือกใหม่': 396, 'เศรษฐกิจ': 3716, 'เสร็จรวมไทย': 435, 'รวมพลังประชาชน': 369, 'ห้องที่ไทย': 40, 'อนาคตไทย': 68, 'พลังเพื่อไทย': 124, 'ไทยชนต': 99, 'พลังสังคมใหม่': 27, 'สังคมประชาธิปไตยไทย': 25, 'ไทรวมพลัง': 81, 'ก้าวอิสระ': 17, 'ปวงชนไทย': 69, 'วิชชั่นใหม่': 40, 'เพื่อชีวิตใหม่': 39, 'คลองไทย': 43, 'ประชาธิปไตย': 2920, 'ไทยก้าวหน้า': 130, 'ไทยภักดี': 783, 'แรงงานสร้างชาติ': 182, 'ประชากรไทย': 125, 'ครูไทยเพื่อประชาชน': 117, 'ประชาชาติ': 66, 'สร้างอนาคตไทย': 224, 'รักชาติ': 250, 'ไทยพร้อม': 145, 'ภูมิใจไทย': 30151, 'พลังธรรมใหม่': 217, 'กรีน': 37, 'ไทยธรรม': 56, 'แผ่นดินธรรม': 39, 'กล้าธรรม': 231, 'พลังประชาธิปไตย': 147, 'โอกาสใหม่': 43, 'เป็นธรรม': 55, 'ประชาชน': 25820, 'ประชาไทย': 108, 'ไทยสร้างไทย': 459, 'ไทยก้าวใหม่': 288, 'พร้อม': 30, 'เครือข่ายชาวบ้านหักประเภทไทย': 15, 'ไทยพิทักษ์ธรรม': 13, 'ความหวังใหม่': 22, 'ไทยร่วมไทย': 18, 'เพื่อบ้านเมือง': 23, 'พลังไทยรักชาติ': 63}

Processing:  94%|█████████▍| 282/300 [34:50<02:40,  8.90s/doc]

party_list_32_2 {'ไทยพร้พย์ทวี': 207, 'เพื่อชาติไทย': 872, 'มิติใหม่': 131, 'รวมใจไทย': 1781, 'รวมไทยสร้างชาติ': 1174, 'พลวัต': 2272, 'ประชาธิปไตยใหม่': 555, 'เพื่อไทย': 16500, 'ทางเลือกใหม่': 407, 'เศรษฐกิจ': 3331, 'เสรีรวมไทย': 337, 'รวมพลังประชาชน': 482, 'ท้องที่ไทย': 83, 'อนาคตไทย': 34, 'พลังเพื่อไทย': 184, 'ไทยชนอ': 144, 'พลังสังคมใหม่': 30, 'สังคมประชาธิปไตยไทย': 34, 'ฟิวชัน': 24, 'ไทรวมพลัง': 37, 'ก้าวอิสรอ': 40, 'ปวงชนไทย': 134, 'วิชชั่นใหม่': 28, 'เพื่อชีวิตใหม่': 32, 'คลองไทย': 42, 'ประชาธิปไตย': 2016, 'ไทยก้าวหน้า': 83, 'ไทยภัยดี': 277, 'แรงงานสร้างชาติ': 87, 'ประชากรไทย': 172, 'ครูไทยเพื่อประชาชน': 136, 'ประชาชาติ': 88, 'สร้างอนาคตไทย': 134, 'รักชาติ': 159, 'ไทยพร้อม': 356, 'ภูมิใจไทย': 33078, 'พลังธรรมใหม่': 318, 'กรีน': 53, 'ไทยธรรม': 40, 'แผ่นดินธรรม': 20, 'กล้าธรรม': 138, 'พลังประชาธิปไตย': 162, 'โอกาสใหม่': 16, 'เป็นธรรม': 50, 'ประชาชน': 20648, 'ประชาไทย': 233, 'ไทยสร้างไทย': 320, 'ไทยก้าวใหม่': 153, 'ประชาอาสาชาติ': 11, 'พร้อม': 33, 'เครือข่ายชาวบ้านแห่งประเทศไทย': 14, 'ไทยพิทักษ์ธรรม': 11, 'ความหวังใหม่': 15, 'ไทยรวมไทย': 15, 'เพื่อบ้านเมือง': 38, 'พลังไทยรักชาติ': 67}

Processing:  94%|█████████▍| 283/300 [35:00<02:33,  9.05s/doc]

party_list_32_3 {'ไทยพรัพย์พี': 601, 'เพื่อขาดไทย': 1089, 'รวมถึงไทย': 579, 'รวมไทยสร้างชาติ': 1000, 'พลวัต': 769, 'ประชาธิปไตยไหม': 417, 'เพื่อไทย': 17479, 'เศรษฐกิจ': 2901, 'เสรีรวมไทย': 420, 'รวมพลังประชาชน': 430, 'ท้องฟีไทย': 65, 'อนาคตไทย': 79, 'พลังเพื่อไทย': 207, 'พลังสังคมไหม': 18, 'สังคมประชาธิปไตยไทย': 19, 'ฟิวชัน': 19, 'โทรวมพลัง': 85, 'ก้าวอิสระ': 26, 'ปวงชนไทย': 74, 'วิชชั่นไหม': 53, 'เพื่อชีวิตไหม': 26, 'คอลงไทย': 65, 'ประชาธิปไตย': 1450, 'ไทยก้าวหน้า': 100, 'ไทยภักดี': 219, 'แรงงานสร้างชาติ': 146, 'ประชากรไทย': 210, 'ครูไทยเพื่อประชาชน': 129, 'ประชาชาติ': 225, 'สร้างอนาคตไทย': 204, 'รักชาติ': 113, 'ไทยพร้อม': 274, 'ภูมิใจไทย': 25142, 'พลังธรรมไหม': 372, 'กรีน': 31, 'ไทยธรรม': 105, 'แผ่นดินธรรม': 18, 'กล้าธรรม': 114, 'พลังประชารัฐ': 186, 'โอกาสไหม': 32, 'เป็นธรรม': 66, 'ประชาชน': 19444, 'ประชาไทย': 203, 'ไทยสร้างไทย': 410, 'ไทยก้าวไหม': 116, 'ประชาอาสาชาติ': 12, 'พร้อม': 35, 'เครือข่ายชาวนาแห่งประเทศไทย': 20, 'ไทยพิทักษ์ธรรม': 12, 'ความหวังไหม': 34, 'ไทยรวมไทย': 20, 'เพื่อบ้านเมือง': 45, 'พลังไทยรักชาติ': 82}

Processing:  95%|█████████▍| 284/300 [35:08<02:22,  8.94s/doc]

party_list_32_4 {'ไทยพรัชย์ทวี': 1381, 'เพื่อชาติไทย': 1303, 'มิติใหม่': 182, 'รวมใจไทย': 523, 'รวมไทยสร้างชาติ': 363, 'ประชาธิปไตยใหม่': 430, 'เพื่อไทย': 21729, 'ทางเลือกใหม่': 336, 'เศรษฐกิจ': 2700, 'รวมพลังประชาชน': 449, 'ท้องที่ไทย': 36, 'อนาคตไทย': 64, 'พลังเพื่อไทย': 235, 'ไทยชนะ': 348, 'พลังสังคมใหม่': 43, 'สังคมประชาธิปไตยไทย': 35, 'ฟิวชัน': 16, 'ไตรมพลัง': 36, 'ก้าวอิสระ': 29, 'ปวงชนไทย': 53, 'วัชชั่นใหม่': 36, 'เพื่อชีวิตใหม่': 32, 'คอองไทย': 44, 'ประชาธิปไตย': 1361, 'ไทยก้าวหน้า': 136, 'ไทยภักดี': 246, 'แรงงานสร้างชาติ': 216, 'ประชากรไทย': 232, 'ครูไทยเพื่อประชาชน': 111, 'ประชาชาติ': 101, 'สร้างอนาคตไทย': 133, 'รักชาติ': 107, 'ไทยพร้อม': 317, 'ภูมิใจไทย': 23054, 'พลังธรรมใหม่': 442, 'กรีน': 59, 'ไทยธรรม': 53, 'แผ่นดินธรรม': 25, 'กล้าธรรม': 384, 'พลังประชารัฐ': 250, 'โอกาสใหม่': 31, 'เป็นธรรม': 32, 'ประชาชน': 17741, 'ประชาไทย': 134, 'ไทยสร้างไทย': 418, 'ไทยก้าวใหม่': 218, 'ประชาชนสาขาต': 11, 'พร้อม': 36, 'เครือข่ายชาวนาแห่งประเทศไทย': 23, 'ไทยพิทักษ์ธรรม': 13, 'ความหวังใหม่': 28, 'ไทยรวมไทย': 17, 'เพื่อบ้านเมือง': 40, 'พลังไทยรักชาติ': 66}

Processing:  95%|█████████▌| 285/300 [35:17<02:15,  9.03s/doc]

party_list_32_5 {'ไทยทรัพย์ทวี': 1432, 'เพื่อชาติไทย': 1171, 'มิติใหม่': 2271, 'รวมใจไทย': 871, 'รวมไทยสร้างชาติ': 835, 'พลวัต': 89, 'ประชาธิปไตยใหม่': 382, 'เพื่อไทย': 17292, 'ทางเลือกใหม่': 283, 'เศรษฐกิจ': 2381, 'เสร็จรวมไทย': 350, 'รวมพลังประชาชน': 390, 'ท้องที่ไทย': 78, 'อนาคตไทย': 73, 'พลังเพื่อไทย': 177, 'ไทยชนะ': 115, 'พลังสังคมใหม่': 29, 'สังคมประชาธิปไตยไทย': 28, 'พิวชัน': 22, 'ไทรวมพลัง': 85, 'ก้าวอิสระ': 40, 'ปวงชนไทย': 84, 'วิชชั่นใหม่': 195, 'เพื่อชีวิตใหม่': 92, 'คลองไทย': 53, 'ประชาธิปัตย์': 1462, 'ไทยก้าวหน้า': 110, 'ไทยภักดี': 247, 'แรงงานสร้างชาติ': 310, 'ประชากรไทย': 207, 'ครูไทยเพื่อประชาชน': 190, 'ประชาชาติ': 271, 'สร้างอนาคตไทย': 923, 'รักชาติ': 96, 'ไทยพร้อม': 143, 'ภูมิใจไทย': 21659, 'พลังธรรมใหม่': 402, 'กรีน': 72, 'ไทยธรรม': 69, 'แผ่นดินธรรม': 68, 'กล้าธรรม': 3407, 'พลังประชารัฐ': 157, 'โอกาสใหม่': 171, 'เป็นธรรม': 82, 'ประชาชน': 17796, 'ประชาไทย': 147, 'ไทยสร้างไทย': 299, 'ไทยก้าวใหม่': 168, 'ประชาอาสาชาติ': 15, 'พร้อม': 32, 'เครือข่ายชาวนาแห่งประเทศไทย': 37, 'ไทยพิทักษ์ธรรม': 23, 'ความหวังใหม่': 26, 'ไทยรวมไทย': 18, 'เพื่อบ้านเมือง': 44, 'พลังไทยรักชาติ': 50}

Processing:  95%|█████████▌| 286/300 [35:27<02:06,  9.03s/doc]

party_list_32_6 {'ไทยทรัพย์ทวี': 445, 'เพื่อขาดไทย': 2167, 'รวมไม้ไทย': 872, 'รวมไทยสร้างชาติ': 1060, 'พลวัต': 141, 'ประชาธิปไตยใหม่': 531, 'เพื่อไทย': 14011, 'ทางเลือกใหม่': 334, 'เศรษฐกิจ': 4099, 'เสร็จรวมไทย': 413, 'รวมพลังประชาชน': 389, 'ท้องที่ไทย': 89, 'อนาคตไทย': 80, 'พลังเพื่อไทย': 212, 'พลังสังคมใหม่': 37, 'สังคมประชาธิปไตยไทย': 49, 'ไตรมพลัง': 315, 'ก้าวอิสระ': 38, 'ปวงชนไทย': 65, 'วิชชั้นใหม่': 71, 'เพื่อชีวิตใหม่': 37, 'คลองไทย': 83, 'ประชาธิปไตย': 1183, 'ไทยก้าวหน้า': 95, 'ไทยภักดี': 206, 'แรงงานสร้างชาติ': 144, 'ประชากรไทย': 319, 'ครูไทยเพื่อประชาชน': 159, 'ประชาชาติ': 291, 'สร้างอนาคตไทย': 244, 'รักชาติ': 145, 'ไทยพร้อม': 208, 'ภูมิใจไทย': 26445, 'พลังธรรมใหม่': 332, 'กรีน': 77, 'ไทยธรรม': 87, 'แผ่นดินธรรม': 50, 'กล้าธรรม': 166, 'พลังประชาธิปไตย': 108, 'โอกาสใหม่': 71, 'เป็นธรรม': 69, 'ประชาชน': 16081, 'ประชาไทย': 150, 'ไทยสร้างไทย': 287, 'ไทยก้าวใหม่': 104, 'ประชาชนสาขาต': 9, 'พร้อม': 30, 'เครือข่ายชาวนาแห่งประเทศไทย': 10, 'ไทยพิทักษ์ธรรม': 15, 'ความหวังใหม่': 29, 'ไทยรวมไทย': 12, 'เพื่อบ้านเมือง': 41, 'พลังไทยรักชาติ': 80}

Processing:  96%|█████████▌| 287/300 [35:35<01:56,  8.97s/doc]

party_list_32_7 {}

Processing:  96%|█████████▌| 288/300 [35:44<01:47,  8.99s/doc]

party_list_32_8 {'ไทยทรัพย์ทวี': 365, 'เพื่อชาติไทย': 4446, 'มิติไมม่': 612, 'รวมถึงไทย': 1017, 'รวมไทยสร้างชาติ': 1084, 'ประชาธิปไตยไมม่': 500, 'เพื่อไทย': 11914, 'ทางเลือกไมม่': 164, 'เศรษฐกิจ': 7780, 'เสร็จรวมไทย': 411, 'รวมพลังประชาชน': 360, 'ท้องที่ไทย': 40, 'อนาคตไทย': 87, 'หลังเพื่อไทย': 174, 'ไทยชนม': 187, 'พลังสังคมไมม่': 42, 'สังคมประชาธิปไตยไทย': 45, 'ฟิวชัน': 29, 'ไทรวมพลัง': 127, 'ก้าวสีสระ': 56, 'ปวเชนไทย': 79, 'วิชชั่นไมม่': 50, 'เพื่อชีวิตไมม่': 18, 'คอองไทย': 85, 'ประชาธิปไตย': 1964, 'ไทยก้าวหน้า': 81, 'ไทยภักดี': 309, 'แรงงานสร้างชาติ': 146, 'ประชากรไทย': 507, 'ครูไทยเพื่อประชาชน': 236, 'ประชาชาติ': 140, 'สร้างอนาคตไทย': 162, 'รักชาติ': 121, 'ไทยทรัพย์': 217, 'ภูมิใจไทย': 26405, 'พลังธรรมไมม่': 247, 'กรีน': 47, 'ไทยธรรม': 121, 'แผ่นดินธรรม': 22, 'กล้าถรรม': 131, 'พลังประชาธิปไตย': 91, 'โอกาสไมม่': 16, 'เงินธรรม': 75, 'ประชาชน': 17064, 'ประชาไทย': 124, 'ไพมสร้างไทย': 268, 'ไทยก้าวไมม่': 123, 'ประชาอวดชาติด': 9, 'พร้อม': 26, 'เครื่องรักชาวมาแห่งประเทศไทย': 25, 'ไทยพิพิทน์ธรรม': 17, 'ความหวังไมม่': 17, 'ไทยรวมไทย': 25, 'เพื่อบ้านเมือง': 37, 'พลังไทยรักชาติ': 38}

Processing:  96%|█████████▋| 289/300 [35:53<01:39,  9.02s/doc]

party_list_33_1 {'ไทยทรัพย์ทวี': 264, 'เพื่อชาติไทย': 334, 'มิติใหม่': 106, 'รวมใจไทย': 2222, 'รวมไทยสร้างชาติ': 1011, 'พลวัต': 74, 'ประชาธิปไตยใหม่': 539, 'เพื่อไทย': 25842, 'ทางเลือกใหม่': 278, 'เศรษฐกิจ': 2144, 'เสร็จรวมไทย': 160, 'รวมพลังประชาชน': 356, 'อนาคตไทย': 66, 'พลังเพื่อไทย': 209, 'ไทยชนะ': 38, 'พลังสังคมใหม่': 20, 'สังคมประชาธิปไตย': 38, 'ไทรวมพลัง': 150, 'ก้าวอิสระ': 20, 'ปวงชนไทย': 153, 'วิชชั้นใหม่': 32, 'เพื่อชีวิตใหม่': 29, 'คลองไทย': 30, 'ประชาธิปไตย': 1518, 'ไทยก้าวหน้า': 79, 'ไทยภักดี': 105, 'แรงงานสร้างชาติ': 79, 'ประชากรไทย': 186, 'ครูไทยเพื่อประชาชน': 175, 'ประชาชาติ': 89, 'สร้างอนาคตไทย': 175, 'รักชาติ': 216, 'ไทยพร้อม': 152, 'ภูมิใจไทย': 29342, 'พลังธรรมใหม่': 540, 'กรีน': 74, 'ไทยธรรม': 39, 'แผ่นดินธรรม': 38, 'กล้ารรรม': 84, 'พลังประชารัฐ': 79, 'โอกาสใหม่': 28, 'เป็นธรรม': 103, 'ประชาชน': 22305, 'ประชาไทย': 109, 'ไทยสร้างไทย': 353, 'ไทยก้าวใหม่': 212, 'ประชาอาสาชาติ': 7, 'พร้อม': 25, 'เครือข่ายชาวบนต่อประเทศไทย': 6, 'ไทยพิพักษ์ธรรม': 9, 'ความหวังใหม่': 11, 'ไทยรวมไทย': 13, 'เพื่อบ้านเมือง': 25, 'พลังไทยรักชาติ': 42}

Processing:  97%|█████████▋| 290/300 [36:03<01:31,  9.12s/doc]

party_list_33_2 {'ไทยทรัพย์ทวี': 349, 'เดือชาติไทย': 4912, 'รวมไฟไทย': 634, 'รวมไทยสร้างชาติ': 742, 'ประชาธิปไตยไทม์': 461, 'เพื่อไทย': 25212, 'ทางเลือกไทม์': 285, 'เศรษฐกิจ': 2981, 'เสร็จรวมไทย': 478, 'รวมหลังประชาชน': 592, 'ท้องที่ไทย': 53, 'อนาคตไทย': 60, 'หลังเพื่อไทย': 263, 'สังคมประชาธิปไตยไทย': 33, 'ฟิวชัน': 14, 'โทรวมพลัง': 237, 'ก้าวอิสระ': 26, 'ปวงชนไทย': 54, 'วิชชั่นไทม์': 58, 'เพื่อชีวิตไทม์': 22, 'คลองไทย': 53, 'ประชาธิปไตย': 1038, 'ไทยก้าวหน้า': 91, 'ไทยภักดี': 196, 'แรงงานสร้างชาติ': 102, 'ประชากรไทย': 428, 'ครูไทยเพื่อประชาชน': 177, 'ประชาชาติ': 287, 'สร้างอนาคตไทย': 239, 'ไทยพร้อม': 179, 'ภูมิใจไทย': 17903, 'พลังธรรมไทม์': 481, 'กรีน': 61, 'ไทยธรรม': 70, 'แผ่นดินธรรม': 26, 'กล้าธรรม': 192, 'พลังประชาธิปไตย': 107, 'เงินธรรม': 72, 'ประชาชน': 16089, 'ประชาไทย': 135, 'ไทยสร้างไทย': 579, 'ไทยก้าวไทม์': 188, 'ประชาอาสาชาติ': 15, 'พร้อม': 22, 'เครือข่ายชาวนาแห่งประเทศไทย': 20, 'ไทยพิทักษ์ธรรม': 5, 'ความหวังไทม์': 25, 'ไทยรวมไทย': 28, 'เพื่อบ้านเมือง': 27, 'พลังไทยรักชาติ': 55}

Processing:  97%|█████████▋| 291/300 [36:13<01:25,  9.49s/doc]

party_list_33_3 {}

Processing:  97%|█████████▋| 292/300 [36:24<01:18,  9.87s/doc]

party_list_33_4 {'เพื่อชาติไทย': 2552, 'รวมใจไทย': 646, 'รวมไทยสร้างชาติ': 1040, 'ประชาธิปไตยไทม์': 557, 'เพื่อไทย': 10492, 'ทางเลือกไหม': 286, 'เศรษฐกิจ': 5863, 'เสรีรวมไทย': 322, 'รวมพลังประชาชน': 133, 'ท้องที่ไทย': 83, 'อนาคตไทย': 31, 'พลังเพื่อไทย': 144, 'พลังสังคมไทม์': 28, 'สังคมประชาธิปไตยไทย': 22, 'ไทรวมพลัง': 3126, 'ก้าวอิสระ': 61, 'ปวเชนไทย': 33, 'วิชชั่นไทม์': 129, 'เพื่อชีวิตไทม์': 39, 'คลองไทย': 58, 'ประชาธิปไตย': 1246, 'ไทยก้าวหน้า': 83, 'ไทยภักดี': 284, 'แรงรามสร้างชาติ': 114, 'ประชากรไทย': 320, 'ครูไทยเพื่อประชาชน': 217, 'ประชาชาติ': 264, 'สร้างอนาคตไทย': 266, 'รักชาติ': 130, 'ไทยพร้อม': 184, 'ภูมิใจไทย': 26965, 'พลังธรรมไทม์': 260, 'กรีน': 55, 'ไทยธรรม': 129, 'แผ่นดินธรรม': 43, 'กล้าธรรม': 1630, 'พลังประชารัฐ': 113, 'เป็นธรรม': 47, 'ประชาชน': 13876, 'ประชาไทย': 145, 'ไทยสร้างไทย': 300, 'ไทยกาวไทม์': 107, 'ประชาอาสาชาติ': 27, 'พร้อม': 44, 'เครือขายขาวนาแทคประเทศไทย': 15, 'ไทยพิทักษ์ธรรม': 14, 'ความหวังไทม์': 17, 'ไทยรวมไทย': 17, 'เพื่อบ้านเมือง': 38, 'พลังไทยรักชาติ': 50}

Processing:  98%|█████████▊| 293/300 [36:34<01:08,  9.82s/doc]

party_list_33_5 {'ไทยทรัพย์ทวี': 275, 'เพื่อชาติไทย': 1382, 'มิติใหม่': 2172, 'รวมใจไทย': 2485, 'รวมไทยสร้างชาติ': 1123, 'พลวัต': 163, 'ประชาธิปไตยใหม่': 584, 'เพื่อไทย': 19812, 'ทางเลือกใหม่': 317, 'เศรษฐกิจ': 3407, 'เสรีรวมไทย': 259, 'รวมพลังประชาชน': 377, 'ท้องที่ไทย': 64, 'อนาคตไทย': 81, 'พลังเพื่อไทย': 209, 'ไทยชนะ': 169, 'พลังสังคมใหม่': 31, 'สังคมประชาธิปไตยไทย': 44, 'ฟิวชัน': 38, 'ไทรวมพลัง': 860, 'ก้าวอิสระ': 30, 'ปวงชนไทย': 64, 'วิชชั่นใหม่': 50, 'เพื่อชีวิตใหม่': 40, 'คลองไทย': 69, 'ประชาธิปไตย': 1132, 'ไทยก้าวหน้า': 85, 'ไทยภักดี': 241, 'แรงงานสร้างชาติ': 118, 'ประชากรไทย': 254, 'ครูไทยเพื่อประชาชน': 153, 'ประชาชาติ': 268, 'สร้างอนาคตไทย': 303, 'รักชาติ': 173, 'ไทยพร้อม': 168, 'ภูมิใจไทย': 23418, 'พลังธรรมใหม่': 389, 'กรีน': 59, 'ไทยธรรม': 65, 'แผ่นดินธรรม': 28, 'กล้าธรรม': 134, 'พลังประชาธิปไตย': 78, 'โอกาสใหม่': 25, 'เป็นธรรม': 39, 'ประชาชน': 16048, 'ประชาไทย': 142, 'ไทยสร้างไทย': 228, 'ไทยก้าวใหม่': 112, 'ประชาอาสาชาติ': 11, 'พร้อม': 21, 'เครือข่ายชาวนาแห่งประเทศไทย': 14, 'ไทยพิทักษ์ธรรม': 15, 'ความหวังใหม่': 22, 'ไทยรวมไทย': 22, 'เพื่อบ้านเมือง': 23, 'พลังไทยรักชาติ': 67}

Processing:  98%|█████████▊| 294/300 [36:47<01:05, 10.84s/doc]

party_list_33_6 {}

Processing:  98%|█████████▊| 295/300 [36:59<00:56, 11.25s/doc]

party_list_33_7 {}

Processing:  99%|█████████▊| 296/300 [37:12<00:47, 11.78s/doc]

party_list_33_8 {'ไทยพรัชย์ทวี': 167, 'เพื่อชาติไทย': 3056, 'มิติใหม่': 520, 'รวมใจไทย': 367, 'รวมไทยสร้างชาติ': 673, 'พลวัต': 88, 'ประชาธิปไตยใหม่': 548, 'เพื่อไทย': 19414, 'ทางเลือกใหม่': 225, 'เศรษฐกิจ': 1961, 'รวมพลังประชาชน': 400, 'ท้องฟื้ไทย': 45, 'อนาคตไทย': 47, 'พลังเพื่อไทย': 187, 'พลังสังคมใหม่': 18, 'สังคมประชาธิปไตยไทย': 31, 'ฟิวจัน': 12, 'ไทรวมพลัง': 87, 'ก้าวอิสระ': 27, 'ปวงชนไทย': 91, 'วิชชั่นใหม่': 45, 'เพื่อชีวิตใหม่': 18, 'คลองไทย': 42, 'ประชาธิปัตย์': 989, 'ไทยก้าวหน้า': 77, 'ไทยภักดี': 240, 'แรงงานสร้างชาติ': 110, 'ประชากรไทย': 175, 'ครูไทยเพื่อประชาชน': 195, 'ประชาชาติ': 159, 'สร้างอนาคตไทย': 161, 'รักชาติ': 111, 'ไทยพร้อม': 351, 'ภูมิใจไทย': 30867, 'พลังธรรมใหม่': 466, 'กรีน': 67, 'ไทยธรรม': 56, 'แผ่นดินธรรม': 57, 'กล้าอรวม': 101, 'พลังประชาธิปไตย': 56, 'โอกาสใหม่': 32, 'เป็นธรรม': 55, 'ประชาชน': 19144, 'ประชาไทย': 158, 'ไทยสร้างไทย': 350, 'ไทยก้าวใหม่': 166, 'ประชาอาสาชาติ': 14, 'พร้อม': 31, 'เครือข่ายชาวนาแห่งประเทศไทย': 10, 'ไทยพิทักษ์ธรรม': 12, 'ความหวังใหม่': 15, 'ไทยรวมไทย': 13, 'เพื่อบ้านเมือง': 24, 'พลังไทยรักชาติ': 50}

Processing:  99%|█████████▉| 297/300 [37:22<00:33, 11.16s/doc]

party_list_33_9 {'ไทยพร้อมท่า': 504, 'เพื่อชาติไทย': 4074, 'มิติใหม่': 114, 'รวมใจไทย': 466, 'รวมไทยสร้างชาติ': 372, 'ประชาธิปไตยใหม่': 375, 'เพื่อไทย': 33279, 'ทางเลือกใหม่': 2208, 'เศรษฐกิจ': 2050, 'เสร็จรวมไทย': 324, 'รวมพลังประชาชน': 405, 'ท้องฟีไทย': 138, 'อนาคตไทย': 48, 'หลังเพื่อไทย': 309, 'ไทยชนะ': 112, 'หลังสังคมใหม่': 24, 'สังคมประชาธิปไตยไทย': 29, 'พิวชัน': 22, 'ไทรวมพลัง': 107, 'ก้าวอิสระ': 26, 'ปวเชนไทย': 44, 'วิชชั่นใหม่': 32, 'เพื่อชีวิตใหม่': 26, 'คลองไทย': 56, 'ประชาธิปไตย': 1033, 'ไทยก้าวหน้า': 89, 'ไทยภักดี': 203, 'แรงงานสร้างชาติ': 144, 'ประชากรไทย': 414, 'ครูไทยเพื่อประชาชน': 184, 'ประชาชาติ': 58, 'สร้างอนาคตไทย': 88, 'รักชาติ': 81, 'ไทยพร้อม': 140, 'ภูมิใจไทย': 17994, 'พลังธรรมใหม่': 638, 'กรีน': 239, 'ไทยธรรม': 62, 'แม่มตินธรรม': 29, 'กล้าระรม': 1106, 'พลังประชาธิปไตย': 171, 'โอกาสใหม่': 32, 'เป็นธรรม': 54, 'ประชาชน': 1788, 'ประชาไทย': 121, 'ไทยสร้างไทย': 334, 'ไทยก้าวใหม่': 147, 'ประชาอาสาชาติ': 6, 'พร้อม': 42, 'เครือข่ายชาวนาแห่งประเทศไทย': 14, 'ไทยพิทักษ์ธรรม': 15, 'ความหวังใหม่': 23, 'ไทยรวมไทย': 20, 'เพื่อบ้านเมือง': 13, 'พลังไทยรักชาติ': 50}

Processing:  99%|█████████▉| 298/300 [37:31<00:21, 10.67s/doc]

party_list_34_1 {'ไทยทรัพย์ทวี': 299, 'เพื่อขาตีไทย': 3027, 'มิติใหม่': 290, 'รวมใจไทย': 567, 'รวมไทยสร้างชาติ': 1860, 'พลวัต': 447, 'ประชาธิปไตยใหม่': 687, 'เพื่อไทย': 20879, 'ทางเลือกใหม่': 423, 'เศรษฐกิจ': 3346, 'เสร็จรถไทย': 520, 'รวมพลังประชาชน': 400, 'ท้องที่ไทย': 23, 'อนาคตไทย': 57, 'พลังเพื่อไทย': 149, 'พลังสังคมใหม่': 22, 'สังคมประชาธิปไตยไทย': 50, 'โทรวมพลัง': 2230, 'ก้าวอิสระ': 37, 'ปวงขนไทย': 24, 'วิชชั้นใหม่': 91, 'เพื่อชีวิตใหม่': 24, 'คะองไทย': 47, 'ประชาธิปไตย': 5058, 'ไทยก้าวหน้า': 126, 'แรงงานสร้างชาติ': 87, 'ประชากรไทย': 129, 'ครูไทยเพื่อประชาชน': 30, 'ประชาชาติ': 104, 'สร้างอนาคตไทย': 60, 'รักชาติ': 80, 'ไทยพร้อม': 77, 'ภูมิใจไทย': 12515, 'พลังธรรมใหม่': 160, 'กรีน': 37, 'ไทยธรรม': 26, 'แผ่นดินธรรม': 26, 'กล้าถรวม': 188, 'พลังประชาธิปไตย': 146, 'โอกาสใหม่': 50, 'เป็นธรรม': 64, 'ประชาชน': 33820, 'ประชาไทย': 113, 'ไทยสร้างไทย': 2056, 'ไทยก้าวใหม่': 340, 'พร้อม': 48, 'เครือข่ายชาวบ้านแห่งประเทศไทย': 25, 'ไทยพิทักษ์ธรรม': 5, 'ความหรังใหม่': 19, 'ไทยรวมไทย': 10, 'เพื่อบ้านเมือง': 38, 'พลังไทยรักชาติ': 38}

Processing: 100%|█████████▉| 299/300 [37:41<00:10, 10.41s/doc]

party_list_34_10 {'เพื่อชาติไทย': 4187, 'รวมใจไทย': 68, 'รวมใจลดร้างชาติ': 759, 'ประชาธิปไตยไหม้': 669, 'เพื่อไทย': 7462, 'เศรษฐกิจ': 6896, 'เสร็จรถไทย': 61, 'รวมพลังประชาชน': 728, 'ท้องที่ไทย': 63, 'อนาคตไทย': 58, 'พลังเพื่อไทย': 172, 'สังคมประชาธิปไตยไทย': 17, 'ฟิวชัน': 175, 'ไทรวมพลัง': 46161, 'ก้าวอิสระ': 321, 'ปวงชนไทย': 74, 'เพื่อชีวิตไหม้': 39, 'คอองไทย': 65, 'ประชาธิปไตย': 1146, 'ไทยก้าวหน้า': 106, 'ไทยภักดี': 172, 'แรงงานสร้างชาติ': 133, 'ประชากรไทย': 477, 'ครูไทยเพื่อประชาชน': 148, 'ประชาชาติ': 85, 'สร้างอนาคตไทย': 58, 'รักชาติ': 72, 'ไทยพร้อม': 75, 'ภูมิใจไทย': 5520, 'พลังธรรมไหม้': 664, 'กรีน': 40, 'ไทยธรรม': 64, 'แผ่นดินธรรม': 51, 'กล้าธรรม': 54, 'พลังประชารัฐ': 35, 'โอกาสไหม้': 18, 'เป็นธรรม': 41, 'ประชาชน': 11557, 'ประชาไทย': 56, 'ไทยสร้างไทย': 666, 'ไทยก้าวไหม้': 89, 'ประชาอาสาชาติ': 557, 'พร้อม': 61, 'เครือข่ายชาวนาแห่งประเทศไทย': 14, 'ไทยพิพิธภัณฑ์ธรรม': 15, 'ความหวังไหม้': 14, 'ไทยรวมไทย': 44, 'เพื่อบ้านไหม้': 34, 'พลังไทยรักชาติ': 81}

Processing: 100%|██████████| 300/300 [37:51<00:00,  7.57s/doc]

party_list_34_11 {'ไทยพร้อมลำไส้': 162, 'เพื่อชาติต่อ': 1552, 'มิติใหม่': 505, 'รวมใจไทย': 361, 'รวมไทยสร้างชาติ': 1670, 'พลวัต': 234, 'ประชาธิปไตยใหม่': 558, 'เพื่อไทย': 13111, 'ทางเลือกใหม่': 134, 'เศรษฐกิจ': 1913, 'เสร็จรวมไทย': 569, 'รวมพลังประชาชน': 506, 'ท้องที่ไทย': 72, 'อนาคตไทย': 85, 'พลังเพื่อไทย': 232, 'ไทยชนะ': 185, 'พลังสังคมใหม่': 30, 'สังคมประชาธิปไตยไทย': 54, 'ฟิวชัน': 63, 'ไตรวมพลัง': 6554, 'ก้าวอิสระ': 71, 'ปวงชนไทย': 115, 'วิชชั่นใหม่': 317, 'เพื่อชีวิตใหม่': 57, 'คอยงไทย': 120, 'ประชาธิปัตย์': 2921, 'ไทยก้าวหน้า': 171, 'แรงงานสร้างชาติ': 134, 'ประชากรไทย': 284, 'ครูไทยเพื่อประชาชน': 255, 'ประชาชาติ': 202, 'สร้างอนาคตไทย': 151, 'รักชาติ': 142, 'ไทยพร้อม': 204, 'ภูมิใจไทย': 16830, 'พลังธรรมใหม่': 300, 'กรีน': 58, 'ไทยธรรม': 110, 'แผ่นดินธรรม': 34, 'กล้าธรรม': 157, 'พลังประชารัฐ': 178, 'โอกาสใหม่': 34, 'เป็นธรรม': 70, 'ประชาชน': 17866, 'ประชาไทย': 162, 'ไทยสร้างไทย': 1146, 'ไทยก้าวใหม่': 143, 'ประชาอาสาชาติ': 64, 'พร้อม': 43, 'เครือข่ายชาวนาแห่งประเทศไทย': 20, 'ไทยพิทักษ์ธรรม': 14, 'ความหวังใหม่': 41, 'ไทยรวมไทย': 29, 'เพื่อบ้านเมือง': 41, 'พลังไทยรักชาติ': 71}

In [76]:
submission_df

                        id      party_name  votes             doc_id
0      constituency_10_1_1    ประชาธิปัตย์  14813  constituency_10_1
1      constituency_10_1_2       ภูมิใจไทย  14368  constituency_10_1
2      constituency_10_1_3        เศรษฐกิจ    979  constituency_10_1
3      constituency_10_1_4        กล้าธรรม    244  constituency_10_1
4      constituency_10_1_5           พลวัต    351  constituency_10_1
...                    ...             ...    ...                ...
10048  party_list_34_11_53  ไทยพิทักษ์ธรรม     14   party_list_34_11
10049  party_list_34_11_54    ความหวังใหม่     41   party_list_34_11
10050  party_list_34_11_55       ไทยรวมไทย     29   party_list_34_11
10051  party_list_34_11_56  เพื่อบ้านเมือง     41   party_list_34_11
10052  party_list_34_11_57  พลังไทยรักชาติ     71   party_list_34_11

[10053 rows x 4 columns]

In [77]:
output_df = submission_df.drop(['doc_id', 'party_name'], axis=1)

In [78]:
output_df

                        id  votes
0      constituency_10_1_1  14813
1      constituency_10_1_2  14368
2      constituency_10_1_3    979
3      constituency_10_1_4    244
4      constituency_10_1_5    351
...                    ...    ...
10048  party_list_34_11_53     14
10049  party_list_34_11_54     41
10050  party_list_34_11_55     29
10051  party_list_34_11_56     41
10052  party_list_34_11_57     71

[10053 rows x 2 columns]

In [79]:
output_df.to_csv("submission2.csv", index=False)

In [82]:
output_df[output_df['votes'] == 0].count()

id       1581
votes    1581
dtype: int64