In [1]:
import pandas as pd

In [2]:
SUBMISSION_PATH = "../data/submission_template.csv"

In [3]:
submission_df = pd.read_csv(SUBMISSION_PATH)
submission_df

                        id             doc_id  row_num      party_name  votes
0      constituency_10_1_1  constituency_10_1        1    ประชาธิปัตย์      0
1      constituency_10_1_2  constituency_10_1        2       ภูมิใจไทย      0
2      constituency_10_1_3  constituency_10_1        3        เศรษฐกิจ      0
3      constituency_10_1_4  constituency_10_1        4        กล้าธรรม      0
4      constituency_10_1_5  constituency_10_1        5           พลวัต      0
...                    ...                ...      ...             ...    ...
10048  party_list_34_11_53   party_list_34_11       53  ไทยพิทักษ์ธรรม      0
10049  party_list_34_11_54   party_list_34_11       54    ความหวังใหม่      0
10050  party_list_34_11_55   party_list_34_11       55       ไทยรวมไทย      0
10051  party_list_34_11_56   party_list_34_11       56  เพื่อบ้านเมือง      0
10052  party_list_34_11_57   party_list_34_11       57  พลังไทยรักชาติ      0

[10053 rows x 5 columns]

In [4]:
submission_df['party_name'].unique()

array(['ประชาธิปัตย์', 'ภูมิใจไทย', 'เศรษฐกิจ', 'กล้าธรรม', 'พลวัต',
       'ประชาชน', 'เพื่อไทย', 'ไทยภักดี', 'รวมไทยสร้างชาติ', 'ปวงชนไทย',
       'ไทยสร้างไทย', 'โอกาสใหม่', 'วิชชั่นใหม่', 'ประชาธิปไตยใหม่',
       'รักชาติ', 'ไทยก้าวใหม่', 'ทางเลือกใหม่', 'พลังประชารัฐ',
       'ประชากรไทย', 'ความหวังใหม่', 'อนาคตไทย', 'บ้านเมือง',
       'เพื่อบ้านเมือง', 'ไทยก้าวหน้า', 'รวมไทยสร้าง', 'แรงงานสร้างชาติ',
       'ไทยชนะ', 'พร้อม', 'ไทยพิทักษ์ธรรม', 'ไทยก้าวไทย', 'ไทยก้าวใหม',
       'เสรีรวมไทย', 'เป็นธรรม', 'ไทยธรรม', 'ฟิวชน', 'ฟิวชัน',
       'รวมพลังประชาชน', 'แรงงานสร้างไทย', 'ไทยสร้างชาติ', nan,
       'ปวงชนชาวไทย', 'กลาธรรม', 'สังคมประชาธิปไตยไทย', 'คลองไทย',
       'รวมใจไทย', 'รวมไทยสร้างชา', 'รักษ์ธรรม', 'ชาติ', 'ไทยพร้อม',
       'สร้างชาติ', 'ใหม่', 'พลังสังคมใหม่', 'สร้างอนาคตไทย',
       'ไทยทรัพย์ทวี', 'รวมพลัง', 'ไทรวมพลัง', 'เพื่อชาติไทย', 'มิติใหม่',
       'ท้องที่ไทย', 'พลังเพื่อไทย', 'ก้าวอิสระ', 'เพื่อชีวิตใหม่',
       'ครูไทยเพื่อประชาชน', 'ประชาชาติ', 'พลังธรรมใหม่', 'กรีน',
       'แผ่นดินธรรม', 'ประชาไทย', 'ประชาอาสาชาติ',
       'เครือข่ายชาวนาแห่งประเทศไทย', 'ไทยรวมไทย', 'พลังไทยรักชาติ',
       'ไทยรวมพลัง', 'พลังธรรมไทย', 'บิติใหม่', 'วิชั่นใหม่',
       'สังคมประชาธิปไตย', 'กาวอิสระ', 'แผนดินธรรม', 'พรอม', 'ฟิวซัน',
       'พลังประเสริฐ', 'ฟิวชั่น', 'วิชชันใหม่', 'ประชาติปไตยใหม่',
       'UNKNOWN', 'บ่วงชนไทย', 'เครือข่าวชาวนาแห่งประเทศไทย', 'พรรคที่ 1',
       'รวมพลังประชาชน์', 'สังคมใหม่', 'พรรคที่ 1 (ไม่ระบุชื่อ)',
       'ครูไทยเพื่อปวงชน', 'พรรครวมใจไทย', 'อนาคตใหม่', 'ประชาธิปปัตย์',
       'เครือข่ายชาวนา', 'ไม่ระบุ', 'หลังสังคมใหม่', 'กริน', 'กสิกรธรรม',
       'ชาติพัฒนา', 'Unknown Party', 'วิชซั่นใหม่', 'วิชชั่นไทย',
       'เพื่อบ้านใหม่'], dtype=object)

In [5]:
submission_df.head()

                    id             doc_id  row_num    party_name  votes
0  constituency_10_1_1  constituency_10_1        1  ประชาธิปัตย์      0
1  constituency_10_1_2  constituency_10_1        2     ภูมิใจไทย      0
2  constituency_10_1_3  constituency_10_1        3      เศรษฐกิจ      0
3  constituency_10_1_4  constituency_10_1        4      กล้าธรรม      0
4  constituency_10_1_5  constituency_10_1        5         พลวัต      0

In [22]:
invalid_name = ["Unknown Party", "พรรคที่ 1 (ไม่ระบุชื่อ)", "ไม่ระบุ"]

NaN_df = submission_df[
    submission_df['party_name'].isna() | submission_df['party_name'].isin(invalid_name)
]

NaN_df

                        id             doc_id  row_num party_name  votes
737   constituency_14_2_10  constituency_14_2       10        NaN      0
738   constituency_14_2_11  constituency_14_2       11        NaN      0
739   constituency_14_2_12  constituency_14_2       12        NaN      0
740   constituency_14_2_13  constituency_14_2       13        NaN      0
741   constituency_14_2_14  constituency_14_2       14        NaN      0
742   constituency_14_2_15  constituency_14_2       15        NaN      0
743   constituency_14_2_16  constituency_14_2       16        NaN      0
744   constituency_14_2_17  constituency_14_2       17        NaN      0
7375     party_list_27_3_1    party_list_27_3        1    ไม่ระบุ      0

In [7]:
# 737 - 744 Correctly Null
submission_df.iloc[737]

id            constituency_14_2_10
doc_id           constituency_14_2
row_num                         10
party_name                     NaN
votes                            0
Name: 737, dtype: object

In [8]:
# 2698
submission_df.iloc[2698]

id            party_list_10_3_1
doc_id          party_list_10_3
row_num                       1
party_name                  NaN
votes                         0
Name: 2698, dtype: object

In [9]:
# 2700
submission_df.iloc[2700]

id            party_list_10_3_3
doc_id          party_list_10_3
row_num                       3
party_name                  NaN
votes                         0
Name: 2700, dtype: object

In [10]:
# 6461
submission_df.iloc[6461]

id                  party_list_21_4_1
doc_id                party_list_21_4
row_num                             1
party_name    พรรคที่ 1 (ไม่ระบุชื่อ)
votes                               0
Name: 6461, dtype: object

In [11]:
# 6892
submission_df.iloc[6892]

id            party_list_24_2_33
doc_id           party_list_24_2
row_num                       33
party_name                   NaN
votes                          0
Name: 6892, dtype: object

In [12]:
# 7031
submission_df.iloc[7031]

id            party_list_25_1_1
doc_id          party_list_25_1
row_num                       1
party_name                  NaN
votes                         0
Name: 7031, dtype: object

In [13]:
# 7033
submission_df.iloc[7033]

id            party_list_25_1_3
doc_id          party_list_25_1
row_num                       3
party_name                  NaN
votes                         0
Name: 7033, dtype: object

In [14]:
# 8000
submission_df.iloc[8000]

id            party_list_30_4_1
doc_id          party_list_30_4
row_num                       1
party_name        Unknown Party
votes                         0
Name: 8000, dtype: object

In [15]:
# 9426
submission_df.iloc[9426]

id            party_list_33_2_1
doc_id          party_list_33_2
row_num                       1
party_name                  NaN
votes                         0
Name: 9426, dtype: object

In [17]:
fix_invalid = {
    2698: ('ไทยทรัพย์ทวี', 31),
    2700: ('ใหม่', 149),
    6461: ('ไทยทรัพย์ทวี', 473),
    6892: ('ประชาชาติ', 632),
    7031: ('ไทยทรัพย์ทวี', 2250),
    7033: ('ใหม่', 481),
    8000: ('ไทยทรัพย์ทวี', 420),
    9426: ('ไทยทรัพย์ทวี', 347)
}

In [20]:
for idx, (party, vote) in fix_invalid.items():
    submission_df.loc[idx, 'party_name'] = party
    submission_df.loc[idx, 'votes'] = vote

for idx, (party, vote) in fix_invalid.items():
    print(submission_df.iloc[idx])
    print()

id            party_list_10_3_1
doc_id          party_list_10_3
row_num                       1
party_name         ไทยทรัพย์ทวี
votes                        31
Name: 2698, dtype: object

id            party_list_10_3_3
doc_id          party_list_10_3
row_num                       3
party_name                 ใหม่
votes                       149
Name: 2700, dtype: object

id            party_list_21_4_1
doc_id          party_list_21_4
row_num                       1
party_name         ไทยทรัพย์ทวี
votes                       473
Name: 6461, dtype: object

id            party_list_24_2_33
doc_id           party_list_24_2
row_num                       33
party_name             ประชาชาติ
votes                        632
Name: 6892, dtype: object

id            party_list_25_1_1
doc_id          party_list_25_1
row_num                       1
party_name         ไทยทรัพย์ทวี
votes                      2250
Name: 7031, dtype: object

id            party_list_25_1_3
doc_id          party_list_25_1
row_num                       3
party_name                 ใหม่
votes                       481
Name: 7033, dtype: object

id            party_list_30_4_1
doc_id          party_list_30_4
row_num                       1
party_name         ไทยทรัพย์ทวี
votes                       420
Name: 8000, dtype: object

id            party_list_33_2_1
doc_id          party_list_33_2
row_num                       1
party_name         ไทยทรัพย์ทวี
votes                       347
Name: 9426, dtype: object

In [16]:
for doc_id in submission_df['doc_id'].unique():
    matched_rows = submission_df[submission_df['doc_id'] == doc_id]
    print(matched_rows)
    break

                      id             doc_id  row_num       party_name  votes
0    constituency_10_1_1  constituency_10_1        1     ประชาธิปัตย์      0
1    constituency_10_1_2  constituency_10_1        2        ภูมิใจไทย      0
2    constituency_10_1_3  constituency_10_1        3         เศรษฐกิจ      0
3    constituency_10_1_4  constituency_10_1        4         กล้าธรรม      0
4    constituency_10_1_5  constituency_10_1        5            พลวัต      0
5    constituency_10_1_6  constituency_10_1        6          ประชาชน      0
6    constituency_10_1_7  constituency_10_1        7         เพื่อไทย      0
7    constituency_10_1_8  constituency_10_1        8         ไทยภักดี      0
8    constituency_10_1_9  constituency_10_1        9  รวมไทยสร้างชาติ      0
9   constituency_10_1_10  constituency_10_1       10         ปวงชนไทย      0
10  constituency_10_1_11  constituency_10_1       11      ไทยสร้างไทย      0
11  constituency_10_1_12  constituency_10_1       12        โอกาสใหม่      0
12  constituency_10_1_13  constituency_10_1       13      วิชชั่นใหม่      0
13  constituency_10_1_14  constituency_10_1       14  ประชาธิปไตยใหม่      0
14  constituency_10_1_15  constituency_10_1       15          รักชาติ      0
15  constituency_10_1_16  constituency_10_1       16      ไทยก้าวใหม่      0
16  constituency_10_1_17  constituency_10_1       17     ทางเลือกใหม่      0
17  constituency_10_1_18  constituency_10_1       18     พลังประชารัฐ      0